defmodule UniboV4.Ofbiz.Order do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.Order.OrderAdjustment
    resource UniboV4.Ofbiz.Order.OrderAdjustment.Version
    resource UniboV4.Ofbiz.Order.OrderAdjustmentAttribute
    resource UniboV4.Ofbiz.Order.OrderAdjustmentAttribute.Version
    resource UniboV4.Ofbiz.Order.OrderAdjustmentType
    resource UniboV4.Ofbiz.Order.OrderAdjustmentType.Version
    resource UniboV4.Ofbiz.Order.OrderAdjustmentBilling
    resource UniboV4.Ofbiz.Order.OrderAdjustmentTypeAttr
    resource UniboV4.Ofbiz.Order.OrderAdjustmentTypeAttr.Version
    resource UniboV4.Ofbiz.Order.OrderAttribute
    resource UniboV4.Ofbiz.Order.OrderAttribute.Version
    resource UniboV4.Ofbiz.Order.OldOrderBlacklist
    resource UniboV4.Ofbiz.Order.OldOrderBlacklist.Version
    resource UniboV4.Ofbiz.Order.OldOrderBlacklistType
    resource UniboV4.Ofbiz.Order.OldOrderBlacklistType.Version
    resource UniboV4.Ofbiz.Order.OrderDenylist
    resource UniboV4.Ofbiz.Order.OrderDenylist.Version
    resource UniboV4.Ofbiz.Order.OrderDenylistType
    resource UniboV4.Ofbiz.Order.OrderDenylistType.Version
    resource UniboV4.Ofbiz.Order.CommunicationEventOrder
    resource UniboV4.Ofbiz.Order.CommunicationEventOrder.Version
    resource UniboV4.Ofbiz.Order.OrderContactMech
    resource UniboV4.Ofbiz.Order.OrderContent
    resource UniboV4.Ofbiz.Order.OrderContentType
    resource UniboV4.Ofbiz.Order.OrderContentType.Version
    resource UniboV4.Ofbiz.Order.OrderDeliverySchedule
    resource UniboV4.Ofbiz.Order.OrderDeliverySchedule.Version
    resource UniboV4.Ofbiz.Order.OrderHeader
    resource UniboV4.Ofbiz.Order.OrderHeader.Version
    resource UniboV4.Ofbiz.Order.OrderHeaderNote
    resource UniboV4.Ofbiz.Order.OrderHeaderNote.Version
    resource UniboV4.Ofbiz.Order.OrderHeaderWorkEffort
    resource UniboV4.Ofbiz.Order.OrderHeaderWorkEffort.Version
    resource UniboV4.Ofbiz.Order.OrderItem
    resource UniboV4.Ofbiz.Order.OrderItem.Version
    resource UniboV4.Ofbiz.Order.OrderItemAssoc
    resource UniboV4.Ofbiz.Order.OrderItemAssocType
    resource UniboV4.Ofbiz.Order.OrderItemAssocType.Version
    resource UniboV4.Ofbiz.Order.OrderItemAttribute
    resource UniboV4.Ofbiz.Order.OrderItemBilling
    resource UniboV4.Ofbiz.Order.OrderItemChange
    resource UniboV4.Ofbiz.Order.OrderItemChange.Version
    resource UniboV4.Ofbiz.Order.OrderItemContactMech
    resource UniboV4.Ofbiz.Order.OrderItemGroup
    resource UniboV4.Ofbiz.Order.OrderItemGroup.Version
    resource UniboV4.Ofbiz.Order.OrderItemGroupOrder
    resource UniboV4.Ofbiz.Order.OrderItemPriceInfo
    resource UniboV4.Ofbiz.Order.OrderItemPriceInfo.Version
    resource UniboV4.Ofbiz.Order.OrderItemRole
    resource UniboV4.Ofbiz.Order.OrderItemShipGroup
    resource UniboV4.Ofbiz.Order.OrderItemShipGroup.Version
    resource UniboV4.Ofbiz.Order.OrderItemShipGroupAssoc
    resource UniboV4.Ofbiz.Order.OrderItemShipGrpInvRes
    resource UniboV4.Ofbiz.Order.OrderItemType
    resource UniboV4.Ofbiz.Order.OrderItemType.Version
    resource UniboV4.Ofbiz.Order.OrderItemTypeAttr
    resource UniboV4.Ofbiz.Order.OrderItemTypeAttr.Version
    resource UniboV4.Ofbiz.Order.OrderNotification
    resource UniboV4.Ofbiz.Order.OrderNotification.Version
    resource UniboV4.Ofbiz.Order.OrderPaymentPreference
    resource UniboV4.Ofbiz.Order.OrderPaymentPreference.Version
    resource UniboV4.Ofbiz.Order.OrderProductPromoCode
    resource UniboV4.Ofbiz.Order.OrderProductPromoCode.Version
    resource UniboV4.Ofbiz.Order.OrderRole
    resource UniboV4.Ofbiz.Order.OrderShipment
    resource UniboV4.Ofbiz.Order.OrderStatus
    resource UniboV4.Ofbiz.Order.OrderStatus.Version
    resource UniboV4.Ofbiz.Order.OrderSummaryEntry
    resource UniboV4.Ofbiz.Order.OrderTerm
    resource UniboV4.Ofbiz.Order.OrderTermAttribute
    resource UniboV4.Ofbiz.Order.OrderType
    resource UniboV4.Ofbiz.Order.OrderType.Version
    resource UniboV4.Ofbiz.Order.OrderTypeAttr
    resource UniboV4.Ofbiz.Order.OrderTypeAttr.Version
    resource UniboV4.Ofbiz.Order.ProductOrderItem
    resource UniboV4.Ofbiz.Order.WorkOrderItemFulfillment
    resource UniboV4.Ofbiz.Order.Quote
    resource UniboV4.Ofbiz.Order.Quote.Version
    resource UniboV4.Ofbiz.Order.QuoteAttribute
    resource UniboV4.Ofbiz.Order.QuoteAttribute.Version
    resource UniboV4.Ofbiz.Order.QuoteCoefficient
    resource UniboV4.Ofbiz.Order.QuoteCoefficient.Version
    resource UniboV4.Ofbiz.Order.QuoteItem
    resource UniboV4.Ofbiz.Order.QuoteItem.Version
    resource UniboV4.Ofbiz.Order.QuoteNote
    resource UniboV4.Ofbiz.Order.QuoteNote.Version
    resource UniboV4.Ofbiz.Order.QuoteRole
    resource UniboV4.Ofbiz.Order.QuoteTerm
    resource UniboV4.Ofbiz.Order.QuoteTermAttribute
    resource UniboV4.Ofbiz.Order.QuoteType
    resource UniboV4.Ofbiz.Order.QuoteType.Version
    resource UniboV4.Ofbiz.Order.QuoteTypeAttr
    resource UniboV4.Ofbiz.Order.QuoteTypeAttr.Version
    resource UniboV4.Ofbiz.Order.QuoteWorkEffort
    resource UniboV4.Ofbiz.Order.QuoteWorkEffort.Version
    resource UniboV4.Ofbiz.Order.QuoteAdjustment
    resource UniboV4.Ofbiz.Order.QuoteAdjustment.Version
    resource UniboV4.Ofbiz.Order.CustRequest
    resource UniboV4.Ofbiz.Order.CustRequest.Version
    resource UniboV4.Ofbiz.Order.CustRequestAttribute
    resource UniboV4.Ofbiz.Order.CustRequestAttribute.Version
    resource UniboV4.Ofbiz.Order.CustRequestCategory
    resource UniboV4.Ofbiz.Order.CustRequestCategory.Version
    resource UniboV4.Ofbiz.Order.CustRequestCommEvent
    resource UniboV4.Ofbiz.Order.CustRequestCommEvent.Version
    resource UniboV4.Ofbiz.Order.CustRequestContent
    resource UniboV4.Ofbiz.Order.CustRequestItem
    resource UniboV4.Ofbiz.Order.CustRequestItem.Version
    resource UniboV4.Ofbiz.Order.CustRequestNote
    resource UniboV4.Ofbiz.Order.CustRequestNote.Version
    resource UniboV4.Ofbiz.Order.CustRequestItemNote
    resource UniboV4.Ofbiz.Order.CustRequestItemWorkEffort
    resource UniboV4.Ofbiz.Order.CustRequestResolution
    resource UniboV4.Ofbiz.Order.CustRequestResolution.Version
    resource UniboV4.Ofbiz.Order.CustRequestParty
    resource UniboV4.Ofbiz.Order.CustRequestStatus
    resource UniboV4.Ofbiz.Order.CustRequestStatus.Version
    resource UniboV4.Ofbiz.Order.CustRequestType
    resource UniboV4.Ofbiz.Order.CustRequestType.Version
    resource UniboV4.Ofbiz.Order.CustRequestTypeAttr
    resource UniboV4.Ofbiz.Order.CustRequestTypeAttr.Version
    resource UniboV4.Ofbiz.Order.CustRequestWorkEffort
    resource UniboV4.Ofbiz.Order.CustRequestWorkEffort.Version
    resource UniboV4.Ofbiz.Order.RespondingParty
    resource UniboV4.Ofbiz.Order.DesiredFeature
    resource UniboV4.Ofbiz.Order.DesiredFeature.Version
    resource UniboV4.Ofbiz.Order.OrderRequirementCommitment
    resource UniboV4.Ofbiz.Order.OrderRequirementCommitment.Version
    resource UniboV4.Ofbiz.Order.Requirement
    resource UniboV4.Ofbiz.Order.Requirement.Version
    resource UniboV4.Ofbiz.Order.RequirementAttribute
    resource UniboV4.Ofbiz.Order.RequirementAttribute.Version
    resource UniboV4.Ofbiz.Order.RequirementBudgetAllocation
    resource UniboV4.Ofbiz.Order.RequirementCustRequest
    resource UniboV4.Ofbiz.Order.RequirementCustRequest.Version
    resource UniboV4.Ofbiz.Order.RequirementRole
    resource UniboV4.Ofbiz.Order.RequirementStatus
    resource UniboV4.Ofbiz.Order.RequirementStatus.Version
    resource UniboV4.Ofbiz.Order.RequirementType
    resource UniboV4.Ofbiz.Order.RequirementType.Version
    resource UniboV4.Ofbiz.Order.RequirementTypeAttr
    resource UniboV4.Ofbiz.Order.RequirementTypeAttr.Version
    resource UniboV4.Ofbiz.Order.WorkReqFulfType
    resource UniboV4.Ofbiz.Order.WorkReqFulfType.Version
    resource UniboV4.Ofbiz.Order.WorkRequirementFulfillment
    resource UniboV4.Ofbiz.Order.WorkRequirementFulfillment.Version
    resource UniboV4.Ofbiz.Order.ReturnAdjustment
    resource UniboV4.Ofbiz.Order.ReturnAdjustment.Version
    resource UniboV4.Ofbiz.Order.ReturnAdjustmentType
    resource UniboV4.Ofbiz.Order.ReturnAdjustmentType.Version
    resource UniboV4.Ofbiz.Order.ReturnHeader
    resource UniboV4.Ofbiz.Order.ReturnHeader.Version
    resource UniboV4.Ofbiz.Order.ReturnHeaderType
    resource UniboV4.Ofbiz.Order.ReturnHeaderType.Version
    resource UniboV4.Ofbiz.Order.ReturnItem
    resource UniboV4.Ofbiz.Order.ReturnItem.Version
    resource UniboV4.Ofbiz.Order.ReturnItemResponse
    resource UniboV4.Ofbiz.Order.ReturnItemResponse.Version
    resource UniboV4.Ofbiz.Order.ReturnItemType
    resource UniboV4.Ofbiz.Order.ReturnItemType.Version
    resource UniboV4.Ofbiz.Order.ReturnItemTypeMap
    resource UniboV4.Ofbiz.Order.ReturnItemTypeMap.Version
    resource UniboV4.Ofbiz.Order.ReturnReason
    resource UniboV4.Ofbiz.Order.ReturnReason.Version
    resource UniboV4.Ofbiz.Order.ReturnStatus
    resource UniboV4.Ofbiz.Order.ReturnStatus.Version
    resource UniboV4.Ofbiz.Order.ReturnType
    resource UniboV4.Ofbiz.Order.ReturnType.Version
    resource UniboV4.Ofbiz.Order.ReturnItemBilling
    resource UniboV4.Ofbiz.Order.ReturnItemShipment
    resource UniboV4.Ofbiz.Order.ReturnContactMech
    resource UniboV4.Ofbiz.Order.CommunicationEventReturn
    resource UniboV4.Ofbiz.Order.CommunicationEventReturn.Version
    resource UniboV4.Ofbiz.Order.CartAbandonedLine
    resource UniboV4.Ofbiz.Order.ShoppingList
    resource UniboV4.Ofbiz.Order.ShoppingList.Version
    resource UniboV4.Ofbiz.Order.ShoppingListItem
    resource UniboV4.Ofbiz.Order.ShoppingListItem.Version
    resource UniboV4.Ofbiz.Order.ShoppingListItemAttribute
    resource UniboV4.Ofbiz.Order.ShoppingListItemSurvey
    resource UniboV4.Ofbiz.Order.ShoppingListType
    resource UniboV4.Ofbiz.Order.ShoppingListType.Version
    resource UniboV4.Ofbiz.Order.ShoppingListWorkEffort
    resource UniboV4.Ofbiz.Order.ShoppingListWorkEffort.Version
    resource UniboV4.Ofbiz.Order.AllocationPlanType
    resource UniboV4.Ofbiz.Order.AllocationPlanType.Version
    resource UniboV4.Ofbiz.Order.AllocationPlanHeader
    resource UniboV4.Ofbiz.Order.AllocationPlanItem
  end
end
