# Generated by bdd_compiler from /home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl. DO NOT EDIT.

defmodule UniboExPoc.BDD.Generated.ACCOUNTING_PAYMENT_APPLICATIONTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_create_create
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_create_create]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_create_create"}
    # line 4: GIVEN given_seed_context id="accounting_payment_application_action_payment_application_create_create" module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_payment_application_action_payment_application_create_create", module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 4, raw: "GIVEN given_seed_context id=\"accounting_payment_application_action_payment_application_create_create\" module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_destroy_destroy_2
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_destroy_destroy_2]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_destroy_destroy_2"}
    # line 9: GIVEN given_seed_context id="accounting_payment_application_action_payment_application_destroy_destroy_2" module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_payment_application_action_payment_application_destroy_destroy_2", module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 9, raw: "GIVEN given_seed_context id=\"accounting_payment_application_action_payment_application_destroy_destroy_2\" module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_update_update
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_update_update]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_update_update"}
    # line 14: GIVEN given_seed_context id="accounting_payment_application_action_payment_application_update_update" module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_payment_application_action_payment_application_update_update", module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 14, raw: "GIVEN given_seed_context id=\"accounting_payment_application_action_payment_application_update_update\" module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_workflow_payment_application_payment_application_lifecycle
  @tag :seed
  @tag :workflow_contract
  test "[BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_workflow_payment_application_payment_application_lifecycle]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_workflow_payment_application_payment_application_lifecycle"}
    # line 19: GIVEN given_seed_context id="accounting_payment_application_workflow_payment_application_payment_application_lifecycle" module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_payment_application_workflow_payment_application_payment_application_lifecycle", module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 19, raw: "GIVEN given_seed_context id=\"accounting_payment_application_workflow_payment_application_payment_application_lifecycle\" module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_destroy_destroy
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_destroy_destroy]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_destroy_destroy"}
    # line 24: GIVEN given_seed_context id="accounting_payment_application_action_payment_application_destroy_destroy" module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_payment_application_action_payment_application_destroy_destroy", module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 24, raw: "GIVEN given_seed_context id=\"accounting_payment_application_action_payment_application_destroy_destroy\" module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 24)
    # line 25: WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 25, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 25)
    # line 26: THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 26, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_read_read
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_read_read]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_read_read"}
    # line 29: GIVEN given_seed_context id="accounting_payment_application_action_payment_application_read_read" module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_payment_application_action_payment_application_read_read", module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 29, raw: "GIVEN given_seed_context id=\"accounting_payment_application_action_payment_application_read_read\" module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 29)
    # line 30: WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 30, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 30)
    # line 31: THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 31, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 31)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_read_read_2
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_read_read_2]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_read_read_2"}
    # line 34: GIVEN given_seed_context id="accounting_payment_application_action_payment_application_read_read_2" module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_payment_application_action_payment_application_read_read_2", module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 34, raw: "GIVEN given_seed_context id=\"accounting_payment_application_action_payment_application_read_read_2\" module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 34)
    # line 35: WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 35, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 35)
    # line 36: THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 36, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_create_create_2
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_create_create_2]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_create_create_2"}
    # line 39: GIVEN given_seed_context id="accounting_payment_application_action_payment_application_create_create_2" module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_payment_application_action_payment_application_create_create_2", module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 39, raw: "GIVEN given_seed_context id=\"accounting_payment_application_action_payment_application_create_create_2\" module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 39)
    # line 40: WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 40, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 40)
    # line 41: THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_PAYMENT_APPLICATION"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ACCOUNTING_PAYMENT_APPLICATION.dsl", line: 41, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_PAYMENT_APPLICATION\""}, 41)
    _ctx = ctx
    :ok
  end

end
