# Generated by bdd_compiler from /home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl. DO NOT EDIT.

defmodule UniboExPoc.BDD.Generated.ACCOUNTING_GL_JOURNALTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_update_update
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_update_update]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_update_update"}
    # line 4: GIVEN given_seed_context id="accounting_gl_journal_action_gl_journal_update_update" module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_gl_journal_action_gl_journal_update_update", module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 4, raw: "GIVEN given_seed_context id=\"accounting_gl_journal_action_gl_journal_update_update\" module=\"ACCOUNTING_GL_JOURNAL\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_GL_JOURNAL\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_GL_JOURNAL\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_destroy_destroy
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_destroy_destroy]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_destroy_destroy"}
    # line 9: GIVEN given_seed_context id="accounting_gl_journal_action_gl_journal_destroy_destroy" module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_gl_journal_action_gl_journal_destroy_destroy", module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 9, raw: "GIVEN given_seed_context id=\"accounting_gl_journal_action_gl_journal_destroy_destroy\" module=\"ACCOUNTING_GL_JOURNAL\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_GL_JOURNAL\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_GL_JOURNAL\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_create_create
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_create_create]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_create_create"}
    # line 14: GIVEN given_seed_context id="accounting_gl_journal_action_gl_journal_create_create" module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_gl_journal_action_gl_journal_create_create", module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 14, raw: "GIVEN given_seed_context id=\"accounting_gl_journal_action_gl_journal_create_create\" module=\"ACCOUNTING_GL_JOURNAL\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_GL_JOURNAL\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_GL_JOURNAL\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_read_read
  @tag :action_contract
  @tag :seed
  test "[BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_read_read]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_read_read"}
    # line 19: GIVEN given_seed_context id="accounting_gl_journal_action_gl_journal_read_read" module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "accounting_gl_journal_action_gl_journal_read_read", module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 19, raw: "GIVEN given_seed_context id=\"accounting_gl_journal_action_gl_journal_read_read\" module=\"ACCOUNTING_GL_JOURNAL\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"ACCOUNTING_GL_JOURNAL\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="ACCOUNTING_GL_JOURNAL"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ACCOUNTING_GL_JOURNAL"}, %{file: "/home/wangbo/unibo_ex_poc-travel-recompile/travel/docs/bdd/features/ACCOUNTING_GL_JOURNAL.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"ACCOUNTING_GL_JOURNAL\""}, 21)
    _ctx = ctx
    :ok
  end

end
