# Generated by bdd_compiler from /home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl. DO NOT EDIT.

defmodule UniboExPoc.BDD.Generated.DELIVERY_SHIPMENT_ROUTE_SEGMENTTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated
  @tag :event_contract
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated"}
    # line 4: GIVEN given_seed_context id="delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 4, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_read_read
  @tag :action_contract
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_read_read]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_read_read"}
    # line 9: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_read_read" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_read_read", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 9, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_read_read\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update
  @tag :action_contract
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update"}
    # line 14: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 14, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update
  @tag :action_contract
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update"}
    # line 19: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 19, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update
  @tag :action_contract
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update"}
    # line 24: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_update_update" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_update_update", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 24, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_update_update\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 24)
    # line 25: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 25, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 25)
    # line 26: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 26, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update
  @tag :action_contract
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update"}
    # line 29: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 29, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 29)
    # line 30: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 30, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 30)
    # line 31: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 31, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 31)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create
  @tag :action_contract
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create"}
    # line 34: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_create_create" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_create_create", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 34, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_create_create\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 34)
    # line 35: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 35, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 35)
    # line 36: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 36, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow
  @tag :seed
  @tag :workflow_contract
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow"}
    # line 39: GIVEN given_seed_context id="delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 39, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 39)
    # line 40: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 40, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 40)
    # line 41: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 41, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy
  @tag :action_contract
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy"}
    # line 44: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 44, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 44)
    # line 45: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 45, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 45)
    # line 46: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 46, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 46)
    _ctx = ctx
    :ok
  end

end
