# Generated by bdd_compiler from /home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl. DO NOT EDIT.

defmodule BDD.Generated.ORDER_QUOTETest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-ORDER_QUOTE-SEED-order_quote_action_quote_read_read
  @tag :action_contract
  @tag :seed
  test "[BDD-ORDER_QUOTE-SEED-order_quote_action_quote_read_read]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ORDER_QUOTE-SEED-order_quote_action_quote_read_read"}
    # line 4: GIVEN given_seed_context id="order_quote_action_quote_read_read" module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "order_quote_action_quote_read_read", module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 4, raw: "GIVEN given_seed_context id=\"order_quote_action_quote_read_read\" module=\"ORDER_QUOTE\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"ORDER_QUOTE\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"ORDER_QUOTE\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ORDER_QUOTE-SEED-order_quote_action_quote_create_create
  @tag :action_contract
  @tag :seed
  test "[BDD-ORDER_QUOTE-SEED-order_quote_action_quote_create_create]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ORDER_QUOTE-SEED-order_quote_action_quote_create_create"}
    # line 9: GIVEN given_seed_context id="order_quote_action_quote_create_create" module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "order_quote_action_quote_create_create", module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 9, raw: "GIVEN given_seed_context id=\"order_quote_action_quote_create_create\" module=\"ORDER_QUOTE\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"ORDER_QUOTE\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"ORDER_QUOTE\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ORDER_QUOTE-SEED-order_quote_action_quote_destroy_destroy
  @tag :action_contract
  @tag :seed
  test "[BDD-ORDER_QUOTE-SEED-order_quote_action_quote_destroy_destroy]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ORDER_QUOTE-SEED-order_quote_action_quote_destroy_destroy"}
    # line 14: GIVEN given_seed_context id="order_quote_action_quote_destroy_destroy" module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "order_quote_action_quote_destroy_destroy", module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 14, raw: "GIVEN given_seed_context id=\"order_quote_action_quote_destroy_destroy\" module=\"ORDER_QUOTE\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"ORDER_QUOTE\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"ORDER_QUOTE\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-ORDER_QUOTE-SEED-order_quote_action_quote_update_update
  @tag :action_contract
  @tag :seed
  test "[BDD-ORDER_QUOTE-SEED-order_quote_action_quote_update_update]" do
    run_id = UniboExPoc.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ORDER_QUOTE-SEED-order_quote_action_quote_update_update"}
    # line 19: GIVEN given_seed_context id="order_quote_action_quote_update_update" module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "order_quote_action_quote_update_update", module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 19, raw: "GIVEN given_seed_context id=\"order_quote_action_quote_update_update\" module=\"ORDER_QUOTE\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"ORDER_QUOTE\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="ORDER_QUOTE"
    ctx = UniboExPoc.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ORDER_QUOTE"}, %{file: "/home/wangbo/document/unibo_ex_poc/travel/docs/bdd/features/ORDER_QUOTE.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"ORDER_QUOTE\""}, 21)
    _ctx = ctx
    :ok
  end

end
