[SCENARIO: BDD-CURRENCY_CURRENCY-SEED-currency_currency_action_currency_destroy_destroy_risk_success] TITLE: CURRENCY_CURRENCY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="currency_currency_action_currency_destroy_destroy_risk_success" module="CURRENCY_CURRENCY"
WHEN when_execute_seed_contract module="CURRENCY_CURRENCY"
THEN then_seed_contract_should_hold module="CURRENCY_CURRENCY"
