[SCENARIO: BDD-CURRENCY_CURRENCY-SEED-currency_currency_action_currency_create_create_risk_validation_fail] TITLE: CURRENCY_CURRENCY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="currency_currency_action_currency_create_create_risk_validation_fail" module="CURRENCY_CURRENCY"
WHEN when_execute_seed_contract module="CURRENCY_CURRENCY"
THEN then_seed_contract_should_hold module="CURRENCY_CURRENCY"
