[SCENARIO: BDD-DATA_RECYCLE_RECYCLE_RECORD-SEED-data_recycle_recycle_record_action_recycle_record_validate_update] TITLE: DATA_RECYCLE_RECYCLE_RECORD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="data_recycle_recycle_record_action_recycle_record_validate_update" module="DATA_RECYCLE_RECYCLE_RECORD"
WHEN when_execute_seed_contract module="DATA_RECYCLE_RECYCLE_RECORD"
THEN then_seed_contract_should_hold module="DATA_RECYCLE_RECYCLE_RECORD"
