[SCENARIO: BDD-DATA_RECYCLE_RECYCLE_MODEL-SEED-data_recycle_recycle_model_workflow_recycle_model_recycle_model_lifecycle_risk_mainline] TITLE: DATA_RECYCLE_RECYCLE_MODEL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="data_recycle_recycle_model_workflow_recycle_model_recycle_model_lifecycle_risk_mainline" module="DATA_RECYCLE_RECYCLE_MODEL"
WHEN when_execute_seed_contract module="DATA_RECYCLE_RECYCLE_MODEL"
THEN then_seed_contract_should_hold module="DATA_RECYCLE_RECYCLE_MODEL"
