[SCENARIO: BDD-MARKETING_MAILING-SEED-marketing_mailing_action_mailing_send_winner_mailing_update_risk_success] TITLE: MARKETING_MAILING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_mailing_action_mailing_send_winner_mailing_update_risk_success" module="MARKETING_MAILING"
WHEN when_execute_seed_contract module="MARKETING_MAILING"
THEN then_seed_contract_should_hold module="MARKETING_MAILING"
