[SCENARIO: BDD-MARKETING_EVENT_REGISTRATION-SEED-marketing_event_registration_workflow_event_registration_event_registration_lifecycle] TITLE: MARKETING_EVENT_REGISTRATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_event_registration_workflow_event_registration_event_registration_lifecycle" module="MARKETING_EVENT_REGISTRATION"
WHEN when_execute_seed_contract module="MARKETING_EVENT_REGISTRATION"
THEN then_seed_contract_should_hold module="MARKETING_EVENT_REGISTRATION"
