[SCENARIO: BDD-MARKETING_EVENT_BOOTH-SEED-marketing_event_booth_workflow_event_booth_event_booth_lifecycle_risk_mainline] TITLE: MARKETING_EVENT_BOOTH contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_event_booth_workflow_event_booth_event_booth_lifecycle_risk_mainline" module="MARKETING_EVENT_BOOTH"
WHEN when_execute_seed_contract module="MARKETING_EVENT_BOOTH"
THEN then_seed_contract_should_hold module="MARKETING_EVENT_BOOTH"
