[SCENARIO: BDD-MARKETING_AUTOMATION_ACTIVITY-SEED-marketing_automation_activity_workflow_automation_activity_automation_activity_maintain_flow_risk_branch_or_exception] TITLE: MARKETING_AUTOMATION_ACTIVITY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_automation_activity_workflow_automation_activity_automation_activity_maintain_flow_risk_branch_or_exception" module="MARKETING_AUTOMATION_ACTIVITY"
WHEN when_execute_seed_contract module="MARKETING_AUTOMATION_ACTIVITY"
THEN then_seed_contract_should_hold module="MARKETING_AUTOMATION_ACTIVITY"
