[SCENARIO: BDD-MARKETING_EVENT_MAIL_SCHEDULE-SEED-marketing_event_mail_schedule_workflow_event_mail_schedule_event_mail_schedule_maintain_flow_risk_branch_or_exception] TITLE: MARKETING_EVENT_MAIL_SCHEDULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_event_mail_schedule_workflow_event_mail_schedule_event_mail_schedule_maintain_flow_risk_branch_or_exception" module="MARKETING_EVENT_MAIL_SCHEDULE"
WHEN when_execute_seed_contract module="MARKETING_EVENT_MAIL_SCHEDULE"
THEN then_seed_contract_should_hold module="MARKETING_EVENT_MAIL_SCHEDULE"
