[SCENARIO: BDD-MARKETING_AUTOMATION_CAMPAIGN-SEED-marketing_automation_campaign_action_automation_campaign_update_update] TITLE: MARKETING_AUTOMATION_CAMPAIGN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_automation_campaign_action_automation_campaign_update_update" module="MARKETING_AUTOMATION_CAMPAIGN"
WHEN when_execute_seed_contract module="MARKETING_AUTOMATION_CAMPAIGN"
THEN then_seed_contract_should_hold module="MARKETING_AUTOMATION_CAMPAIGN"
