[SCENARIO: BDD-MARKETING_CAMPAIGN_ROLE-SEED-marketing_campaign_role_workflow_campaign_role_campaign_role_manage_flow_risk_branch_or_exception] TITLE: MARKETING_CAMPAIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_campaign_role_workflow_campaign_role_campaign_role_manage_flow_risk_branch_or_exception" module="MARKETING_CAMPAIGN_ROLE"
WHEN when_execute_seed_contract module="MARKETING_CAMPAIGN_ROLE"
THEN then_seed_contract_should_hold module="MARKETING_CAMPAIGN_ROLE"
