[SCENARIO: BDD-MARKETING_EVENT_MAIL_SCHEDULE-SEED-marketing_event_mail_schedule_action_event_mail_schedule_create_create_risk_validation_fail] TITLE: MARKETING_EVENT_MAIL_SCHEDULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_event_mail_schedule_action_event_mail_schedule_create_create_risk_validation_fail" module="MARKETING_EVENT_MAIL_SCHEDULE"
WHEN when_execute_seed_contract module="MARKETING_EVENT_MAIL_SCHEDULE"
THEN then_seed_contract_should_hold module="MARKETING_EVENT_MAIL_SCHEDULE"
