[SCENARIO: BDD-MARKETING_UTM_SOURCE-SEED-marketing_utm_source_workflow_utm_source_utm_source_maintain_flow_risk_mainline] TITLE: MARKETING_UTM_SOURCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_utm_source_workflow_utm_source_utm_source_maintain_flow_risk_mainline" module="MARKETING_UTM_SOURCE"
WHEN when_execute_seed_contract module="MARKETING_UTM_SOURCE"
THEN then_seed_contract_should_hold module="MARKETING_UTM_SOURCE"
