[SCENARIO: BDD-MARKETING_EVENT-SEED-marketing_event_action_event_complete_update_risk_validation_fail] TITLE: MARKETING_EVENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_event_action_event_complete_update_risk_validation_fail" module="MARKETING_EVENT"
WHEN when_execute_seed_contract module="MARKETING_EVENT"
THEN then_seed_contract_should_hold module="MARKETING_EVENT"
