[SCENARIO: BDD-MARKETING_UTM_SOURCE-SEED-marketing_utm_source_action_utm_source_update_update_risk_success] TITLE: MARKETING_UTM_SOURCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_utm_source_action_utm_source_update_update_risk_success" module="MARKETING_UTM_SOURCE"
WHEN when_execute_seed_contract module="MARKETING_UTM_SOURCE"
THEN then_seed_contract_should_hold module="MARKETING_UTM_SOURCE"
