[SCENARIO: BDD-MARKETING_SOCIAL_POST-SEED-marketing_social_post_action_social_post_schedule_update_risk_success] TITLE: MARKETING_SOCIAL_POST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_social_post_action_social_post_schedule_update_risk_success" module="MARKETING_SOCIAL_POST"
WHEN when_execute_seed_contract module="MARKETING_SOCIAL_POST"
THEN then_seed_contract_should_hold module="MARKETING_SOCIAL_POST"
