[SCENARIO: BDD-MARKETING_SMS_TEMPLATE-SEED-marketing_sms_template_action_sms_template_unlink_sidebar_action_custom_risk_change_effect] TITLE: MARKETING_SMS_TEMPLATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_sms_template_action_sms_template_unlink_sidebar_action_custom_risk_change_effect" module="MARKETING_SMS_TEMPLATE"
WHEN when_execute_seed_contract module="MARKETING_SMS_TEMPLATE"
THEN then_seed_contract_should_hold module="MARKETING_SMS_TEMPLATE"
