[SCENARIO: BDD-MARKETING_UTM_CAMPAIGN-SEED-marketing_utm_campaign_workflow_utm_campaign_utm_campaign_maintain_flow_risk_branch_or_exception] TITLE: MARKETING_UTM_CAMPAIGN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_utm_campaign_workflow_utm_campaign_utm_campaign_maintain_flow_risk_branch_or_exception" module="MARKETING_UTM_CAMPAIGN"
WHEN when_execute_seed_contract module="MARKETING_UTM_CAMPAIGN"
THEN then_seed_contract_should_hold module="MARKETING_UTM_CAMPAIGN"
