[SCENARIO: BDD-UOM_UOM_CATEGORY-SEED-uom_uom_category_workflow_uom_category_uom_category_maintain_flow_risk_mainline] TITLE: UOM_UOM_CATEGORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="uom_uom_category_workflow_uom_category_uom_category_maintain_flow_risk_mainline" module="UOM_UOM_CATEGORY"
WHEN when_execute_seed_contract module="UOM_UOM_CATEGORY"
THEN then_seed_contract_should_hold module="UOM_UOM_CATEGORY"
