defmodule UniboV4.Ofbiz.HumanRes do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.HumanRes.PartyQual
    resource UniboV4.Ofbiz.HumanRes.PartyQual.Version
    resource UniboV4.Ofbiz.HumanRes.PartyQualType
    resource UniboV4.Ofbiz.HumanRes.PartyQualType.Version
    resource UniboV4.Ofbiz.HumanRes.PartyResume
    resource UniboV4.Ofbiz.HumanRes.PartyResume.Version
    resource UniboV4.Ofbiz.HumanRes.PartySkill
    resource UniboV4.Ofbiz.HumanRes.PartySkill.Version
    resource UniboV4.Ofbiz.HumanRes.PerfRatingType
    resource UniboV4.Ofbiz.HumanRes.PerfRatingType.Version
    resource UniboV4.Ofbiz.HumanRes.PerfReview
    resource UniboV4.Ofbiz.HumanRes.PerfReviewItem
    resource UniboV4.Ofbiz.HumanRes.PerfReviewItemType
    resource UniboV4.Ofbiz.HumanRes.PerfReviewItemType.Version
    resource UniboV4.Ofbiz.HumanRes.PerformanceNote
    resource UniboV4.Ofbiz.HumanRes.PersonTraining
    resource UniboV4.Ofbiz.HumanRes.PersonTraining.Version
    resource UniboV4.Ofbiz.HumanRes.ResponsibilityType
    resource UniboV4.Ofbiz.HumanRes.ResponsibilityType.Version
    resource UniboV4.Ofbiz.HumanRes.SkillType
    resource UniboV4.Ofbiz.HumanRes.SkillType.Version
    resource UniboV4.Ofbiz.HumanRes.TrainingClassType
    resource UniboV4.Ofbiz.HumanRes.TrainingClassType.Version
    resource UniboV4.Ofbiz.HumanRes.BenefitType
    resource UniboV4.Ofbiz.HumanRes.BenefitType.Version
    resource UniboV4.Ofbiz.HumanRes.Employment
    resource UniboV4.Ofbiz.HumanRes.EmploymentApp
    resource UniboV4.Ofbiz.HumanRes.EmploymentApp.Version
    resource UniboV4.Ofbiz.HumanRes.EmploymentAppSourceType
    resource UniboV4.Ofbiz.HumanRes.EmploymentAppSourceType.Version
    resource UniboV4.Ofbiz.HumanRes.EmplLeave
    resource UniboV4.Ofbiz.HumanRes.EmplLeave.Version
    resource UniboV4.Ofbiz.HumanRes.EmplLeaveType
    resource UniboV4.Ofbiz.HumanRes.EmplLeaveType.Version
    resource UniboV4.Ofbiz.HumanRes.PartyBenefit
    resource UniboV4.Ofbiz.HumanRes.PayGrade
    resource UniboV4.Ofbiz.HumanRes.PayGrade.Version
    resource UniboV4.Ofbiz.HumanRes.PayHistory
    resource UniboV4.Ofbiz.HumanRes.PayrollPreference
    resource UniboV4.Ofbiz.HumanRes.SalaryStep
    resource UniboV4.Ofbiz.HumanRes.TerminationReason
    resource UniboV4.Ofbiz.HumanRes.TerminationReason.Version
    resource UniboV4.Ofbiz.HumanRes.TerminationType
    resource UniboV4.Ofbiz.HumanRes.TerminationType.Version
    resource UniboV4.Ofbiz.HumanRes.UnemploymentClaim
    resource UniboV4.Ofbiz.HumanRes.UnemploymentClaim.Version
    resource UniboV4.Ofbiz.HumanRes.EmplPosition
    resource UniboV4.Ofbiz.HumanRes.EmplPosition.Version
    resource UniboV4.Ofbiz.HumanRes.EmplPositionClassType
    resource UniboV4.Ofbiz.HumanRes.EmplPositionClassType.Version
    resource UniboV4.Ofbiz.HumanRes.EmplPositionFulfillment
    resource UniboV4.Ofbiz.HumanRes.EmplPositionFulfillment.Version
    resource UniboV4.Ofbiz.HumanRes.EmplPositionReportingStruct
    resource UniboV4.Ofbiz.HumanRes.EmplPositionReportingStruct.Version
    resource UniboV4.Ofbiz.HumanRes.EmplPositionResponsibility
    resource UniboV4.Ofbiz.HumanRes.EmplPositionResponsibility.Version
    resource UniboV4.Ofbiz.HumanRes.EmplPositionType
    resource UniboV4.Ofbiz.HumanRes.EmplPositionType.Version
    resource UniboV4.Ofbiz.HumanRes.EmplPositionTypeClass
    resource UniboV4.Ofbiz.HumanRes.EmplPositionTypeClass.Version
    resource UniboV4.Ofbiz.HumanRes.ValidResponsibility
    resource UniboV4.Ofbiz.HumanRes.ValidResponsibility.Version
    resource UniboV4.Ofbiz.HumanRes.EmplPositionTypeRate
    resource UniboV4.Ofbiz.HumanRes.EmplPositionTypeRate.Version
    resource UniboV4.Ofbiz.HumanRes.JobRequisition
    resource UniboV4.Ofbiz.HumanRes.JobRequisition.Version
    resource UniboV4.Ofbiz.HumanRes.JobInterview
    resource UniboV4.Ofbiz.HumanRes.JobInterview.Version
    resource UniboV4.Ofbiz.HumanRes.JobInterviewType
    resource UniboV4.Ofbiz.HumanRes.JobInterviewType.Version
    resource UniboV4.Ofbiz.HumanRes.TrainingRequest
    resource UniboV4.Ofbiz.HumanRes.TrainingRequest.Version
    resource UniboV4.Ofbiz.HumanRes.EmplLeaveReasonType
    resource UniboV4.Ofbiz.HumanRes.EmplLeaveReasonType.Version
    resource UniboV4.Ofbiz.HumanRes.Content
    resource UniboV4.Ofbiz.HumanRes.DeductionType
    resource UniboV4.Ofbiz.HumanRes.Enumeration
    resource UniboV4.Ofbiz.HumanRes.Party
    resource UniboV4.Ofbiz.HumanRes.Payment
    resource UniboV4.Ofbiz.HumanRes.PaymentMethodType
    resource UniboV4.Ofbiz.HumanRes.PeriodType
    resource UniboV4.Ofbiz.HumanRes.Person
    resource UniboV4.Ofbiz.HumanRes.RateType
    resource UniboV4.Ofbiz.HumanRes.StatusItem
    resource UniboV4.Ofbiz.HumanRes.WorkEffort
  end
end
