[SCENARIO: BDD-SCHEDULING_SCHEDULING_PERIOD-SEED-action_scheduling_period_mark_generated_update_risk_validation_fail] TITLE: SCHEDULING_SCHEDULING_PERIOD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_scheduling_period_mark_generated_update_risk_validation_fail" module="SCHEDULING_SCHEDULING_PERIOD"
WHEN when_execute_seed_contract module="SCHEDULING_SCHEDULING_PERIOD"
THEN then_seed_contract_should_hold module="SCHEDULING_SCHEDULING_PERIOD"
