[SCENARIO: BDD-SCHEDULING_SCHEDULING_CONSTRAINT-SEED-action_scheduling_constraint_destroy_destroy] TITLE: SCHEDULING_SCHEDULING_CONSTRAINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_scheduling_constraint_destroy_destroy" module="SCHEDULING_SCHEDULING_CONSTRAINT"
WHEN when_execute_seed_contract module="SCHEDULING_SCHEDULING_CONSTRAINT"
THEN then_seed_contract_should_hold module="SCHEDULING_SCHEDULING_CONSTRAINT"
