[SCENARIO: BDD-SCHEDULING_SCHEDULING_PERIOD-SEED-action_scheduling_period_mark_adjusted_update_risk_success] TITLE: SCHEDULING_SCHEDULING_PERIOD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_scheduling_period_mark_adjusted_update_risk_success" module="SCHEDULING_SCHEDULING_PERIOD"
WHEN when_execute_seed_contract module="SCHEDULING_SCHEDULING_PERIOD"
THEN then_seed_contract_should_hold module="SCHEDULING_SCHEDULING_PERIOD"
