[SCENARIO: BDD-SCHEDULING_SHIFT_TYPE-SEED-action_shift_type_create_create_risk_validation_fail] TITLE: SCHEDULING_SHIFT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_shift_type_create_create_risk_validation_fail" module="SCHEDULING_SHIFT_TYPE"
WHEN when_execute_seed_contract module="SCHEDULING_SHIFT_TYPE"
THEN then_seed_contract_should_hold module="SCHEDULING_SHIFT_TYPE"
