[SCENARIO: BDD-SCHEDULING_COVERAGE_REQUIREMENT-SEED-action_coverage_requirement_destroy_destroy_risk_success] TITLE: SCHEDULING_COVERAGE_REQUIREMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_coverage_requirement_destroy_destroy_risk_success" module="SCHEDULING_COVERAGE_REQUIREMENT"
WHEN when_execute_seed_contract module="SCHEDULING_COVERAGE_REQUIREMENT"
THEN then_seed_contract_should_hold module="SCHEDULING_COVERAGE_REQUIREMENT"
