[SCENARIO: BDD-SCHEDULING_SCHEDULING_PERIOD-SEED-determination_scheduling_period_on_schedule_version_publish_risk_read_set_unavailable] TITLE: SCHEDULING_SCHEDULING_PERIOD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="determination_scheduling_period_on_schedule_version_publish_risk_read_set_unavailable" module="SCHEDULING_SCHEDULING_PERIOD"
WHEN when_execute_seed_contract module="SCHEDULING_SCHEDULING_PERIOD"
THEN then_seed_contract_should_hold module="SCHEDULING_SCHEDULING_PERIOD"
