[SCENARIO: BDD-SCHEDULING_SOLVER_RUN-SEED-workflow_solver_run_solver_run_lifecycle_risk_mainline] TITLE: SCHEDULING_SOLVER_RUN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="workflow_solver_run_solver_run_lifecycle_risk_mainline" module="SCHEDULING_SOLVER_RUN"
WHEN when_execute_seed_contract module="SCHEDULING_SOLVER_RUN"
THEN then_seed_contract_should_hold module="SCHEDULING_SOLVER_RUN"
