defmodule UniboV4.Ofbiz.Content do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.Content.Content
    resource UniboV4.Ofbiz.Content.Content.Version
    resource UniboV4.Ofbiz.Content.ContentApproval
    resource UniboV4.Ofbiz.Content.ContentApproval.Version
    resource UniboV4.Ofbiz.Content.ContentAssoc
    resource UniboV4.Ofbiz.Content.ContentAssoc.Version
    resource UniboV4.Ofbiz.Content.ContentAssocPredicate
    resource UniboV4.Ofbiz.Content.ContentAssocPredicate.Version
    resource UniboV4.Ofbiz.Content.ContentAssocType
    resource UniboV4.Ofbiz.Content.ContentAssocType.Version
    resource UniboV4.Ofbiz.Content.ContentAttribute
    resource UniboV4.Ofbiz.Content.ContentAttribute.Version
    resource UniboV4.Ofbiz.Content.ContentMetaData
    resource UniboV4.Ofbiz.Content.ContentMetaData.Version
    resource UniboV4.Ofbiz.Content.ContentOperation
    resource UniboV4.Ofbiz.Content.ContentOperation.Version
    resource UniboV4.Ofbiz.Content.ContentPurpose
    resource UniboV4.Ofbiz.Content.ContentPurpose.Version
    resource UniboV4.Ofbiz.Content.ContentPurposeOperation
    resource UniboV4.Ofbiz.Content.ContentPurposeType
    resource UniboV4.Ofbiz.Content.ContentPurposeType.Version
    resource UniboV4.Ofbiz.Content.ContentRevision
    resource UniboV4.Ofbiz.Content.ContentRevision.Version
    resource UniboV4.Ofbiz.Content.ContentRevisionItem
    resource UniboV4.Ofbiz.Content.ContentRole
    resource UniboV4.Ofbiz.Content.ContentType
    resource UniboV4.Ofbiz.Content.ContentType.Version
    resource UniboV4.Ofbiz.Content.ContentTypeAttr
    resource UniboV4.Ofbiz.Content.ContentTypeAttr.Version
    resource UniboV4.Ofbiz.Content.AudioDataResource
    resource UniboV4.Ofbiz.Content.AudioDataResource.Version
    resource UniboV4.Ofbiz.Content.CharacterSet
    resource UniboV4.Ofbiz.Content.CharacterSet.Version
    resource UniboV4.Ofbiz.Content.DataCategory
    resource UniboV4.Ofbiz.Content.DataCategory.Version
    resource UniboV4.Ofbiz.Content.DataResource
    resource UniboV4.Ofbiz.Content.DataResource.Version
    resource UniboV4.Ofbiz.Content.DataResourceAttribute
    resource UniboV4.Ofbiz.Content.DataResourceAttribute.Version
    resource UniboV4.Ofbiz.Content.DataResourceMetaData
    resource UniboV4.Ofbiz.Content.DataResourceMetaData.Version
    resource UniboV4.Ofbiz.Content.DataResourcePurpose
    resource UniboV4.Ofbiz.Content.DataResourcePurpose.Version
    resource UniboV4.Ofbiz.Content.DataResourceRole
    resource UniboV4.Ofbiz.Content.DataResourceType
    resource UniboV4.Ofbiz.Content.DataResourceType.Version
    resource UniboV4.Ofbiz.Content.DataResourceTypeAttr
    resource UniboV4.Ofbiz.Content.DataResourceTypeAttr.Version
    resource UniboV4.Ofbiz.Content.DataTemplateType
    resource UniboV4.Ofbiz.Content.DataTemplateType.Version
    resource UniboV4.Ofbiz.Content.ElectronicText
    resource UniboV4.Ofbiz.Content.ElectronicText.Version
    resource UniboV4.Ofbiz.Content.FileExtension
    resource UniboV4.Ofbiz.Content.FileExtension.Version
    resource UniboV4.Ofbiz.Content.ImageDataResource
    resource UniboV4.Ofbiz.Content.ImageDataResource.Version
    resource UniboV4.Ofbiz.Content.MetaDataPredicate
    resource UniboV4.Ofbiz.Content.MetaDataPredicate.Version
    resource UniboV4.Ofbiz.Content.MimeType
    resource UniboV4.Ofbiz.Content.MimeType.Version
    resource UniboV4.Ofbiz.Content.MimeTypeHtmlTemplate
    resource UniboV4.Ofbiz.Content.MimeTypeHtmlTemplate.Version
    resource UniboV4.Ofbiz.Content.OtherDataResource
    resource UniboV4.Ofbiz.Content.OtherDataResource.Version
    resource UniboV4.Ofbiz.Content.VideoDataResource
    resource UniboV4.Ofbiz.Content.VideoDataResource.Version
    resource UniboV4.Ofbiz.Content.Document
    resource UniboV4.Ofbiz.Content.Document.Version
    resource UniboV4.Ofbiz.Content.DocumentAttribute
    resource UniboV4.Ofbiz.Content.DocumentAttribute.Version
    resource UniboV4.Ofbiz.Content.DocumentType
    resource UniboV4.Ofbiz.Content.DocumentType.Version
    resource UniboV4.Ofbiz.Content.DocumentTypeAttr
    resource UniboV4.Ofbiz.Content.DocumentTypeAttr.Version
    resource UniboV4.Ofbiz.Content.WebPreferenceType
    resource UniboV4.Ofbiz.Content.WebPreferenceType.Version
    resource UniboV4.Ofbiz.Content.WebUserPreference
    resource UniboV4.Ofbiz.Content.Survey
    resource UniboV4.Ofbiz.Content.Survey.Version
    resource UniboV4.Ofbiz.Content.SurveyApplType
    resource UniboV4.Ofbiz.Content.SurveyApplType.Version
    resource UniboV4.Ofbiz.Content.SurveyMultiResp
    resource UniboV4.Ofbiz.Content.SurveyMultiResp.Version
    resource UniboV4.Ofbiz.Content.SurveyMultiRespColumn
    resource UniboV4.Ofbiz.Content.SurveyPage
    resource UniboV4.Ofbiz.Content.SurveyPage.Version
    resource UniboV4.Ofbiz.Content.SurveyQuestion
    resource UniboV4.Ofbiz.Content.SurveyQuestion.Version
    resource UniboV4.Ofbiz.Content.SurveyQuestionAppl
    resource UniboV4.Ofbiz.Content.SurveyQuestionAppl.Version
    resource UniboV4.Ofbiz.Content.SurveyQuestionCategory
    resource UniboV4.Ofbiz.Content.SurveyQuestionCategory.Version
    resource UniboV4.Ofbiz.Content.SurveyQuestionOption
    resource UniboV4.Ofbiz.Content.SurveyQuestionOption.Version
    resource UniboV4.Ofbiz.Content.SurveyQuestionType
    resource UniboV4.Ofbiz.Content.SurveyQuestionType.Version
    resource UniboV4.Ofbiz.Content.SurveyResponse
    resource UniboV4.Ofbiz.Content.SurveyResponse.Version
    resource UniboV4.Ofbiz.Content.SurveyResponseAnswer
    resource UniboV4.Ofbiz.Content.SurveyResponseAnswer.Version
    resource UniboV4.Ofbiz.Content.SurveyTrigger
    resource UniboV4.Ofbiz.Content.SurveyTrigger.Version
    resource UniboV4.Ofbiz.Content.WebSiteContent
    resource UniboV4.Ofbiz.Content.WebSiteContentType
    resource UniboV4.Ofbiz.Content.WebSiteContentType.Version
    resource UniboV4.Ofbiz.Content.WebSitePathAlias
    resource UniboV4.Ofbiz.Content.WebSitePublishPoint
    resource UniboV4.Ofbiz.Content.WebSitePublishPoint.Version
    resource UniboV4.Ofbiz.Content.WebSiteRole
    resource UniboV4.Ofbiz.Content.ContentKeyword
    resource UniboV4.Ofbiz.Content.ContentKeyword.Version
    resource UniboV4.Ofbiz.Content.ContentSearchConstraint
    resource UniboV4.Ofbiz.Content.ContentSearchConstraint.Version
    resource UniboV4.Ofbiz.Content.ContentSearchResult
    resource UniboV4.Ofbiz.Content.ContentSearchResult.Version
    resource UniboV4.Ofbiz.Content.WebAnalyticsConfig
    resource UniboV4.Ofbiz.Content.WebAnalyticsConfig.Version
    resource UniboV4.Ofbiz.Content.WebAnalyticsType
    resource UniboV4.Ofbiz.Content.WebAnalyticsType.Version
  end
end
