# bddc instructions spec (v1)
#
# 说明：
# - 该文件必须返回一个 map：%{instruction_atom => spec_map}
# - 你可以手工维护，也可以预留 GENERATED 区域由 bddc registry.upsert 写入。

%{
  # BEGIN BDDC GENERATED
  unibo_accounting_billing_account_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_billing_account_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_billing_account_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_billing_account_workflow_billing_account_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_full_reconcile_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_full_reconcile_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_full_reconcile_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_full_reconcile_workflow_full_reconcile_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_action_deactivate: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_workflow_gl_account_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_approve: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_create: %{
  args: %{items: %{type: :string, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_send: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_void: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_event_approve_accounting_invoice_approved: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_event_send_accounting_invoice_sent: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_item_action_create: %{
  args: %{gl_account_id: %{type: :uuid, allowed: nil, required?: false}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_item_workflow_invoice_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_workflow_invoice_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_create: %{
  args: %{lines: %{type: :string, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_post: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_reset_to_draft: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_event_cancel_accounting_journal_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_event_post_accounting_journal_posted: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_event_reset_to_draft_accounting_journal_reset_to_draft: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_line_action_create: %{
  args: %{gl_account_id: %{type: :uuid, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_line_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_line_tax_rel_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_line_workflow_journal_entry_line_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_workflow_journal_entry_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partial_reconcile_action_create: %{
  args: %{
    credit_line_id: %{type: :uuid, allowed: nil, required?: true},
    debit_line_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partial_reconcile_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partial_reconcile_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partial_reconcile_workflow_reconciliation_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_party_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_post: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_reset_to_draft: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_application_action_create: %{
  args: %{
    invoice_id: %{type: :uuid, allowed: nil, required?: true},
    payment_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_application_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_application_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_application_workflow_payment_application_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_event_cancel_accounting_payment_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_event_post_accounting_payment_posted: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_workflow_payment_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_tax_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_carrier_shipment_method_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_carrier_shipment_method_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_carrier_shipment_method_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_carrier_shipment_method_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_carrier_shipment_method_workflow_carrier_method_bind_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_confirm_source: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_create: %{
  args: %{
    source_party_id: %{type: :uuid, allowed: nil, required?: true},
    source_sales_order_id: %{type: :uuid, allowed: nil, required?: true},
    target_party_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_create_mirror_purchase_order: %{
  args: %{
    target_purchase_order_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_mark_failed: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_mark_fulfilled: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_mark_settled: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_event_cancel_delivery_cross_org_transaction_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_event_confirm_source_delivery_cross_org_transaction_source_confirmed: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_event_create_mirror_purchase_order_delivery_cross_org_transaction_mirror_created: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_event_mark_failed_delivery_cross_org_transaction_failed: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_event_mark_fulfilled_delivery_cross_org_transaction_fulfilled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_event_mark_settled_delivery_cross_org_transaction_settled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_cross_org_transaction_workflow_cross_org_transaction_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_delivery_action_arrive: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_delivery_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_delivery_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_delivery_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_delivery_action_start: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_delivery_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_delivery_workflow_delivery_trip_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_facility_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_fixed_asset_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_party_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_product_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_deliver: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_pack: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_pick: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_ship: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_submit: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_box_type_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_box_type_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_box_type_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_box_type_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_box_type_workflow_shipment_box_type_maintain_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_cost_estimate_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_cost_estimate_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_cost_estimate_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_cost_estimate_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_cost_estimate_workflow_cost_estimate_maintain_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_event_cancel_delivery_shipment_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_event_deliver_delivery_shipment_delivered: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_event_ship_delivery_shipment_dispatched: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_item_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_item_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_item_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_item_workflow_shipment_item_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_method_type_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_method_type_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_method_type_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_method_type_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_method_type_workflow_shipment_method_type_maintain_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_content_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_content_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_content_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_content_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_content_workflow_shipment_package_content_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_route_seg_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_route_seg_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_route_seg_action_mark_printed: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_route_seg_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_route_seg_action_update_cost: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_route_seg_action_update_label: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_route_seg_workflow_package_route_seg_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_package_workflow_shipment_package_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_action_confirm_shipment: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_action_record_cost: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_action_update_tracking: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_event_update_tracking_delivery_tracking_updated: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_route_segment_workflow_route_segment_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_status_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_status_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_status_workflow_shipment_status_record_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_type_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_type_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_type_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_type_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_type_workflow_shipment_type_maintain_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_delivery_shipment_workflow_shipment_lifecycle_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  # END BDDC GENERATED

  create_temp_dir: %{
    kind: :given,
    args: %{key: %{type: :string, required?: true, allowed: nil}},
    outputs: %{path: :string},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :test_runtime,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  create_temp_file: %{
    kind: :given,
    args: %{
      dir: %{type: :string, required?: true, allowed: nil},
      filename: %{type: :string, required?: true, allowed: nil},
      content: %{type: :string, required?: false, allowed: nil}
    },
    outputs: %{path: :string},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :test_runtime,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  noop: %{
    kind: :when,
    args: %{},
    outputs: %{},
    rules: [],
    scopes: [:unit, :integration, :e2e],
    boundary: :test_runtime,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  assert_noop: %{
    kind: :then,
    args: %{},
    outputs: %{},
    rules: [],
    scopes: [:unit, :integration, :e2e],
    boundary: :test_runtime,
    async?: false,
    eventually?: false,
    assert_class: :weak
  },
  given_seed_context: %{
    args: %{
      id: %{type: :string, required?: true, allowed: nil},
      module: %{type: :string, required?: true, allowed: nil}
    },
    kind: :given,
    outputs: %{},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :service,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  when_execute_seed_contract: %{
    args: %{module: %{type: :string, required?: true, allowed: nil}},
    kind: :when,
    outputs: %{},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :service,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  then_seed_contract_should_hold: %{
    args: %{module: %{type: :string, required?: true, allowed: nil}},
    kind: :then,
    outputs: %{},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :service,
    async?: false,
    eventually?: false,
    assert_class: nil
  }
}
