defmodule UniboV4.Ofbiz.Shipment do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.Shipment.ItemIssuance
    resource UniboV4.Ofbiz.Shipment.ItemIssuance.Version
    resource UniboV4.Ofbiz.Shipment.ItemIssuanceRole
    resource UniboV4.Ofbiz.Shipment.ItemIssuanceRole.Version
    resource UniboV4.Ofbiz.Shipment.Picklist
    resource UniboV4.Ofbiz.Shipment.Picklist.Version
    resource UniboV4.Ofbiz.Shipment.PicklistBin
    resource UniboV4.Ofbiz.Shipment.PicklistBin.Version
    resource UniboV4.Ofbiz.Shipment.PicklistItem
    resource UniboV4.Ofbiz.Shipment.PicklistRole
    resource UniboV4.Ofbiz.Shipment.PicklistRole.Version
    resource UniboV4.Ofbiz.Shipment.OldPicklistStatusHistory
    resource UniboV4.Ofbiz.Shipment.OldPicklistStatusHistory.Version
    resource UniboV4.Ofbiz.Shipment.PicklistStatus
    resource UniboV4.Ofbiz.Shipment.PicklistStatus.Version
    resource UniboV4.Ofbiz.Shipment.RejectionReason
    resource UniboV4.Ofbiz.Shipment.RejectionReason.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentReceipt
    resource UniboV4.Ofbiz.Shipment.ShipmentReceipt.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentReceiptRole
    resource UniboV4.Ofbiz.Shipment.ShipmentReceiptRole.Version
    resource UniboV4.Ofbiz.Shipment.CarrierShipmentMethod
    resource UniboV4.Ofbiz.Shipment.CarrierShipmentMethod.Version
    resource UniboV4.Ofbiz.Shipment.CarrierShipmentBoxType
    resource UniboV4.Ofbiz.Shipment.CarrierShipmentBoxType.Version
    resource UniboV4.Ofbiz.Shipment.Delivery
    resource UniboV4.Ofbiz.Shipment.Delivery.Version
    resource UniboV4.Ofbiz.Shipment.Shipment
    resource UniboV4.Ofbiz.Shipment.Shipment.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentAttribute
    resource UniboV4.Ofbiz.Shipment.ShipmentAttribute.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentBoxType
    resource UniboV4.Ofbiz.Shipment.ShipmentBoxType.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentContactMech
    resource UniboV4.Ofbiz.Shipment.ShipmentContactMech.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentContactMechType
    resource UniboV4.Ofbiz.Shipment.ShipmentContactMechType.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentCostEstimate
    resource UniboV4.Ofbiz.Shipment.ShipmentCostEstimate.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentTimeEstimate
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayConfigType
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayConfigType.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayConfig
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayConfig.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayDhl
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayDhl.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayFedex
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayFedex.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayUps
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayUps.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayUsps
    resource UniboV4.Ofbiz.Shipment.ShipmentGatewayUsps.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentItem
    resource UniboV4.Ofbiz.Shipment.ShipmentItem.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentItemBilling
    resource UniboV4.Ofbiz.Shipment.ShipmentItemFeature
    resource UniboV4.Ofbiz.Shipment.ShipmentItemFeature.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentMethodType
    resource UniboV4.Ofbiz.Shipment.ShipmentMethodType.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentPackage
    resource UniboV4.Ofbiz.Shipment.ShipmentPackage.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentPackageContent
    resource UniboV4.Ofbiz.Shipment.ShipmentPackageRouteSeg
    resource UniboV4.Ofbiz.Shipment.ShipmentRouteSegment
    resource UniboV4.Ofbiz.Shipment.ShipmentRouteSegment.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentStatus
    resource UniboV4.Ofbiz.Shipment.ShipmentStatus.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentType
    resource UniboV4.Ofbiz.Shipment.ShipmentType.Version
    resource UniboV4.Ofbiz.Shipment.ShipmentTypeAttr
    resource UniboV4.Ofbiz.Shipment.ShipmentTypeAttr.Version
    resource UniboV4.Ofbiz.Shipment.ShippingDocument
    resource UniboV4.Ofbiz.Shipment.ShippingDocument.Version
    resource UniboV4.Ofbiz.Shipment.ContactMech
    resource UniboV4.Ofbiz.Shipment.Document
    resource UniboV4.Ofbiz.Shipment.Facility
    resource UniboV4.Ofbiz.Shipment.FixedAsset
    resource UniboV4.Ofbiz.Shipment.Geo
    resource UniboV4.Ofbiz.Shipment.InventoryItem
    resource UniboV4.Ofbiz.Shipment.Invoice
    resource UniboV4.Ofbiz.Shipment.OrderHeader
    resource UniboV4.Ofbiz.Shipment.Party
    resource UniboV4.Ofbiz.Shipment.PartyGroup
    resource UniboV4.Ofbiz.Shipment.Person
    resource UniboV4.Ofbiz.Shipment.PostalAddress
    resource UniboV4.Ofbiz.Shipment.Product
    resource UniboV4.Ofbiz.Shipment.ProductFeature
    resource UniboV4.Ofbiz.Shipment.ProductStoreShipmentMeth
    resource UniboV4.Ofbiz.Shipment.QuantityBreak
    resource UniboV4.Ofbiz.Shipment.ReturnHeader
    resource UniboV4.Ofbiz.Shipment.RoleType
    resource UniboV4.Ofbiz.Shipment.StatusItem
    resource UniboV4.Ofbiz.Shipment.TelecomNumber
    resource UniboV4.Ofbiz.Shipment.Uom
    resource UniboV4.Ofbiz.Shipment.UserLogin
    resource UniboV4.Ofbiz.Shipment.WorkEffort
  end
end
