defmodule UniboExPoc.Marketing do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboExPoc.Marketing.Campaign
    resource UniboExPoc.Marketing.Campaign.Version
    resource UniboExPoc.Marketing.CampaignRole
    resource UniboExPoc.Marketing.CampaignRole.Version
    resource UniboExPoc.Marketing.MailingList
    resource UniboExPoc.Marketing.MailingList.Version
    resource UniboExPoc.Marketing.MailingListMember
    resource UniboExPoc.Marketing.MailingListMember.Version
    resource UniboExPoc.Marketing.Mailing
    resource UniboExPoc.Marketing.Mailing.Version
    resource UniboExPoc.Marketing.MailingTrace
    resource UniboExPoc.Marketing.MailingTrace.Version
    resource UniboExPoc.Marketing.Segment
    resource UniboExPoc.Marketing.Segment.Version
    resource UniboExPoc.Marketing.Event
    resource UniboExPoc.Marketing.Event.Version
    resource UniboExPoc.Marketing.EventTicket
    resource UniboExPoc.Marketing.EventTicket.Version
    resource UniboExPoc.Marketing.EventMailSchedule
    resource UniboExPoc.Marketing.EventMailSchedule.Version
    resource UniboExPoc.Marketing.EventRegistration
    resource UniboExPoc.Marketing.EventRegistration.Version
    resource UniboExPoc.Marketing.SmsMessage
    resource UniboExPoc.Marketing.SmsMessage.Version
    resource UniboExPoc.Marketing.SmsTemplate
    resource UniboExPoc.Marketing.SmsTemplate.Version
    resource UniboExPoc.Marketing.SocialPost
    resource UniboExPoc.Marketing.SocialPost.Version
    resource UniboExPoc.Marketing.SocialAccount
    resource UniboExPoc.Marketing.SocialAccount.Version
    resource UniboExPoc.Marketing.AutomationCampaign
    resource UniboExPoc.Marketing.AutomationCampaign.Version
    resource UniboExPoc.Marketing.AutomationActivity
    resource UniboExPoc.Marketing.AutomationActivity.Version
    resource UniboExPoc.Marketing.AutomationParticipant
    resource UniboExPoc.Marketing.AutomationTrace
    resource UniboExPoc.Marketing.AutomationTrace.Version
    resource UniboExPoc.Marketing.UtmCampaign
    resource UniboExPoc.Marketing.UtmCampaign.Version
    resource UniboExPoc.Marketing.UtmSource
    resource UniboExPoc.Marketing.UtmSource.Version
    resource UniboExPoc.Marketing.UtmMedium
    resource UniboExPoc.Marketing.UtmMedium.Version
    resource UniboExPoc.Marketing.UtmTag
    resource UniboExPoc.Marketing.UtmTag.Version
    resource UniboExPoc.Marketing.UtmStage
    resource UniboExPoc.Marketing.UtmStage.Version
    resource UniboExPoc.Marketing.UtmCampaignTagLink
    resource UniboExPoc.Marketing.EventBoothCategory
    resource UniboExPoc.Marketing.EventBoothCategory.Version
    resource UniboExPoc.Marketing.EventBooth
    resource UniboExPoc.Marketing.EventBooth.Version
    resource UniboExPoc.Marketing.EventTypeBooth
    resource UniboExPoc.Marketing.EventTypeBooth.Version
    resource UniboExPoc.Marketing.EventLeadRule
    resource UniboExPoc.Marketing.EventLeadRule.Version
    resource UniboExPoc.Marketing.EventLeadRuleEventType
    resource UniboExPoc.Marketing.MailingContactListLink
    resource UniboExPoc.Marketing.SocialPostAccountLink
    resource UniboExPoc.Marketing.Contact
    resource UniboExPoc.Marketing.Party
  end
end
