defmodule UniboV4.Marketing do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Marketing.Campaign
    resource UniboV4.Marketing.Campaign.Version
    resource UniboV4.Marketing.CampaignRole
    resource UniboV4.Marketing.CampaignRole.Version
    resource UniboV4.Marketing.MailingList
    resource UniboV4.Marketing.MailingList.Version
    resource UniboV4.Marketing.MailingListMember
    resource UniboV4.Marketing.MailingListMember.Version
    resource UniboV4.Marketing.Mailing
    resource UniboV4.Marketing.Mailing.Version
    resource UniboV4.Marketing.MailingTrace
    resource UniboV4.Marketing.MailingTrace.Version
    resource UniboV4.Marketing.Segment
    resource UniboV4.Marketing.Segment.Version
    resource UniboV4.Marketing.Event
    resource UniboV4.Marketing.Event.Version
    resource UniboV4.Marketing.EventTicket
    resource UniboV4.Marketing.EventTicket.Version
    resource UniboV4.Marketing.EventMailSchedule
    resource UniboV4.Marketing.EventMailSchedule.Version
    resource UniboV4.Marketing.EventRegistration
    resource UniboV4.Marketing.EventRegistration.Version
    resource UniboV4.Marketing.SmsMessage
    resource UniboV4.Marketing.SmsMessage.Version
    resource UniboV4.Marketing.SmsTemplate
    resource UniboV4.Marketing.SmsTemplate.Version
    resource UniboV4.Marketing.SocialPost
    resource UniboV4.Marketing.SocialPost.Version
    resource UniboV4.Marketing.SocialAccount
    resource UniboV4.Marketing.SocialAccount.Version
    resource UniboV4.Marketing.AutomationCampaign
    resource UniboV4.Marketing.AutomationCampaign.Version
    resource UniboV4.Marketing.AutomationActivity
    resource UniboV4.Marketing.AutomationActivity.Version
    resource UniboV4.Marketing.AutomationParticipant
    resource UniboV4.Marketing.AutomationTrace
    resource UniboV4.Marketing.AutomationTrace.Version
    resource UniboV4.Marketing.UtmCampaign
    resource UniboV4.Marketing.UtmCampaign.Version
    resource UniboV4.Marketing.UtmSource
    resource UniboV4.Marketing.UtmSource.Version
    resource UniboV4.Marketing.UtmMedium
    resource UniboV4.Marketing.UtmMedium.Version
    resource UniboV4.Marketing.UtmTag
    resource UniboV4.Marketing.UtmTag.Version
    resource UniboV4.Marketing.UtmStage
    resource UniboV4.Marketing.UtmStage.Version
    resource UniboV4.Marketing.UtmCampaignTagLink
    resource UniboV4.Marketing.EventBoothCategory
    resource UniboV4.Marketing.EventBoothCategory.Version
    resource UniboV4.Marketing.EventBooth
    resource UniboV4.Marketing.EventBooth.Version
    resource UniboV4.Marketing.EventTypeBooth
    resource UniboV4.Marketing.EventTypeBooth.Version
    resource UniboV4.Marketing.EventLeadRule
    resource UniboV4.Marketing.EventLeadRule.Version
    resource UniboV4.Marketing.EventLeadRuleEventType
    resource UniboV4.Marketing.MailingContactListLink
    resource UniboV4.Marketing.SocialPostAccountLink
    resource UniboV4.Marketing.Contact
    resource UniboV4.Marketing.Party
  end
end
