defmodule UniboV4.Generated.BddModuleDirs do
  @moduledoc "自动生成的 BDD 模块→目录映射 — 由 UniBO 编译器生成，请勿手动编辑"

  @doc "返回模块名 → BDD 目录名的映射"
  def module_dirs do
    %{
      "ACCOUNTING" => "accounting",
      "ANALYTIC" => "analytic",
      "APPROVALS" => "approvals",
      "BARCODE" => "barcode",
      "BLOG" => "blog",
      "CRM" => "crm",
      "CALENDAR" => "calendar",
      "COMMUNICATION" => "communication",
      "CURRENCY" => "currency",
      "DATA_RECYCLE" => "data_recycle",
      "DELIVERY" => "delivery",
      "DOCUMENTS" => "documents",
      "E_LEARNING" => "e_learning",
      "ECOMMERCE" => "ecommerce",
      "EVENTS" => "events",
      "EXPENSES" => "expenses",
      "FLEET" => "fleet",
      "FORUM" => "forum",
      "GAMIFICATION" => "gamification",
      "HR" => "hr",
      "HELPDESK" => "helpdesk",
      "INVENTORY" => "inventory",
      "IO_T" => "io_t",
      "KNOWLEDGE" => "knowledge",
      "LIVE_CHAT" => "live_chat",
      "LOYALTY" => "loyalty",
      "LUNCH" => "lunch",
      "MAINTENANCE" => "maintenance",
      "MANUFACTURING" => "manufacturing",
      "MARKETING" => "marketing",
      "MEMBERSHIP" => "membership",
      "PLM" => "plm",
      "POS" => "pos",
      "PAYMENT" => "payment",
      "PROJECT" => "project",
      "PURCHASING" => "purchasing",
      "QUALITY" => "quality",
      "RATING" => "rating",
      "RENTAL" => "rental",
      "REPAIR" => "repair",
      "SALES" => "sales",
      "SIGN" => "sign",
      "SPREADSHEET" => "spreadsheet",
      "STUDIO" => "studio",
      "SUBSCRIPTIONS" => "subscriptions",
      "SURVEY" => "survey",
      "UOM" => "uom",
    }
  end
end
