defmodule UniboV4.Generated.BddModuleDirs do
  @moduledoc "自动生成的 BDD 模块→目录映射 — 由 UniBO 编译器生成，请勿手动编辑"

  @doc "返回模块名 → BDD 目录名的映射"
  def module_dirs do
    %{
      "Accounting" => "accounting",
      "Analytic" => "analytic",
      "Approvals" => "approvals",
      "Barcode" => "barcode",
      "Blog" => "blog",
      "CRM" => "crm",
      "Calendar" => "calendar",
      "Communication" => "communication",
      "Currency" => "currency",
      "DataRecycle" => "data_recycle",
      "Delivery" => "delivery",
      "Documents" => "documents",
      "ELearning" => "e_learning",
      "Ecommerce" => "ecommerce",
      "Events" => "events",
      "Expenses" => "expenses",
      "Fleet" => "fleet",
      "Forum" => "forum",
      "Gamification" => "gamification",
      "HR" => "hr",
      "Helpdesk" => "helpdesk",
      "Inventory" => "inventory",
      "IoT" => "io_t",
      "Knowledge" => "knowledge",
      "LiveChat" => "live_chat",
      "Loyalty" => "loyalty",
      "Lunch" => "lunch",
      "Maintenance" => "maintenance",
      "Manufacturing" => "manufacturing",
      "Marketing" => "marketing",
      "Membership" => "membership",
      "PLM" => "plm",
      "POS" => "pos",
      "Payment" => "payment",
      "Project" => "project",
      "Purchasing" => "purchasing",
      "Quality" => "quality",
      "Rating" => "rating",
      "Rental" => "rental",
      "Repair" => "repair",
      "Sales" => "sales",
      "Sign" => "sign",
      "Spreadsheet" => "spreadsheet",
      "Studio" => "studio",
      "Subscriptions" => "subscriptions",
      "Survey" => "survey",
      "Uom" => "uom",
    }
  end
end
