defmodule UniboV4.Generated.BddDomainRegistry do
  @moduledoc "自动生成的 BDD 域注册表 — 由 UniBO 编译器生成，请勿手动编辑"

  @doc "BDD 域名 → Ash Domain 模块映射"
  def domain_map do
    %{
      "ACCOUNTING" => UniboV4.Accounting,
      "ANALYTIC" => UniboV4.Analytic,
      "APPROVALS" => UniboV4.Approvals,
      "BARCODE" => UniboV4.Barcode,
      "BLOG" => UniboV4.Blog,
      "CRM" => UniboV4.CRM,
      "CALENDAR" => UniboV4.Calendar,
      "COMMUNICATION" => UniboV4.Communication,
      "CURRENCY" => UniboV4.Currency,
      "DATA_RECYCLE" => UniboV4.DataRecycle,
      "DELIVERY" => UniboV4.Delivery,
      "DOCUMENTS" => UniboV4.Documents,
      "E_LEARNING" => UniboV4.ELearning,
      "ECOMMERCE" => UniboV4.Ecommerce,
      "EVENTS" => UniboV4.Events,
      "EXPENSES" => UniboV4.Expenses,
      "FLEET" => UniboV4.Fleet,
      "FORUM" => UniboV4.Forum,
      "GAMIFICATION" => UniboV4.Gamification,
      "HR" => UniboV4.HR,
      "HELPDESK" => UniboV4.Helpdesk,
      "INVENTORY" => UniboV4.Inventory,
      "IO_T" => UniboV4.IoT,
      "KNOWLEDGE" => UniboV4.Knowledge,
      "LIVE_CHAT" => UniboV4.LiveChat,
      "LOYALTY" => UniboV4.Loyalty,
      "LUNCH" => UniboV4.Lunch,
      "MAINTENANCE" => UniboV4.Maintenance,
      "MANUFACTURING" => UniboV4.Manufacturing,
      "MARKETING" => UniboV4.Marketing,
      "MEMBERSHIP" => UniboV4.Membership,
      "PLM" => UniboV4.PLM,
      "POS" => UniboV4.POS,
      "PAYMENT" => UniboV4.Payment,
      "PROJECT" => UniboV4.Project,
      "PURCHASING" => UniboV4.Purchasing,
      "QUALITY" => UniboV4.Quality,
      "RATING" => UniboV4.Rating,
      "RENTAL" => UniboV4.Rental,
      "REPAIR" => UniboV4.Repair,
      "SALES" => UniboV4.Sales,
      "SIGN" => UniboV4.Sign,
      "SPREADSHEET" => UniboV4.Spreadsheet,
      "STUDIO" => UniboV4.Studio,
      "SUBSCRIPTIONS" => UniboV4.Subscriptions,
      "SURVEY" => UniboV4.Survey,
      "UOM" => UniboV4.Uom,
    }
  end

  @doc "BDD 域名 → 目录名映射"
  def module_dirs do
    %{
      "ACCOUNTING" => "accounting",
      "ANALYTIC" => "analytic",
      "APPROVALS" => "approvals",
      "BARCODE" => "barcode",
      "BLOG" => "blog",
      "CRM" => "crm",
      "CALENDAR" => "calendar",
      "COMMUNICATION" => "communication",
      "CURRENCY" => "currency",
      "DATA_RECYCLE" => "data_recycle",
      "DELIVERY" => "delivery",
      "DOCUMENTS" => "documents",
      "E_LEARNING" => "elearning",
      "ECOMMERCE" => "ecommerce",
      "EVENTS" => "events",
      "EXPENSES" => "expenses",
      "FLEET" => "fleet",
      "FORUM" => "forum",
      "GAMIFICATION" => "gamification",
      "HR" => "hr",
      "HELPDESK" => "helpdesk",
      "INVENTORY" => "inventory",
      "IO_T" => "iot",
      "KNOWLEDGE" => "knowledge",
      "LIVE_CHAT" => "livechat",
      "LOYALTY" => "loyalty",
      "LUNCH" => "lunch",
      "MAINTENANCE" => "maintenance",
      "MANUFACTURING" => "manufacturing",
      "MARKETING" => "marketing",
      "MEMBERSHIP" => "membership",
      "PLM" => "plm",
      "POS" => "pos",
      "PAYMENT" => "payment",
      "PROJECT" => "project",
      "PURCHASING" => "purchasing",
      "QUALITY" => "quality",
      "RATING" => "rating",
      "RENTAL" => "rental",
      "REPAIR" => "repair",
      "SALES" => "sales",
      "SIGN" => "sign",
      "SPREADSHEET" => "spreadsheet",
      "STUDIO" => "studio",
      "SUBSCRIPTIONS" => "subscriptions",
      "SURVEY" => "survey",
      "UOM" => "uom",
    }
  end

  @doc "所有已注册的 Ash Domain 模块列表"
  def domains do
    [
      UniboV4.Accounting,
      UniboV4.Analytic,
      UniboV4.Approvals,
      UniboV4.Barcode,
      UniboV4.Blog,
      UniboV4.CRM,
      UniboV4.Calendar,
      UniboV4.Communication,
      UniboV4.Currency,
      UniboV4.DataRecycle,
      UniboV4.Delivery,
      UniboV4.Documents,
      UniboV4.ELearning,
      UniboV4.Ecommerce,
      UniboV4.Events,
      UniboV4.Expenses,
      UniboV4.Fleet,
      UniboV4.Forum,
      UniboV4.Gamification,
      UniboV4.HR,
      UniboV4.Helpdesk,
      UniboV4.Inventory,
      UniboV4.IoT,
      UniboV4.Knowledge,
      UniboV4.LiveChat,
      UniboV4.Loyalty,
      UniboV4.Lunch,
      UniboV4.Maintenance,
      UniboV4.Manufacturing,
      UniboV4.Marketing,
      UniboV4.Membership,
      UniboV4.PLM,
      UniboV4.POS,
      UniboV4.Payment,
      UniboV4.Project,
      UniboV4.Purchasing,
      UniboV4.Quality,
      UniboV4.Rating,
      UniboV4.Rental,
      UniboV4.Repair,
      UniboV4.Sales,
      UniboV4.Sign,
      UniboV4.Spreadsheet,
      UniboV4.Studio,
      UniboV4.Subscriptions,
      UniboV4.Survey,
      UniboV4.Uom,
    ]
  end
end
