defmodule UniboExPoc.Ofbiz.WorkEffort do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboExPoc.Ofbiz.WorkEffort.TimeEntry
    resource UniboExPoc.Ofbiz.WorkEffort.TimeEntry.Version
    resource UniboExPoc.Ofbiz.WorkEffort.Timesheet
    resource UniboExPoc.Ofbiz.WorkEffort.Timesheet.Version
    resource UniboExPoc.Ofbiz.WorkEffort.TimesheetRole
    resource UniboExPoc.Ofbiz.WorkEffort.TimesheetRole.Version
    resource UniboExPoc.Ofbiz.WorkEffort.ApplicationSandbox
    resource UniboExPoc.Ofbiz.WorkEffort.ApplicationSandbox.Version
    resource UniboExPoc.Ofbiz.WorkEffort.CommunicationEventWorkEff
    resource UniboExPoc.Ofbiz.WorkEffort.CommunicationEventWorkEff.Version
    resource UniboExPoc.Ofbiz.WorkEffort.Deliverable
    resource UniboExPoc.Ofbiz.WorkEffort.Deliverable.Version
    resource UniboExPoc.Ofbiz.WorkEffort.DeliverableType
    resource UniboExPoc.Ofbiz.WorkEffort.DeliverableType.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffort
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffort.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAssoc
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAssoc.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAssocAttribute
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAssocType
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAssocType.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAssocTypeAttr
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAssocTypeAttr.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAttribute
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortAttribute.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortBilling
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortBilling.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortContactMech
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortContactMech.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortContent
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortContent.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortContentType
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortContentType.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortDeliverableProd
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortDeliverableProd.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortEventReminder
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortEventReminder.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortFixedAssetAssign
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortFixedAssetAssign.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortFixedAssetStd
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortFixedAssetStd.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortGoodStandard
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortGoodStandard.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortGoodStandardType
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortGoodStandardType.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortIcalData
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortIcalData.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortInventoryAssign
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortInventoryAssign.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortInventoryProduced
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortInventoryProduced.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortCostCalc
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortCostCalc.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortKeyword
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortKeyword.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortNote
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortNote.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortPartyAssignment
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortPartyAssignment.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortPurposeType
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortPurposeType.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortReview
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortReview.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortSearchConstraint
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortSearchConstraint.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortSearchResult
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortSearchResult.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortSkillStandard
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortSkillStandard.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortStatus
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortStatus.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortTransBox
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortType
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortType.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortTypeAttr
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortTypeAttr.Version
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortSurveyAppl
    resource UniboExPoc.Ofbiz.WorkEffort.WorkEffortSurveyAppl.Version
    resource UniboExPoc.Ofbiz.WorkEffort.AccommodationMap
    resource UniboExPoc.Ofbiz.WorkEffort.AccommodationSpot
    resource UniboExPoc.Ofbiz.WorkEffort.CommunicationEvent
    resource UniboExPoc.Ofbiz.WorkEffort.ContactMech
    resource UniboExPoc.Ofbiz.WorkEffort.Content
    resource UniboExPoc.Ofbiz.WorkEffort.CostComponentCalc
    resource UniboExPoc.Ofbiz.WorkEffort.CostComponentType
    resource UniboExPoc.Ofbiz.WorkEffort.CustomMethod
    resource UniboExPoc.Ofbiz.WorkEffort.Enumeration
    resource UniboExPoc.Ofbiz.WorkEffort.Facility
    resource UniboExPoc.Ofbiz.WorkEffort.FixedAsset
    resource UniboExPoc.Ofbiz.WorkEffort.FixedAssetType
    resource UniboExPoc.Ofbiz.WorkEffort.InventoryItem
    resource UniboExPoc.Ofbiz.WorkEffort.Invoice
    resource UniboExPoc.Ofbiz.WorkEffort.NoteData
    resource UniboExPoc.Ofbiz.WorkEffort.Party
    resource UniboExPoc.Ofbiz.WorkEffort.Product
    resource UniboExPoc.Ofbiz.WorkEffort.ProductStoreSurveyAppl
    resource UniboExPoc.Ofbiz.WorkEffort.RateType
    resource UniboExPoc.Ofbiz.WorkEffort.RecurrenceInfo
    resource UniboExPoc.Ofbiz.WorkEffort.RoleType
    resource UniboExPoc.Ofbiz.WorkEffort.RuntimeData
    resource UniboExPoc.Ofbiz.WorkEffort.SkillType
    resource UniboExPoc.Ofbiz.WorkEffort.StatusItem
    resource UniboExPoc.Ofbiz.WorkEffort.Survey
    resource UniboExPoc.Ofbiz.WorkEffort.TelecomNumber
    resource UniboExPoc.Ofbiz.WorkEffort.TemporalExpression
    resource UniboExPoc.Ofbiz.WorkEffort.Uom
    resource UniboExPoc.Ofbiz.WorkEffort.UserLogin
  end
end
