defmodule UniboExPocWeb.Schema do
  use Absinthe.Schema

  use AshGraphql,
    domains: [
      UniboExPoc.Accounting,
      UniboExPoc.Analytic,
      UniboExPoc.Approvals,
      UniboExPoc.Barcode,
      UniboExPoc.Blog,
      UniboExPoc.CRM,
      UniboExPoc.Calendar,
      UniboExPoc.Communication,
      UniboExPoc.Currency,
      UniboExPoc.DataRecycle,
      UniboExPoc.Delivery,
      UniboExPoc.Documents,
      UniboExPoc.ELearning,
      UniboExPoc.Ecommerce,
      UniboExPoc.Events,
      UniboExPoc.Expenses,
      UniboExPoc.Fleet,
      UniboExPoc.Forum,
      UniboExPoc.Gamification,
      UniboExPoc.HR,
      UniboExPoc.Helpdesk,
      UniboExPoc.Inventory,
      UniboExPoc.IoT,
      UniboExPoc.Knowledge,
      UniboExPoc.LiveChat,
      UniboExPoc.Loyalty,
      UniboExPoc.Lunch,
      UniboExPoc.Maintenance,
      UniboExPoc.Manufacturing,
      UniboExPoc.Marketing,
      UniboExPoc.Membership,
      UniboExPoc.Ofbiz.Accounting,
      UniboExPoc.Ofbiz.Common,
      UniboExPoc.Ofbiz.Content,
      UniboExPoc.Ofbiz.HumanRes,
      UniboExPoc.Ofbiz.Manufacturing,
      UniboExPoc.Ofbiz.Marketing,
      UniboExPoc.Ofbiz.Order,
      UniboExPoc.Ofbiz.Party,
      UniboExPoc.Ofbiz.Product,
      UniboExPoc.Ofbiz.Security,
      UniboExPoc.Ofbiz.Service,
      UniboExPoc.Ofbiz.Shipment,
      UniboExPoc.Ofbiz.WorkEffort,
      UniboExPoc.Organization,
      UniboExPoc.PLM,
      UniboExPoc.POS,
      UniboExPoc.Payment,
      UniboExPoc.Project,
      UniboExPoc.Purchasing,
      UniboExPoc.Quality,
      UniboExPoc.Rating,
      UniboExPoc.Rental,
      UniboExPoc.Repair,
      UniboExPoc.Sales,
      UniboExPoc.Sign,
      UniboExPoc.Spreadsheet,
      UniboExPoc.Studio,
      UniboExPoc.Subscriptions,
      UniboExPoc.Survey,
      UniboExPoc.Travel,
      UniboExPoc.Uom,
      UniboExPoc.Website,
    ]

  query do
  end

  mutation do
  end
end
