defmodule UniboV4.Ofbiz.Common do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.Common.DataSource
    resource UniboV4.Ofbiz.Common.DataSource.Version
    resource UniboV4.Ofbiz.Common.DataSourceType
    resource UniboV4.Ofbiz.Common.DataSourceType.Version
    resource UniboV4.Ofbiz.Common.EmailTemplateSetting
    resource UniboV4.Ofbiz.Common.EmailTemplateSetting.Version
    resource UniboV4.Ofbiz.Common.Enumeration
    resource UniboV4.Ofbiz.Common.Enumeration.Version
    resource UniboV4.Ofbiz.Common.EnumerationType
    resource UniboV4.Ofbiz.Common.EnumerationType.Version
    resource UniboV4.Ofbiz.Common.CountryCapital
    resource UniboV4.Ofbiz.Common.CountryCapital.Version
    resource UniboV4.Ofbiz.Common.CountryCode
    resource UniboV4.Ofbiz.Common.CountryCode.Version
    resource UniboV4.Ofbiz.Common.CountryTeleCode
    resource UniboV4.Ofbiz.Common.CountryTeleCode.Version
    resource UniboV4.Ofbiz.Common.CountryAddressFormat
    resource UniboV4.Ofbiz.Common.CountryAddressFormat.Version
    resource UniboV4.Ofbiz.Common.Geo
    resource UniboV4.Ofbiz.Common.Geo.Version
    resource UniboV4.Ofbiz.Common.GeoAssoc
    resource UniboV4.Ofbiz.Common.GeoAssoc.Version
    resource UniboV4.Ofbiz.Common.GeoAssocType
    resource UniboV4.Ofbiz.Common.GeoAssocType.Version
    resource UniboV4.Ofbiz.Common.GeoPoint
    resource UniboV4.Ofbiz.Common.GeoPoint.Version
    resource UniboV4.Ofbiz.Common.GeoType
    resource UniboV4.Ofbiz.Common.GeoType.Version
    resource UniboV4.Ofbiz.Common.KeywordThesaurus
    resource UniboV4.Ofbiz.Common.KeywordThesaurus.Version
    resource UniboV4.Ofbiz.Common.StandardLanguage
    resource UniboV4.Ofbiz.Common.StandardLanguage.Version
    resource UniboV4.Ofbiz.Common.CustomMethod
    resource UniboV4.Ofbiz.Common.CustomMethod.Version
    resource UniboV4.Ofbiz.Common.CustomMethodType
    resource UniboV4.Ofbiz.Common.CustomMethodType.Version
    resource UniboV4.Ofbiz.Common.NoteData
    resource UniboV4.Ofbiz.Common.NoteData.Version
    resource UniboV4.Ofbiz.Common.CustomTimePeriod
    resource UniboV4.Ofbiz.Common.CustomTimePeriod.Version
    resource UniboV4.Ofbiz.Common.PeriodType
    resource UniboV4.Ofbiz.Common.PeriodType.Version
    resource UniboV4.Ofbiz.Common.StatusItem
    resource UniboV4.Ofbiz.Common.StatusItem.Version
    resource UniboV4.Ofbiz.Common.StatusType
    resource UniboV4.Ofbiz.Common.StatusType.Version
    resource UniboV4.Ofbiz.Common.StatusValidChange
    resource UniboV4.Ofbiz.Common.StatusValidChange.Version
    resource UniboV4.Ofbiz.Common.Uom
    resource UniboV4.Ofbiz.Common.Uom.Version
    resource UniboV4.Ofbiz.Common.UomConversion
    resource UniboV4.Ofbiz.Common.UomConversion.Version
    resource UniboV4.Ofbiz.Common.UomConversionDated
    resource UniboV4.Ofbiz.Common.UomConversionDated.Version
    resource UniboV4.Ofbiz.Common.UomGroup
    resource UniboV4.Ofbiz.Common.UomGroup.Version
    resource UniboV4.Ofbiz.Common.UomType
    resource UniboV4.Ofbiz.Common.UomType.Version
    resource UniboV4.Ofbiz.Common.UserPreference
    resource UniboV4.Ofbiz.Common.UserPreference.Version
    resource UniboV4.Ofbiz.Common.UserPrefGroupType
    resource UniboV4.Ofbiz.Common.UserPrefGroupType.Version
    resource UniboV4.Ofbiz.Common.CustomScreen
    resource UniboV4.Ofbiz.Common.CustomScreen.Version
    resource UniboV4.Ofbiz.Common.CustomScreenType
    resource UniboV4.Ofbiz.Common.CustomScreenType.Version
    resource UniboV4.Ofbiz.Common.VisualThemeSet
    resource UniboV4.Ofbiz.Common.VisualThemeSet.Version
    resource UniboV4.Ofbiz.Common.VisualTheme
    resource UniboV4.Ofbiz.Common.VisualTheme.Version
    resource UniboV4.Ofbiz.Common.VisualThemeResource
    resource UniboV4.Ofbiz.Common.VisualThemeResource.Version
    resource UniboV4.Ofbiz.Common.PortalPortlet
    resource UniboV4.Ofbiz.Common.PortalPortlet.Version
    resource UniboV4.Ofbiz.Common.PortletCategory
    resource UniboV4.Ofbiz.Common.PortletCategory.Version
    resource UniboV4.Ofbiz.Common.PortletPortletCategory
    resource UniboV4.Ofbiz.Common.PortletPortletCategory.Version
    resource UniboV4.Ofbiz.Common.PortalPage
    resource UniboV4.Ofbiz.Common.PortalPage.Version
    resource UniboV4.Ofbiz.Common.PortalPageColumn
    resource UniboV4.Ofbiz.Common.PortalPageColumn.Version
    resource UniboV4.Ofbiz.Common.PortalPagePortlet
    resource UniboV4.Ofbiz.Common.PortalPagePortlet.Version
    resource UniboV4.Ofbiz.Common.PortletAttribute
    resource UniboV4.Ofbiz.Common.PortletAttribute.Version
    resource UniboV4.Ofbiz.Common.SystemProperty
    resource UniboV4.Ofbiz.Common.SystemProperty.Version
    resource UniboV4.Ofbiz.Common.TelecomMethodType
    resource UniboV4.Ofbiz.Common.TelecomMethodType.Version
    resource UniboV4.Ofbiz.Common.TelecomGatewayConfig
    resource UniboV4.Ofbiz.Common.TelecomGatewayConfig.Version
  end
end
