defmodule UniboExPoc.Ofbiz.Common do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboExPoc.Ofbiz.Common.DataSource
    resource UniboExPoc.Ofbiz.Common.DataSource.Version
    resource UniboExPoc.Ofbiz.Common.DataSourceType
    resource UniboExPoc.Ofbiz.Common.DataSourceType.Version
    resource UniboExPoc.Ofbiz.Common.EmailTemplateSetting
    resource UniboExPoc.Ofbiz.Common.EmailTemplateSetting.Version
    resource UniboExPoc.Ofbiz.Common.Enumeration
    resource UniboExPoc.Ofbiz.Common.Enumeration.Version
    resource UniboExPoc.Ofbiz.Common.EnumerationType
    resource UniboExPoc.Ofbiz.Common.EnumerationType.Version
    resource UniboExPoc.Ofbiz.Common.CountryCapital
    resource UniboExPoc.Ofbiz.Common.CountryCapital.Version
    resource UniboExPoc.Ofbiz.Common.CountryCode
    resource UniboExPoc.Ofbiz.Common.CountryCode.Version
    resource UniboExPoc.Ofbiz.Common.CountryTeleCode
    resource UniboExPoc.Ofbiz.Common.CountryTeleCode.Version
    resource UniboExPoc.Ofbiz.Common.CountryAddressFormat
    resource UniboExPoc.Ofbiz.Common.CountryAddressFormat.Version
    resource UniboExPoc.Ofbiz.Common.Geo
    resource UniboExPoc.Ofbiz.Common.Geo.Version
    resource UniboExPoc.Ofbiz.Common.GeoAssoc
    resource UniboExPoc.Ofbiz.Common.GeoAssocType
    resource UniboExPoc.Ofbiz.Common.GeoAssocType.Version
    resource UniboExPoc.Ofbiz.Common.GeoPoint
    resource UniboExPoc.Ofbiz.Common.GeoPoint.Version
    resource UniboExPoc.Ofbiz.Common.GeoType
    resource UniboExPoc.Ofbiz.Common.GeoType.Version
    resource UniboExPoc.Ofbiz.Common.KeywordThesaurus
    resource UniboExPoc.Ofbiz.Common.StandardLanguage
    resource UniboExPoc.Ofbiz.Common.StandardLanguage.Version
    resource UniboExPoc.Ofbiz.Common.CustomMethod
    resource UniboExPoc.Ofbiz.Common.CustomMethod.Version
    resource UniboExPoc.Ofbiz.Common.CustomMethodType
    resource UniboExPoc.Ofbiz.Common.CustomMethodType.Version
    resource UniboExPoc.Ofbiz.Common.NoteData
    resource UniboExPoc.Ofbiz.Common.NoteData.Version
    resource UniboExPoc.Ofbiz.Common.CustomTimePeriod
    resource UniboExPoc.Ofbiz.Common.CustomTimePeriod.Version
    resource UniboExPoc.Ofbiz.Common.PeriodType
    resource UniboExPoc.Ofbiz.Common.PeriodType.Version
    resource UniboExPoc.Ofbiz.Common.StatusItem
    resource UniboExPoc.Ofbiz.Common.StatusItem.Version
    resource UniboExPoc.Ofbiz.Common.StatusType
    resource UniboExPoc.Ofbiz.Common.StatusType.Version
    resource UniboExPoc.Ofbiz.Common.StatusValidChange
    resource UniboExPoc.Ofbiz.Common.Uom
    resource UniboExPoc.Ofbiz.Common.Uom.Version
    resource UniboExPoc.Ofbiz.Common.UomConversion
    resource UniboExPoc.Ofbiz.Common.UomConversionDated
    resource UniboExPoc.Ofbiz.Common.UomGroup
    resource UniboExPoc.Ofbiz.Common.UomType
    resource UniboExPoc.Ofbiz.Common.UomType.Version
    resource UniboExPoc.Ofbiz.Common.UserPreference
    resource UniboExPoc.Ofbiz.Common.UserPrefGroupType
    resource UniboExPoc.Ofbiz.Common.UserPrefGroupType.Version
    resource UniboExPoc.Ofbiz.Common.CustomScreen
    resource UniboExPoc.Ofbiz.Common.CustomScreen.Version
    resource UniboExPoc.Ofbiz.Common.CustomScreenType
    resource UniboExPoc.Ofbiz.Common.CustomScreenType.Version
    resource UniboExPoc.Ofbiz.Common.VisualThemeSet
    resource UniboExPoc.Ofbiz.Common.VisualThemeSet.Version
    resource UniboExPoc.Ofbiz.Common.VisualTheme
    resource UniboExPoc.Ofbiz.Common.VisualTheme.Version
    resource UniboExPoc.Ofbiz.Common.VisualThemeResource
    resource UniboExPoc.Ofbiz.Common.PortalPortlet
    resource UniboExPoc.Ofbiz.Common.PortalPortlet.Version
    resource UniboExPoc.Ofbiz.Common.PortletCategory
    resource UniboExPoc.Ofbiz.Common.PortletCategory.Version
    resource UniboExPoc.Ofbiz.Common.PortletPortletCategory
    resource UniboExPoc.Ofbiz.Common.PortalPage
    resource UniboExPoc.Ofbiz.Common.PortalPage.Version
    resource UniboExPoc.Ofbiz.Common.PortalPageColumn
    resource UniboExPoc.Ofbiz.Common.PortalPagePortlet
    resource UniboExPoc.Ofbiz.Common.PortletAttribute
    resource UniboExPoc.Ofbiz.Common.SystemProperty
    resource UniboExPoc.Ofbiz.Common.TelecomMethodType
    resource UniboExPoc.Ofbiz.Common.TelecomMethodType.Version
    resource UniboExPoc.Ofbiz.Common.TelecomGatewayConfig
    resource UniboExPoc.Ofbiz.Common.TelecomGatewayConfig.Version
  end
end
