# Generated by bdd_compiler from /home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl. DO NOT EDIT.

defmodule HospitalScheduling.BDD.Generated.SCHEDULING_MEDICAL_STAFF_PROFILETest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_create_create
  @tag :all
  @tag :seed
  test "[BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_create_create]" do
    run_id = HospitalScheduling.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_create_create"}
    # line 2: GIVEN given_seed_context id="action_medical_staff_profile_create_create" module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "action_medical_staff_profile_create_create", module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 2, raw: "GIVEN given_seed_context id=\"action_medical_staff_profile_create_create\" module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 2)
    # line 3: WHEN when_execute_seed_contract module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 3, raw: "WHEN when_execute_seed_contract module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 3)
    # line 4: THEN then_seed_contract_should_hold module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 4, raw: "THEN then_seed_contract_should_hold module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 4)
    _ctx = ctx
    :ok
  end

  # Source: BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_read_read
  @tag :all
  @tag :seed
  test "[BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_read_read]" do
    run_id = HospitalScheduling.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_read_read"}
    # line 7: GIVEN given_seed_context id="action_medical_staff_profile_read_read" module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "action_medical_staff_profile_read_read", module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 7, raw: "GIVEN given_seed_context id=\"action_medical_staff_profile_read_read\" module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 7)
    # line 8: WHEN when_execute_seed_contract module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 8, raw: "WHEN when_execute_seed_contract module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 8)
    # line 9: THEN then_seed_contract_should_hold module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 9, raw: "THEN then_seed_contract_should_hold module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 9)
    _ctx = ctx
    :ok
  end

  # Source: BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_update_update
  @tag :all
  @tag :seed
  test "[BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_update_update]" do
    run_id = HospitalScheduling.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-action_medical_staff_profile_update_update"}
    # line 12: GIVEN given_seed_context id="action_medical_staff_profile_update_update" module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "action_medical_staff_profile_update_update", module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 12, raw: "GIVEN given_seed_context id=\"action_medical_staff_profile_update_update\" module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 12)
    # line 13: WHEN when_execute_seed_contract module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 13, raw: "WHEN when_execute_seed_contract module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 13)
    # line 14: THEN then_seed_contract_should_hold module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 14, raw: "THEN then_seed_contract_should_hold module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 14)
    _ctx = ctx
    :ok
  end

  # Source: BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-graphql_contract_medical_staff_profile
  @tag :graphql_contract
  @tag :seed
  test "[BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-graphql_contract_medical_staff_profile]" do
    run_id = HospitalScheduling.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-SCHEDULING_MEDICAL_STAFF_PROFILE-SEED-graphql_contract_medical_staff_profile"}
    # line 17: GIVEN given_seed_context id="graphql_contract_medical_staff_profile" module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "graphql_contract_medical_staff_profile", module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 17, raw: "GIVEN given_seed_context id=\"graphql_contract_medical_staff_profile\" module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 17)
    # line 18: WHEN when_execute_seed_contract module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 18, raw: "WHEN when_execute_seed_contract module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 18)
    # line 19: THEN then_seed_contract_should_hold module="SCHEDULING_MEDICAL_STAFF_PROFILE"
    ctx = HospitalScheduling.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "SCHEDULING_MEDICAL_STAFF_PROFILE"}, %{file: "/home/wangbo/unibo_ex_poc-sched-graphql/hospital_scheduling/docs/bdd/SCHEDULING_MEDICAL_STAFF_PROFILE.dsl", line: 19, raw: "THEN then_seed_contract_should_hold module=\"SCHEDULING_MEDICAL_STAFF_PROFILE\""}, 19)
    _ctx = ctx
    :ok
  end

end
