# bddc instructions spec (v1)
#
# 说明：
# - 该文件必须返回一个 map：%{instruction_atom => spec_map}
# - 你可以手工维护，也可以预留 GENERATED 区域由 bddc registry.upsert 写入。

%{
  # -- seed 通用指令（手写） --
  given_seed_context: %{
    args: %{id: %{type: :string, required?: true, allowed: nil}, module: %{type: :string, required?: true, allowed: nil}},
    kind: :given,
    outputs: %{},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :service,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  when_execute_seed_contract: %{
    args: %{module: %{type: :string, required?: true, allowed: nil}},
    kind: :when,
    outputs: %{},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :service,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  then_seed_contract_should_hold: %{
    args: %{module: %{type: :string, required?: true, allowed: nil}},
    kind: :then,
    outputs: %{},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :service,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  # BEGIN BDDC GENERATED
  unibo_accounting_billing_account_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_billing_account_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_billing_account_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_billing_account_workflow_billing_account_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_action_approve: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_action_create: %{
  args: %{items: %{type: :string, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_action_reject: %{
  args: %{reason: %{type: :string, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_action_submit: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_event_approve_accounting_budget_approved: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_item_action_create: %{
  args: %{gl_account_id: %{type: :uuid, allowed: nil, required?: false}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_item_workflow_budget_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_budget_workflow_budget_approval: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_full_reconcile_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_full_reconcile_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_full_reconcile_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_full_reconcile_workflow_full_reconcile_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_action_deactivate: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_gl_account_workflow_gl_account_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_approve: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_create: %{
  args: %{items: %{type: :string, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_send: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_action_void: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_event_approve_accounting_invoice_approved: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_event_send_accounting_invoice_sent: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_item_action_create: %{
  args: %{gl_account_id: %{type: :uuid, allowed: nil, required?: false}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_item_workflow_invoice_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_invoice_workflow_invoice_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_create: %{
  args: %{lines: %{type: :string, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_post: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_action_reset_to_draft: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_event_cancel_accounting_journal_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_event_post_accounting_journal_posted: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_event_reset_to_draft_accounting_journal_reset_to_draft: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_line_action_create: %{
  args: %{gl_account_id: %{type: :uuid, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_line_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_line_tax_rel_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_line_workflow_journal_entry_line_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_journal_entry_workflow_journal_entry_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partial_reconcile_action_create: %{
  args: %{
    credit_line_id: %{type: :uuid, allowed: nil, required?: true},
    debit_line_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partial_reconcile_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partial_reconcile_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partial_reconcile_workflow_reconciliation_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_partner_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_post: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_action_reset_to_draft: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_application_action_create: %{
  args: %{
    invoice_id: %{type: :uuid, allowed: nil, required?: true},
    payment_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_application_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_application_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_application_workflow_payment_application_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_event_cancel_accounting_payment_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_event_post_accounting_payment_posted: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_payment_workflow_payment_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_tax_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_accounting_user_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_line_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_line_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_line_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_line_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_line_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_line_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_account_move_line_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_confirm: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_create: %{
  args: %{
    items: %{type: :string, allowed: nil, required?: true},
    purchase_order_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_event_confirm_purchasing_receipt_confirmed: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_item_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_item_workflow_receipt_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_goods_receipt_workflow_goods_receipt_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_event_create_purchasing_supplierinfo_created: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_product_supplierinfo_workflow_supplierinfo_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_action_create_invoice: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_button_approve: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_button_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_button_confirm: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_button_done: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_button_draft: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_button_unlock: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_create: %{
  args: %{
    supplier_id: %{type: :uuid, allowed: nil, required?: true},
    order_lines: %{type: :string, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_print_quotation: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_send_rfq: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_action_create_invoice_purchasing_order_invoice_created: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_button_approve_purchasing_order_approved: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_button_cancel_purchasing_order_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_button_confirm_purchasing_order_confirmed: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_button_done_purchasing_order_locked: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_button_draft_purchasing_order_reset_to_draft: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_button_unlock_purchasing_order_unlocked: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_print_quotation_purchasing_order_rfq_printed: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_event_send_rfq_purchasing_order_rfq_sent: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_item_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_item_workflow_order_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_line_workflow_order_line_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_workflow_procurement_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_order_workflow_purchase_order_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_action_done: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_action_draft: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_action_in_progress: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_action_open: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_create: %{
  args: %{
    items: %{type: :string, allowed: nil, required?: true},
    type_id: %{type: :uuid, allowed: nil, required?: true},
    vendor_id: %{type: :uuid, allowed: nil, required?: false}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_event_action_cancel_purchasing_requisition_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_event_action_done_purchasing_requisition_done: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_event_action_in_progress_purchasing_requisition_confirmed: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_item_action_create: %{
  args: %{product_id: %{type: :uuid, allowed: nil, required?: false}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_item_workflow_requisition_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_type_workflow_requisition_type_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_workflow_requisition_lifecycle_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_purchase_requisition_workflow_requisition_reopen_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_activate: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_block: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_create: %{
  args: %{supplier_id: %{type: :uuid, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_product_workflow_supplier_product_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_supplier_workflow_supplier_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_user_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_user_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_user_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_user_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_user_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_user_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_purchasing_user_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_block: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_customer_workflow_customer_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_create: %{
  args: %{product_id: %{type: :uuid, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_rate_shipment: %{
  args: %{order_id: %{type: :uuid, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_carrier_workflow_delivery_carrier_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_create: %{
  args: %{carrier_id: %{type: :uuid, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_destroy: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_delivery_price_rule_workflow_price_rule_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_product_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_product_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_product_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_product_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_product_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_product_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_product_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_accept: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_create: %{
  args: %{
    items: %{type: :string, allowed: nil, required?: true},
    customer_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_reject: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_action_submit: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_event_accept_sales_quote_accepted: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_event_submit_sales_quote_submitted: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_item_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_item_workflow_quote_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_quote_workflow_quote_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_approve: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_complete: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_create: %{
  args: %{
    items: %{type: :string, allowed: nil, required?: true},
    customer_id: %{type: :uuid, allowed: nil, required?: true},
    sales_order_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_receive: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_event_approve_sales_return_approved: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_event_complete_sales_return_completed: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_item_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_item_workflow_return_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_return_workflow_return_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_action_cancel: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_action_confirm: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_action_done: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_action_draft: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_action_quotation_send: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_create: %{
  args: %{
    items: %{type: :string, allowed: nil, required?: true},
    customer_id: %{type: :uuid, allowed: nil, required?: true}
  },
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_create_invoices: %{
  args: %{final: %{type: :bool, allowed: nil, required?: false}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_event_action_cancel_sales_order_cancelled: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_event_action_confirm_sales_order_confirmed: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_event_action_done_sales_order_done: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_event_action_draft_sales_order_reset_to_draft: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_event_action_quotation_send_sales_order_sent: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_event_create_invoices_sales_order_invoice_created: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_action_create: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_action_update: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_tax_rel_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_tax_rel_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_tax_rel_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_tax_rel_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_tax_rel_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_tax_rel_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_tax_rel_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_item_workflow_order_item_editing: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_create: %{
  args: %{sales_order_id: %{type: :uuid, allowed: nil, required?: true}},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_deliver: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_action_ship: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_event_deliver_sales_shipment_delivered: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_event_ship_sales_shipment_shipped: %{
  args: %{},
  kind: :then,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_shipment_workflow_shipment_lifecycle: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_workflow_pricing_chain: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_workflow_sales_order_lifecycle_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_sales_order_workflow_sales_order_reopen_flow: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_tax_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_tax_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_tax_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_tax_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_tax_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_tax_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_tax_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_user_action_compute: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_user_action_get: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_user_action_list: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_user_action_lookup: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_user_action_preview: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_user_action_read: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  unibo_sales_user_action_search: %{
  args: %{},
  kind: :when,
  outputs: %{},
  rules: [],
  scopes: [:integration, :e2e],
  boundary: :service,
  async?: false,
  eventually?: false,
  assert_class: nil
},
  # END BDDC GENERATED

  create_temp_dir: %{
    kind: :given,
    args: %{key: %{type: :string, required?: true, allowed: nil}},
    outputs: %{path: :string},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :test_runtime,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  create_temp_file: %{
    kind: :given,
    args: %{
      dir: %{type: :string, required?: true, allowed: nil},
      filename: %{type: :string, required?: true, allowed: nil},
      content: %{type: :string, required?: false, allowed: nil}
    },
    outputs: %{path: :string},
    rules: [],
    scopes: [:integration, :e2e],
    boundary: :test_runtime,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  noop: %{
    kind: :when,
    args: %{},
    outputs: %{},
    rules: [],
    scopes: [:unit, :integration, :e2e],
    boundary: :test_runtime,
    async?: false,
    eventually?: false,
    assert_class: nil
  },
  assert_noop: %{
    kind: :then,
    args: %{},
    outputs: %{},
    rules: [],
    scopes: [:unit, :integration, :e2e],
    boundary: :test_runtime,
    async?: false,
    eventually?: false,
    assert_class: :weak
  }
}
