defmodule UniboV4.Ofbiz.Product do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.Product.ProdCatalog
    resource UniboV4.Ofbiz.Product.ProdCatalog.Version
    resource UniboV4.Ofbiz.Product.ProdCatalogCategory
    resource UniboV4.Ofbiz.Product.ProdCatalogCategory.Version
    resource UniboV4.Ofbiz.Product.ProdCatalogCategoryType
    resource UniboV4.Ofbiz.Product.ProdCatalogCategoryType.Version
    resource UniboV4.Ofbiz.Product.ProdCatalogInvFacility
    resource UniboV4.Ofbiz.Product.ProdCatalogInvFacility.Version
    resource UniboV4.Ofbiz.Product.ProdCatalogRole
    resource UniboV4.Ofbiz.Product.ProductCategory
    resource UniboV4.Ofbiz.Product.ProductCategory.Version
    resource UniboV4.Ofbiz.Product.ProductCategoryAttribute
    resource UniboV4.Ofbiz.Product.ProductCategoryAttribute.Version
    resource UniboV4.Ofbiz.Product.ProductCategoryContent
    resource UniboV4.Ofbiz.Product.ProductCategoryContentType
    resource UniboV4.Ofbiz.Product.ProductCategoryContentType.Version
    resource UniboV4.Ofbiz.Product.ProductCategoryGlAccount
    resource UniboV4.Ofbiz.Product.ProductCategoryLink
    resource UniboV4.Ofbiz.Product.ProductCategoryMember
    resource UniboV4.Ofbiz.Product.ProductCategoryMember.Version
    resource UniboV4.Ofbiz.Product.ProductCategoryRole
    resource UniboV4.Ofbiz.Product.ProductCategoryRollup
    resource UniboV4.Ofbiz.Product.ProductCategoryRollup.Version
    resource UniboV4.Ofbiz.Product.ProductCategoryType
    resource UniboV4.Ofbiz.Product.ProductCategoryType.Version
    resource UniboV4.Ofbiz.Product.ProductCategoryTypeAttr
    resource UniboV4.Ofbiz.Product.ProductCategoryTypeAttr.Version
    resource UniboV4.Ofbiz.Product.ProductConfig
    resource UniboV4.Ofbiz.Product.ProductConfigItem
    resource UniboV4.Ofbiz.Product.ProductConfigItem.Version
    resource UniboV4.Ofbiz.Product.ProdConfItemContent
    resource UniboV4.Ofbiz.Product.ProdConfItemContentType
    resource UniboV4.Ofbiz.Product.ProdConfItemContentType.Version
    resource UniboV4.Ofbiz.Product.ProductConfigOption
    resource UniboV4.Ofbiz.Product.ProductConfigOption.Version
    resource UniboV4.Ofbiz.Product.ProductConfigOptionIactn
    resource UniboV4.Ofbiz.Product.ProductConfigProduct
    resource UniboV4.Ofbiz.Product.ProductConfigProduct.Version
    resource UniboV4.Ofbiz.Product.ProductConfigConfig
    resource UniboV4.Ofbiz.Product.ProductConfigStats
    resource UniboV4.Ofbiz.Product.ProductConfigStats.Version
    resource UniboV4.Ofbiz.Product.ConfigOptionProductOption
    resource UniboV4.Ofbiz.Product.CostComponent
    resource UniboV4.Ofbiz.Product.CostComponent.Version
    resource UniboV4.Ofbiz.Product.CostComponentAttribute
    resource UniboV4.Ofbiz.Product.CostComponentAttribute.Version
    resource UniboV4.Ofbiz.Product.CostComponentType
    resource UniboV4.Ofbiz.Product.CostComponentType.Version
    resource UniboV4.Ofbiz.Product.CostComponentTypeAttr
    resource UniboV4.Ofbiz.Product.CostComponentTypeAttr.Version
    resource UniboV4.Ofbiz.Product.CostComponentCalc
    resource UniboV4.Ofbiz.Product.CostComponentCalc.Version
    resource UniboV4.Ofbiz.Product.ProductCostComponentCalc
    resource UniboV4.Ofbiz.Product.ProductCostComponentCalc.Version
    resource UniboV4.Ofbiz.Product.Container
    resource UniboV4.Ofbiz.Product.Container.Version
    resource UniboV4.Ofbiz.Product.ContainerType
    resource UniboV4.Ofbiz.Product.ContainerType.Version
    resource UniboV4.Ofbiz.Product.ContainerGeoPoint
    resource UniboV4.Ofbiz.Product.Facility
    resource UniboV4.Ofbiz.Product.Facility.Version
    resource UniboV4.Ofbiz.Product.FacilityAttribute
    resource UniboV4.Ofbiz.Product.FacilityAttribute.Version
    resource UniboV4.Ofbiz.Product.FacilityCalendar
    resource UniboV4.Ofbiz.Product.FacilityCalendarType
    resource UniboV4.Ofbiz.Product.FacilityCalendarType.Version
    resource UniboV4.Ofbiz.Product.FacilityCarrierShipment
    resource UniboV4.Ofbiz.Product.FacilityContactMech
    resource UniboV4.Ofbiz.Product.FacilityContactMechPurpose
    resource UniboV4.Ofbiz.Product.FacilityGroup
    resource UniboV4.Ofbiz.Product.FacilityGroup.Version
    resource UniboV4.Ofbiz.Product.FacilityGroupMember
    resource UniboV4.Ofbiz.Product.FacilityGroupMember.Version
    resource UniboV4.Ofbiz.Product.FacilityGroupRole
    resource UniboV4.Ofbiz.Product.FacilityGroupRollup
    resource UniboV4.Ofbiz.Product.FacilityGroupRollup.Version
    resource UniboV4.Ofbiz.Product.FacilityGroupType
    resource UniboV4.Ofbiz.Product.FacilityGroupType.Version
    resource UniboV4.Ofbiz.Product.FacilityLocation
    resource UniboV4.Ofbiz.Product.FacilityLocation.Version
    resource UniboV4.Ofbiz.Product.FacilityLocationGeoPoint
    resource UniboV4.Ofbiz.Product.FacilityParty
    resource UniboV4.Ofbiz.Product.FacilityContent
    resource UniboV4.Ofbiz.Product.FacilityType
    resource UniboV4.Ofbiz.Product.FacilityType.Version
    resource UniboV4.Ofbiz.Product.FacilityTypeAttr
    resource UniboV4.Ofbiz.Product.FacilityTypeAttr.Version
    resource UniboV4.Ofbiz.Product.ProductFacility
    resource UniboV4.Ofbiz.Product.ProductFacility.Version
    resource UniboV4.Ofbiz.Product.FacilityAssocType
    resource UniboV4.Ofbiz.Product.FacilityAssocType.Version
    resource UniboV4.Ofbiz.Product.ProductFacilityAssoc
    resource UniboV4.Ofbiz.Product.ProductFacilityAssoc.Version
    resource UniboV4.Ofbiz.Product.ProductFacilityLocation
    resource UniboV4.Ofbiz.Product.ProductFacilityLocation.Version
    resource UniboV4.Ofbiz.Product.ProductFeature
    resource UniboV4.Ofbiz.Product.ProductFeature.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureAppl
    resource UniboV4.Ofbiz.Product.ProductFeatureAppl.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureApplType
    resource UniboV4.Ofbiz.Product.ProductFeatureApplType.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureApplAttr
    resource UniboV4.Ofbiz.Product.ProductFeatureCategory
    resource UniboV4.Ofbiz.Product.ProductFeatureCategory.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureCategoryAppl
    resource UniboV4.Ofbiz.Product.ProductFeatureCategoryAppl.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureCatGrpAppl
    resource UniboV4.Ofbiz.Product.ProductFeatureCatGrpAppl.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureDataResource
    resource UniboV4.Ofbiz.Product.ProductFeatureDataResource.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureGroup
    resource UniboV4.Ofbiz.Product.ProductFeatureGroup.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureGroupAppl
    resource UniboV4.Ofbiz.Product.ProductFeatureGroupAppl.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureIactn
    resource UniboV4.Ofbiz.Product.ProductFeatureIactn.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureIactnType
    resource UniboV4.Ofbiz.Product.ProductFeatureIactnType.Version
    resource UniboV4.Ofbiz.Product.ProductFeatureType
    resource UniboV4.Ofbiz.Product.ProductFeatureType.Version
    resource UniboV4.Ofbiz.Product.ProductFeaturePrice
    resource UniboV4.Ofbiz.Product.InventoryItem
    resource UniboV4.Ofbiz.Product.InventoryItem.Version
    resource UniboV4.Ofbiz.Product.InventoryItemAttribute
    resource UniboV4.Ofbiz.Product.InventoryItemAttribute.Version
    resource UniboV4.Ofbiz.Product.InventoryItemDetail
    resource UniboV4.Ofbiz.Product.InventoryItemDetail.Version
    resource UniboV4.Ofbiz.Product.InventoryItemStatus
    resource UniboV4.Ofbiz.Product.InventoryItemTempRes
    resource UniboV4.Ofbiz.Product.InventoryItemTempRes.Version
    resource UniboV4.Ofbiz.Product.InventoryItemType
    resource UniboV4.Ofbiz.Product.InventoryItemType.Version
    resource UniboV4.Ofbiz.Product.InventoryItemTypeAttr
    resource UniboV4.Ofbiz.Product.InventoryItemTypeAttr.Version
    resource UniboV4.Ofbiz.Product.InventoryItemVariance
    resource UniboV4.Ofbiz.Product.InventoryItemVariance.Version
    resource UniboV4.Ofbiz.Product.InventoryItemLabelType
    resource UniboV4.Ofbiz.Product.InventoryItemLabelType.Version
    resource UniboV4.Ofbiz.Product.InventoryItemLabel
    resource UniboV4.Ofbiz.Product.InventoryItemLabel.Version
    resource UniboV4.Ofbiz.Product.InventoryItemLabelAppl
    resource UniboV4.Ofbiz.Product.InventoryItemLabelAppl.Version
    resource UniboV4.Ofbiz.Product.InventoryTransfer
    resource UniboV4.Ofbiz.Product.InventoryTransfer.Version
    resource UniboV4.Ofbiz.Product.Lot
    resource UniboV4.Ofbiz.Product.Lot.Version
    resource UniboV4.Ofbiz.Product.PhysicalInventory
    resource UniboV4.Ofbiz.Product.PhysicalInventory.Version
    resource UniboV4.Ofbiz.Product.VarianceReason
    resource UniboV4.Ofbiz.Product.VarianceReason.Version
    resource UniboV4.Ofbiz.Product.ProductPaymentMethodType
    resource UniboV4.Ofbiz.Product.ProductPrice
    resource UniboV4.Ofbiz.Product.ProductPriceAction
    resource UniboV4.Ofbiz.Product.ProductPriceAction.Version
    resource UniboV4.Ofbiz.Product.ProductPriceActionType
    resource UniboV4.Ofbiz.Product.ProductPriceActionType.Version
    resource UniboV4.Ofbiz.Product.ProductPriceAutoNotice
    resource UniboV4.Ofbiz.Product.ProductPriceAutoNotice.Version
    resource UniboV4.Ofbiz.Product.ProductPriceChange
    resource UniboV4.Ofbiz.Product.ProductPriceChange.Version
    resource UniboV4.Ofbiz.Product.ProductPriceCond
    resource UniboV4.Ofbiz.Product.ProductPriceCond.Version
    resource UniboV4.Ofbiz.Product.ProductPricePurpose
    resource UniboV4.Ofbiz.Product.ProductPricePurpose.Version
    resource UniboV4.Ofbiz.Product.ProductPriceRule
    resource UniboV4.Ofbiz.Product.ProductPriceRule.Version
    resource UniboV4.Ofbiz.Product.ProductPriceType
    resource UniboV4.Ofbiz.Product.ProductPriceType.Version
    resource UniboV4.Ofbiz.Product.QuantityBreak
    resource UniboV4.Ofbiz.Product.QuantityBreak.Version
    resource UniboV4.Ofbiz.Product.QuantityBreakType
    resource UniboV4.Ofbiz.Product.QuantityBreakType.Version
    resource UniboV4.Ofbiz.Product.SaleType
    resource UniboV4.Ofbiz.Product.SaleType.Version
    resource UniboV4.Ofbiz.Product.GoodIdentification
    resource UniboV4.Ofbiz.Product.GoodIdentification.Version
    resource UniboV4.Ofbiz.Product.GoodIdentificationType
    resource UniboV4.Ofbiz.Product.GoodIdentificationType.Version
    resource UniboV4.Ofbiz.Product.Product
    resource UniboV4.Ofbiz.Product.Product.Version
    resource UniboV4.Ofbiz.Product.ProductAssoc
    resource UniboV4.Ofbiz.Product.ProductAssoc.Version
    resource UniboV4.Ofbiz.Product.ProductAssocType
    resource UniboV4.Ofbiz.Product.ProductAssocType.Version
    resource UniboV4.Ofbiz.Product.ProductRole
    resource UniboV4.Ofbiz.Product.ProductAttribute
    resource UniboV4.Ofbiz.Product.ProductAttribute.Version
    resource UniboV4.Ofbiz.Product.ProductCalculatedInfo
    resource UniboV4.Ofbiz.Product.ProductCalculatedInfo.Version
    resource UniboV4.Ofbiz.Product.ProductContent
    resource UniboV4.Ofbiz.Product.ProductContentType
    resource UniboV4.Ofbiz.Product.ProductContentType.Version
    resource UniboV4.Ofbiz.Product.ProductGeo
    resource UniboV4.Ofbiz.Product.ProductGeo.Version
    resource UniboV4.Ofbiz.Product.ProductGlAccount
    resource UniboV4.Ofbiz.Product.ProductKeyword
    resource UniboV4.Ofbiz.Product.ProductMeter
    resource UniboV4.Ofbiz.Product.ProductMeter.Version
    resource UniboV4.Ofbiz.Product.ProductMeterType
    resource UniboV4.Ofbiz.Product.ProductMeterType.Version
    resource UniboV4.Ofbiz.Product.ProductMaint
    resource UniboV4.Ofbiz.Product.ProductMaint.Version
    resource UniboV4.Ofbiz.Product.ProductMaintType
    resource UniboV4.Ofbiz.Product.ProductMaintType.Version
    resource UniboV4.Ofbiz.Product.ProductReview
    resource UniboV4.Ofbiz.Product.ProductReview.Version
    resource UniboV4.Ofbiz.Product.ProductSearchConstraint
    resource UniboV4.Ofbiz.Product.ProductSearchConstraint.Version
    resource UniboV4.Ofbiz.Product.ProductSearchResult
    resource UniboV4.Ofbiz.Product.ProductSearchResult.Version
    resource UniboV4.Ofbiz.Product.ProductType
    resource UniboV4.Ofbiz.Product.ProductType.Version
    resource UniboV4.Ofbiz.Product.ProductTypeAttr
    resource UniboV4.Ofbiz.Product.ProductTypeAttr.Version
    resource UniboV4.Ofbiz.Product.VendorProduct
    resource UniboV4.Ofbiz.Product.VendorProduct.Version
    resource UniboV4.Ofbiz.Product.ProductPromo
    resource UniboV4.Ofbiz.Product.ProductPromo.Version
    resource UniboV4.Ofbiz.Product.ProductPromoAction
    resource UniboV4.Ofbiz.Product.ProductPromoCategory
    resource UniboV4.Ofbiz.Product.ProductPromoCode
    resource UniboV4.Ofbiz.Product.ProductPromoCode.Version
    resource UniboV4.Ofbiz.Product.OldProductPromoCodeEmail
    resource UniboV4.Ofbiz.Product.OldProductPromoCodeEmail.Version
    resource UniboV4.Ofbiz.Product.ProdPromoCodeContactMech
    resource UniboV4.Ofbiz.Product.ProdPromoCodeContactMech.Version
    resource UniboV4.Ofbiz.Product.ProductPromoCodeParty
    resource UniboV4.Ofbiz.Product.ProductPromoCodeParty.Version
    resource UniboV4.Ofbiz.Product.ProductPromoCond
    resource UniboV4.Ofbiz.Product.ProductPromoProduct
    resource UniboV4.Ofbiz.Product.ProductPromoRule
    resource UniboV4.Ofbiz.Product.ProductPromoRule.Version
    resource UniboV4.Ofbiz.Product.ProductPromoUse
    resource UniboV4.Ofbiz.Product.ProductStore
    resource UniboV4.Ofbiz.Product.ProductStore.Version
    resource UniboV4.Ofbiz.Product.ProductStoreCatalog
    resource UniboV4.Ofbiz.Product.ProductStoreCatalog.Version
    resource UniboV4.Ofbiz.Product.ProductStoreEmailSetting
    resource UniboV4.Ofbiz.Product.ProductStoreEmailSetting.Version
    resource UniboV4.Ofbiz.Product.ProductStoreFinActSetting
    resource UniboV4.Ofbiz.Product.ProductStoreFinActSetting.Version
    resource UniboV4.Ofbiz.Product.ProductStoreFacility
    resource UniboV4.Ofbiz.Product.ProductStoreFacility.Version
    resource UniboV4.Ofbiz.Product.ProductStoreGroup
    resource UniboV4.Ofbiz.Product.ProductStoreGroup.Version
    resource UniboV4.Ofbiz.Product.ProductStoreGroupMember
    resource UniboV4.Ofbiz.Product.ProductStoreGroupMember.Version
    resource UniboV4.Ofbiz.Product.ProductStoreGroupRole
    resource UniboV4.Ofbiz.Product.ProductStoreGroupRollup
    resource UniboV4.Ofbiz.Product.ProductStoreGroupRollup.Version
    resource UniboV4.Ofbiz.Product.ProductStoreGroupType
    resource UniboV4.Ofbiz.Product.ProductStoreGroupType.Version
    resource UniboV4.Ofbiz.Product.ProductStoreKeywordOvrd
    resource UniboV4.Ofbiz.Product.ProductStorePaymentSetting
    resource UniboV4.Ofbiz.Product.ProductStorePromoAppl
    resource UniboV4.Ofbiz.Product.ProductStorePromoAppl.Version
    resource UniboV4.Ofbiz.Product.ProductStoreRole
    resource UniboV4.Ofbiz.Product.ProductStoreShipmentMeth
    resource UniboV4.Ofbiz.Product.ProductStoreShipmentMeth.Version
    resource UniboV4.Ofbiz.Product.ProductStoreSurveyAppl
    resource UniboV4.Ofbiz.Product.ProductStoreSurveyAppl.Version
    resource UniboV4.Ofbiz.Product.ProductStoreVendorPayment
    resource UniboV4.Ofbiz.Product.ProductStoreVendorShipment
    resource UniboV4.Ofbiz.Product.ProductSubscriptionResource
    resource UniboV4.Ofbiz.Product.ProductSubscriptionResource.Version
    resource UniboV4.Ofbiz.Product.Subscription
    resource UniboV4.Ofbiz.Product.Subscription.Version
    resource UniboV4.Ofbiz.Product.SubscriptionActivity
    resource UniboV4.Ofbiz.Product.SubscriptionActivity.Version
    resource UniboV4.Ofbiz.Product.SubscriptionAttribute
    resource UniboV4.Ofbiz.Product.SubscriptionAttribute.Version
    resource UniboV4.Ofbiz.Product.SubscriptionFulfillmentPiece
    resource UniboV4.Ofbiz.Product.SubscriptionFulfillmentPiece.Version
    resource UniboV4.Ofbiz.Product.SubscriptionResource
    resource UniboV4.Ofbiz.Product.SubscriptionResource.Version
    resource UniboV4.Ofbiz.Product.SubscriptionType
    resource UniboV4.Ofbiz.Product.SubscriptionType.Version
    resource UniboV4.Ofbiz.Product.SubscriptionTypeAttr
    resource UniboV4.Ofbiz.Product.SubscriptionTypeAttr.Version
    resource UniboV4.Ofbiz.Product.SubscriptionCommEvent
    resource UniboV4.Ofbiz.Product.SubscriptionCommEvent.Version
    resource UniboV4.Ofbiz.Product.MarketInterest
    resource UniboV4.Ofbiz.Product.ReorderGuideline
    resource UniboV4.Ofbiz.Product.ReorderGuideline.Version
    resource UniboV4.Ofbiz.Product.SupplierPrefOrder
    resource UniboV4.Ofbiz.Product.SupplierPrefOrder.Version
    resource UniboV4.Ofbiz.Product.SupplierProduct
    resource UniboV4.Ofbiz.Product.SupplierProductFeature
    resource UniboV4.Ofbiz.Product.SupplierProductFeature.Version
    resource UniboV4.Ofbiz.Product.SupplierRatingType
    resource UniboV4.Ofbiz.Product.SupplierRatingType.Version
    resource UniboV4.Ofbiz.Product.ProductPromoContent
    resource UniboV4.Ofbiz.Product.ProductGroupOrder
    resource UniboV4.Ofbiz.Product.ProductGroupOrder.Version
    resource UniboV4.Ofbiz.Product.ProductStoreTelecomSetting
  end
end
