[SCENARIO: BDD-SCHEDULING_SCHEDULING_PERIOD_READ_READ-SEED-action_scheduling_period_read_read] TITLE: SCHEDULING_SCHEDULING_PERIOD contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="action_scheduling_period_read_read" module="SCHEDULING_SCHEDULING_PERIOD"
WHEN when_execute_seed_contract module="SCHEDULING_SCHEDULING_PERIOD"
THEN then_seed_contract_should_hold module="SCHEDULING_SCHEDULING_PERIOD"
