[SCENARIO: BDD-SCHEDULING_SOLVER_RUN_START_RUN_UPDATE-SEED-action_solver_run_start_run_update] TITLE: SCHEDULING_SOLVER_RUN_START_RUN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="action_solver_run_start_run_update" module="SCHEDULING_SOLVER_RUN_START_RUN"
WHEN when_execute_seed_contract module="SCHEDULING_SOLVER_RUN_START_RUN"
THEN then_seed_contract_should_hold module="SCHEDULING_SOLVER_RUN_START_RUN"
