[SCENARIO: BDD-SCHEDULING_SOLVER_RUN_COMPLETE_FEASIBLE_UPDATE-SEED-action_solver_run_complete_feasible_update] TITLE: SCHEDULING_SOLVER_RUN_COMPLETE_FEASIBLE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="action_solver_run_complete_feasible_update" module="SCHEDULING_SOLVER_RUN_COMPLETE_FEASIBLE"
WHEN when_execute_seed_contract module="SCHEDULING_SOLVER_RUN_COMPLETE_FEASIBLE"
THEN then_seed_contract_should_hold module="SCHEDULING_SOLVER_RUN_COMPLETE_FEASIBLE"
