[SCENARIO: BDD-SCHEDULING_SHIFT_ASSIGNMENT-SEED-action_shift_assignment_create_create] TITLE: SCHEDULING_SHIFT_ASSIGNMENT contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="action_shift_assignment_create_create" module="SCHEDULING_SHIFT_ASSIGNMENT"
WHEN when_execute_seed_contract module="SCHEDULING_SHIFT_ASSIGNMENT"
THEN then_seed_contract_should_hold module="SCHEDULING_SHIFT_ASSIGNMENT"
