[SCENARIO: BDD-SCHEDULING_CONSTRAINT_VIOLATION_READ_READ-SEED-action_constraint_violation_read_read] TITLE: SCHEDULING_CONSTRAINT_VIOLATION contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="action_constraint_violation_read_read" module="SCHEDULING_CONSTRAINT_VIOLATION"
WHEN when_execute_seed_contract module="SCHEDULING_CONSTRAINT_VIOLATION"
THEN then_seed_contract_should_hold module="SCHEDULING_CONSTRAINT_VIOLATION"
