[SCENARIO: BDD-SCHEDULING_SHIFT_ASSIGNMENT_LOCK_UPDATE-SEED-action_shift_assignment_lock_update] TITLE: SCHEDULING_SHIFT_ASSIGNMENT_LOCK contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="action_shift_assignment_lock_update" module="SCHEDULING_SHIFT_ASSIGNMENT_LOCK"
WHEN when_execute_seed_contract module="SCHEDULING_SHIFT_ASSIGNMENT_LOCK"
THEN then_seed_contract_should_hold module="SCHEDULING_SHIFT_ASSIGNMENT_LOCK"
