[SCENARIO: BDD-SCHEDULING_SHIFT_PREFERENCE_CREATE_CREATE-SEED-action_shift_preference_create_create] TITLE: SCHEDULING_SHIFT_PREFERENCE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="action_shift_preference_create_create" module="SCHEDULING_SHIFT_PREFERENCE"
WHEN when_execute_seed_contract module="SCHEDULING_SHIFT_PREFERENCE"
THEN then_seed_contract_should_hold module="SCHEDULING_SHIFT_PREFERENCE"
