[SCENARIO: BDD-SCHEDULING_SOLVER_RUN_MARK_ERROR_UPDATE-SEED-action_solver_run_mark_error_update] TITLE: SCHEDULING_SOLVER_RUN_MARK_ERROR contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="action_solver_run_mark_error_update" module="SCHEDULING_SOLVER_RUN_MARK_ERROR"
WHEN when_execute_seed_contract module="SCHEDULING_SOLVER_RUN_MARK_ERROR"
THEN then_seed_contract_should_hold module="SCHEDULING_SOLVER_RUN_MARK_ERROR"
