[SCENARIO: BDD-SCHEDULING_COVERAGE_REQUIREMENT-SEED-action_coverage_requirement_create_create] TITLE: SCHEDULING_COVERAGE_REQUIREMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_coverage_requirement_create_create" module="SCHEDULING_COVERAGE_REQUIREMENT"
WHEN when_execute_seed_contract module="SCHEDULING_COVERAGE_REQUIREMENT"
THEN then_seed_contract_should_hold module="SCHEDULING_COVERAGE_REQUIREMENT"

[SCENARIO: BDD-SCHEDULING_COVERAGE_REQUIREMENT-SEED-action_coverage_requirement_destroy_destroy] TITLE: SCHEDULING_COVERAGE_REQUIREMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_coverage_requirement_destroy_destroy" module="SCHEDULING_COVERAGE_REQUIREMENT"
WHEN when_execute_seed_contract module="SCHEDULING_COVERAGE_REQUIREMENT"
THEN then_seed_contract_should_hold module="SCHEDULING_COVERAGE_REQUIREMENT"

[SCENARIO: BDD-SCHEDULING_COVERAGE_REQUIREMENT-SEED-action_coverage_requirement_read_read] TITLE: SCHEDULING_COVERAGE_REQUIREMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_coverage_requirement_read_read" module="SCHEDULING_COVERAGE_REQUIREMENT"
WHEN when_execute_seed_contract module="SCHEDULING_COVERAGE_REQUIREMENT"
THEN then_seed_contract_should_hold module="SCHEDULING_COVERAGE_REQUIREMENT"

[SCENARIO: BDD-SCHEDULING_COVERAGE_REQUIREMENT-SEED-action_coverage_requirement_update_update] TITLE: SCHEDULING_COVERAGE_REQUIREMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="action_coverage_requirement_update_update" module="SCHEDULING_COVERAGE_REQUIREMENT"
WHEN when_execute_seed_contract module="SCHEDULING_COVERAGE_REQUIREMENT"
THEN then_seed_contract_should_hold module="SCHEDULING_COVERAGE_REQUIREMENT"

[SCENARIO: BDD-SCHEDULING_COVERAGE_REQUIREMENT-SEED-graphql_contract_coverage_requirement] TITLE: SCHEDULING_COVERAGE_REQUIREMENT contract seed scenario TAGS: seed graphql_contract
GIVEN given_seed_context id="graphql_contract_coverage_requirement" module="SCHEDULING_COVERAGE_REQUIREMENT"
WHEN when_execute_seed_contract module="SCHEDULING_COVERAGE_REQUIREMENT"
THEN then_seed_contract_should_hold module="SCHEDULING_COVERAGE_REQUIREMENT"
