[SCENARIO: BDD-SCHEDULING_SCHEDULING_PERIOD-SEED-workflow_scheduling_period_scheduling_period_lifecycle] TITLE: SCHEDULING_SCHEDULING_PERIOD contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="workflow_scheduling_period_scheduling_period_lifecycle" module="SCHEDULING_SCHEDULING_PERIOD"
WHEN when_execute_seed_contract module="SCHEDULING_SCHEDULING_PERIOD"
THEN then_seed_contract_should_hold module="SCHEDULING_SCHEDULING_PERIOD"
