# Generated by: bcc bdd seed --step organize

[SCENARIO: BDD-APPROVALS_COMPANY-SEED-approvals_company_action_company_read_read] TITLE: APPROVALS_COMPANY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="approvals_company_action_company_read_read" module="APPROVALS_COMPANY"
WHEN when_execute_seed_contract module="APPROVALS_COMPANY"
THEN then_seed_contract_should_hold module="APPROVALS_COMPANY"

