# Generated by: bcc bdd seed --step organize

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_create_create_risk_change_effect] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_create_create_risk_change_effect" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_create_create] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_create_create" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_read_read] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_read_read" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_create_create_risk_validation_fail] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_create_create_risk_validation_fail" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_destroy_destroy_risk_success] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_destroy_destroy_risk_success" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_update_update_risk_success] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_update_update_risk_success" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_workflow_sign_role_sign_role_write_flow_risk_branch_or_exception] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_workflow_sign_role_sign_role_write_flow_risk_branch_or_exception" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_update_update_risk_change_effect] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_update_update_risk_change_effect" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_destroy_destroy_risk_change_effect] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_destroy_destroy_risk_change_effect" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_workflow_sign_role_sign_role_write_flow] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_workflow_sign_role_sign_role_write_flow" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_destroy_destroy] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_destroy_destroy" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_create_create_risk_success] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_create_create_risk_success" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_action_sign_role_update_update] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_action_sign_role_update_update" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

[SCENARIO: BDD-SIGN_SIGN_ROLE-SEED-sign_sign_role_workflow_sign_role_sign_role_write_flow_risk_mainline] TITLE: SIGN_SIGN_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_role_workflow_sign_role_sign_role_write_flow_risk_mainline" module="SIGN_SIGN_ROLE"
WHEN when_execute_seed_contract module="SIGN_SIGN_ROLE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_ROLE"

