defmodule UniboExPoc.Ofbiz.Accounting do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboExPoc.Ofbiz.Accounting.Budget
    resource UniboExPoc.Ofbiz.Accounting.Budget.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetAttribute
    resource UniboExPoc.Ofbiz.Accounting.BudgetAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetItem
    resource UniboExPoc.Ofbiz.Accounting.BudgetItem.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetItemAttribute
    resource UniboExPoc.Ofbiz.Accounting.BudgetItemAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetItemType
    resource UniboExPoc.Ofbiz.Accounting.BudgetItemType.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetItemTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.BudgetItemTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetReview
    resource UniboExPoc.Ofbiz.Accounting.BudgetReview.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetReviewResultType
    resource UniboExPoc.Ofbiz.Accounting.BudgetReviewResultType.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetRevision
    resource UniboExPoc.Ofbiz.Accounting.BudgetRevision.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetRevisionImpact
    resource UniboExPoc.Ofbiz.Accounting.BudgetRevisionImpact.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetRole
    resource UniboExPoc.Ofbiz.Accounting.BudgetRole.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetScenario
    resource UniboExPoc.Ofbiz.Accounting.BudgetScenario.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetScenarioApplication
    resource UniboExPoc.Ofbiz.Accounting.BudgetScenarioApplication.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetScenarioRule
    resource UniboExPoc.Ofbiz.Accounting.BudgetScenarioRule.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetStatus
    resource UniboExPoc.Ofbiz.Accounting.BudgetStatus.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetType
    resource UniboExPoc.Ofbiz.Accounting.BudgetType.Version
    resource UniboExPoc.Ofbiz.Accounting.BudgetTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.BudgetTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccount
    resource UniboExPoc.Ofbiz.Accounting.FinAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountAttribute
    resource UniboExPoc.Ofbiz.Accounting.FinAccountAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountAuth
    resource UniboExPoc.Ofbiz.Accounting.FinAccountAuth.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountRole
    resource UniboExPoc.Ofbiz.Accounting.FinAccountRole.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountStatus
    resource UniboExPoc.Ofbiz.Accounting.FinAccountStatus.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTrans
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTrans.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTransAttribute
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTransAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTransType
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTransType.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTransTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTransTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountType
    resource UniboExPoc.Ofbiz.Accounting.FinAccountType.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTypeGlAccount
    resource UniboExPoc.Ofbiz.Accounting.FinAccountTypeGlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAsset
    resource UniboExPoc.Ofbiz.Accounting.FixedAsset.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetAttribute
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetDepMethod
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetDepMethod.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetGeoPoint
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetGeoPoint.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetIdent
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetIdent.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetIdentType
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetIdentType.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetMaint
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetMaint.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetMeter
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetMeter.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetProduct
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetProduct.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetProductType
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetProductType.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetTypeGlAccount
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetTypeGlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetRegistration
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetRegistration.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetStdCost
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetStdCost.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetStdCostType
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetStdCostType.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetType
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetType.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.PartyFixedAssetAssignment
    resource UniboExPoc.Ofbiz.Accounting.PartyFixedAssetAssignment.Version
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetMaintOrder
    resource UniboExPoc.Ofbiz.Accounting.FixedAssetMaintOrder.Version
    resource UniboExPoc.Ofbiz.Accounting.AccommodationClass
    resource UniboExPoc.Ofbiz.Accounting.AccommodationClass.Version
    resource UniboExPoc.Ofbiz.Accounting.AccommodationSpot
    resource UniboExPoc.Ofbiz.Accounting.AccommodationSpot.Version
    resource UniboExPoc.Ofbiz.Accounting.AccommodationMap
    resource UniboExPoc.Ofbiz.Accounting.AccommodationMap.Version
    resource UniboExPoc.Ofbiz.Accounting.AccommodationMapType
    resource UniboExPoc.Ofbiz.Accounting.AccommodationMapType.Version
    resource UniboExPoc.Ofbiz.Accounting.Invoice
    resource UniboExPoc.Ofbiz.Accounting.Invoice.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceAttribute
    resource UniboExPoc.Ofbiz.Accounting.InvoiceAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceContent
    resource UniboExPoc.Ofbiz.Accounting.InvoiceContent.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceContentType
    resource UniboExPoc.Ofbiz.Accounting.InvoiceContentType.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceContactMech
    resource UniboExPoc.Ofbiz.Accounting.InvoiceContactMech.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItem
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItem.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemAssoc
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemAssoc.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemAssocType
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemAssocType.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemAttribute
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemType
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemType.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemTypeGlAccount
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemTypeGlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemTypeMap
    resource UniboExPoc.Ofbiz.Accounting.InvoiceItemTypeMap.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceRole
    resource UniboExPoc.Ofbiz.Accounting.InvoiceRole.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceStatus
    resource UniboExPoc.Ofbiz.Accounting.InvoiceStatus.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceTerm
    resource UniboExPoc.Ofbiz.Accounting.InvoiceTerm.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceTermAttribute
    resource UniboExPoc.Ofbiz.Accounting.InvoiceTermAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceType
    resource UniboExPoc.Ofbiz.Accounting.InvoiceType.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.InvoiceTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.InvoiceNote
    resource UniboExPoc.Ofbiz.Accounting.InvoiceNote.Version
    resource UniboExPoc.Ofbiz.Accounting.AcctgTrans
    resource UniboExPoc.Ofbiz.Accounting.AcctgTrans.Version
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransAttribute
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransEntry
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransEntry.Version
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransEntryType
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransEntryType.Version
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransType
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransType.Version
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.AcctgTransTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccount
    resource UniboExPoc.Ofbiz.Accounting.GlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountClass
    resource UniboExPoc.Ofbiz.Accounting.GlAccountClass.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountGroup
    resource UniboExPoc.Ofbiz.Accounting.GlAccountGroup.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountGroupMember
    resource UniboExPoc.Ofbiz.Accounting.GlAccountGroupMember.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountGroupType
    resource UniboExPoc.Ofbiz.Accounting.GlAccountGroupType.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountHistory
    resource UniboExPoc.Ofbiz.Accounting.GlAccountHistory.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountOrganization
    resource UniboExPoc.Ofbiz.Accounting.GlAccountOrganization.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountRole
    resource UniboExPoc.Ofbiz.Accounting.GlAccountRole.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountType
    resource UniboExPoc.Ofbiz.Accounting.GlAccountType.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountTypeDefault
    resource UniboExPoc.Ofbiz.Accounting.GlAccountTypeDefault.Version
    resource UniboExPoc.Ofbiz.Accounting.GlBudgetXref
    resource UniboExPoc.Ofbiz.Accounting.GlBudgetXref.Version
    resource UniboExPoc.Ofbiz.Accounting.GlFiscalType
    resource UniboExPoc.Ofbiz.Accounting.GlFiscalType.Version
    resource UniboExPoc.Ofbiz.Accounting.GlJournal
    resource UniboExPoc.Ofbiz.Accounting.GlJournal.Version
    resource UniboExPoc.Ofbiz.Accounting.GlReconciliation
    resource UniboExPoc.Ofbiz.Accounting.GlReconciliation.Version
    resource UniboExPoc.Ofbiz.Accounting.GlReconciliationEntry
    resource UniboExPoc.Ofbiz.Accounting.GlReconciliationEntry.Version
    resource UniboExPoc.Ofbiz.Accounting.GlResourceType
    resource UniboExPoc.Ofbiz.Accounting.GlResourceType.Version
    resource UniboExPoc.Ofbiz.Accounting.GlXbrlClass
    resource UniboExPoc.Ofbiz.Accounting.GlXbrlClass.Version
    resource UniboExPoc.Ofbiz.Accounting.PartyAcctgPreference
    resource UniboExPoc.Ofbiz.Accounting.PartyAcctgPreference.Version
    resource UniboExPoc.Ofbiz.Accounting.PartyPrefDocTypeTpl
    resource UniboExPoc.Ofbiz.Accounting.PartyPrefDocTypeTpl.Version
    resource UniboExPoc.Ofbiz.Accounting.ProductAverageCost
    resource UniboExPoc.Ofbiz.Accounting.ProductAverageCost.Version
    resource UniboExPoc.Ofbiz.Accounting.ProductAverageCostType
    resource UniboExPoc.Ofbiz.Accounting.ProductAverageCostType.Version
    resource UniboExPoc.Ofbiz.Accounting.SettlementTerm
    resource UniboExPoc.Ofbiz.Accounting.SettlementTerm.Version
    resource UniboExPoc.Ofbiz.Accounting.VarianceReasonGlAccount
    resource UniboExPoc.Ofbiz.Accounting.VarianceReasonGlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.BillingAccount
    resource UniboExPoc.Ofbiz.Accounting.BillingAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.BillingAccountRole
    resource UniboExPoc.Ofbiz.Accounting.BillingAccountRole.Version
    resource UniboExPoc.Ofbiz.Accounting.BillingAccountTerm
    resource UniboExPoc.Ofbiz.Accounting.BillingAccountTerm.Version
    resource UniboExPoc.Ofbiz.Accounting.BillingAccountTermAttr
    resource UniboExPoc.Ofbiz.Accounting.BillingAccountTermAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.CreditCard
    resource UniboExPoc.Ofbiz.Accounting.CreditCard.Version
    resource UniboExPoc.Ofbiz.Accounting.CreditCardTypeGlAccount
    resource UniboExPoc.Ofbiz.Accounting.CreditCardTypeGlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.Deduction
    resource UniboExPoc.Ofbiz.Accounting.Deduction.Version
    resource UniboExPoc.Ofbiz.Accounting.DeductionType
    resource UniboExPoc.Ofbiz.Accounting.DeductionType.Version
    resource UniboExPoc.Ofbiz.Accounting.EftAccount
    resource UniboExPoc.Ofbiz.Accounting.EftAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.CheckAccount
    resource UniboExPoc.Ofbiz.Accounting.CheckAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.GiftCard
    resource UniboExPoc.Ofbiz.Accounting.GiftCard.Version
    resource UniboExPoc.Ofbiz.Accounting.GiftCardFulfillment
    resource UniboExPoc.Ofbiz.Accounting.GiftCardFulfillment.Version
    resource UniboExPoc.Ofbiz.Accounting.Payment
    resource UniboExPoc.Ofbiz.Accounting.Payment.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentApplication
    resource UniboExPoc.Ofbiz.Accounting.PaymentApplication.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentAttribute
    resource UniboExPoc.Ofbiz.Accounting.PaymentAttribute.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentBudgetAllocation
    resource UniboExPoc.Ofbiz.Accounting.PaymentBudgetAllocation.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentContent
    resource UniboExPoc.Ofbiz.Accounting.PaymentContent.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentContentType
    resource UniboExPoc.Ofbiz.Accounting.PaymentContentType.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentMethod
    resource UniboExPoc.Ofbiz.Accounting.PaymentMethod.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentMethodType
    resource UniboExPoc.Ofbiz.Accounting.PaymentMethodType.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentMethodTypeGlAccount
    resource UniboExPoc.Ofbiz.Accounting.PaymentMethodTypeGlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentType
    resource UniboExPoc.Ofbiz.Accounting.PaymentType.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentTypeAttr
    resource UniboExPoc.Ofbiz.Accounting.PaymentTypeAttr.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGlAccountTypeMap
    resource UniboExPoc.Ofbiz.Accounting.PaymentGlAccountTypeMap.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayConfigType
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayConfigType.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayConfig
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayConfig.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewaySagePay
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewaySagePay.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayAuthorizeNet
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayAuthorizeNet.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayEway
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayEway.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayCyberSource
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayCyberSource.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayPayflowPro
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayPayflowPro.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayPayPal
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayPayPal.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayClearCommerce
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayClearCommerce.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayWorldPay
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayWorldPay.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayOrbital
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayOrbital.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewaySecurePay
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewaySecurePay.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayRespMsg
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayRespMsg.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayResponse
    resource UniboExPoc.Ofbiz.Accounting.PaymentGatewayResponse.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGroup
    resource UniboExPoc.Ofbiz.Accounting.PaymentGroup.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGroupType
    resource UniboExPoc.Ofbiz.Accounting.PaymentGroupType.Version
    resource UniboExPoc.Ofbiz.Accounting.PaymentGroupMember
    resource UniboExPoc.Ofbiz.Accounting.PaymentGroupMember.Version
    resource UniboExPoc.Ofbiz.Accounting.PayPalPaymentMethod
    resource UniboExPoc.Ofbiz.Accounting.PayPalPaymentMethod.Version
    resource UniboExPoc.Ofbiz.Accounting.ValueLinkKey
    resource UniboExPoc.Ofbiz.Accounting.ValueLinkKey.Version
    resource UniboExPoc.Ofbiz.Accounting.PartyTaxAuthInfo
    resource UniboExPoc.Ofbiz.Accounting.PartyTaxAuthInfo.Version
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthority
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthority.Version
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityAssoc
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityAssoc.Version
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityAssocType
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityAssocType.Version
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityCategory
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityCategory.Version
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityGlAccount
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityGlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityRateProduct
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityRateProduct.Version
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityRateType
    resource UniboExPoc.Ofbiz.Accounting.TaxAuthorityRateType.Version
    resource UniboExPoc.Ofbiz.Accounting.ZipSalesRuleLookup
    resource UniboExPoc.Ofbiz.Accounting.ZipSalesRuleLookup.Version
    resource UniboExPoc.Ofbiz.Accounting.ZipSalesTaxLookup
    resource UniboExPoc.Ofbiz.Accounting.ZipSalesTaxLookup.Version
    resource UniboExPoc.Ofbiz.Accounting.PartyGlAccount
    resource UniboExPoc.Ofbiz.Accounting.PartyGlAccount.Version
    resource UniboExPoc.Ofbiz.Accounting.RateType
    resource UniboExPoc.Ofbiz.Accounting.RateType.Version
    resource UniboExPoc.Ofbiz.Accounting.RateAmount
    resource UniboExPoc.Ofbiz.Accounting.RateAmount.Version
    resource UniboExPoc.Ofbiz.Accounting.PartyRate
    resource UniboExPoc.Ofbiz.Accounting.PartyRate.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountCategory
    resource UniboExPoc.Ofbiz.Accounting.GlAccountCategory.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountCategoryMember
    resource UniboExPoc.Ofbiz.Accounting.GlAccountCategoryMember.Version
    resource UniboExPoc.Ofbiz.Accounting.GlAccountCategoryType
    resource UniboExPoc.Ofbiz.Accounting.GlAccountCategoryType.Version
  end
end
