# Generated by bdd_compiler from /home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl. DO NOT EDIT.

defmodule UniboV4.BDD.Generated.DELIVERY_SHIPMENT_ROUTE_SEGMENTTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated"}
    # line 4: GIVEN given_seed_context id="delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 4, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_branch_or_exception
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_branch_or_exception]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_branch_or_exception"}
    # line 9: GIVEN given_seed_context id="delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_branch_or_exception" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_branch_or_exception", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 9, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_branch_or_exception\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_change_effect"}
    # line 14: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_change_effect" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_change_effect", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 14, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_change_effect\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_success
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_success"}
    # line 19: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_success" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_success", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 19, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_success\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_read_read
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_read_read]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_read_read"}
    # line 24: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_read_read" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_read_read", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 24, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_read_read\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 24)
    # line 25: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 25, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 25)
    # line 26: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 26, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_change_effect"}
    # line 29: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_change_effect" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_change_effect", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 29, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_change_effect\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 29)
    # line 30: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 30, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 30)
    # line 31: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 31, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 31)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_validation_fail"}
    # line 34: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_validation_fail" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_validation_fail", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 34, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_validation_fail\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 34)
    # line 35: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 35, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 35)
    # line 36: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 36, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_change_effect"}
    # line 39: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_change_effect" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_change_effect", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 39, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_change_effect\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 39)
    # line 40: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 40, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 40)
    # line 41: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 41, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update"}
    # line 44: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 44, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 44)
    # line 45: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 45, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 45)
    # line 46: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 46, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_idempotent_replay
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_idempotent_replay]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_idempotent_replay"}
    # line 49: GIVEN given_seed_context id="delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_idempotent_replay" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_idempotent_replay", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 49, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_idempotent_replay\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 49)
    # line 50: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 50, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 50)
    # line 51: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 51, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 51)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update"}
    # line 54: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 54, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 54)
    # line 55: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 55, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 55)
    # line 56: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 56, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 56)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_success"}
    # line 59: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_success" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_success", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 59, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_success\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 59)
    # line 60: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 60, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 60)
    # line 61: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 61, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 61)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_success"}
    # line 64: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_success" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_success", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 64, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_confirm_shipment_update_risk_success\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 64)
    # line 65: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 65, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 65)
    # line 66: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 66, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 66)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_change_effect"}
    # line 69: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_change_effect" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_change_effect", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 69, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_change_effect\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 69)
    # line 70: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 70, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 70)
    # line 71: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 71, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 71)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_normal_publish
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_normal_publish]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_normal_publish"}
    # line 74: GIVEN given_seed_context id="delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_normal_publish" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_normal_publish", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 74, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_event_shipment_route_segment_update_tracking_delivery_tracking_updated_risk_normal_publish\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 74)
    # line 75: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 75, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 75)
    # line 76: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 76, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 76)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_mainline
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_mainline]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_mainline"}
    # line 79: GIVEN given_seed_context id="delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_mainline" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_mainline", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 79, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow_risk_mainline\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 79)
    # line 80: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 80, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 80)
    # line 81: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 81, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 81)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update"}
    # line 84: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_update_update" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_update_update", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 84, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_update_update\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 84)
    # line 85: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 85, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 85)
    # line 86: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 86, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 86)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_change_effect"}
    # line 89: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_change_effect" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_change_effect", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 89, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy_risk_change_effect\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 89)
    # line 90: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 90, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 90)
    # line 91: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 91, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 91)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update"}
    # line 94: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 94, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 94)
    # line 95: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 95, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 95)
    # line 96: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 96, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 96)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_success"}
    # line 99: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_success" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_success", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 99, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_update_update_risk_success\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 99)
    # line 100: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 100, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 100)
    # line 101: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 101, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 101)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create"}
    # line 104: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_create_create" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_create_create", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 104, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_create_create\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 104)
    # line 105: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 105, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 105)
    # line 106: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 106, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 106)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_change_effect"}
    # line 109: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_change_effect" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_change_effect", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 109, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_record_cost_update_risk_change_effect\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 109)
    # line 110: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 110, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 110)
    # line 111: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 111, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 111)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_success"}
    # line 114: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_success" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_success", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 114, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_update_tracking_update_risk_success\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 114)
    # line 115: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 115, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 115)
    # line 116: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 116, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 116)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow"}
    # line 119: GIVEN given_seed_context id="delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 119, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_workflow_shipment_route_segment_route_segment_flow\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 119)
    # line 120: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 120, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 120)
    # line 121: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 121, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 121)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_success
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_success"}
    # line 124: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_success" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_success", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 124, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_create_create_risk_success\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 124)
    # line 125: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 125, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 125)
    # line 126: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 126, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 126)
    _ctx = ctx
    :ok
  end

  # Source: BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy
  @tag :all
  @tag :seed
  test "[BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-DELIVERY_SHIPMENT_ROUTE_SEGMENT-SEED-delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy"}
    # line 129: GIVEN given_seed_context id="delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy" module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy", module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 129, raw: "GIVEN given_seed_context id=\"delivery_shipment_route_segment_action_shipment_route_segment_destroy_destroy\" module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 129)
    # line 130: WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 130, raw: "WHEN when_execute_seed_contract module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 130)
    # line 131: THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ROUTE_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "DELIVERY_SHIPMENT_ROUTE_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/DELIVERY_SHIPMENT_ROUTE_SEGMENT.dsl", line: 131, raw: "THEN then_seed_contract_should_hold module=\"DELIVERY_SHIPMENT_ROUTE_SEGMENT\""}, 131)
    _ctx = ctx
    :ok
  end

end
