# Generated by bdd_compiler from /home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/ECOMMERCE_MAIL_TEMPLATE.dsl. DO NOT EDIT.

defmodule UniboV4.BDD.Generated.ECOMMERCE_MAIL_TEMPLATETest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-ECOMMERCE_MAIL_TEMPLATE-SEED-ecommerce_mail_template_action_mail_template_read_read
  @tag :all
  @tag :seed
  test "[BDD-ECOMMERCE_MAIL_TEMPLATE-SEED-ecommerce_mail_template_action_mail_template_read_read]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-ECOMMERCE_MAIL_TEMPLATE-SEED-ecommerce_mail_template_action_mail_template_read_read"}
    # line 4: GIVEN given_seed_context id="ecommerce_mail_template_action_mail_template_read_read" module="ECOMMERCE_MAIL_TEMPLATE"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "ecommerce_mail_template_action_mail_template_read_read", module: "ECOMMERCE_MAIL_TEMPLATE"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/ECOMMERCE_MAIL_TEMPLATE.dsl", line: 4, raw: "GIVEN given_seed_context id=\"ecommerce_mail_template_action_mail_template_read_read\" module=\"ECOMMERCE_MAIL_TEMPLATE\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="ECOMMERCE_MAIL_TEMPLATE"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "ECOMMERCE_MAIL_TEMPLATE"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/ECOMMERCE_MAIL_TEMPLATE.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"ECOMMERCE_MAIL_TEMPLATE\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="ECOMMERCE_MAIL_TEMPLATE"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "ECOMMERCE_MAIL_TEMPLATE"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/ECOMMERCE_MAIL_TEMPLATE.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"ECOMMERCE_MAIL_TEMPLATE\""}, 6)
    _ctx = ctx
    :ok
  end

end
