# Generated by bdd_compiler from /home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK.dsl. DO NOT EDIT.

defmodule UniboV4.BDD.Generated.HELPDESK_FIELD_SERVICE_ORDER_TAG_LINKTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK-SEED-helpdesk_field_service_order_tag_link_action_field_service_order_tag_link_read_read
  @tag :all
  @tag :seed
  test "[BDD-HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK-SEED-helpdesk_field_service_order_tag_link_action_field_service_order_tag_link_read_read]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK-SEED-helpdesk_field_service_order_tag_link_action_field_service_order_tag_link_read_read"}
    # line 4: GIVEN given_seed_context id="helpdesk_field_service_order_tag_link_action_field_service_order_tag_link_read_read" module="HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "helpdesk_field_service_order_tag_link_action_field_service_order_tag_link_read_read", module: "HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK.dsl", line: 4, raw: "GIVEN given_seed_context id=\"helpdesk_field_service_order_tag_link_action_field_service_order_tag_link_read_read\" module=\"HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK\""}, 6)
    _ctx = ctx
    :ok
  end

end
