# Generated by bdd_compiler from /home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl. DO NOT EDIT.

defmodule UniboV4.BDD.Generated.HR_DEPARTMENTTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_read_read
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_read_read]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_read_read"}
    # line 4: GIVEN given_seed_context id="hr_department_action_department_read_read" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_read_read", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 4, raw: "GIVEN given_seed_context id=\"hr_department_action_department_read_read\" module=\"HR_DEPARTMENT\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update"}
    # line 9: GIVEN given_seed_context id="hr_department_action_department_update_update" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_update_update", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 9, raw: "GIVEN given_seed_context id=\"hr_department_action_department_update_update\" module=\"HR_DEPARTMENT\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_change_effect"}
    # line 14: GIVEN given_seed_context id="hr_department_action_department_update_update_risk_change_effect" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_update_update_risk_change_effect", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 14, raw: "GIVEN given_seed_context id=\"hr_department_action_department_update_update_risk_change_effect\" module=\"HR_DEPARTMENT\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow"}
    # line 19: GIVEN given_seed_context id="hr_department_workflow_department_department_write_flow" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_workflow_department_department_write_flow", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 19, raw: "GIVEN given_seed_context id=\"hr_department_workflow_department_department_write_flow\" module=\"HR_DEPARTMENT\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow_risk_mainline
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow_risk_mainline]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow_risk_mainline"}
    # line 24: GIVEN given_seed_context id="hr_department_workflow_department_department_write_flow_risk_mainline" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_workflow_department_department_write_flow_risk_mainline", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 24, raw: "GIVEN given_seed_context id=\"hr_department_workflow_department_department_write_flow_risk_mainline\" module=\"HR_DEPARTMENT\""}, 24)
    # line 25: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 25, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 25)
    # line 26: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 26, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_success
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_success"}
    # line 29: GIVEN given_seed_context id="hr_department_action_department_create_create_risk_success" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_create_create_risk_success", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 29, raw: "GIVEN given_seed_context id=\"hr_department_action_department_create_create_risk_success\" module=\"HR_DEPARTMENT\""}, 29)
    # line 30: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 30, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 30)
    # line 31: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 31, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 31)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_validation_fail"}
    # line 34: GIVEN given_seed_context id="hr_department_action_department_create_create_risk_validation_fail" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_create_create_risk_validation_fail", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 34, raw: "GIVEN given_seed_context id=\"hr_department_action_department_create_create_risk_validation_fail\" module=\"HR_DEPARTMENT\""}, 34)
    # line 35: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 35, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 35)
    # line 36: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 36, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create"}
    # line 39: GIVEN given_seed_context id="hr_department_action_department_create_create" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_create_create", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 39, raw: "GIVEN given_seed_context id=\"hr_department_action_department_create_create\" module=\"HR_DEPARTMENT\""}, 39)
    # line 40: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 40, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 40)
    # line 41: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 41, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_validation_fail"}
    # line 44: GIVEN given_seed_context id="hr_department_action_department_update_update_risk_validation_fail" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_update_update_risk_validation_fail", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 44, raw: "GIVEN given_seed_context id=\"hr_department_action_department_update_update_risk_validation_fail\" module=\"HR_DEPARTMENT\""}, 44)
    # line 45: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 45, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 45)
    # line 46: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 46, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_update_update_risk_success"}
    # line 49: GIVEN given_seed_context id="hr_department_action_department_update_update_risk_success" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_update_update_risk_success", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 49, raw: "GIVEN given_seed_context id=\"hr_department_action_department_update_update_risk_success\" module=\"HR_DEPARTMENT\""}, 49)
    # line 50: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 50, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 50)
    # line 51: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 51, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 51)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_action_department_create_create_risk_change_effect"}
    # line 54: GIVEN given_seed_context id="hr_department_action_department_create_create_risk_change_effect" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_action_department_create_create_risk_change_effect", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 54, raw: "GIVEN given_seed_context id=\"hr_department_action_department_create_create_risk_change_effect\" module=\"HR_DEPARTMENT\""}, 54)
    # line 55: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 55, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 55)
    # line 56: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 56, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 56)
    _ctx = ctx
    :ok
  end

  # Source: BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow_risk_branch_or_exception
  @tag :all
  @tag :seed
  test "[BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow_risk_branch_or_exception]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-HR_DEPARTMENT-SEED-hr_department_workflow_department_department_write_flow_risk_branch_or_exception"}
    # line 59: GIVEN given_seed_context id="hr_department_workflow_department_department_write_flow_risk_branch_or_exception" module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "hr_department_workflow_department_department_write_flow_risk_branch_or_exception", module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 59, raw: "GIVEN given_seed_context id=\"hr_department_workflow_department_department_write_flow_risk_branch_or_exception\" module=\"HR_DEPARTMENT\""}, 59)
    # line 60: WHEN when_execute_seed_contract module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 60, raw: "WHEN when_execute_seed_contract module=\"HR_DEPARTMENT\""}, 60)
    # line 61: THEN then_seed_contract_should_hold module="HR_DEPARTMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "HR_DEPARTMENT"}, %{file: "/home/wangbo/document/unibo_ex_poc/v4/docs/bdd/HR_DEPARTMENT.dsl", line: 61, raw: "THEN then_seed_contract_should_hold module=\"HR_DEPARTMENT\""}, 61)
    _ctx = ctx
    :ok
  end

end
