# Generated by bdd_compiler from /home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl. DO NOT EDIT.

defmodule UniboV4.BDD.Generated.INVENTORY_PICKING_BATCHTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create_risk_change_effect"}
    # line 4: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_create_create_risk_change_effect" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_create_create_risk_change_effect", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 4, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_create_create_risk_change_effect\" module=\"INVENTORY_PICKING_BATCH\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_change_effect"}
    # line 9: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_confirm_update_risk_change_effect" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_confirm_update_risk_change_effect", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 9, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_confirm_update_risk_change_effect\" module=\"INVENTORY_PICKING_BATCH\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update"}
    # line 14: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_done_update" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_done_update", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 14, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_done_update\" module=\"INVENTORY_PICKING_BATCH\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update_risk_change_effect"}
    # line 19: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_update_update_risk_change_effect" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_update_update_risk_change_effect", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 19, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_update_update_risk_change_effect\" module=\"INVENTORY_PICKING_BATCH\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update"}
    # line 24: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_assign_update" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_assign_update", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 24, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_assign_update\" module=\"INVENTORY_PICKING_BATCH\""}, 24)
    # line 25: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 25, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 25)
    # line 26: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 26, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow"}
    # line 29: GIVEN given_seed_context id="inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 29, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow\" module=\"INVENTORY_PICKING_BATCH\""}, 29)
    # line 30: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 30, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 30)
    # line 31: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 31, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 31)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_branch_or_exception
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_branch_or_exception]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_branch_or_exception"}
    # line 34: GIVEN given_seed_context id="inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_branch_or_exception" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_branch_or_exception", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 34, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_branch_or_exception\" module=\"INVENTORY_PICKING_BATCH\""}, 34)
    # line 35: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 35, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 35)
    # line 36: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 36, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_change_effect"}
    # line 39: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_cancel_update_risk_change_effect" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_cancel_update_risk_change_effect", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 39, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_cancel_update_risk_change_effect\" module=\"INVENTORY_PICKING_BATCH\""}, 39)
    # line 40: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 40, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 40)
    # line 41: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 41, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update"}
    # line 44: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_confirm_update" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_confirm_update", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 44, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_confirm_update\" module=\"INVENTORY_PICKING_BATCH\""}, 44)
    # line 45: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 45, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 45)
    # line 46: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 46, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_change_effect"}
    # line 49: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_assign_update_risk_change_effect" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_assign_update_risk_change_effect", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 49, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_assign_update_risk_change_effect\" module=\"INVENTORY_PICKING_BATCH\""}, 49)
    # line 50: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 50, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 50)
    # line 51: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 51, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 51)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow"}
    # line 54: GIVEN given_seed_context id="inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 54, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow\" module=\"INVENTORY_PICKING_BATCH\""}, 54)
    # line 55: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 55, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 55)
    # line 56: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 56, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 56)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_read_read
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_read_read]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_read_read"}
    # line 59: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_read_read" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_read_read", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 59, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_read_read\" module=\"INVENTORY_PICKING_BATCH\""}, 59)
    # line 60: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 60, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 60)
    # line 61: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 61, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 61)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_change_effect"}
    # line 64: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_done_update_risk_change_effect" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_done_update_risk_change_effect", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 64, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_done_update_risk_change_effect\" module=\"INVENTORY_PICKING_BATCH\""}, 64)
    # line 65: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 65, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 65)
    # line 66: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 66, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 66)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_branch_or_exception
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_branch_or_exception]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_branch_or_exception"}
    # line 69: GIVEN given_seed_context id="inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_branch_or_exception" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_branch_or_exception", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 69, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_branch_or_exception\" module=\"INVENTORY_PICKING_BATCH\""}, 69)
    # line 70: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 70, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 70)
    # line 71: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 71, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 71)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_success"}
    # line 74: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_confirm_update_risk_success" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_confirm_update_risk_success", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 74, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_confirm_update_risk_success\" module=\"INVENTORY_PICKING_BATCH\""}, 74)
    # line 75: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 75, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 75)
    # line 76: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 76, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 76)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create"}
    # line 79: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_create_create" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_create_create", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 79, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_create_create\" module=\"INVENTORY_PICKING_BATCH\""}, 79)
    # line 80: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 80, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 80)
    # line 81: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 81, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 81)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_success"}
    # line 84: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_cancel_update_risk_success" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_cancel_update_risk_success", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 84, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_cancel_update_risk_success\" module=\"INVENTORY_PICKING_BATCH\""}, 84)
    # line 85: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 85, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 85)
    # line 86: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 86, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 86)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_validation_fail"}
    # line 89: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_assign_update_risk_validation_fail" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_assign_update_risk_validation_fail", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 89, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_assign_update_risk_validation_fail\" module=\"INVENTORY_PICKING_BATCH\""}, 89)
    # line 90: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 90, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 90)
    # line 91: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 91, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 91)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update_risk_success"}
    # line 94: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_update_update_risk_success" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_update_update_risk_success", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 94, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_update_update_risk_success\" module=\"INVENTORY_PICKING_BATCH\""}, 94)
    # line 95: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 95, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 95)
    # line 96: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 96, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 96)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update_risk_validation_fail"}
    # line 99: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_cancel_update_risk_validation_fail" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_cancel_update_risk_validation_fail", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 99, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_cancel_update_risk_validation_fail\" module=\"INVENTORY_PICKING_BATCH\""}, 99)
    # line 100: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 100, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 100)
    # line 101: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 101, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 101)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_update_update"}
    # line 104: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_update_update" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_update_update", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 104, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_update_update\" module=\"INVENTORY_PICKING_BATCH\""}, 104)
    # line 105: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 105, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 105)
    # line 106: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 106, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 106)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_assign_update_risk_success"}
    # line 109: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_assign_update_risk_success" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_assign_update_risk_success", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 109, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_assign_update_risk_success\" module=\"INVENTORY_PICKING_BATCH\""}, 109)
    # line 110: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 110, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 110)
    # line 111: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 111, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 111)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_confirm_update_risk_validation_fail"}
    # line 114: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_confirm_update_risk_validation_fail" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_confirm_update_risk_validation_fail", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 114, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_confirm_update_risk_validation_fail\" module=\"INVENTORY_PICKING_BATCH\""}, 114)
    # line 115: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 115, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 115)
    # line 116: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 116, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 116)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_validation_fail"}
    # line 119: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_done_update_risk_validation_fail" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_done_update_risk_validation_fail", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 119, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_done_update_risk_validation_fail\" module=\"INVENTORY_PICKING_BATCH\""}, 119)
    # line 120: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 120, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 120)
    # line 121: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 121, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 121)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_mainline
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_mainline]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_mainline"}
    # line 124: GIVEN given_seed_context id="inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_mainline" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_mainline", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 124, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_workflow_picking_batch_picking_batch_cancel_flow_risk_mainline\" module=\"INVENTORY_PICKING_BATCH\""}, 124)
    # line 125: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 125, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 125)
    # line 126: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 126, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 126)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_mainline
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_mainline]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_mainline"}
    # line 129: GIVEN given_seed_context id="inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_mainline" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_mainline", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 129, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_workflow_picking_batch_picking_batch_lifecycle_flow_risk_mainline\" module=\"INVENTORY_PICKING_BATCH\""}, 129)
    # line 130: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 130, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 130)
    # line 131: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 131, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 131)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_done_update_risk_success"}
    # line 134: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_done_update_risk_success" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_done_update_risk_success", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 134, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_done_update_risk_success\" module=\"INVENTORY_PICKING_BATCH\""}, 134)
    # line 135: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 135, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 135)
    # line 136: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 136, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 136)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create_risk_success
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_create_create_risk_success"}
    # line 139: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_create_create_risk_success" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_create_create_risk_success", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 139, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_create_create_risk_success\" module=\"INVENTORY_PICKING_BATCH\""}, 139)
    # line 140: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 140, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 140)
    # line 141: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 141, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 141)
    _ctx = ctx
    :ok
  end

  # Source: BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update
  @tag :all
  @tag :seed
  test "[BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-INVENTORY_PICKING_BATCH-SEED-inventory_picking_batch_action_picking_batch_action_cancel_update"}
    # line 144: GIVEN given_seed_context id="inventory_picking_batch_action_picking_batch_action_cancel_update" module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "inventory_picking_batch_action_picking_batch_action_cancel_update", module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 144, raw: "GIVEN given_seed_context id=\"inventory_picking_batch_action_picking_batch_action_cancel_update\" module=\"INVENTORY_PICKING_BATCH\""}, 144)
    # line 145: WHEN when_execute_seed_contract module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 145, raw: "WHEN when_execute_seed_contract module=\"INVENTORY_PICKING_BATCH\""}, 145)
    # line 146: THEN then_seed_contract_should_hold module="INVENTORY_PICKING_BATCH"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "INVENTORY_PICKING_BATCH"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/INVENTORY_PICKING_BATCH.dsl", line: 146, raw: "THEN then_seed_contract_should_hold module=\"INVENTORY_PICKING_BATCH\""}, 146)
    _ctx = ctx
    :ok
  end

end
