# Generated by bdd_compiler from /home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl. DO NOT EDIT.

defmodule UniboV4.BDD.Generated.IO_T_VO_IP_PROVIDERTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update"}
    # line 4: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_update_update" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_update_update", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 4, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_update_update\" module=\"IO_T_VO_IP_PROVIDER\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_success"}
    # line 9: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_success" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_success", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 9, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_success\" module=\"IO_T_VO_IP_PROVIDER\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow"}
    # line 14: GIVEN given_seed_context id="io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 14, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow\" module=\"IO_T_VO_IP_PROVIDER\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_change_effect"}
    # line 19: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_change_effect" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_change_effect", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 19, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_change_effect\" module=\"IO_T_VO_IP_PROVIDER\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_branch_or_exception
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_branch_or_exception]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_branch_or_exception"}
    # line 24: GIVEN given_seed_context id="io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_branch_or_exception" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_branch_or_exception", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 24, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_branch_or_exception\" module=\"IO_T_VO_IP_PROVIDER\""}, 24)
    # line 25: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 25, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 25)
    # line 26: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 26, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_success
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_success"}
    # line 29: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_success" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_success", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 29, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy_risk_success\" module=\"IO_T_VO_IP_PROVIDER\""}, 29)
    # line 30: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 30, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 30)
    # line 31: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 31, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 31)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_read_read
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_read_read]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_read_read"}
    # line 34: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_read_read" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_read_read", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 34, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_read_read\" module=\"IO_T_VO_IP_PROVIDER\""}, 34)
    # line 35: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 35, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 35)
    # line 36: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 36, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_success
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_success"}
    # line 39: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_success" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_success", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 39, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_success\" module=\"IO_T_VO_IP_PROVIDER\""}, 39)
    # line 40: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 40, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 40)
    # line 41: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 41, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_mainline
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_mainline]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_mainline"}
    # line 44: GIVEN given_seed_context id="io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_mainline" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_mainline", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 44, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_workflow_vo_ip_provider_voip_provider_lifecycle_flow_risk_mainline\" module=\"IO_T_VO_IP_PROVIDER\""}, 44)
    # line 45: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 45, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 45)
    # line 46: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 46, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy"}
    # line 49: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 49, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_destroy_destroy\" module=\"IO_T_VO_IP_PROVIDER\""}, 49)
    # line 50: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 50, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 50)
    # line 51: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 51, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 51)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create"}
    # line 54: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_create_create" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_create_create", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 54, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_create_create\" module=\"IO_T_VO_IP_PROVIDER\""}, 54)
    # line 55: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 55, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 55)
    # line 56: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 56, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 56)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_change_effect"}
    # line 59: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_change_effect" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_change_effect", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 59, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_change_effect\" module=\"IO_T_VO_IP_PROVIDER\""}, 59)
    # line 60: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 60, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 60)
    # line 61: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 61, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 61)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_validation_fail"}
    # line 64: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_validation_fail" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_validation_fail", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 64, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_create_create_risk_validation_fail\" module=\"IO_T_VO_IP_PROVIDER\""}, 64)
    # line 65: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 65, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 65)
    # line 66: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 66, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 66)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_change_effect"}
    # line 69: GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_change_effect" module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_change_effect", module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 69, raw: "GIVEN given_seed_context id=\"io_t_vo_ip_provider_action_vo_ip_provider_update_update_risk_change_effect\" module=\"IO_T_VO_IP_PROVIDER\""}, 69)
    # line 70: WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 70, raw: "WHEN when_execute_seed_contract module=\"IO_T_VO_IP_PROVIDER\""}, 70)
    # line 71: THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_VO_IP_PROVIDER"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_VO_IP_PROVIDER.dsl", line: 71, raw: "THEN then_seed_contract_should_hold module=\"IO_T_VO_IP_PROVIDER\""}, 71)
    _ctx = ctx
    :ok
  end

end
