# Generated by bdd_compiler from /home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl. DO NOT EDIT.

defmodule UniboV4.BDD.Generated.IO_T_IO_T_BOXTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_idempotent_replay
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_idempotent_replay]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_idempotent_replay"}
    # line 4: GIVEN given_seed_context id="io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_idempotent_replay" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_idempotent_replay", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 4, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_idempotent_replay\" module=\"IO_T_IO_T_BOX\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired"}
    # line 9: GIVEN given_seed_context id="io_t_io_t_box_event_io_t_box_register_box_iot_box_paired" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_event_io_t_box_register_box_iot_box_paired", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 9, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_event_io_t_box_register_box_iot_box_paired\" module=\"IO_T_IO_T_BOX\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_change_effect"}
    # line 14: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_create_create_risk_change_effect" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_create_create_risk_change_effect", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 14, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_create_create_risk_change_effect\" module=\"IO_T_IO_T_BOX\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_read_read
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_read_read]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_read_read"}
    # line 19: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_read_read" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_read_read", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 19, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_read_read\" module=\"IO_T_IO_T_BOX\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update_risk_change_effect"}
    # line 24: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_heartbeat_update_risk_change_effect" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_heartbeat_update_risk_change_effect", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 24, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_heartbeat_update_risk_change_effect\" module=\"IO_T_IO_T_BOX\""}, 24)
    # line 25: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 25, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 25)
    # line 26: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 26, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_validation_fail"}
    # line 29: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_register_box_update_risk_validation_fail" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_register_box_update_risk_validation_fail", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 29, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_register_box_update_risk_validation_fail\" module=\"IO_T_IO_T_BOX\""}, 29)
    # line 30: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 30, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 30)
    # line 31: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 31, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 31)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update"}
    # line 34: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_heartbeat_update" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_heartbeat_update", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 34, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_heartbeat_update\" module=\"IO_T_IO_T_BOX\""}, 34)
    # line 35: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 35, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 35)
    # line 36: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 36, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow"}
    # line 39: GIVEN given_seed_context id="io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 39, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow\" module=\"IO_T_IO_T_BOX\""}, 39)
    # line 40: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 40, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 40)
    # line 41: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 41, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_heartbeat_update_risk_success"}
    # line 44: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_heartbeat_update_risk_success" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_heartbeat_update_risk_success", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 44, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_heartbeat_update_risk_success\" module=\"IO_T_IO_T_BOX\""}, 44)
    # line 45: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 45, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 45)
    # line 46: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 46, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_normal_publish
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_normal_publish]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_normal_publish"}
    # line 49: GIVEN given_seed_context id="io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_normal_publish" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_normal_publish", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 49, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline_risk_normal_publish\" module=\"IO_T_IO_T_BOX\""}, 49)
    # line 50: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 50, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 50)
    # line 51: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 51, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 51)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update_risk_change_effect"}
    # line 54: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_update_update_risk_change_effect" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_update_update_risk_change_effect", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 54, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_update_update_risk_change_effect\" module=\"IO_T_IO_T_BOX\""}, 54)
    # line 55: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 55, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 55)
    # line 56: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 56, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 56)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update"}
    # line 59: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_update_update" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_update_update", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 59, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_update_update\" module=\"IO_T_IO_T_BOX\""}, 59)
    # line 60: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 60, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 60)
    # line 61: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 61, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 61)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_validation_fail"}
    # line 64: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_create_create_risk_validation_fail" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_create_create_risk_validation_fail", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 64, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_create_create_risk_validation_fail\" module=\"IO_T_IO_T_BOX\""}, 64)
    # line 65: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 65, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 65)
    # line 66: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 66, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 66)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update"}
    # line 69: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_register_box_update" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_register_box_update", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 69, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_register_box_update\" module=\"IO_T_IO_T_BOX\""}, 69)
    # line 70: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 70, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 70)
    # line 71: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 71, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 71)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_update_update_risk_success"}
    # line 74: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_update_update_risk_success" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_update_update_risk_success", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 74, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_update_update_risk_success\" module=\"IO_T_IO_T_BOX\""}, 74)
    # line 75: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 75, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 75)
    # line 76: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 76, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 76)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline"}
    # line 79: GIVEN given_seed_context id="io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 79, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_event_io_t_box_heartbeat_timeout_iot_box_offline\" module=\"IO_T_IO_T_BOX\""}, 79)
    # line 80: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 80, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 80)
    # line 81: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 81, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 81)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_mainline
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_mainline]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_mainline"}
    # line 84: GIVEN given_seed_context id="io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_mainline" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_mainline", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 84, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_mainline\" module=\"IO_T_IO_T_BOX\""}, 84)
    # line 85: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 85, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 85)
    # line 86: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 86, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 86)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create"}
    # line 89: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_create_create" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_create_create", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 89, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_create_create\" module=\"IO_T_IO_T_BOX\""}, 89)
    # line 90: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 90, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 90)
    # line 91: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 91, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 91)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_branch_or_exception
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_branch_or_exception]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_branch_or_exception"}
    # line 94: GIVEN given_seed_context id="io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_branch_or_exception" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_branch_or_exception", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 94, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_workflow_io_t_box_iot_box_lifecycle_flow_risk_branch_or_exception\" module=\"IO_T_IO_T_BOX\""}, 94)
    # line 95: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 95, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 95)
    # line 96: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 96, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 96)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_success"}
    # line 99: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_register_box_update_risk_success" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_register_box_update_risk_success", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 99, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_register_box_update_risk_success\" module=\"IO_T_IO_T_BOX\""}, 99)
    # line 100: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 100, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 100)
    # line 101: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 101, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 101)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_register_box_update_risk_change_effect"}
    # line 104: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_register_box_update_risk_change_effect" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_register_box_update_risk_change_effect", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 104, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_register_box_update_risk_change_effect\" module=\"IO_T_IO_T_BOX\""}, 104)
    # line 105: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 105, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 105)
    # line 106: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 106, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 106)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_idempotent_replay
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_idempotent_replay]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_idempotent_replay"}
    # line 109: GIVEN given_seed_context id="io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_idempotent_replay" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_idempotent_replay", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 109, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_idempotent_replay\" module=\"IO_T_IO_T_BOX\""}, 109)
    # line 110: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 110, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 110)
    # line 111: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 111, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 111)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_success
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_action_io_t_box_create_create_risk_success"}
    # line 114: GIVEN given_seed_context id="io_t_io_t_box_action_io_t_box_create_create_risk_success" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_action_io_t_box_create_create_risk_success", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 114, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_action_io_t_box_create_create_risk_success\" module=\"IO_T_IO_T_BOX\""}, 114)
    # line 115: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 115, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 115)
    # line 116: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 116, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 116)
    _ctx = ctx
    :ok
  end

  # Source: BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_normal_publish
  @tag :all
  @tag :seed
  test "[BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_normal_publish]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-IO_T_IO_T_BOX-SEED-io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_normal_publish"}
    # line 119: GIVEN given_seed_context id="io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_normal_publish" module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_normal_publish", module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 119, raw: "GIVEN given_seed_context id=\"io_t_io_t_box_event_io_t_box_register_box_iot_box_paired_risk_normal_publish\" module=\"IO_T_IO_T_BOX\""}, 119)
    # line 120: WHEN when_execute_seed_contract module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 120, raw: "WHEN when_execute_seed_contract module=\"IO_T_IO_T_BOX\""}, 120)
    # line 121: THEN then_seed_contract_should_hold module="IO_T_IO_T_BOX"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "IO_T_IO_T_BOX"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/IO_T_IO_T_BOX.dsl", line: 121, raw: "THEN then_seed_contract_should_hold module=\"IO_T_IO_T_BOX\""}, 121)
    _ctx = ctx
    :ok
  end

end
