# Generated by bdd_compiler from /home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl. DO NOT EDIT.

defmodule UniboV4.BDD.Generated.MARKETING_SEGMENTTest do
  use ExUnit.Case, async: false

  @moduletag :bdd_generated

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create"}
    # line 4: GIVEN given_seed_context id="marketing_segment_action_segment_create_create" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_create_create", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 4, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_create_create\" module=\"MARKETING_SEGMENT\""}, 4)
    # line 5: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 5, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 5)
    # line 6: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 6, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 6)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_change_effect"}
    # line 9: GIVEN given_seed_context id="marketing_segment_action_segment_create_create_risk_change_effect" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_create_create_risk_change_effect", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 9, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_create_create_risk_change_effect\" module=\"MARKETING_SEGMENT\""}, 9)
    # line 10: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 10, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 10)
    # line 11: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 11, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 11)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_success
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_success"}
    # line 14: GIVEN given_seed_context id="marketing_segment_action_segment_create_create_risk_success" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_create_create_risk_success", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 14, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_create_create_risk_success\" module=\"MARKETING_SEGMENT\""}, 14)
    # line 15: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 15, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 15)
    # line 16: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 16, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 16)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_create_create_risk_validation_fail"}
    # line 19: GIVEN given_seed_context id="marketing_segment_action_segment_create_create_risk_validation_fail" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_create_create_risk_validation_fail", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 19, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_create_create_risk_validation_fail\" module=\"MARKETING_SEGMENT\""}, 19)
    # line 20: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 20, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 20)
    # line 21: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 21, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 21)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_read_read
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_read_read]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_read_read"}
    # line 24: GIVEN given_seed_context id="marketing_segment_action_segment_read_read" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_read_read", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 24, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_read_read\" module=\"MARKETING_SEGMENT\""}, 24)
    # line 25: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 25, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 25)
    # line 26: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 26, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 26)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update"}
    # line 29: GIVEN given_seed_context id="marketing_segment_action_segment_refresh_count_update" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_refresh_count_update", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 29, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_refresh_count_update\" module=\"MARKETING_SEGMENT\""}, 29)
    # line 30: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 30, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 30)
    # line 31: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 31, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 31)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_change_effect"}
    # line 34: GIVEN given_seed_context id="marketing_segment_action_segment_refresh_count_update_risk_change_effect" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_refresh_count_update_risk_change_effect", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 34, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_refresh_count_update_risk_change_effect\" module=\"MARKETING_SEGMENT\""}, 34)
    # line 35: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 35, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 35)
    # line 36: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 36, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 36)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_success"}
    # line 39: GIVEN given_seed_context id="marketing_segment_action_segment_refresh_count_update_risk_success" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_refresh_count_update_risk_success", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 39, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_refresh_count_update_risk_success\" module=\"MARKETING_SEGMENT\""}, 39)
    # line 40: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 40, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 40)
    # line 41: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 41, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 41)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_refresh_count_update_risk_validation_fail"}
    # line 44: GIVEN given_seed_context id="marketing_segment_action_segment_refresh_count_update_risk_validation_fail" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_refresh_count_update_risk_validation_fail", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 44, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_refresh_count_update_risk_validation_fail\" module=\"MARKETING_SEGMENT\""}, 44)
    # line 45: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 45, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 45)
    # line 46: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 46, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 46)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update"}
    # line 49: GIVEN given_seed_context id="marketing_segment_action_segment_update_update" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_update_update", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 49, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_update_update\" module=\"MARKETING_SEGMENT\""}, 49)
    # line 50: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 50, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 50)
    # line 51: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 51, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 51)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_change_effect
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_change_effect]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_change_effect"}
    # line 54: GIVEN given_seed_context id="marketing_segment_action_segment_update_update_risk_change_effect" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_update_update_risk_change_effect", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 54, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_update_update_risk_change_effect\" module=\"MARKETING_SEGMENT\""}, 54)
    # line 55: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 55, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 55)
    # line 56: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 56, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 56)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_success
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_success]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_success"}
    # line 59: GIVEN given_seed_context id="marketing_segment_action_segment_update_update_risk_success" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_update_update_risk_success", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 59, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_update_update_risk_success\" module=\"MARKETING_SEGMENT\""}, 59)
    # line 60: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 60, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 60)
    # line 61: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 61, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 61)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_validation_fail
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_validation_fail]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_action_segment_update_update_risk_validation_fail"}
    # line 64: GIVEN given_seed_context id="marketing_segment_action_segment_update_update_risk_validation_fail" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_action_segment_update_update_risk_validation_fail", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 64, raw: "GIVEN given_seed_context id=\"marketing_segment_action_segment_update_update_risk_validation_fail\" module=\"MARKETING_SEGMENT\""}, 64)
    # line 65: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 65, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 65)
    # line 66: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 66, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 66)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow"}
    # line 69: GIVEN given_seed_context id="marketing_segment_workflow_segment_segment_maintain_flow" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_workflow_segment_segment_maintain_flow", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 69, raw: "GIVEN given_seed_context id=\"marketing_segment_workflow_segment_segment_maintain_flow\" module=\"MARKETING_SEGMENT\""}, 69)
    # line 70: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 70, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 70)
    # line 71: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 71, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 71)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow_risk_branch_or_exception
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow_risk_branch_or_exception]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow_risk_branch_or_exception"}
    # line 74: GIVEN given_seed_context id="marketing_segment_workflow_segment_segment_maintain_flow_risk_branch_or_exception" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_workflow_segment_segment_maintain_flow_risk_branch_or_exception", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 74, raw: "GIVEN given_seed_context id=\"marketing_segment_workflow_segment_segment_maintain_flow_risk_branch_or_exception\" module=\"MARKETING_SEGMENT\""}, 74)
    # line 75: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 75, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 75)
    # line 76: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 76, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 76)
    _ctx = ctx
    :ok
  end

  # Source: BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow_risk_mainline
  @tag :all
  @tag :seed
  test "[BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow_risk_mainline]" do
    run_id = UniboV4.BDD.Instructions.V1.new_run_id()
    ctx = %{run_id: run_id, scenario_id: "BDD-MARKETING_SEGMENT-SEED-marketing_segment_workflow_segment_segment_maintain_flow_risk_mainline"}
    # line 79: GIVEN given_seed_context id="marketing_segment_workflow_segment_segment_maintain_flow_risk_mainline" module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :given, :given_seed_context, %{id: "marketing_segment_workflow_segment_segment_maintain_flow_risk_mainline", module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 79, raw: "GIVEN given_seed_context id=\"marketing_segment_workflow_segment_segment_maintain_flow_risk_mainline\" module=\"MARKETING_SEGMENT\""}, 79)
    # line 80: WHEN when_execute_seed_contract module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :when, :when_execute_seed_contract, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 80, raw: "WHEN when_execute_seed_contract module=\"MARKETING_SEGMENT\""}, 80)
    # line 81: THEN then_seed_contract_should_hold module="MARKETING_SEGMENT"
    ctx = UniboV4.BDD.Instructions.V1.run_step!(ctx, :then, :then_seed_contract_should_hold, %{module: "MARKETING_SEGMENT"}, %{file: "/home/wangbo/document/unibo-ex-poc-verify/v4/docs/bdd/MARKETING_SEGMENT.dsl", line: 81, raw: "THEN then_seed_contract_should_hold module=\"MARKETING_SEGMENT\""}, 81)
    _ctx = ctx
    :ok
  end

end
