defmodule UniboV4.Ofbiz.Party do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.Party.Addendum
    resource UniboV4.Ofbiz.Party.Addendum.Version
    resource UniboV4.Ofbiz.Party.Agreement
    resource UniboV4.Ofbiz.Party.Agreement.Version
    resource UniboV4.Ofbiz.Party.AgreementAttribute
    resource UniboV4.Ofbiz.Party.AgreementAttribute.Version
    resource UniboV4.Ofbiz.Party.AgreementGeographicalApplic
    resource UniboV4.Ofbiz.Party.AgreementGeographicalApplic.Version
    resource UniboV4.Ofbiz.Party.AgreementItem
    resource UniboV4.Ofbiz.Party.AgreementItem.Version
    resource UniboV4.Ofbiz.Party.AgreementItemAttribute
    resource UniboV4.Ofbiz.Party.AgreementItemType
    resource UniboV4.Ofbiz.Party.AgreementItemType.Version
    resource UniboV4.Ofbiz.Party.AgreementItemTypeAttr
    resource UniboV4.Ofbiz.Party.AgreementItemTypeAttr.Version
    resource UniboV4.Ofbiz.Party.AgreementContent
    resource UniboV4.Ofbiz.Party.AgreementContentType
    resource UniboV4.Ofbiz.Party.AgreementContentType.Version
    resource UniboV4.Ofbiz.Party.AgreementPartyApplic
    resource UniboV4.Ofbiz.Party.AgreementPartyApplic.Version
    resource UniboV4.Ofbiz.Party.AgreementProductAppl
    resource UniboV4.Ofbiz.Party.AgreementProductAppl.Version
    resource UniboV4.Ofbiz.Party.AgreementPromoAppl
    resource UniboV4.Ofbiz.Party.AgreementFacilityAppl
    resource UniboV4.Ofbiz.Party.AgreementFacilityAppl.Version
    resource UniboV4.Ofbiz.Party.AgreementRole
    resource UniboV4.Ofbiz.Party.AgreementRole.Version
    resource UniboV4.Ofbiz.Party.AgreementStatus
    resource UniboV4.Ofbiz.Party.AgreementStatus.Version
    resource UniboV4.Ofbiz.Party.AgreementTerm
    resource UniboV4.Ofbiz.Party.AgreementTerm.Version
    resource UniboV4.Ofbiz.Party.AgreementTermAttribute
    resource UniboV4.Ofbiz.Party.AgreementTermAttribute.Version
    resource UniboV4.Ofbiz.Party.AgreementType
    resource UniboV4.Ofbiz.Party.AgreementType.Version
    resource UniboV4.Ofbiz.Party.AgreementTypeAttr
    resource UniboV4.Ofbiz.Party.AgreementTypeAttr.Version
    resource UniboV4.Ofbiz.Party.AgreementWorkEffortApplic
    resource UniboV4.Ofbiz.Party.AgreementWorkEffortApplic.Version
    resource UniboV4.Ofbiz.Party.TermType
    resource UniboV4.Ofbiz.Party.TermType.Version
    resource UniboV4.Ofbiz.Party.TermTypeAttr
    resource UniboV4.Ofbiz.Party.TermTypeAttr.Version
    resource UniboV4.Ofbiz.Party.AgreementEmploymentAppl
    resource UniboV4.Ofbiz.Party.CommContentAssocType
    resource UniboV4.Ofbiz.Party.CommContentAssocType.Version
    resource UniboV4.Ofbiz.Party.CommEventContentAssoc
    resource UniboV4.Ofbiz.Party.CommEventContentAssoc.Version
    resource UniboV4.Ofbiz.Party.CommunicationEvent
    resource UniboV4.Ofbiz.Party.CommunicationEvent.Version
    resource UniboV4.Ofbiz.Party.CommunicationEventProduct
    resource UniboV4.Ofbiz.Party.CommunicationEventProduct.Version
    resource UniboV4.Ofbiz.Party.CommunicationEventPrpTyp
    resource UniboV4.Ofbiz.Party.CommunicationEventPrpTyp.Version
    resource UniboV4.Ofbiz.Party.CommunicationEventPurpose
    resource UniboV4.Ofbiz.Party.CommunicationEventPurpose.Version
    resource UniboV4.Ofbiz.Party.CommunicationEventRole
    resource UniboV4.Ofbiz.Party.CommunicationEventRole.Version
    resource UniboV4.Ofbiz.Party.CommunicationEventType
    resource UniboV4.Ofbiz.Party.CommunicationEventType.Version
    resource UniboV4.Ofbiz.Party.ContactMech
    resource UniboV4.Ofbiz.Party.ContactMech.Version
    resource UniboV4.Ofbiz.Party.ContactMechAttribute
    resource UniboV4.Ofbiz.Party.ContactMechAttribute.Version
    resource UniboV4.Ofbiz.Party.ContactMechLink
    resource UniboV4.Ofbiz.Party.ContactMechLink.Version
    resource UniboV4.Ofbiz.Party.ContactMechPurposeType
    resource UniboV4.Ofbiz.Party.ContactMechPurposeType.Version
    resource UniboV4.Ofbiz.Party.ContactMechType
    resource UniboV4.Ofbiz.Party.ContactMechType.Version
    resource UniboV4.Ofbiz.Party.ContactMechTypeAttr
    resource UniboV4.Ofbiz.Party.ContactMechTypeAttr.Version
    resource UniboV4.Ofbiz.Party.ContactMechTypePurpose
    resource UniboV4.Ofbiz.Party.ContactMechTypePurpose.Version
    resource UniboV4.Ofbiz.Party.EmailAddressVerification
    resource UniboV4.Ofbiz.Party.EmailAddressVerification.Version
    resource UniboV4.Ofbiz.Party.PartyContactMech
    resource UniboV4.Ofbiz.Party.PartyContactMech.Version
    resource UniboV4.Ofbiz.Party.PartyContactMechPurpose
    resource UniboV4.Ofbiz.Party.PartyContactMechPurpose.Version
    resource UniboV4.Ofbiz.Party.PostalAddress
    resource UniboV4.Ofbiz.Party.PostalAddress.Version
    resource UniboV4.Ofbiz.Party.PostalAddressBoundary
    resource UniboV4.Ofbiz.Party.PostalAddressBoundary.Version
    resource UniboV4.Ofbiz.Party.TelecomNumber
    resource UniboV4.Ofbiz.Party.TelecomNumber.Version
    resource UniboV4.Ofbiz.Party.FtpAddress
    resource UniboV4.Ofbiz.Party.FtpAddress.Version
    resource UniboV4.Ofbiz.Party.ValidContactMechRole
    resource UniboV4.Ofbiz.Party.ValidContactMechRole.Version
    resource UniboV4.Ofbiz.Party.NeedType
    resource UniboV4.Ofbiz.Party.NeedType.Version
    resource UniboV4.Ofbiz.Party.PartyNeed
    resource UniboV4.Ofbiz.Party.PartyNeed.Version
    resource UniboV4.Ofbiz.Party.AddressMatchMap
    resource UniboV4.Ofbiz.Party.Affiliate
    resource UniboV4.Ofbiz.Party.Affiliate.Version
    resource UniboV4.Ofbiz.Party.Party
    resource UniboV4.Ofbiz.Party.Party.Version
    resource UniboV4.Ofbiz.Party.PartyIdentification
    resource UniboV4.Ofbiz.Party.PartyIdentification.Version
    resource UniboV4.Ofbiz.Party.PartyIdentificationType
    resource UniboV4.Ofbiz.Party.PartyIdentificationType.Version
    resource UniboV4.Ofbiz.Party.PartyGeoPoint
    resource UniboV4.Ofbiz.Party.PartyGeoPoint.Version
    resource UniboV4.Ofbiz.Party.PartyAttribute
    resource UniboV4.Ofbiz.Party.PartyAttribute.Version
    resource UniboV4.Ofbiz.Party.PartyCarrierAccount
    resource UniboV4.Ofbiz.Party.PartyCarrierAccount.Version
    resource UniboV4.Ofbiz.Party.PartyClassification
    resource UniboV4.Ofbiz.Party.PartyClassification.Version
    resource UniboV4.Ofbiz.Party.PartyClassificationGroup
    resource UniboV4.Ofbiz.Party.PartyClassificationGroup.Version
    resource UniboV4.Ofbiz.Party.PartyClassificationType
    resource UniboV4.Ofbiz.Party.PartyClassificationType.Version
    resource UniboV4.Ofbiz.Party.PartyContent
    resource UniboV4.Ofbiz.Party.PartyContent.Version
    resource UniboV4.Ofbiz.Party.PartyContentType
    resource UniboV4.Ofbiz.Party.PartyContentType.Version
    resource UniboV4.Ofbiz.Party.PartyDataSource
    resource UniboV4.Ofbiz.Party.PartyDataSource.Version
    resource UniboV4.Ofbiz.Party.PartyGroup
    resource UniboV4.Ofbiz.Party.PartyGroup.Version
    resource UniboV4.Ofbiz.Party.PartyIcsAvsOverride
    resource UniboV4.Ofbiz.Party.PartyIcsAvsOverride.Version
    resource UniboV4.Ofbiz.Party.PartyInvitation
    resource UniboV4.Ofbiz.Party.PartyInvitation.Version
    resource UniboV4.Ofbiz.Party.PartyInvitationGroupAssoc
    resource UniboV4.Ofbiz.Party.PartyInvitationGroupAssoc.Version
    resource UniboV4.Ofbiz.Party.PartyInvitationRoleAssoc
    resource UniboV4.Ofbiz.Party.PartyInvitationRoleAssoc.Version
    resource UniboV4.Ofbiz.Party.PartyNameHistory
    resource UniboV4.Ofbiz.Party.PartyNameHistory.Version
    resource UniboV4.Ofbiz.Party.PartyNote
    resource UniboV4.Ofbiz.Party.PartyNote.Version
    resource UniboV4.Ofbiz.Party.PartyProfileDefault
    resource UniboV4.Ofbiz.Party.PartyProfileDefault.Version
    resource UniboV4.Ofbiz.Party.PartyRelationship
    resource UniboV4.Ofbiz.Party.PartyRelationship.Version
    resource UniboV4.Ofbiz.Party.PartyRelationshipType
    resource UniboV4.Ofbiz.Party.PartyRelationshipType.Version
    resource UniboV4.Ofbiz.Party.PartyRole
    resource UniboV4.Ofbiz.Party.PartyRole.Version
    resource UniboV4.Ofbiz.Party.PartyStatus
    resource UniboV4.Ofbiz.Party.PartyStatus.Version
    resource UniboV4.Ofbiz.Party.PartyType
    resource UniboV4.Ofbiz.Party.PartyType.Version
    resource UniboV4.Ofbiz.Party.PartyTypeAttr
    resource UniboV4.Ofbiz.Party.PartyTypeAttr.Version
    resource UniboV4.Ofbiz.Party.Person
    resource UniboV4.Ofbiz.Party.Person.Version
    resource UniboV4.Ofbiz.Party.PriorityType
    resource UniboV4.Ofbiz.Party.PriorityType.Version
    resource UniboV4.Ofbiz.Party.RoleType
    resource UniboV4.Ofbiz.Party.RoleType.Version
    resource UniboV4.Ofbiz.Party.RoleTypeAttr
    resource UniboV4.Ofbiz.Party.RoleTypeAttr.Version
    resource UniboV4.Ofbiz.Party.Vendor
    resource UniboV4.Ofbiz.Party.Vendor.Version
    resource UniboV4.Ofbiz.Party.MaritalStatus
    resource UniboV4.Ofbiz.Party.MaritalStatus.Version
    resource UniboV4.Ofbiz.Party.MaritalStatusType
    resource UniboV4.Ofbiz.Party.MaritalStatusType.Version
    resource UniboV4.Ofbiz.Party.ContactList
    resource UniboV4.Ofbiz.Party.Content
    resource UniboV4.Ofbiz.Party.DataSource
    resource UniboV4.Ofbiz.Party.Enumeration
    resource UniboV4.Ofbiz.Party.Facility
    resource UniboV4.Ofbiz.Party.Geo
    resource UniboV4.Ofbiz.Party.GeoPoint
    resource UniboV4.Ofbiz.Party.InvoiceItemType
    resource UniboV4.Ofbiz.Party.MimeType
    resource UniboV4.Ofbiz.Party.NoteData
    resource UniboV4.Ofbiz.Party.Product
    resource UniboV4.Ofbiz.Party.ProductCategory
    resource UniboV4.Ofbiz.Party.ProductPromo
    resource UniboV4.Ofbiz.Party.ProductStore
    resource UniboV4.Ofbiz.Party.SecurityGroup
    resource UniboV4.Ofbiz.Party.StatusItem
    resource UniboV4.Ofbiz.Party.Uom
    resource UniboV4.Ofbiz.Party.UserLogin
    resource UniboV4.Ofbiz.Party.WorkEffort
  end
end
