defmodule UniboV4.Ofbiz.WorkEffort do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.WorkEffort.TimeEntry
    resource UniboV4.Ofbiz.WorkEffort.TimeEntry.Version
    resource UniboV4.Ofbiz.WorkEffort.Timesheet
    resource UniboV4.Ofbiz.WorkEffort.Timesheet.Version
    resource UniboV4.Ofbiz.WorkEffort.TimesheetRole
    resource UniboV4.Ofbiz.WorkEffort.TimesheetRole.Version
    resource UniboV4.Ofbiz.WorkEffort.ApplicationSandbox
    resource UniboV4.Ofbiz.WorkEffort.ApplicationSandbox.Version
    resource UniboV4.Ofbiz.WorkEffort.CommunicationEventWorkEff
    resource UniboV4.Ofbiz.WorkEffort.CommunicationEventWorkEff.Version
    resource UniboV4.Ofbiz.WorkEffort.Deliverable
    resource UniboV4.Ofbiz.WorkEffort.Deliverable.Version
    resource UniboV4.Ofbiz.WorkEffort.DeliverableType
    resource UniboV4.Ofbiz.WorkEffort.DeliverableType.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffort
    resource UniboV4.Ofbiz.WorkEffort.WorkEffort.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAssoc
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAssoc.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAssocAttribute
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAssocType
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAssocType.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAssocTypeAttr
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAssocTypeAttr.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAttribute
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortAttribute.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortBilling
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortBilling.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortContactMech
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortContactMech.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortContent
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortContent.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortContentType
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortContentType.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortDeliverableProd
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortDeliverableProd.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortEventReminder
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortEventReminder.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortFixedAssetAssign
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortFixedAssetAssign.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortFixedAssetStd
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortFixedAssetStd.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortGoodStandard
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortGoodStandard.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortGoodStandardType
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortGoodStandardType.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortIcalData
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortIcalData.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortInventoryAssign
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortInventoryAssign.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortInventoryProduced
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortInventoryProduced.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortCostCalc
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortCostCalc.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortKeyword
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortKeyword.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortNote
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortNote.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortPartyAssignment
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortPartyAssignment.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortPurposeType
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortPurposeType.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortReview
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortReview.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortSearchConstraint
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortSearchConstraint.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortSearchResult
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortSearchResult.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortSkillStandard
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortSkillStandard.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortStatus
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortStatus.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortTransBox
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortType
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortType.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortTypeAttr
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortTypeAttr.Version
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortSurveyAppl
    resource UniboV4.Ofbiz.WorkEffort.WorkEffortSurveyAppl.Version
    resource UniboV4.Ofbiz.WorkEffort.AccommodationMap
    resource UniboV4.Ofbiz.WorkEffort.AccommodationSpot
    resource UniboV4.Ofbiz.WorkEffort.CommunicationEvent
    resource UniboV4.Ofbiz.WorkEffort.ContactMech
    resource UniboV4.Ofbiz.WorkEffort.Content
    resource UniboV4.Ofbiz.WorkEffort.CostComponentCalc
    resource UniboV4.Ofbiz.WorkEffort.CostComponentType
    resource UniboV4.Ofbiz.WorkEffort.CustomMethod
    resource UniboV4.Ofbiz.WorkEffort.Enumeration
    resource UniboV4.Ofbiz.WorkEffort.Facility
    resource UniboV4.Ofbiz.WorkEffort.FixedAsset
    resource UniboV4.Ofbiz.WorkEffort.FixedAssetType
    resource UniboV4.Ofbiz.WorkEffort.InventoryItem
    resource UniboV4.Ofbiz.WorkEffort.Invoice
    resource UniboV4.Ofbiz.WorkEffort.NoteData
    resource UniboV4.Ofbiz.WorkEffort.Party
    resource UniboV4.Ofbiz.WorkEffort.Product
    resource UniboV4.Ofbiz.WorkEffort.ProductStoreSurveyAppl
    resource UniboV4.Ofbiz.WorkEffort.RateType
    resource UniboV4.Ofbiz.WorkEffort.RecurrenceInfo
    resource UniboV4.Ofbiz.WorkEffort.RoleType
    resource UniboV4.Ofbiz.WorkEffort.RuntimeData
    resource UniboV4.Ofbiz.WorkEffort.SkillType
    resource UniboV4.Ofbiz.WorkEffort.StatusItem
    resource UniboV4.Ofbiz.WorkEffort.Survey
    resource UniboV4.Ofbiz.WorkEffort.TelecomNumber
    resource UniboV4.Ofbiz.WorkEffort.TemporalExpression
    resource UniboV4.Ofbiz.WorkEffort.Uom
    resource UniboV4.Ofbiz.WorkEffort.UserLogin
  end
end
