defmodule UniboExPoc.Ofbiz.Party do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboExPoc.Ofbiz.Party.Addendum
    resource UniboExPoc.Ofbiz.Party.Addendum.Version
    resource UniboExPoc.Ofbiz.Party.Agreement
    resource UniboExPoc.Ofbiz.Party.Agreement.Version
    resource UniboExPoc.Ofbiz.Party.AgreementAttribute
    resource UniboExPoc.Ofbiz.Party.AgreementAttribute.Version
    resource UniboExPoc.Ofbiz.Party.AgreementGeographicalApplic
    resource UniboExPoc.Ofbiz.Party.AgreementGeographicalApplic.Version
    resource UniboExPoc.Ofbiz.Party.AgreementItem
    resource UniboExPoc.Ofbiz.Party.AgreementItem.Version
    resource UniboExPoc.Ofbiz.Party.AgreementItemAttribute
    resource UniboExPoc.Ofbiz.Party.AgreementItemType
    resource UniboExPoc.Ofbiz.Party.AgreementItemType.Version
    resource UniboExPoc.Ofbiz.Party.AgreementItemTypeAttr
    resource UniboExPoc.Ofbiz.Party.AgreementItemTypeAttr.Version
    resource UniboExPoc.Ofbiz.Party.AgreementContent
    resource UniboExPoc.Ofbiz.Party.AgreementContentType
    resource UniboExPoc.Ofbiz.Party.AgreementContentType.Version
    resource UniboExPoc.Ofbiz.Party.AgreementPartyApplic
    resource UniboExPoc.Ofbiz.Party.AgreementPartyApplic.Version
    resource UniboExPoc.Ofbiz.Party.AgreementProductAppl
    resource UniboExPoc.Ofbiz.Party.AgreementProductAppl.Version
    resource UniboExPoc.Ofbiz.Party.AgreementPromoAppl
    resource UniboExPoc.Ofbiz.Party.AgreementFacilityAppl
    resource UniboExPoc.Ofbiz.Party.AgreementFacilityAppl.Version
    resource UniboExPoc.Ofbiz.Party.AgreementRole
    resource UniboExPoc.Ofbiz.Party.AgreementRole.Version
    resource UniboExPoc.Ofbiz.Party.AgreementStatus
    resource UniboExPoc.Ofbiz.Party.AgreementStatus.Version
    resource UniboExPoc.Ofbiz.Party.AgreementTerm
    resource UniboExPoc.Ofbiz.Party.AgreementTerm.Version
    resource UniboExPoc.Ofbiz.Party.AgreementTermAttribute
    resource UniboExPoc.Ofbiz.Party.AgreementTermAttribute.Version
    resource UniboExPoc.Ofbiz.Party.AgreementType
    resource UniboExPoc.Ofbiz.Party.AgreementType.Version
    resource UniboExPoc.Ofbiz.Party.AgreementTypeAttr
    resource UniboExPoc.Ofbiz.Party.AgreementTypeAttr.Version
    resource UniboExPoc.Ofbiz.Party.AgreementWorkEffortApplic
    resource UniboExPoc.Ofbiz.Party.AgreementWorkEffortApplic.Version
    resource UniboExPoc.Ofbiz.Party.TermType
    resource UniboExPoc.Ofbiz.Party.TermType.Version
    resource UniboExPoc.Ofbiz.Party.TermTypeAttr
    resource UniboExPoc.Ofbiz.Party.TermTypeAttr.Version
    resource UniboExPoc.Ofbiz.Party.AgreementEmploymentAppl
    resource UniboExPoc.Ofbiz.Party.CommContentAssocType
    resource UniboExPoc.Ofbiz.Party.CommContentAssocType.Version
    resource UniboExPoc.Ofbiz.Party.CommEventContentAssoc
    resource UniboExPoc.Ofbiz.Party.CommEventContentAssoc.Version
    resource UniboExPoc.Ofbiz.Party.CommunicationEvent
    resource UniboExPoc.Ofbiz.Party.CommunicationEvent.Version
    resource UniboExPoc.Ofbiz.Party.CommunicationEventProduct
    resource UniboExPoc.Ofbiz.Party.CommunicationEventProduct.Version
    resource UniboExPoc.Ofbiz.Party.CommunicationEventPrpTyp
    resource UniboExPoc.Ofbiz.Party.CommunicationEventPrpTyp.Version
    resource UniboExPoc.Ofbiz.Party.CommunicationEventPurpose
    resource UniboExPoc.Ofbiz.Party.CommunicationEventPurpose.Version
    resource UniboExPoc.Ofbiz.Party.CommunicationEventRole
    resource UniboExPoc.Ofbiz.Party.CommunicationEventRole.Version
    resource UniboExPoc.Ofbiz.Party.CommunicationEventType
    resource UniboExPoc.Ofbiz.Party.CommunicationEventType.Version
    resource UniboExPoc.Ofbiz.Party.ContactMech
    resource UniboExPoc.Ofbiz.Party.ContactMech.Version
    resource UniboExPoc.Ofbiz.Party.ContactMechAttribute
    resource UniboExPoc.Ofbiz.Party.ContactMechAttribute.Version
    resource UniboExPoc.Ofbiz.Party.ContactMechLink
    resource UniboExPoc.Ofbiz.Party.ContactMechLink.Version
    resource UniboExPoc.Ofbiz.Party.ContactMechPurposeType
    resource UniboExPoc.Ofbiz.Party.ContactMechPurposeType.Version
    resource UniboExPoc.Ofbiz.Party.ContactMechType
    resource UniboExPoc.Ofbiz.Party.ContactMechType.Version
    resource UniboExPoc.Ofbiz.Party.ContactMechTypeAttr
    resource UniboExPoc.Ofbiz.Party.ContactMechTypeAttr.Version
    resource UniboExPoc.Ofbiz.Party.ContactMechTypePurpose
    resource UniboExPoc.Ofbiz.Party.ContactMechTypePurpose.Version
    resource UniboExPoc.Ofbiz.Party.EmailAddressVerification
    resource UniboExPoc.Ofbiz.Party.EmailAddressVerification.Version
    resource UniboExPoc.Ofbiz.Party.PartyContactMech
    resource UniboExPoc.Ofbiz.Party.PartyContactMech.Version
    resource UniboExPoc.Ofbiz.Party.PartyContactMechPurpose
    resource UniboExPoc.Ofbiz.Party.PartyContactMechPurpose.Version
    resource UniboExPoc.Ofbiz.Party.PostalAddress
    resource UniboExPoc.Ofbiz.Party.PostalAddress.Version
    resource UniboExPoc.Ofbiz.Party.PostalAddressBoundary
    resource UniboExPoc.Ofbiz.Party.PostalAddressBoundary.Version
    resource UniboExPoc.Ofbiz.Party.TelecomNumber
    resource UniboExPoc.Ofbiz.Party.TelecomNumber.Version
    resource UniboExPoc.Ofbiz.Party.FtpAddress
    resource UniboExPoc.Ofbiz.Party.FtpAddress.Version
    resource UniboExPoc.Ofbiz.Party.ValidContactMechRole
    resource UniboExPoc.Ofbiz.Party.ValidContactMechRole.Version
    resource UniboExPoc.Ofbiz.Party.NeedType
    resource UniboExPoc.Ofbiz.Party.NeedType.Version
    resource UniboExPoc.Ofbiz.Party.PartyNeed
    resource UniboExPoc.Ofbiz.Party.PartyNeed.Version
    resource UniboExPoc.Ofbiz.Party.AddressMatchMap
    resource UniboExPoc.Ofbiz.Party.Affiliate
    resource UniboExPoc.Ofbiz.Party.Affiliate.Version
    resource UniboExPoc.Ofbiz.Party.Party
    resource UniboExPoc.Ofbiz.Party.Party.Version
    resource UniboExPoc.Ofbiz.Party.PartyIdentification
    resource UniboExPoc.Ofbiz.Party.PartyIdentification.Version
    resource UniboExPoc.Ofbiz.Party.PartyIdentificationType
    resource UniboExPoc.Ofbiz.Party.PartyIdentificationType.Version
    resource UniboExPoc.Ofbiz.Party.PartyGeoPoint
    resource UniboExPoc.Ofbiz.Party.PartyGeoPoint.Version
    resource UniboExPoc.Ofbiz.Party.PartyAttribute
    resource UniboExPoc.Ofbiz.Party.PartyAttribute.Version
    resource UniboExPoc.Ofbiz.Party.PartyCarrierAccount
    resource UniboExPoc.Ofbiz.Party.PartyCarrierAccount.Version
    resource UniboExPoc.Ofbiz.Party.PartyClassification
    resource UniboExPoc.Ofbiz.Party.PartyClassification.Version
    resource UniboExPoc.Ofbiz.Party.PartyClassificationGroup
    resource UniboExPoc.Ofbiz.Party.PartyClassificationGroup.Version
    resource UniboExPoc.Ofbiz.Party.PartyClassificationType
    resource UniboExPoc.Ofbiz.Party.PartyClassificationType.Version
    resource UniboExPoc.Ofbiz.Party.PartyContent
    resource UniboExPoc.Ofbiz.Party.PartyContent.Version
    resource UniboExPoc.Ofbiz.Party.PartyContentType
    resource UniboExPoc.Ofbiz.Party.PartyContentType.Version
    resource UniboExPoc.Ofbiz.Party.PartyDataSource
    resource UniboExPoc.Ofbiz.Party.PartyDataSource.Version
    resource UniboExPoc.Ofbiz.Party.PartyGroup
    resource UniboExPoc.Ofbiz.Party.PartyGroup.Version
    resource UniboExPoc.Ofbiz.Party.PartyIcsAvsOverride
    resource UniboExPoc.Ofbiz.Party.PartyIcsAvsOverride.Version
    resource UniboExPoc.Ofbiz.Party.PartyInvitation
    resource UniboExPoc.Ofbiz.Party.PartyInvitation.Version
    resource UniboExPoc.Ofbiz.Party.PartyInvitationGroupAssoc
    resource UniboExPoc.Ofbiz.Party.PartyInvitationGroupAssoc.Version
    resource UniboExPoc.Ofbiz.Party.PartyInvitationRoleAssoc
    resource UniboExPoc.Ofbiz.Party.PartyInvitationRoleAssoc.Version
    resource UniboExPoc.Ofbiz.Party.PartyNameHistory
    resource UniboExPoc.Ofbiz.Party.PartyNameHistory.Version
    resource UniboExPoc.Ofbiz.Party.PartyNote
    resource UniboExPoc.Ofbiz.Party.PartyNote.Version
    resource UniboExPoc.Ofbiz.Party.PartyProfileDefault
    resource UniboExPoc.Ofbiz.Party.PartyProfileDefault.Version
    resource UniboExPoc.Ofbiz.Party.PartyRelationship
    resource UniboExPoc.Ofbiz.Party.PartyRelationship.Version
    resource UniboExPoc.Ofbiz.Party.PartyRelationshipType
    resource UniboExPoc.Ofbiz.Party.PartyRelationshipType.Version
    resource UniboExPoc.Ofbiz.Party.PartyRole
    resource UniboExPoc.Ofbiz.Party.PartyRole.Version
    resource UniboExPoc.Ofbiz.Party.PartyStatus
    resource UniboExPoc.Ofbiz.Party.PartyStatus.Version
    resource UniboExPoc.Ofbiz.Party.PartyType
    resource UniboExPoc.Ofbiz.Party.PartyType.Version
    resource UniboExPoc.Ofbiz.Party.PartyTypeAttr
    resource UniboExPoc.Ofbiz.Party.PartyTypeAttr.Version
    resource UniboExPoc.Ofbiz.Party.Person
    resource UniboExPoc.Ofbiz.Party.Person.Version
    resource UniboExPoc.Ofbiz.Party.PriorityType
    resource UniboExPoc.Ofbiz.Party.PriorityType.Version
    resource UniboExPoc.Ofbiz.Party.RoleType
    resource UniboExPoc.Ofbiz.Party.RoleType.Version
    resource UniboExPoc.Ofbiz.Party.RoleTypeAttr
    resource UniboExPoc.Ofbiz.Party.RoleTypeAttr.Version
    resource UniboExPoc.Ofbiz.Party.Vendor
    resource UniboExPoc.Ofbiz.Party.Vendor.Version
    resource UniboExPoc.Ofbiz.Party.MaritalStatus
    resource UniboExPoc.Ofbiz.Party.MaritalStatus.Version
    resource UniboExPoc.Ofbiz.Party.MaritalStatusType
    resource UniboExPoc.Ofbiz.Party.MaritalStatusType.Version
    resource UniboExPoc.Ofbiz.Party.ContactList
    resource UniboExPoc.Ofbiz.Party.Content
    resource UniboExPoc.Ofbiz.Party.DataSource
    resource UniboExPoc.Ofbiz.Party.Enumeration
    resource UniboExPoc.Ofbiz.Party.Facility
    resource UniboExPoc.Ofbiz.Party.Geo
    resource UniboExPoc.Ofbiz.Party.GeoPoint
    resource UniboExPoc.Ofbiz.Party.InvoiceItemType
    resource UniboExPoc.Ofbiz.Party.MimeType
    resource UniboExPoc.Ofbiz.Party.NoteData
    resource UniboExPoc.Ofbiz.Party.Product
    resource UniboExPoc.Ofbiz.Party.ProductCategory
    resource UniboExPoc.Ofbiz.Party.ProductPromo
    resource UniboExPoc.Ofbiz.Party.ProductStore
    resource UniboExPoc.Ofbiz.Party.SecurityGroup
    resource UniboExPoc.Ofbiz.Party.StatusItem
    resource UniboExPoc.Ofbiz.Party.Uom
    resource UniboExPoc.Ofbiz.Party.UserLogin
    resource UniboExPoc.Ofbiz.Party.WorkEffort
  end
end
