[SCENARIO: BDD-ACCOUNTING_INVOICE-SEED-accounting_invoice_event_invoice_send_accounting_invoice_sent] TITLE: ACCOUNTING_INVOICE contract seed scenario TAGS: seed event_contract
GIVEN given_seed_context id="accounting_invoice_event_invoice_send_accounting_invoice_sent" module="ACCOUNTING_INVOICE"
WHEN when_execute_seed_contract module="ACCOUNTING_INVOICE"
THEN then_seed_contract_should_hold module="ACCOUNTING_INVOICE"
