[SCENARIO: BDD-ACCOUNTING_PAYMENT_APPLICATION-SEED-accounting_payment_application_action_payment_application_destroy_destroy] TITLE: ACCOUNTING_PAYMENT_APPLICATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="accounting_payment_application_action_payment_application_destroy_destroy" module="ACCOUNTING_PAYMENT_APPLICATION"
WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_APPLICATION"
THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_APPLICATION"
