[SCENARIO: BDD-ACCOUNTING_GL_ACCOUNT_CLASS-SEED-accounting_gl_account_class_action_gl_account_class_update_update] TITLE: ACCOUNTING_GL_ACCOUNT_CLASS contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_gl_account_class_action_gl_account_class_update_update" module="ACCOUNTING_GL_ACCOUNT_CLASS"
WHEN when_execute_seed_contract module="ACCOUNTING_GL_ACCOUNT_CLASS"
THEN then_seed_contract_should_hold module="ACCOUNTING_GL_ACCOUNT_CLASS"
