[SCENARIO: BDD-ACCOUNTING_JOURNAL_ENTRY-SEED-accounting_journal_entry_action_journal_entry_create_create] TITLE: ACCOUNTING_JOURNAL_ENTRY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="accounting_journal_entry_action_journal_entry_create_create" module="ACCOUNTING_JOURNAL_ENTRY"
WHEN when_execute_seed_contract module="ACCOUNTING_JOURNAL_ENTRY"
THEN then_seed_contract_should_hold module="ACCOUNTING_JOURNAL_ENTRY"
