[SCENARIO: BDD-ACCOUNTING_PAYMENT_TYPE-SEED-accounting_payment_type_action_payment_type_read_read] TITLE: ACCOUNTING_PAYMENT_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_payment_type_action_payment_type_read_read" module="ACCOUNTING_PAYMENT_TYPE"
WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_TYPE"
THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_TYPE"
