[SCENARIO: BDD-ACCOUNTING_GL_JOURNAL-SEED-accounting_gl_journal_action_gl_journal_read_read] TITLE: ACCOUNTING_GL_JOURNAL contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_gl_journal_action_gl_journal_read_read" module="ACCOUNTING_GL_JOURNAL"
WHEN when_execute_seed_contract module="ACCOUNTING_GL_JOURNAL"
THEN then_seed_contract_should_hold module="ACCOUNTING_GL_JOURNAL"
