[SCENARIO: BDD-ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT-SEED-accounting_tax_authority_rate_product_action_tax_authority_rate_product_read_read] TITLE: ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_tax_authority_rate_product_action_tax_authority_rate_product_read_read" module="ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT"
WHEN when_execute_seed_contract module="ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT"
THEN then_seed_contract_should_hold module="ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT"
