[SCENARIO: BDD-ACCOUNTING_INVOICE_ITEM-SEED-accounting_invoice_item_action_invoice_item_update_update] TITLE: ACCOUNTING_INVOICE_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="accounting_invoice_item_action_invoice_item_update_update" module="ACCOUNTING_INVOICE_ITEM"
WHEN when_execute_seed_contract module="ACCOUNTING_INVOICE_ITEM"
THEN then_seed_contract_should_hold module="ACCOUNTING_INVOICE_ITEM"
