[SCENARIO: BDD-ACCOUNTING_PAYMENT-SEED-accounting_payment_event_payment_post_accounting_payment_posted] TITLE: ACCOUNTING_PAYMENT contract seed scenario TAGS: seed event_contract
GIVEN given_seed_context id="accounting_payment_event_payment_post_accounting_payment_posted" module="ACCOUNTING_PAYMENT"
WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT"
THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT"
