[SCENARIO: BDD-ACCOUNTING_FIN_ACCOUNT_TYPE-SEED-accounting_fin_account_type_action_fin_account_type_read_read] TITLE: ACCOUNTING_FIN_ACCOUNT_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_fin_account_type_action_fin_account_type_read_read" module="ACCOUNTING_FIN_ACCOUNT_TYPE"
WHEN when_execute_seed_contract module="ACCOUNTING_FIN_ACCOUNT_TYPE"
THEN then_seed_contract_should_hold module="ACCOUNTING_FIN_ACCOUNT_TYPE"
