[SCENARIO: BDD-ACCOUNTING_PAYMENT_GATEWAY_CONFIG_TYPE-SEED-accounting_payment_gateway_config_type_action_payment_gateway_config_type_destroy_destroy] TITLE: ACCOUNTING_PAYMENT_GATEWAY_CONFIG_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_payment_gateway_config_type_action_payment_gateway_config_type_destroy_destroy" module="ACCOUNTING_PAYMENT_GATEWAY_CONFIG_TYPE"
WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_GATEWAY_CONFIG_TYPE"
THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_GATEWAY_CONFIG_TYPE"
