[SCENARIO: BDD-ACCOUNTING_INVOICE_ITEM_ATTRIBUTE-SEED-accounting_invoice_item_attribute_action_invoice_item_attribute_read_read] TITLE: ACCOUNTING_INVOICE_ITEM_ATTRIBUTE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_invoice_item_attribute_action_invoice_item_attribute_read_read" module="ACCOUNTING_INVOICE_ITEM_ATTRIBUTE"
WHEN when_execute_seed_contract module="ACCOUNTING_INVOICE_ITEM_ATTRIBUTE"
THEN then_seed_contract_should_hold module="ACCOUNTING_INVOICE_ITEM_ATTRIBUTE"
