[SCENARIO: BDD-ACCOUNTING_GL_ACCOUNT-SEED-accounting_gl_account_workflow_gl_account_gl_account_lifecycle] TITLE: ACCOUNTING_GL_ACCOUNT contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="accounting_gl_account_workflow_gl_account_gl_account_lifecycle" module="ACCOUNTING_GL_ACCOUNT"
WHEN when_execute_seed_contract module="ACCOUNTING_GL_ACCOUNT"
THEN then_seed_contract_should_hold module="ACCOUNTING_GL_ACCOUNT"
