[SCENARIO: BDD-ACCOUNTING_PAYMENT_GATEWAY_RESPONSE-SEED-accounting_payment_gateway_response_action_payment_gateway_response_create_create] TITLE: ACCOUNTING_PAYMENT_GATEWAY_RESPONSE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_payment_gateway_response_action_payment_gateway_response_create_create" module="ACCOUNTING_PAYMENT_GATEWAY_RESPONSE"
WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT_GATEWAY_RESPONSE"
THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT_GATEWAY_RESPONSE"
