[SCENARIO: BDD-ACCOUNTING_FIN_ACCOUNT_TRANS-SEED-accounting_fin_account_trans_action_fin_account_trans_create_create] TITLE: ACCOUNTING_FIN_ACCOUNT_TRANS contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_fin_account_trans_action_fin_account_trans_create_create" module="ACCOUNTING_FIN_ACCOUNT_TRANS"
WHEN when_execute_seed_contract module="ACCOUNTING_FIN_ACCOUNT_TRANS"
THEN then_seed_contract_should_hold module="ACCOUNTING_FIN_ACCOUNT_TRANS"
