[SCENARIO: BDD-ACCOUNTING_JOURNAL_ENTRY-SEED-accounting_journal_entry_event_journal_entry_cancel_accounting_journal_cancelled] TITLE: ACCOUNTING_JOURNAL_ENTRY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="accounting_journal_entry_event_journal_entry_cancel_accounting_journal_cancelled" module="ACCOUNTING_JOURNAL_ENTRY"
WHEN when_execute_seed_contract module="ACCOUNTING_JOURNAL_ENTRY"
THEN then_seed_contract_should_hold module="ACCOUNTING_JOURNAL_ENTRY"
