[SCENARIO: BDD-ACCOUNTING_PAYMENT-SEED-accounting_payment_event_payment_cancel_accounting_payment_cancelled] TITLE: ACCOUNTING_PAYMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="accounting_payment_event_payment_cancel_accounting_payment_cancelled" module="ACCOUNTING_PAYMENT"
WHEN when_execute_seed_contract module="ACCOUNTING_PAYMENT"
THEN then_seed_contract_should_hold module="ACCOUNTING_PAYMENT"
