[SCENARIO: BDD-ACCOUNTING_GL_ACCOUNT_TYPE-SEED-accounting_gl_account_type_action_gl_account_type_create_create] TITLE: ACCOUNTING_GL_ACCOUNT_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_gl_account_type_action_gl_account_type_create_create" module="ACCOUNTING_GL_ACCOUNT_TYPE"
WHEN when_execute_seed_contract module="ACCOUNTING_GL_ACCOUNT_TYPE"
THEN then_seed_contract_should_hold module="ACCOUNTING_GL_ACCOUNT_TYPE"
