[SCENARIO: BDD-ACCOUNTING_JOURNAL_ENTRY_LINE_TAX_REL-SEED-accounting_journal_entry_line_tax_rel_action_journal_entry_line_tax_rel_read_read] TITLE: ACCOUNTING_JOURNAL_ENTRY_LINE_TAX_REL contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_journal_entry_line_tax_rel_action_journal_entry_line_tax_rel_read_read" module="ACCOUNTING_JOURNAL_ENTRY_LINE_TAX_REL"
WHEN when_execute_seed_contract module="ACCOUNTING_JOURNAL_ENTRY_LINE_TAX_REL"
THEN then_seed_contract_should_hold module="ACCOUNTING_JOURNAL_ENTRY_LINE_TAX_REL"
