[SCENARIO: BDD-ACCOUNTING_SETTLEMENT_TERM-SEED-accounting_settlement_term_action_settlement_term_create_create] TITLE: ACCOUNTING_SETTLEMENT_TERM contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="accounting_settlement_term_action_settlement_term_create_create" module="ACCOUNTING_SETTLEMENT_TERM"
WHEN when_execute_seed_contract module="ACCOUNTING_SETTLEMENT_TERM"
THEN then_seed_contract_should_hold module="ACCOUNTING_SETTLEMENT_TERM"
