[SCENARIO: BDD-ACCOUNTING_JOURNAL_ENTRY-SEED-accounting_journal_entry_workflow_journal_entry_journal_entry_lifecycle] TITLE: ACCOUNTING_JOURNAL_ENTRY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="accounting_journal_entry_workflow_journal_entry_journal_entry_lifecycle" module="ACCOUNTING_JOURNAL_ENTRY"
WHEN when_execute_seed_contract module="ACCOUNTING_JOURNAL_ENTRY"
THEN then_seed_contract_should_hold module="ACCOUNTING_JOURNAL_ENTRY"
