[SCENARIO: BDD-ANALYTIC_ANALYTIC_ACCOUNT-SEED-analytic_analytic_account_workflow_analytic_account_analytic_account_lifecycle] TITLE: ANALYTIC_ANALYTIC_ACCOUNT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="analytic_analytic_account_workflow_analytic_account_analytic_account_lifecycle" module="ANALYTIC_ANALYTIC_ACCOUNT"
WHEN when_execute_seed_contract module="ANALYTIC_ANALYTIC_ACCOUNT"
THEN then_seed_contract_should_hold module="ANALYTIC_ANALYTIC_ACCOUNT"
