[SCENARIO: BDD-ANALYTIC_ANALYTIC_DISTRIBUTION-SEED-analytic_analytic_distribution_workflow_analytic_distribution_analytic_distribution_setup] TITLE: ANALYTIC_ANALYTIC_DISTRIBUTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="analytic_analytic_distribution_workflow_analytic_distribution_analytic_distribution_setup" module="ANALYTIC_ANALYTIC_DISTRIBUTION"
WHEN when_execute_seed_contract module="ANALYTIC_ANALYTIC_DISTRIBUTION"
THEN then_seed_contract_should_hold module="ANALYTIC_ANALYTIC_DISTRIBUTION"
