[SCENARIO: BDD-ANALYTIC_ANALYTIC_PLAN-SEED-analytic_analytic_plan_workflow_analytic_plan_analytic_plan_lifecycle] TITLE: ANALYTIC_ANALYTIC_PLAN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="analytic_analytic_plan_workflow_analytic_plan_analytic_plan_lifecycle" module="ANALYTIC_ANALYTIC_PLAN"
WHEN when_execute_seed_contract module="ANALYTIC_ANALYTIC_PLAN"
THEN then_seed_contract_should_hold module="ANALYTIC_ANALYTIC_PLAN"
