[SCENARIO: BDD-APPROVALS_APPROVAL_REQUEST-SEED-approvals_approval_request_workflow_approval_request_approval_request_refuse_resubmit_flow] TITLE: APPROVALS_APPROVAL_REQUEST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="approvals_approval_request_workflow_approval_request_approval_request_refuse_resubmit_flow" module="APPROVALS_APPROVAL_REQUEST"
WHEN when_execute_seed_contract module="APPROVALS_APPROVAL_REQUEST"
THEN then_seed_contract_should_hold module="APPROVALS_APPROVAL_REQUEST"
