[SCENARIO: BDD-APPROVALS_APPROVER-SEED-approvals_approver_workflow_approver_approver_refuse_flow] TITLE: APPROVALS_APPROVER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="approvals_approver_workflow_approver_approver_refuse_flow" module="APPROVALS_APPROVER"
WHEN when_execute_seed_contract module="APPROVALS_APPROVER"
THEN then_seed_contract_should_hold module="APPROVALS_APPROVER"
