[SCENARIO: BDD-BARCODE_GS1_APPLICATION_IDENTIFIER-SEED-barcode_gs1_application_identifier_action_gs1_application_identifier_create_create] TITLE: BARCODE_GS1_APPLICATION_IDENTIFIER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="barcode_gs1_application_identifier_action_gs1_application_identifier_create_create" module="BARCODE_GS1_APPLICATION_IDENTIFIER"
WHEN when_execute_seed_contract module="BARCODE_GS1_APPLICATION_IDENTIFIER"
THEN then_seed_contract_should_hold module="BARCODE_GS1_APPLICATION_IDENTIFIER"
