[SCENARIO: BDD-BARCODE_BARCODE_MAPPING-SEED-barcode_barcode_mapping_workflow_barcode_mapping_mapping_lifecycle] TITLE: BARCODE_BARCODE_MAPPING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="barcode_barcode_mapping_workflow_barcode_mapping_mapping_lifecycle" module="BARCODE_BARCODE_MAPPING"
WHEN when_execute_seed_contract module="BARCODE_BARCODE_MAPPING"
THEN then_seed_contract_should_hold module="BARCODE_BARCODE_MAPPING"
