[SCENARIO: BDD-CALENDAR_CALENDAR_EVENT-SEED-calendar_calendar_event_action_calendar_event_update_update] TITLE: CALENDAR_CALENDAR_EVENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="calendar_calendar_event_action_calendar_event_update_update" module="CALENDAR_CALENDAR_EVENT"
WHEN when_execute_seed_contract module="CALENDAR_CALENDAR_EVENT"
THEN then_seed_contract_should_hold module="CALENDAR_CALENDAR_EVENT"
