[SCENARIO: BDD-CALENDAR_ATTENDEE-SEED-calendar_attendee_workflow_attendee_attendee_response_flow] TITLE: CALENDAR_ATTENDEE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="calendar_attendee_workflow_attendee_attendee_response_flow" module="CALENDAR_ATTENDEE"
WHEN when_execute_seed_contract module="CALENDAR_ATTENDEE"
THEN then_seed_contract_should_hold module="CALENDAR_ATTENDEE"
