[SCENARIO: BDD-CALENDAR_CALENDAR_EVENT-SEED-calendar_calendar_event_event_calendar_event_cancel_calendar_event_cancelled] TITLE: CALENDAR_CALENDAR_EVENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="calendar_calendar_event_event_calendar_event_cancel_calendar_event_cancelled" module="CALENDAR_CALENDAR_EVENT"
WHEN when_execute_seed_contract module="CALENDAR_CALENDAR_EVENT"
THEN then_seed_contract_should_hold module="CALENDAR_CALENDAR_EVENT"
