[SCENARIO: BDD-CALENDAR_WORK_SCHEDULE-SEED-calendar_work_schedule_action_work_schedule_read_read] TITLE: CALENDAR_WORK_SCHEDULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="calendar_work_schedule_action_work_schedule_read_read" module="CALENDAR_WORK_SCHEDULE"
WHEN when_execute_seed_contract module="CALENDAR_WORK_SCHEDULE"
THEN then_seed_contract_should_hold module="CALENDAR_WORK_SCHEDULE"
