[SCENARIO: BDD-COMMUNICATION_MAIL_GROUP_MESSAGE-SEED-communication_mail_group_message_action_mail_group_message_moderate_reject_update] TITLE: COMMUNICATION_MAIL_GROUP_MESSAGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="communication_mail_group_message_action_mail_group_message_moderate_reject_update" module="COMMUNICATION_MAIL_GROUP_MESSAGE"
WHEN when_execute_seed_contract module="COMMUNICATION_MAIL_GROUP_MESSAGE"
THEN then_seed_contract_should_hold module="COMMUNICATION_MAIL_GROUP_MESSAGE"
