[SCENARIO: BDD-COMMUNICATION_MESSAGE-SEED-communication_message_action_message_destroy_destroy] TITLE: COMMUNICATION_MESSAGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="communication_message_action_message_destroy_destroy" module="COMMUNICATION_MESSAGE"
WHEN when_execute_seed_contract module="COMMUNICATION_MESSAGE"
THEN then_seed_contract_should_hold module="COMMUNICATION_MESSAGE"
