[SCENARIO: BDD-COMMUNICATION_MAIL_GROUP_MEMBER-SEED-communication_mail_group_member_workflow_mail_group_member_mail_group_member_join_leave_flow] TITLE: COMMUNICATION_MAIL_GROUP_MEMBER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="communication_mail_group_member_workflow_mail_group_member_mail_group_member_join_leave_flow" module="COMMUNICATION_MAIL_GROUP_MEMBER"
WHEN when_execute_seed_contract module="COMMUNICATION_MAIL_GROUP_MEMBER"
THEN then_seed_contract_should_hold module="COMMUNICATION_MAIL_GROUP_MEMBER"
