[SCENARIO: BDD-COMMUNICATION_MAIL_GROUP_MESSAGE-SEED-communication_mail_group_message_workflow_mail_group_message_mail_group_message_moderation_flow] TITLE: COMMUNICATION_MAIL_GROUP_MESSAGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="communication_mail_group_message_workflow_mail_group_message_mail_group_message_moderation_flow" module="COMMUNICATION_MAIL_GROUP_MESSAGE"
WHEN when_execute_seed_contract module="COMMUNICATION_MAIL_GROUP_MESSAGE"
THEN then_seed_contract_should_hold module="COMMUNICATION_MAIL_GROUP_MESSAGE"
