[SCENARIO: BDD-CRM_CONTACT_ADDRESS-SEED-crm_contact_address_action_contact_address_create_create] TITLE: CRM_CONTACT_ADDRESS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="crm_contact_address_action_contact_address_create_create" module="CRM_CONTACT_ADDRESS"
WHEN when_execute_seed_contract module="CRM_CONTACT_ADDRESS"
THEN then_seed_contract_should_hold module="CRM_CONTACT_ADDRESS"
