[SCENARIO: BDD-DATA_RECYCLE_RECYCLE_MODEL_NOTIFY_USER-SEED-data_recycle_recycle_model_notify_user_workflow_recycle_model_notify_user_recycle_model_notify_user_management] TITLE: DATA_RECYCLE_RECYCLE_MODEL_NOTIFY_USER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="data_recycle_recycle_model_notify_user_workflow_recycle_model_notify_user_recycle_model_notify_user_management" module="DATA_RECYCLE_RECYCLE_MODEL_NOTIFY_USER"
WHEN when_execute_seed_contract module="DATA_RECYCLE_RECYCLE_MODEL_NOTIFY_USER"
THEN then_seed_contract_should_hold module="DATA_RECYCLE_RECYCLE_MODEL_NOTIFY_USER"
