[SCENARIO: BDD-DELIVERY_SHIPMENT_STATUS-SEED-delivery_shipment_status_action_shipment_status_read_read] TITLE: DELIVERY_SHIPMENT_STATUS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="delivery_shipment_status_action_shipment_status_read_read" module="DELIVERY_SHIPMENT_STATUS"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_STATUS"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_STATUS"
