[SCENARIO: BDD-DELIVERY_SHIPMENT_ITEM-SEED-delivery_shipment_item_action_shipment_item_destroy_destroy] TITLE: DELIVERY_SHIPMENT_ITEM contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="delivery_shipment_item_action_shipment_item_destroy_destroy" module="DELIVERY_SHIPMENT_ITEM"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_ITEM"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_ITEM"
