[SCENARIO: BDD-DELIVERY_SHIPMENT_BOX_TYPE-SEED-delivery_shipment_box_type_action_shipment_box_type_update_update] TITLE: DELIVERY_SHIPMENT_BOX_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="delivery_shipment_box_type_action_shipment_box_type_update_update" module="DELIVERY_SHIPMENT_BOX_TYPE"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_BOX_TYPE"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_BOX_TYPE"
