[SCENARIO: BDD-DELIVERY_DELIVERY-SEED-delivery_delivery_workflow_delivery_delivery_trip_flow] TITLE: DELIVERY_DELIVERY contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="delivery_delivery_workflow_delivery_delivery_trip_flow" module="DELIVERY_DELIVERY"
WHEN when_execute_seed_contract module="DELIVERY_DELIVERY"
THEN then_seed_contract_should_hold module="DELIVERY_DELIVERY"
