[SCENARIO: BDD-DELIVERY_SHIPMENT-SEED-delivery_shipment_event_shipment_ship_delivery_shipment_dispatched] TITLE: DELIVERY_SHIPMENT contract seed scenario TAGS: seed event_contract
GIVEN given_seed_context id="delivery_shipment_event_shipment_ship_delivery_shipment_dispatched" module="DELIVERY_SHIPMENT"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT"
