[SCENARIO: BDD-DELIVERY_SHIPMENT_PACKAGE_ROUTE_SEG-SEED-delivery_shipment_package_route_seg_workflow_shipment_package_route_seg_package_route_seg_flow] TITLE: DELIVERY_SHIPMENT_PACKAGE_ROUTE_SEG contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="delivery_shipment_package_route_seg_workflow_shipment_package_route_seg_package_route_seg_flow" module="DELIVERY_SHIPMENT_PACKAGE_ROUTE_SEG"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_PACKAGE_ROUTE_SEG"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_PACKAGE_ROUTE_SEG"
