[SCENARIO: BDD-DELIVERY_CROSS_ORG_TRANSACTION-SEED-delivery_cross_org_transaction_event_cross_org_transaction_create_mirror_purchase_order_delivery_cross_org_transaction_mirror_created] TITLE: DELIVERY_CROSS_ORG_TRANSACTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="delivery_cross_org_transaction_event_cross_org_transaction_create_mirror_purchase_order_delivery_cross_org_transaction_mirror_created" module="DELIVERY_CROSS_ORG_TRANSACTION"
WHEN when_execute_seed_contract module="DELIVERY_CROSS_ORG_TRANSACTION"
THEN then_seed_contract_should_hold module="DELIVERY_CROSS_ORG_TRANSACTION"
