[SCENARIO: BDD-DELIVERY_SHIPMENT_PACKAGE-SEED-delivery_shipment_package_action_shipment_package_read_read] TITLE: DELIVERY_SHIPMENT_PACKAGE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="delivery_shipment_package_action_shipment_package_read_read" module="DELIVERY_SHIPMENT_PACKAGE"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_PACKAGE"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_PACKAGE"
