[SCENARIO: BDD-DELIVERY_SHIPMENT_METHOD_TYPE-SEED-delivery_shipment_method_type_action_shipment_method_type_destroy_destroy] TITLE: DELIVERY_SHIPMENT_METHOD_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="delivery_shipment_method_type_action_shipment_method_type_destroy_destroy" module="DELIVERY_SHIPMENT_METHOD_TYPE"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_METHOD_TYPE"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_METHOD_TYPE"
