[SCENARIO: BDD-DELIVERY_SHIPMENT_METHOD_TYPE-SEED-delivery_shipment_method_type_workflow_shipment_method_type_shipment_method_type_maintain_flow] TITLE: DELIVERY_SHIPMENT_METHOD_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="delivery_shipment_method_type_workflow_shipment_method_type_shipment_method_type_maintain_flow" module="DELIVERY_SHIPMENT_METHOD_TYPE"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_METHOD_TYPE"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_METHOD_TYPE"
