[SCENARIO: BDD-DELIVERY_SHIPMENT_COST_ESTIMATE-SEED-delivery_shipment_cost_estimate_workflow_shipment_cost_estimate_cost_estimate_maintain_flow] TITLE: DELIVERY_SHIPMENT_COST_ESTIMATE contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="delivery_shipment_cost_estimate_workflow_shipment_cost_estimate_cost_estimate_maintain_flow" module="DELIVERY_SHIPMENT_COST_ESTIMATE"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_COST_ESTIMATE"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_COST_ESTIMATE"
