[SCENARIO: BDD-DELIVERY_SHIPMENT_TYPE-SEED-delivery_shipment_type_action_shipment_type_destroy_destroy] TITLE: DELIVERY_SHIPMENT_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="delivery_shipment_type_action_shipment_type_destroy_destroy" module="DELIVERY_SHIPMENT_TYPE"
WHEN when_execute_seed_contract module="DELIVERY_SHIPMENT_TYPE"
THEN then_seed_contract_should_hold module="DELIVERY_SHIPMENT_TYPE"
