[SCENARIO: BDD-DOCUMENTS_ACTIVITY_TYPE-SEED-documents_activity_type_action_activity_type_read_read] TITLE: DOCUMENTS_ACTIVITY_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="documents_activity_type_action_activity_type_read_read" module="DOCUMENTS_ACTIVITY_TYPE"
WHEN when_execute_seed_contract module="DOCUMENTS_ACTIVITY_TYPE"
THEN then_seed_contract_should_hold module="DOCUMENTS_ACTIVITY_TYPE"
