[SCENARIO: BDD-DOCUMENTS_SHARE_TAG_LINK-SEED-documents_share_tag_link_action_share_tag_link_read_read] TITLE: DOCUMENTS_SHARE_TAG_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="documents_share_tag_link_action_share_tag_link_read_read" module="DOCUMENTS_SHARE_TAG_LINK"
WHEN when_execute_seed_contract module="DOCUMENTS_SHARE_TAG_LINK"
THEN then_seed_contract_should_hold module="DOCUMENTS_SHARE_TAG_LINK"
