[SCENARIO: BDD-DOCUMENTS_DOCUMENT-SEED-documents_document_workflow_document_document_lifecycle_flow] TITLE: DOCUMENTS_DOCUMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="documents_document_workflow_document_document_lifecycle_flow" module="DOCUMENTS_DOCUMENT"
WHEN when_execute_seed_contract module="DOCUMENTS_DOCUMENT"
THEN then_seed_contract_should_hold module="DOCUMENTS_DOCUMENT"
