[SCENARIO: BDD-DOCUMENTS_DOCUMENT-SEED-documents_document_event_document_unlock_documents_document_unlocked] TITLE: DOCUMENTS_DOCUMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="documents_document_event_document_unlock_documents_document_unlocked" module="DOCUMENTS_DOCUMENT"
WHEN when_execute_seed_contract module="DOCUMENTS_DOCUMENT"
THEN then_seed_contract_should_hold module="DOCUMENTS_DOCUMENT"
