[SCENARIO: BDD-DOCUMENTS_WORKFLOW_RULE-SEED-documents_workflow_rule_action_workflow_rule_read_read] TITLE: DOCUMENTS_WORKFLOW_RULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="documents_workflow_rule_action_workflow_rule_read_read" module="DOCUMENTS_WORKFLOW_RULE"
WHEN when_execute_seed_contract module="DOCUMENTS_WORKFLOW_RULE"
THEN then_seed_contract_should_hold module="DOCUMENTS_WORKFLOW_RULE"
