[SCENARIO: BDD-DOCUMENTS_FOLDER_WORKFLOW_RULE_LINK-SEED-documents_folder_workflow_rule_link_action_folder_workflow_rule_link_read_read] TITLE: DOCUMENTS_FOLDER_WORKFLOW_RULE_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="documents_folder_workflow_rule_link_action_folder_workflow_rule_link_read_read" module="DOCUMENTS_FOLDER_WORKFLOW_RULE_LINK"
WHEN when_execute_seed_contract module="DOCUMENTS_FOLDER_WORKFLOW_RULE_LINK"
THEN then_seed_contract_should_hold module="DOCUMENTS_FOLDER_WORKFLOW_RULE_LINK"
