[SCENARIO: BDD-E_LEARNING_ENROLLMENT-SEED-e_learning_enrollment_event_enrollment_recompute_completion_elearning_enrollment_progress_updated] TITLE: E_LEARNING_ENROLLMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="e_learning_enrollment_event_enrollment_recompute_completion_elearning_enrollment_progress_updated" module="E_LEARNING_ENROLLMENT"
WHEN when_execute_seed_contract module="E_LEARNING_ENROLLMENT"
THEN then_seed_contract_should_hold module="E_LEARNING_ENROLLMENT"
