[SCENARIO: BDD-E_LEARNING_SLIDE-SEED-e_learning_slide_event_slide_publish_elearning_slide_published] TITLE: E_LEARNING_SLIDE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="e_learning_slide_event_slide_publish_elearning_slide_published" module="E_LEARNING_SLIDE"
WHEN when_execute_seed_contract module="E_LEARNING_SLIDE"
THEN then_seed_contract_should_hold module="E_LEARNING_SLIDE"
