[SCENARIO: BDD-E_LEARNING_COURSE-SEED-e_learning_course_event_course_archive_elearning_course_archived] TITLE: E_LEARNING_COURSE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="e_learning_course_event_course_archive_elearning_course_archived" module="E_LEARNING_COURSE"
WHEN when_execute_seed_contract module="E_LEARNING_COURSE"
THEN then_seed_contract_should_hold module="E_LEARNING_COURSE"
