[SCENARIO: BDD-E_LEARNING_SLIDE_PROGRESS-SEED-e_learning_slide_progress_workflow_slide_progress_progress_tracking] TITLE: E_LEARNING_SLIDE_PROGRESS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="e_learning_slide_progress_workflow_slide_progress_progress_tracking" module="E_LEARNING_SLIDE_PROGRESS"
WHEN when_execute_seed_contract module="E_LEARNING_SLIDE_PROGRESS"
THEN then_seed_contract_should_hold module="E_LEARNING_SLIDE_PROGRESS"
