[SCENARIO: BDD-E_LEARNING_SLIDE_PROGRESS-SEED-e_learning_slide_progress_action_slide_progress_read_read] TITLE: E_LEARNING_SLIDE_PROGRESS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="e_learning_slide_progress_action_slide_progress_read_read" module="E_LEARNING_SLIDE_PROGRESS"
WHEN when_execute_seed_contract module="E_LEARNING_SLIDE_PROGRESS"
THEN then_seed_contract_should_hold module="E_LEARNING_SLIDE_PROGRESS"
