[SCENARIO: BDD-ECOMMERCE_PRODUCT_VARIANT-SEED-ecommerce_product_variant_workflow_product_variant_variant_lifecycle] TITLE: ECOMMERCE_PRODUCT_VARIANT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_product_variant_workflow_product_variant_variant_lifecycle" module="ECOMMERCE_PRODUCT_VARIANT"
WHEN when_execute_seed_contract module="ECOMMERCE_PRODUCT_VARIANT"
THEN then_seed_contract_should_hold module="ECOMMERCE_PRODUCT_VARIANT"
