[SCENARIO: BDD-ECOMMERCE_PRODUCT_TEMPLATE_PUBLIC_CATEGORY_LINK-SEED-ecommerce_product_template_public_category_link_action_product_template_public_category_link_read_read] TITLE: ECOMMERCE_PRODUCT_TEMPLATE_PUBLIC_CATEGORY_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_product_template_public_category_link_action_product_template_public_category_link_read_read" module="ECOMMERCE_PRODUCT_TEMPLATE_PUBLIC_CATEGORY_LINK"
WHEN when_execute_seed_contract module="ECOMMERCE_PRODUCT_TEMPLATE_PUBLIC_CATEGORY_LINK"
THEN then_seed_contract_should_hold module="ECOMMERCE_PRODUCT_TEMPLATE_PUBLIC_CATEGORY_LINK"
