[SCENARIO: BDD-ECOMMERCE_TRAVEL_STATION-SEED-ecommerce_travel_station_action_travel_station_create_create] TITLE: ECOMMERCE_TRAVEL_STATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_travel_station_action_travel_station_create_create" module="ECOMMERCE_TRAVEL_STATION"
WHEN when_execute_seed_contract module="ECOMMERCE_TRAVEL_STATION"
THEN then_seed_contract_should_hold module="ECOMMERCE_TRAVEL_STATION"
