[SCENARIO: BDD-ECOMMERCE_PRODUCT_TEMPLATE_ORG_VIEW-SEED-ecommerce_product_template_org_view_workflow_product_template_org_view_product_template_org_view_lifecycle] TITLE: ECOMMERCE_PRODUCT_TEMPLATE_ORG_VIEW contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_product_template_org_view_workflow_product_template_org_view_product_template_org_view_lifecycle" module="ECOMMERCE_PRODUCT_TEMPLATE_ORG_VIEW"
WHEN when_execute_seed_contract module="ECOMMERCE_PRODUCT_TEMPLATE_ORG_VIEW"
THEN then_seed_contract_should_hold module="ECOMMERCE_PRODUCT_TEMPLATE_ORG_VIEW"
