[SCENARIO: BDD-ECOMMERCE_PRODUCT_PRICE-SEED-ecommerce_product_price_action_product_price_read_read] TITLE: ECOMMERCE_PRODUCT_PRICE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_product_price_action_product_price_read_read" module="ECOMMERCE_PRODUCT_PRICE"
WHEN when_execute_seed_contract module="ECOMMERCE_PRODUCT_PRICE"
THEN then_seed_contract_should_hold module="ECOMMERCE_PRODUCT_PRICE"
