[SCENARIO: BDD-ECOMMERCE_SHOPPING_CART-SEED-ecommerce_shopping_cart_event_shopping_cart_convert_ecommerce_cart_converted] TITLE: ECOMMERCE_SHOPPING_CART contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_shopping_cart_event_shopping_cart_convert_ecommerce_cart_converted" module="ECOMMERCE_SHOPPING_CART"
WHEN when_execute_seed_contract module="ECOMMERCE_SHOPPING_CART"
THEN then_seed_contract_should_hold module="ECOMMERCE_SHOPPING_CART"
