[SCENARIO: BDD-ECOMMERCE_PRODUCT_CATEGORY-SEED-ecommerce_product_category_action_product_category_update_update] TITLE: ECOMMERCE_PRODUCT_CATEGORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_product_category_action_product_category_update_update" module="ECOMMERCE_PRODUCT_CATEGORY"
WHEN when_execute_seed_contract module="ECOMMERCE_PRODUCT_CATEGORY"
THEN then_seed_contract_should_hold module="ECOMMERCE_PRODUCT_CATEGORY"
