[SCENARIO: BDD-ECOMMERCE_LOYALTY_PROGRAM-SEED-ecommerce_loyalty_program_workflow_loyalty_program_loyalty_program_lifecycle] TITLE: ECOMMERCE_LOYALTY_PROGRAM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_loyalty_program_workflow_loyalty_program_loyalty_program_lifecycle" module="ECOMMERCE_LOYALTY_PROGRAM"
WHEN when_execute_seed_contract module="ECOMMERCE_LOYALTY_PROGRAM"
THEN then_seed_contract_should_hold module="ECOMMERCE_LOYALTY_PROGRAM"
