[SCENARIO: BDD-ECOMMERCE_LOYALTY_CARD-SEED-ecommerce_loyalty_card_workflow_loyalty_card_card_lifecycle] TITLE: ECOMMERCE_LOYALTY_CARD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ecommerce_loyalty_card_workflow_loyalty_card_card_lifecycle" module="ECOMMERCE_LOYALTY_CARD"
WHEN when_execute_seed_contract module="ECOMMERCE_LOYALTY_CARD"
THEN then_seed_contract_should_hold module="ECOMMERCE_LOYALTY_CARD"
