[SCENARIO: BDD-EVENTS_EVENT_TICKET-SEED-events_event_ticket_workflow_event_ticket_ticket_lifecycle] TITLE: EVENTS_EVENT_TICKET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="events_event_ticket_workflow_event_ticket_ticket_lifecycle" module="EVENTS_EVENT_TICKET"
WHEN when_execute_seed_contract module="EVENTS_EVENT_TICKET"
THEN then_seed_contract_should_hold module="EVENTS_EVENT_TICKET"
