[SCENARIO: BDD-EXPENSES_EXPENSE_REPORT-SEED-expenses_expense_report_event_expense_report_refuse_expenses_report_refused] TITLE: EXPENSES_EXPENSE_REPORT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="expenses_expense_report_event_expense_report_refuse_expenses_report_refused" module="EXPENSES_EXPENSE_REPORT"
WHEN when_execute_seed_contract module="EXPENSES_EXPENSE_REPORT"
THEN then_seed_contract_should_hold module="EXPENSES_EXPENSE_REPORT"
