[SCENARIO: BDD-FLEET_FLEET_VEHICLE_TYPE-SEED-fleet_fleet_vehicle_type_workflow_fleet_vehicle_type_fleet_vehicle_type_lifecycle] TITLE: FLEET_FLEET_VEHICLE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="fleet_fleet_vehicle_type_workflow_fleet_vehicle_type_fleet_vehicle_type_lifecycle" module="FLEET_FLEET_VEHICLE_TYPE"
WHEN when_execute_seed_contract module="FLEET_FLEET_VEHICLE_TYPE"
THEN then_seed_contract_should_hold module="FLEET_FLEET_VEHICLE_TYPE"
