[SCENARIO: BDD-FLEET_VEHICLE_SERVICE-SEED-fleet_vehicle_service_event_vehicle_service_complete_fleet_service_completed] TITLE: FLEET_VEHICLE_SERVICE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="fleet_vehicle_service_event_vehicle_service_complete_fleet_service_completed" module="FLEET_VEHICLE_SERVICE"
WHEN when_execute_seed_contract module="FLEET_VEHICLE_SERVICE"
THEN then_seed_contract_should_hold module="FLEET_VEHICLE_SERVICE"
