[SCENARIO: BDD-FLEET_VEHICLE_ASSIGNMENT-SEED-fleet_vehicle_assignment_event_vehicle_assignment_assign_fleet_vehicle_assigned] TITLE: FLEET_VEHICLE_ASSIGNMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="fleet_vehicle_assignment_event_vehicle_assignment_assign_fleet_vehicle_assigned" module="FLEET_VEHICLE_ASSIGNMENT"
WHEN when_execute_seed_contract module="FLEET_VEHICLE_ASSIGNMENT"
THEN then_seed_contract_should_hold module="FLEET_VEHICLE_ASSIGNMENT"
