[SCENARIO: BDD-GAMIFICATION_CHALLENGE_USER_LINK-SEED-gamification_challenge_user_link_action_challenge_user_link_read_read] TITLE: GAMIFICATION_CHALLENGE_USER_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="gamification_challenge_user_link_action_challenge_user_link_read_read" module="GAMIFICATION_CHALLENGE_USER_LINK"
WHEN when_execute_seed_contract module="GAMIFICATION_CHALLENGE_USER_LINK"
THEN then_seed_contract_should_hold module="GAMIFICATION_CHALLENGE_USER_LINK"
