[SCENARIO: BDD-GAMIFICATION_BADGE_USER-SEED-gamification_badge_user_event_badge_user_create_gamification_badge_granted] TITLE: GAMIFICATION_BADGE_USER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="gamification_badge_user_event_badge_user_create_gamification_badge_granted" module="GAMIFICATION_BADGE_USER"
WHEN when_execute_seed_contract module="GAMIFICATION_BADGE_USER"
THEN then_seed_contract_should_hold module="GAMIFICATION_BADGE_USER"
