[SCENARIO: BDD-GAMIFICATION_CHALLENGE_LINE-SEED-gamification_challenge_line_workflow_challenge_line_challenge_line_lifecycle_flow] TITLE: GAMIFICATION_CHALLENGE_LINE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="gamification_challenge_line_workflow_challenge_line_challenge_line_lifecycle_flow" module="GAMIFICATION_CHALLENGE_LINE"
WHEN when_execute_seed_contract module="GAMIFICATION_CHALLENGE_LINE"
THEN then_seed_contract_should_hold module="GAMIFICATION_CHALLENGE_LINE"
