[SCENARIO: BDD-GAMIFICATION_GOAL-SEED-gamification_goal_event_goal_action_reach_gamification_goal_reached] TITLE: GAMIFICATION_GOAL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="gamification_goal_event_goal_action_reach_gamification_goal_reached" module="GAMIFICATION_GOAL"
WHEN when_execute_seed_contract module="GAMIFICATION_GOAL"
THEN then_seed_contract_should_hold module="GAMIFICATION_GOAL"
