[SCENARIO: BDD-HELPDESK_FIELD_SERVICE_ASSIGNMENT-SEED-helpdesk_field_service_assignment_workflow_field_service_assignment_assignment_management] TITLE: HELPDESK_FIELD_SERVICE_ASSIGNMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_field_service_assignment_workflow_field_service_assignment_assignment_management" module="HELPDESK_FIELD_SERVICE_ASSIGNMENT"
WHEN when_execute_seed_contract module="HELPDESK_FIELD_SERVICE_ASSIGNMENT"
THEN then_seed_contract_should_hold module="HELPDESK_FIELD_SERVICE_ASSIGNMENT"
