[SCENARIO: BDD-HELPDESK_HELPDESK_SLA-SEED-helpdesk_helpdesk_sla_action_helpdesk_sla_update_update] TITLE: HELPDESK_HELPDESK_SLA contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_helpdesk_sla_action_helpdesk_sla_update_update" module="HELPDESK_HELPDESK_SLA"
WHEN when_execute_seed_contract module="HELPDESK_HELPDESK_SLA"
THEN then_seed_contract_should_hold module="HELPDESK_HELPDESK_SLA"
