[SCENARIO: BDD-HELPDESK_HELPDESK_SLA-SEED-helpdesk_helpdesk_sla_workflow_helpdesk_sla_sla_policy_management] TITLE: HELPDESK_HELPDESK_SLA contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_helpdesk_sla_workflow_helpdesk_sla_sla_policy_management" module="HELPDESK_HELPDESK_SLA"
WHEN when_execute_seed_contract module="HELPDESK_HELPDESK_SLA"
THEN then_seed_contract_should_hold module="HELPDESK_HELPDESK_SLA"
