[SCENARIO: BDD-HELPDESK_FIELD_SERVICE_ORDER-SEED-helpdesk_field_service_order_event_field_service_order_start_timer_helpdesk_field_service_timer_started] TITLE: HELPDESK_FIELD_SERVICE_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_field_service_order_event_field_service_order_start_timer_helpdesk_field_service_timer_started" module="HELPDESK_FIELD_SERVICE_ORDER"
WHEN when_execute_seed_contract module="HELPDESK_FIELD_SERVICE_ORDER"
THEN then_seed_contract_should_hold module="HELPDESK_FIELD_SERVICE_ORDER"
