[SCENARIO: BDD-HELPDESK_WORKSHEET-SEED-helpdesk_worksheet_workflow_worksheet_worksheet_lifecycle] TITLE: HELPDESK_WORKSHEET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_worksheet_workflow_worksheet_worksheet_lifecycle" module="HELPDESK_WORKSHEET"
WHEN when_execute_seed_contract module="HELPDESK_WORKSHEET"
THEN then_seed_contract_should_hold module="HELPDESK_WORKSHEET"
