[SCENARIO: BDD-HELPDESK_HELPDESK_TICKET-SEED-helpdesk_helpdesk_ticket_event_helpdesk_ticket_close_helpdesk_ticket_closed] TITLE: HELPDESK_HELPDESK_TICKET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_helpdesk_ticket_event_helpdesk_ticket_close_helpdesk_ticket_closed" module="HELPDESK_HELPDESK_TICKET"
WHEN when_execute_seed_contract module="HELPDESK_HELPDESK_TICKET"
THEN then_seed_contract_should_hold module="HELPDESK_HELPDESK_TICKET"
