[SCENARIO: BDD-HELPDESK_FSM_MATERIAL_LINE-SEED-helpdesk_fsm_material_line_workflow_fsm_material_line_material_line_management] TITLE: HELPDESK_FSM_MATERIAL_LINE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_fsm_material_line_workflow_fsm_material_line_material_line_management" module="HELPDESK_FSM_MATERIAL_LINE"
WHEN when_execute_seed_contract module="HELPDESK_FSM_MATERIAL_LINE"
THEN then_seed_contract_should_hold module="HELPDESK_FSM_MATERIAL_LINE"
