[SCENARIO: BDD-HELPDESK_HELPDESK_SLA_PARTNER_LINK-SEED-helpdesk_helpdesk_sla_partner_link_action_helpdesk_sla_partner_link_read_read] TITLE: HELPDESK_HELPDESK_SLA_PARTNER_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_helpdesk_sla_partner_link_action_helpdesk_sla_partner_link_read_read" module="HELPDESK_HELPDESK_SLA_PARTNER_LINK"
WHEN when_execute_seed_contract module="HELPDESK_HELPDESK_SLA_PARTNER_LINK"
THEN then_seed_contract_should_hold module="HELPDESK_HELPDESK_SLA_PARTNER_LINK"
