[SCENARIO: BDD-HELPDESK_WORKSHEET_TEMPLATE-SEED-helpdesk_worksheet_template_action_worksheet_template_update_update] TITLE: HELPDESK_WORKSHEET_TEMPLATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_worksheet_template_action_worksheet_template_update_update" module="HELPDESK_WORKSHEET_TEMPLATE"
WHEN when_execute_seed_contract module="HELPDESK_WORKSHEET_TEMPLATE"
THEN then_seed_contract_should_hold module="HELPDESK_WORKSHEET_TEMPLATE"
