[SCENARIO: BDD-HELPDESK_APPOINTMENT-SEED-helpdesk_appointment_action_appointment_create_create] TITLE: HELPDESK_APPOINTMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_appointment_action_appointment_create_create" module="HELPDESK_APPOINTMENT"
WHEN when_execute_seed_contract module="HELPDESK_APPOINTMENT"
THEN then_seed_contract_should_hold module="HELPDESK_APPOINTMENT"
