[SCENARIO: BDD-HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK-SEED-helpdesk_field_service_order_tag_link_action_field_service_order_tag_link_read_read] TITLE: HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_field_service_order_tag_link_action_field_service_order_tag_link_read_read" module="HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"
WHEN when_execute_seed_contract module="HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"
THEN then_seed_contract_should_hold module="HELPDESK_FIELD_SERVICE_ORDER_TAG_LINK"
