[SCENARIO: BDD-HELPDESK_HELPDESK_TAG-SEED-helpdesk_helpdesk_tag_action_helpdesk_tag_read_read] TITLE: HELPDESK_HELPDESK_TAG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="helpdesk_helpdesk_tag_action_helpdesk_tag_read_read" module="HELPDESK_HELPDESK_TAG"
WHEN when_execute_seed_contract module="HELPDESK_HELPDESK_TAG"
THEN then_seed_contract_should_hold module="HELPDESK_HELPDESK_TAG"
