[SCENARIO: BDD-HR_EMPLOYMENT_CONTRACT-SEED-hr_employment_contract_action_employment_contract_create_create] TITLE: HR_EMPLOYMENT_CONTRACT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="hr_employment_contract_action_employment_contract_create_create" module="HR_EMPLOYMENT_CONTRACT"
WHEN when_execute_seed_contract module="HR_EMPLOYMENT_CONTRACT"
THEN then_seed_contract_should_hold module="HR_EMPLOYMENT_CONTRACT"
