[SCENARIO: BDD-HR_WORK_LOCATION-SEED-hr_work_location_workflow_work_location_work_location_write_flow] TITLE: HR_WORK_LOCATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="hr_work_location_workflow_work_location_work_location_write_flow" module="HR_WORK_LOCATION"
WHEN when_execute_seed_contract module="HR_WORK_LOCATION"
THEN then_seed_contract_should_hold module="HR_WORK_LOCATION"
