[SCENARIO: BDD-INVENTORY_STOCK_PICKING-SEED-inventory_stock_picking_workflow_stock_picking_stock_picking_cancel_flow] TITLE: INVENTORY_STOCK_PICKING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="inventory_stock_picking_workflow_stock_picking_stock_picking_cancel_flow" module="INVENTORY_STOCK_PICKING"
WHEN when_execute_seed_contract module="INVENTORY_STOCK_PICKING"
THEN then_seed_contract_should_hold module="INVENTORY_STOCK_PICKING"
