[SCENARIO: BDD-INVENTORY_LANDED_COST_LINE-SEED-inventory_landed_cost_line_action_landed_cost_line_read_read] TITLE: INVENTORY_LANDED_COST_LINE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="inventory_landed_cost_line_action_landed_cost_line_read_read" module="INVENTORY_LANDED_COST_LINE"
WHEN when_execute_seed_contract module="INVENTORY_LANDED_COST_LINE"
THEN then_seed_contract_should_hold module="INVENTORY_LANDED_COST_LINE"
