[SCENARIO: BDD-INVENTORY_STOCK_MOVE_DEPENDENCY_LINK-SEED-inventory_stock_move_dependency_link_action_stock_move_dependency_link_read_read] TITLE: INVENTORY_STOCK_MOVE_DEPENDENCY_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="inventory_stock_move_dependency_link_action_stock_move_dependency_link_read_read" module="INVENTORY_STOCK_MOVE_DEPENDENCY_LINK"
WHEN when_execute_seed_contract module="INVENTORY_STOCK_MOVE_DEPENDENCY_LINK"
THEN then_seed_contract_should_hold module="INVENTORY_STOCK_MOVE_DEPENDENCY_LINK"
