[SCENARIO: BDD-INVENTORY_STOCK_LOCATION-SEED-inventory_stock_location_workflow_stock_location_stock_location_write_flow] TITLE: INVENTORY_STOCK_LOCATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="inventory_stock_location_workflow_stock_location_stock_location_write_flow" module="INVENTORY_STOCK_LOCATION"
WHEN when_execute_seed_contract module="INVENTORY_STOCK_LOCATION"
THEN then_seed_contract_should_hold module="INVENTORY_STOCK_LOCATION"
