[SCENARIO: BDD-INVENTORY_LANDED_COST-SEED-inventory_landed_cost_action_landed_cost_read_read] TITLE: INVENTORY_LANDED_COST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="inventory_landed_cost_action_landed_cost_read_read" module="INVENTORY_LANDED_COST"
WHEN when_execute_seed_contract module="INVENTORY_LANDED_COST"
THEN then_seed_contract_should_hold module="INVENTORY_LANDED_COST"
