[SCENARIO: BDD-IO_T_HELPDESK_TICKET-SEED-io_t_helpdesk_ticket_action_helpdesk_ticket_read_read] TITLE: IO_T_HELPDESK_TICKET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_helpdesk_ticket_action_helpdesk_ticket_read_read" module="IO_T_HELPDESK_TICKET"
WHEN when_execute_seed_contract module="IO_T_HELPDESK_TICKET"
THEN then_seed_contract_should_hold module="IO_T_HELPDESK_TICKET"
