[SCENARIO: BDD-IO_T_CONFERENCE_ROOM-SEED-io_t_conference_room_event_conference_room_start_conference_voip_conference_started] TITLE: IO_T_CONFERENCE_ROOM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_conference_room_event_conference_room_start_conference_voip_conference_started" module="IO_T_CONFERENCE_ROOM"
WHEN when_execute_seed_contract module="IO_T_CONFERENCE_ROOM"
THEN then_seed_contract_should_hold module="IO_T_CONFERENCE_ROOM"
