[SCENARIO: BDD-IO_T_VO_IP_PROVIDER-SEED-io_t_vo_ip_provider_action_vo_ip_provider_create_create] TITLE: IO_T_VO_IP_PROVIDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_provider_action_vo_ip_provider_create_create" module="IO_T_VO_IP_PROVIDER"
WHEN when_execute_seed_contract module="IO_T_VO_IP_PROVIDER"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_PROVIDER"
