[SCENARIO: BDD-IO_T_VO_IP_USER_CONFIG-SEED-io_t_vo_ip_user_config_action_vo_ip_user_config_set_forwarding_update] TITLE: IO_T_VO_IP_USER_CONFIG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_user_config_action_vo_ip_user_config_set_forwarding_update" module="IO_T_VO_IP_USER_CONFIG"
WHEN when_execute_seed_contract module="IO_T_VO_IP_USER_CONFIG"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_USER_CONFIG"
