[SCENARIO: BDD-IO_T_QUEUE_MEMBER-SEED-io_t_queue_member_workflow_queue_member_queue_member_availability_flow] TITLE: IO_T_QUEUE_MEMBER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_queue_member_workflow_queue_member_queue_member_availability_flow" module="IO_T_QUEUE_MEMBER"
WHEN when_execute_seed_contract module="IO_T_QUEUE_MEMBER"
THEN then_seed_contract_should_hold module="IO_T_QUEUE_MEMBER"
