[SCENARIO: BDD-IO_T_DIAL_PLAN_ELEMENT-SEED-io_t_dial_plan_element_action_dial_plan_element_destroy_destroy] TITLE: IO_T_DIAL_PLAN_ELEMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_dial_plan_element_action_dial_plan_element_destroy_destroy" module="IO_T_DIAL_PLAN_ELEMENT"
WHEN when_execute_seed_contract module="IO_T_DIAL_PLAN_ELEMENT"
THEN then_seed_contract_should_hold module="IO_T_DIAL_PLAN_ELEMENT"
