[SCENARIO: BDD-KNOWLEDGE_ARTICLE-SEED-knowledge_article_event_article_action_archive_knowledge_article_archived] TITLE: KNOWLEDGE_ARTICLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="knowledge_article_event_article_action_archive_knowledge_article_archived" module="KNOWLEDGE_ARTICLE"
WHEN when_execute_seed_contract module="KNOWLEDGE_ARTICLE"
THEN then_seed_contract_should_hold module="KNOWLEDGE_ARTICLE"
