[SCENARIO: BDD-KNOWLEDGE_ARTICLE_TAG_LINK-SEED-knowledge_article_tag_link_action_article_tag_link_read_read] TITLE: KNOWLEDGE_ARTICLE_TAG_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="knowledge_article_tag_link_action_article_tag_link_read_read" module="KNOWLEDGE_ARTICLE_TAG_LINK"
WHEN when_execute_seed_contract module="KNOWLEDGE_ARTICLE_TAG_LINK"
THEN then_seed_contract_should_hold module="KNOWLEDGE_ARTICLE_TAG_LINK"
