[SCENARIO: BDD-LIVE_CHAT_LIVE_CHAT_CHANNEL_USER_LINK-SEED-live_chat_live_chat_channel_user_link_action_live_chat_channel_user_link_read_read] TITLE: LIVE_CHAT_LIVE_CHAT_CHANNEL_USER_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="live_chat_live_chat_channel_user_link_action_live_chat_channel_user_link_read_read" module="LIVE_CHAT_LIVE_CHAT_CHANNEL_USER_LINK"
WHEN when_execute_seed_contract module="LIVE_CHAT_LIVE_CHAT_CHANNEL_USER_LINK"
THEN then_seed_contract_should_hold module="LIVE_CHAT_LIVE_CHAT_CHANNEL_USER_LINK"
