[SCENARIO: BDD-LOYALTY_GIFT_CARD-SEED-loyalty_gift_card_event_gift_card_topup_loyalty_giftcard_topup] TITLE: LOYALTY_GIFT_CARD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="loyalty_gift_card_event_gift_card_topup_loyalty_giftcard_topup" module="LOYALTY_GIFT_CARD"
WHEN when_execute_seed_contract module="LOYALTY_GIFT_CARD"
THEN then_seed_contract_should_hold module="LOYALTY_GIFT_CARD"
