[SCENARIO: BDD-LOYALTY_COUPON-SEED-loyalty_coupon_event_coupon_cancel_coupon_loyalty_coupon_cancelled] TITLE: LOYALTY_COUPON contract seed scenario TAGS: seed all
GIVEN given_seed_context id="loyalty_coupon_event_coupon_cancel_coupon_loyalty_coupon_cancelled" module="LOYALTY_COUPON"
WHEN when_execute_seed_contract module="LOYALTY_COUPON"
THEN then_seed_contract_should_hold module="LOYALTY_COUPON"
