[SCENARIO: BDD-LOYALTY_GIFT_CARD_TRANSACTION-SEED-loyalty_gift_card_transaction_workflow_gift_card_transaction_giftcard_transaction_flow] TITLE: LOYALTY_GIFT_CARD_TRANSACTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="loyalty_gift_card_transaction_workflow_gift_card_transaction_giftcard_transaction_flow" module="LOYALTY_GIFT_CARD_TRANSACTION"
WHEN when_execute_seed_contract module="LOYALTY_GIFT_CARD_TRANSACTION"
THEN then_seed_contract_should_hold module="LOYALTY_GIFT_CARD_TRANSACTION"
