[SCENARIO: BDD-LOYALTY_LOYALTY_TRANSACTION-SEED-loyalty_loyalty_transaction_workflow_loyalty_transaction_transaction_flow] TITLE: LOYALTY_LOYALTY_TRANSACTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="loyalty_loyalty_transaction_workflow_loyalty_transaction_transaction_flow" module="LOYALTY_LOYALTY_TRANSACTION"
WHEN when_execute_seed_contract module="LOYALTY_LOYALTY_TRANSACTION"
THEN then_seed_contract_should_hold module="LOYALTY_LOYALTY_TRANSACTION"
