[SCENARIO: BDD-LOYALTY_LOYALTY_RULE-SEED-loyalty_loyalty_rule_action_loyalty_rule_destroy_destroy] TITLE: LOYALTY_LOYALTY_RULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="loyalty_loyalty_rule_action_loyalty_rule_destroy_destroy" module="LOYALTY_LOYALTY_RULE"
WHEN when_execute_seed_contract module="LOYALTY_LOYALTY_RULE"
THEN then_seed_contract_should_hold module="LOYALTY_LOYALTY_RULE"
