[SCENARIO: BDD-LOYALTY_LOYALTY_PROGRAM-SEED-loyalty_loyalty_program_event_loyalty_program_activate_loyalty_program_activated] TITLE: LOYALTY_LOYALTY_PROGRAM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="loyalty_loyalty_program_event_loyalty_program_activate_loyalty_program_activated" module="LOYALTY_LOYALTY_PROGRAM"
WHEN when_execute_seed_contract module="LOYALTY_LOYALTY_PROGRAM"
THEN then_seed_contract_should_hold module="LOYALTY_LOYALTY_PROGRAM"
