[SCENARIO: BDD-LUNCH_LUNCH_ORDER-SEED-lunch_lunch_order_event_lunch_order_action_cancel_lunch_order_cancelled] TITLE: LUNCH_LUNCH_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="lunch_lunch_order_event_lunch_order_action_cancel_lunch_order_cancelled" module="LUNCH_LUNCH_ORDER"
WHEN when_execute_seed_contract module="LUNCH_LUNCH_ORDER"
THEN then_seed_contract_should_hold module="LUNCH_LUNCH_ORDER"
