[SCENARIO: BDD-LUNCH_LUNCH_TOPPING-SEED-lunch_lunch_topping_workflow_lunch_topping_topping_management] TITLE: LUNCH_LUNCH_TOPPING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="lunch_lunch_topping_workflow_lunch_topping_topping_management" module="LUNCH_LUNCH_TOPPING"
WHEN when_execute_seed_contract module="LUNCH_LUNCH_TOPPING"
THEN then_seed_contract_should_hold module="LUNCH_LUNCH_TOPPING"
