[SCENARIO: BDD-LUNCH_LUNCH_ORDER_TOPPING1_LINK-SEED-lunch_lunch_order_topping1_link_action_lunch_order_topping1_link_read_read] TITLE: LUNCH_LUNCH_ORDER_TOPPING1_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="lunch_lunch_order_topping1_link_action_lunch_order_topping1_link_read_read" module="LUNCH_LUNCH_ORDER_TOPPING1_LINK"
WHEN when_execute_seed_contract module="LUNCH_LUNCH_ORDER_TOPPING1_LINK"
THEN then_seed_contract_should_hold module="LUNCH_LUNCH_ORDER_TOPPING1_LINK"
