[SCENARIO: BDD-LUNCH_LUNCH_SUPPLIER-SEED-lunch_lunch_supplier_action_lunch_supplier_create_create] TITLE: LUNCH_LUNCH_SUPPLIER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="lunch_lunch_supplier_action_lunch_supplier_create_create" module="LUNCH_LUNCH_SUPPLIER"
WHEN when_execute_seed_contract module="LUNCH_LUNCH_SUPPLIER"
THEN then_seed_contract_should_hold module="LUNCH_LUNCH_SUPPLIER"
