[SCENARIO: BDD-LUNCH_LUNCH_CASH_MOVE-SEED-lunch_lunch_cash_move_action_lunch_cash_move_read_read] TITLE: LUNCH_LUNCH_CASH_MOVE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="lunch_lunch_cash_move_action_lunch_cash_move_read_read" module="LUNCH_LUNCH_CASH_MOVE"
WHEN when_execute_seed_contract module="LUNCH_LUNCH_CASH_MOVE"
THEN then_seed_contract_should_hold module="LUNCH_LUNCH_CASH_MOVE"
