[SCENARIO: BDD-MAINTENANCE_MAINTENANCE_SCHEDULE-SEED-maintenance_maintenance_schedule_action_maintenance_schedule_create_create] TITLE: MAINTENANCE_MAINTENANCE_SCHEDULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="maintenance_maintenance_schedule_action_maintenance_schedule_create_create" module="MAINTENANCE_MAINTENANCE_SCHEDULE"
WHEN when_execute_seed_contract module="MAINTENANCE_MAINTENANCE_SCHEDULE"
THEN then_seed_contract_should_hold module="MAINTENANCE_MAINTENANCE_SCHEDULE"
