[SCENARIO: BDD-MAINTENANCE_EQUIPMENT_CATEGORY-SEED-maintenance_equipment_category_action_equipment_category_read_read] TITLE: MAINTENANCE_EQUIPMENT_CATEGORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="maintenance_equipment_category_action_equipment_category_read_read" module="MAINTENANCE_EQUIPMENT_CATEGORY"
WHEN when_execute_seed_contract module="MAINTENANCE_EQUIPMENT_CATEGORY"
THEN then_seed_contract_should_hold module="MAINTENANCE_EQUIPMENT_CATEGORY"
