[SCENARIO: BDD-MAINTENANCE_SALES_ORDER-SEED-maintenance_sales_order_action_sales_order_read_read] TITLE: MAINTENANCE_SALES_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="maintenance_sales_order_action_sales_order_read_read" module="MAINTENANCE_SALES_ORDER"
WHEN when_execute_seed_contract module="MAINTENANCE_SALES_ORDER"
THEN then_seed_contract_should_hold module="MAINTENANCE_SALES_ORDER"
