[SCENARIO: BDD-MAINTENANCE_CONTRACT_SERVICE_ITEM_LINK-SEED-maintenance_contract_service_item_link_action_contract_service_item_link_read_read] TITLE: MAINTENANCE_CONTRACT_SERVICE_ITEM_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="maintenance_contract_service_item_link_action_contract_service_item_link_read_read" module="MAINTENANCE_CONTRACT_SERVICE_ITEM_LINK"
WHEN when_execute_seed_contract module="MAINTENANCE_CONTRACT_SERVICE_ITEM_LINK"
THEN then_seed_contract_should_hold module="MAINTENANCE_CONTRACT_SERVICE_ITEM_LINK"
