[SCENARIO: BDD-MAINTENANCE_VEHICLE_TAG_LINK-SEED-maintenance_vehicle_tag_link_action_vehicle_tag_link_read_read] TITLE: MAINTENANCE_VEHICLE_TAG_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="maintenance_vehicle_tag_link_action_vehicle_tag_link_read_read" module="MAINTENANCE_VEHICLE_TAG_LINK"
WHEN when_execute_seed_contract module="MAINTENANCE_VEHICLE_TAG_LINK"
THEN then_seed_contract_should_hold module="MAINTENANCE_VEHICLE_TAG_LINK"
