[SCENARIO: BDD-MAINTENANCE_STOCK_MOVE-SEED-maintenance_stock_move_action_stock_move_read_read] TITLE: MAINTENANCE_STOCK_MOVE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="maintenance_stock_move_action_stock_move_read_read" module="MAINTENANCE_STOCK_MOVE"
WHEN when_execute_seed_contract module="MAINTENANCE_STOCK_MOVE"
THEN then_seed_contract_should_hold module="MAINTENANCE_STOCK_MOVE"
