[SCENARIO: BDD-MAINTENANCE_ASSIGNMENT_LOG-SEED-maintenance_assignment_log_action_assignment_log_create_create] TITLE: MAINTENANCE_ASSIGNMENT_LOG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="maintenance_assignment_log_action_assignment_log_create_create" module="MAINTENANCE_ASSIGNMENT_LOG"
WHEN when_execute_seed_contract module="MAINTENANCE_ASSIGNMENT_LOG"
THEN then_seed_contract_should_hold module="MAINTENANCE_ASSIGNMENT_LOG"
