[SCENARIO: BDD-MANUFACTURING_WORKCENTER_PRODUCTIVITY-SEED-manufacturing_workcenter_productivity_workflow_workcenter_productivity_workcenter_productivity_tracking_flow] TITLE: MANUFACTURING_WORKCENTER_PRODUCTIVITY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="manufacturing_workcenter_productivity_workflow_workcenter_productivity_workcenter_productivity_tracking_flow" module="MANUFACTURING_WORKCENTER_PRODUCTIVITY"
WHEN when_execute_seed_contract module="MANUFACTURING_WORKCENTER_PRODUCTIVITY"
THEN then_seed_contract_should_hold module="MANUFACTURING_WORKCENTER_PRODUCTIVITY"
