[SCENARIO: BDD-MANUFACTURING_WORK_ORDER_DEPENDENCY_LINK-SEED-manufacturing_work_order_dependency_link_action_work_order_dependency_link_read_read] TITLE: MANUFACTURING_WORK_ORDER_DEPENDENCY_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="manufacturing_work_order_dependency_link_action_work_order_dependency_link_read_read" module="MANUFACTURING_WORK_ORDER_DEPENDENCY_LINK"
WHEN when_execute_seed_contract module="MANUFACTURING_WORK_ORDER_DEPENDENCY_LINK"
THEN then_seed_contract_should_hold module="MANUFACTURING_WORK_ORDER_DEPENDENCY_LINK"
