[SCENARIO: BDD-MANUFACTURING_MANUFACTURING_ORDER-SEED-manufacturing_manufacturing_order_action_manufacturing_order_mark_done_update] TITLE: MANUFACTURING_MANUFACTURING_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="manufacturing_manufacturing_order_action_manufacturing_order_mark_done_update" module="MANUFACTURING_MANUFACTURING_ORDER"
WHEN when_execute_seed_contract module="MANUFACTURING_MANUFACTURING_ORDER"
THEN then_seed_contract_should_hold module="MANUFACTURING_MANUFACTURING_ORDER"
