[SCENARIO: BDD-MANUFACTURING_WORKCENTER_PRODUCTIVITY-SEED-manufacturing_workcenter_productivity_action_workcenter_productivity_update_update] TITLE: MANUFACTURING_WORKCENTER_PRODUCTIVITY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="manufacturing_workcenter_productivity_action_workcenter_productivity_update_update" module="MANUFACTURING_WORKCENTER_PRODUCTIVITY"
WHEN when_execute_seed_contract module="MANUFACTURING_WORKCENTER_PRODUCTIVITY"
THEN then_seed_contract_should_hold module="MANUFACTURING_WORKCENTER_PRODUCTIVITY"
