[SCENARIO: BDD-MARKETING_AUTOMATION_PARTICIPANT-SEED-marketing_automation_participant_workflow_automation_participant_automation_participant_creation_flow] TITLE: MARKETING_AUTOMATION_PARTICIPANT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_automation_participant_workflow_automation_participant_automation_participant_creation_flow" module="MARKETING_AUTOMATION_PARTICIPANT"
WHEN when_execute_seed_contract module="MARKETING_AUTOMATION_PARTICIPANT"
THEN then_seed_contract_should_hold module="MARKETING_AUTOMATION_PARTICIPANT"
