[SCENARIO: BDD-MARKETING_UTM_MEDIUM-SEED-marketing_utm_medium_action_utm_medium_create_create] TITLE: MARKETING_UTM_MEDIUM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_utm_medium_action_utm_medium_create_create" module="MARKETING_UTM_MEDIUM"
WHEN when_execute_seed_contract module="MARKETING_UTM_MEDIUM"
THEN then_seed_contract_should_hold module="MARKETING_UTM_MEDIUM"
