[SCENARIO: BDD-MARKETING_EVENT_TICKET-SEED-marketing_event_ticket_workflow_event_ticket_event_ticket_maintain_flow] TITLE: MARKETING_EVENT_TICKET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="marketing_event_ticket_workflow_event_ticket_event_ticket_maintain_flow" module="MARKETING_EVENT_TICKET"
WHEN when_execute_seed_contract module="MARKETING_EVENT_TICKET"
THEN then_seed_contract_should_hold module="MARKETING_EVENT_TICKET"
