[SCENARIO: BDD-OFBIZ_MARKETING_SALES_OPPORTUNITY_HISTORY-SEED-ofbiz_marketing_sales_opportunity_history_action_sales_opportunity_history_update_update] TITLE: OFBIZ_MARKETING_SALES_OPPORTUNITY_HISTORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_sales_opportunity_history_action_sales_opportunity_history_update_update" module="OFBIZ_MARKETING_SALES_OPPORTUNITY_HISTORY"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SALES_OPPORTUNITY_HISTORY"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SALES_OPPORTUNITY_HISTORY"
