[SCENARIO: BDD-OFBIZ_MARKETING_SALES_OPPORTUNITY_STAGE-SEED-ofbiz_marketing_sales_opportunity_stage_action_sales_opportunity_stage_create_create] TITLE: OFBIZ_MARKETING_SALES_OPPORTUNITY_STAGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_sales_opportunity_stage_action_sales_opportunity_stage_create_create" module="OFBIZ_MARKETING_SALES_OPPORTUNITY_STAGE"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SALES_OPPORTUNITY_STAGE"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SALES_OPPORTUNITY_STAGE"
