[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT-SEED-ofbiz_work_effort_work_effort_action_work_effort_create_create] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_action_work_effort_create_create" module="OFBIZ_WORK_EFFORT_WORK_EFFORT"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT"
