[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_GROUP-SEED-ofbiz_product_product_store_group_action_product_store_group_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_GROUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_group_action_product_store_group_update_update" module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP"
