[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_WORLD_PAY-SEED-ofbiz_accounting_payment_gateway_world_pay_action_payment_gateway_world_pay_read_read] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_WORLD_PAY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_world_pay_action_payment_gateway_world_pay_read_read" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_WORLD_PAY"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_WORLD_PAY"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_WORLD_PAY"
