[SCENARIO: BDD-OFBIZ_PRODUCT_INVENTORY_ITEM_STATUS-SEED-ofbiz_product_inventory_item_status_action_inventory_item_status_destroy_destroy] TITLE: OFBIZ_PRODUCT_INVENTORY_ITEM_STATUS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_inventory_item_status_action_inventory_item_status_destroy_destroy" module="OFBIZ_PRODUCT_INVENTORY_ITEM_STATUS"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_INVENTORY_ITEM_STATUS"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_INVENTORY_ITEM_STATUS"
