[SCENARIO: BDD-OFBIZ_ORDER_QUOTE_ROLE-SEED-ofbiz_order_quote_role_action_quote_role_update_update] TITLE: OFBIZ_ORDER_QUOTE_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_quote_role_action_quote_role_update_update" module="OFBIZ_ORDER_QUOTE_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_QUOTE_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_QUOTE_ROLE"
