[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_PACKAGE-SEED-ofbiz_shipment_shipment_package_action_shipment_package_create_create] TITLE: OFBIZ_SHIPMENT_SHIPMENT_PACKAGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_package_action_shipment_package_create_create" module="OFBIZ_SHIPMENT_SHIPMENT_PACKAGE"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_PACKAGE"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_PACKAGE"
