[SCENARIO: BDD-OFBIZ_PRODUCT_INVENTORY_ITEM_VARIANCE-SEED-ofbiz_product_inventory_item_variance_action_inventory_item_variance_create_create] TITLE: OFBIZ_PRODUCT_INVENTORY_ITEM_VARIANCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_inventory_item_variance_action_inventory_item_variance_create_create" module="OFBIZ_PRODUCT_INVENTORY_ITEM_VARIANCE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_INVENTORY_ITEM_VARIANCE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_INVENTORY_ITEM_VARIANCE"
