[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_POSITION_CLASS_TYPE-SEED-ofbiz_human_res_empl_position_class_type_action_empl_position_class_type_destroy_destroy] TITLE: OFBIZ_HUMAN_RES_EMPL_POSITION_CLASS_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_position_class_type_action_empl_position_class_type_destroy_destroy" module="OFBIZ_HUMAN_RES_EMPL_POSITION_CLASS_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_POSITION_CLASS_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_POSITION_CLASS_TYPE"
