[SCENARIO: BDD-OFBIZ_PARTY_FTP_ADDRESS-SEED-ofbiz_party_ftp_address_action_ftp_address_update_update] TITLE: OFBIZ_PARTY_FTP_ADDRESS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_ftp_address_action_ftp_address_update_update" module="OFBIZ_PARTY_FTP_ADDRESS"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_FTP_ADDRESS"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_FTP_ADDRESS"
