[SCENARIO: BDD-OFBIZ_ORDER_QUOTE_ATTRIBUTE-SEED-ofbiz_order_quote_attribute_action_quote_attribute_update_update] TITLE: OFBIZ_ORDER_QUOTE_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_quote_attribute_action_quote_attribute_update_update" module="OFBIZ_ORDER_QUOTE_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_QUOTE_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_QUOTE_ATTRIBUTE"
