[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_GEO-SEED-ofbiz_product_product_geo_action_product_geo_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_GEO contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_geo_action_product_geo_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_GEO"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_GEO"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_GEO"
