[SCENARIO: BDD-OFBIZ_PRODUCT_QUANTITY_BREAK_TYPE-SEED-ofbiz_product_quantity_break_type_action_quantity_break_type_create_create] TITLE: OFBIZ_PRODUCT_QUANTITY_BREAK_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_quantity_break_type_action_quantity_break_type_create_create" module="OFBIZ_PRODUCT_QUANTITY_BREAK_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_QUANTITY_BREAK_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_QUANTITY_BREAK_TYPE"
