[SCENARIO: BDD-OFBIZ_ACCOUNTING_ACCTG_TRANS_ATTRIBUTE-SEED-ofbiz_accounting_acctg_trans_attribute_action_acctg_trans_attribute_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_ACCTG_TRANS_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_acctg_trans_attribute_action_acctg_trans_attribute_destroy_destroy" module="OFBIZ_ACCOUNTING_ACCTG_TRANS_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_ACCTG_TRANS_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_ACCTG_TRANS_ATTRIBUTE"
