[SCENARIO: BDD-OFBIZ_HUMAN_RES_PERFORMANCE_NOTE-SEED-ofbiz_human_res_performance_note_action_performance_note_destroy_destroy] TITLE: OFBIZ_HUMAN_RES_PERFORMANCE_NOTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_performance_note_action_performance_note_destroy_destroy" module="OFBIZ_HUMAN_RES_PERFORMANCE_NOTE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_PERFORMANCE_NOTE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_PERFORMANCE_NOTE"
