[SCENARIO: BDD-OFBIZ_MANUFACTURING_MRP_EVENT_TYPE-SEED-ofbiz_manufacturing_mrp_event_type_action_mrp_event_type_read_read] TITLE: OFBIZ_MANUFACTURING_MRP_EVENT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_manufacturing_mrp_event_type_action_mrp_event_type_read_read" module="OFBIZ_MANUFACTURING_MRP_EVENT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_MANUFACTURING_MRP_EVENT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_MANUFACTURING_MRP_EVENT_TYPE"
