[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY_APPL-SEED-ofbiz_product_product_feature_category_appl_action_product_feature_category_appl_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY_APPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_feature_category_appl_action_product_feature_category_appl_read_read" module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY_APPL"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY_APPL"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY_APPL"
