[SCENARIO: BDD-OFBIZ_ORDER_QUOTE_TYPE-SEED-ofbiz_order_quote_type_action_quote_type_read_read] TITLE: OFBIZ_ORDER_QUOTE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_quote_type_action_quote_type_read_read" module="OFBIZ_ORDER_QUOTE_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_QUOTE_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_QUOTE_TYPE"
