[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_BILLING-SEED-ofbiz_work_effort_work_effort_billing_action_work_effort_billing_read_read] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_BILLING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_billing_action_work_effort_billing_read_read" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_BILLING"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_BILLING"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_BILLING"
