[SCENARIO: BDD-OFBIZ_CONTENT_DATA_RESOURCE_META_DATA-SEED-ofbiz_content_data_resource_meta_data_action_data_resource_meta_data_read_read] TITLE: OFBIZ_CONTENT_DATA_RESOURCE_META_DATA contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_data_resource_meta_data_action_data_resource_meta_data_read_read" module="OFBIZ_CONTENT_DATA_RESOURCE_META_DATA"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_DATA_RESOURCE_META_DATA"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_DATA_RESOURCE_META_DATA"
