[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PRICE_PURPOSE-SEED-ofbiz_product_product_price_purpose_action_product_price_purpose_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_PRICE_PURPOSE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_price_purpose_action_product_price_purpose_create_create" module="OFBIZ_PRODUCT_PRODUCT_PRICE_PURPOSE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PRICE_PURPOSE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PRICE_PURPOSE"
