[SCENARIO: BDD-OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP-SEED-ofbiz_accounting_gl_account_group_action_gl_account_group_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_gl_account_group_action_gl_account_group_destroy_destroy" module="OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP"
