[SCENARIO: BDD-OFBIZ_PRODUCT_FACILITY_CONTACT_MECH_PURPOSE-SEED-ofbiz_product_facility_contact_mech_purpose_action_facility_contact_mech_purpose_read_read] TITLE: OFBIZ_PRODUCT_FACILITY_CONTACT_MECH_PURPOSE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_facility_contact_mech_purpose_action_facility_contact_mech_purpose_read_read" module="OFBIZ_PRODUCT_FACILITY_CONTACT_MECH_PURPOSE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_FACILITY_CONTACT_MECH_PURPOSE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_FACILITY_CONTACT_MECH_PURPOSE"
