[SCENARIO: BDD-OFBIZ_PRODUCT_CONTAINER_TYPE-SEED-ofbiz_product_container_type_action_container_type_create_create] TITLE: OFBIZ_PRODUCT_CONTAINER_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_container_type_action_container_type_create_create" module="OFBIZ_PRODUCT_CONTAINER_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_CONTAINER_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_CONTAINER_TYPE"
