[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_ITEM-SEED-ofbiz_party_agreement_item_action_agreement_item_update_update] TITLE: OFBIZ_PARTY_AGREEMENT_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_item_action_agreement_item_update_update" module="OFBIZ_PARTY_AGREEMENT_ITEM"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_ITEM"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_ITEM"
