[SCENARIO: BDD-OFBIZ_COMMON_COUNTRY_CODE-SEED-ofbiz_common_country_code_action_country_code_destroy_destroy] TITLE: OFBIZ_COMMON_COUNTRY_CODE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_country_code_action_country_code_destroy_destroy" module="OFBIZ_COMMON_COUNTRY_CODE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_COUNTRY_CODE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_COUNTRY_CODE"
