[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PROMO_PRODUCT-SEED-ofbiz_product_product_promo_product_action_product_promo_product_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_PROMO_PRODUCT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_promo_product_action_product_promo_product_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_PROMO_PRODUCT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PROMO_PRODUCT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PROMO_PRODUCT"
