[SCENARIO: BDD-OFBIZ_CONTENT_CONTENT_APPROVAL-SEED-ofbiz_content_content_approval_action_content_approval_read_read] TITLE: OFBIZ_CONTENT_CONTENT_APPROVAL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_content_approval_action_content_approval_read_read" module="OFBIZ_CONTENT_CONTENT_APPROVAL"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_CONTENT_APPROVAL"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_CONTENT_APPROVAL"
