[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLLUP-SEED-ofbiz_product_product_store_group_rollup_action_product_store_group_rollup_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLLUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_group_rollup_action_product_store_group_rollup_read_read" module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLLUP"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLLUP"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLLUP"
