[SCENARIO: BDD-OFBIZ_WORK_EFFORT_DELIVERABLE_TYPE-SEED-ofbiz_work_effort_deliverable_type_action_deliverable_type_create_create] TITLE: OFBIZ_WORK_EFFORT_DELIVERABLE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_deliverable_type_action_deliverable_type_create_create" module="OFBIZ_WORK_EFFORT_DELIVERABLE_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_DELIVERABLE_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_DELIVERABLE_TYPE"
