[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_GROUP_ORDER-SEED-ofbiz_product_product_group_order_action_product_group_order_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_GROUP_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_group_order_action_product_group_order_read_read" module="OFBIZ_PRODUCT_PRODUCT_GROUP_ORDER"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_GROUP_ORDER"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_GROUP_ORDER"
