[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_FACILITY-SEED-ofbiz_product_product_store_facility_action_product_store_facility_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_FACILITY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_facility_action_product_store_facility_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_STORE_FACILITY"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_FACILITY"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_FACILITY"
