[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_ITEM-SEED-ofbiz_shipment_shipment_item_action_shipment_item_read_read] TITLE: OFBIZ_SHIPMENT_SHIPMENT_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_item_action_shipment_item_read_read" module="OFBIZ_SHIPMENT_SHIPMENT_ITEM"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_ITEM"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_ITEM"
