[SCENARIO: BDD-OFBIZ_HUMAN_RES_PERSON_TRAINING-SEED-ofbiz_human_res_person_training_action_person_training_update_update] TITLE: OFBIZ_HUMAN_RES_PERSON_TRAINING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_person_training_action_person_training_update_update" module="OFBIZ_HUMAN_RES_PERSON_TRAINING"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_PERSON_TRAINING"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_PERSON_TRAINING"
