[SCENARIO: BDD-OFBIZ_PRODUCT_PROD_CONF_ITEM_CONTENT_TYPE-SEED-ofbiz_product_prod_conf_item_content_type_action_prod_conf_item_content_type_create_create] TITLE: OFBIZ_PRODUCT_PROD_CONF_ITEM_CONTENT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_prod_conf_item_content_type_action_prod_conf_item_content_type_create_create" module="OFBIZ_PRODUCT_PROD_CONF_ITEM_CONTENT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PROD_CONF_ITEM_CONTENT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PROD_CONF_ITEM_CONTENT_TYPE"
