[SCENARIO: BDD-OFBIZ_ACCOUNTING_GL_ACCOUNT_TYPE_DEFAULT-SEED-ofbiz_accounting_gl_account_type_default_action_gl_account_type_default_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_GL_ACCOUNT_TYPE_DEFAULT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_gl_account_type_default_action_gl_account_type_default_destroy_destroy" module="OFBIZ_ACCOUNTING_GL_ACCOUNT_TYPE_DEFAULT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_GL_ACCOUNT_TYPE_DEFAULT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_GL_ACCOUNT_TYPE_DEFAULT"
