[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT-SEED-ofbiz_party_agreement_action_agreement_destroy_destroy] TITLE: OFBIZ_PARTY_AGREEMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_action_agreement_destroy_destroy" module="OFBIZ_PARTY_AGREEMENT"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT"
