[SCENARIO: BDD-OFBIZ_ACCOUNTING_PARTY_FIXED_ASSET_ASSIGNMENT-SEED-ofbiz_accounting_party_fixed_asset_assignment_action_party_fixed_asset_assignment_create_create] TITLE: OFBIZ_ACCOUNTING_PARTY_FIXED_ASSET_ASSIGNMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_party_fixed_asset_assignment_action_party_fixed_asset_assignment_create_create" module="OFBIZ_ACCOUNTING_PARTY_FIXED_ASSET_ASSIGNMENT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PARTY_FIXED_ASSET_ASSIGNMENT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PARTY_FIXED_ASSET_ASSIGNMENT"
