[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_RATE-SEED-ofbiz_human_res_empl_position_type_rate_action_empl_position_type_rate_update_update] TITLE: OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_RATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_position_type_rate_action_empl_position_type_rate_update_update" module="OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_RATE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_RATE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_RATE"
