[SCENARIO: BDD-OFBIZ_PRODUCT_INVENTORY_ITEM-SEED-ofbiz_product_inventory_item_action_inventory_item_read_read] TITLE: OFBIZ_PRODUCT_INVENTORY_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_inventory_item_action_inventory_item_read_read" module="OFBIZ_PRODUCT_INVENTORY_ITEM"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_INVENTORY_ITEM"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_INVENTORY_ITEM"
