[SCENARIO: BDD-OFBIZ_ORDER_CUST_REQUEST_ATTRIBUTE-SEED-ofbiz_order_cust_request_attribute_action_cust_request_attribute_update_update] TITLE: OFBIZ_ORDER_CUST_REQUEST_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_cust_request_attribute_action_cust_request_attribute_update_update" module="OFBIZ_ORDER_CUST_REQUEST_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_CUST_REQUEST_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_CUST_REQUEST_ATTRIBUTE"
