[SCENARIO: BDD-OFBIZ_PRODUCT_VENDOR_PRODUCT-SEED-ofbiz_product_vendor_product_action_vendor_product_read_read] TITLE: OFBIZ_PRODUCT_VENDOR_PRODUCT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_vendor_product_action_vendor_product_read_read" module="OFBIZ_PRODUCT_VENDOR_PRODUCT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_VENDOR_PRODUCT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_VENDOR_PRODUCT"
