[SCENARIO: BDD-OFBIZ_PARTY_PARTY_CLASSIFICATION_GROUP-SEED-ofbiz_party_party_classification_group_action_party_classification_group_update_update] TITLE: OFBIZ_PARTY_PARTY_CLASSIFICATION_GROUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_classification_group_action_party_classification_group_update_update" module="OFBIZ_PARTY_PARTY_CLASSIFICATION_GROUP"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_CLASSIFICATION_GROUP"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_CLASSIFICATION_GROUP"
