[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PRICE_ACTION-SEED-ofbiz_product_product_price_action_action_product_price_action_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_PRICE_ACTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_price_action_action_product_price_action_update_update" module="OFBIZ_PRODUCT_PRODUCT_PRICE_ACTION"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PRICE_ACTION"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PRICE_ACTION"
