[SCENARIO: BDD-OFBIZ_PARTY_CONTACT_MECH_PURPOSE_TYPE-SEED-ofbiz_party_contact_mech_purpose_type_action_contact_mech_purpose_type_create_create] TITLE: OFBIZ_PARTY_CONTACT_MECH_PURPOSE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_contact_mech_purpose_type_action_contact_mech_purpose_type_create_create" module="OFBIZ_PARTY_CONTACT_MECH_PURPOSE_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_CONTACT_MECH_PURPOSE_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_CONTACT_MECH_PURPOSE_TYPE"
