[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ITEM_ROLE-SEED-ofbiz_order_order_item_role_action_order_item_role_update_update] TITLE: OFBIZ_ORDER_ORDER_ITEM_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_item_role_action_order_item_role_update_update" module="OFBIZ_ORDER_ORDER_ITEM_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ITEM_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ITEM_ROLE"
