[SCENARIO: BDD-OFBIZ_ORDER_RETURN_ADJUSTMENT_TYPE-SEED-ofbiz_order_return_adjustment_type_action_return_adjustment_type_read_read] TITLE: OFBIZ_ORDER_RETURN_ADJUSTMENT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_return_adjustment_type_action_return_adjustment_type_read_read" module="OFBIZ_ORDER_RETURN_ADJUSTMENT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_RETURN_ADJUSTMENT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_RETURN_ADJUSTMENT_TYPE"
