[SCENARIO: BDD-OFBIZ_CONTENT_SURVEY_QUESTION_APPL-SEED-ofbiz_content_survey_question_appl_action_survey_question_appl_read_read] TITLE: OFBIZ_CONTENT_SURVEY_QUESTION_APPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_survey_question_appl_action_survey_question_appl_read_read" module="OFBIZ_CONTENT_SURVEY_QUESTION_APPL"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_SURVEY_QUESTION_APPL"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_SURVEY_QUESTION_APPL"
