[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLE-SEED-ofbiz_product_product_store_group_role_action_product_store_group_role_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_group_role_action_product_store_group_role_create_create" module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_GROUP_ROLE"
