[SCENARIO: BDD-OFBIZ_COMMON_VISUAL_THEME-SEED-ofbiz_common_visual_theme_action_visual_theme_read_read] TITLE: OFBIZ_COMMON_VISUAL_THEME contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_visual_theme_action_visual_theme_read_read" module="OFBIZ_COMMON_VISUAL_THEME"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_VISUAL_THEME"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_VISUAL_THEME"
