[SCENARIO: BDD-OFBIZ_ORDER_REQUIREMENT_ROLE-SEED-ofbiz_order_requirement_role_action_requirement_role_read_read] TITLE: OFBIZ_ORDER_REQUIREMENT_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_requirement_role_action_requirement_role_read_read" module="OFBIZ_ORDER_REQUIREMENT_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_REQUIREMENT_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_REQUIREMENT_ROLE"
