[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_PACKAGE_CONTENT-SEED-ofbiz_shipment_shipment_package_content_action_shipment_package_content_read_read] TITLE: OFBIZ_SHIPMENT_SHIPMENT_PACKAGE_CONTENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_package_content_action_shipment_package_content_read_read" module="OFBIZ_SHIPMENT_SHIPMENT_PACKAGE_CONTENT"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_PACKAGE_CONTENT"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_PACKAGE_CONTENT"
