[SCENARIO: BDD-OFBIZ_HUMAN_RES_PARTY_QUAL-SEED-ofbiz_human_res_party_qual_action_party_qual_update_update] TITLE: OFBIZ_HUMAN_RES_PARTY_QUAL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_party_qual_action_party_qual_update_update" module="OFBIZ_HUMAN_RES_PARTY_QUAL"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_PARTY_QUAL"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_PARTY_QUAL"
