[SCENARIO: BDD-OFBIZ_COMMON_PORTAL_PAGE-SEED-ofbiz_common_portal_page_action_portal_page_update_update] TITLE: OFBIZ_COMMON_PORTAL_PAGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_portal_page_action_portal_page_update_update" module="OFBIZ_COMMON_PORTAL_PAGE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_PORTAL_PAGE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_PORTAL_PAGE"
