[SCENARIO: BDD-OFBIZ_PARTY_COMMUNICATION_EVENT_ROLE-SEED-ofbiz_party_communication_event_role_action_communication_event_role_update_update] TITLE: OFBIZ_PARTY_COMMUNICATION_EVENT_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_communication_event_role_action_communication_event_role_update_update" module="OFBIZ_PARTY_COMMUNICATION_EVENT_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_COMMUNICATION_EVENT_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_COMMUNICATION_EVENT_ROLE"
