[SCENARIO: BDD-OFBIZ_PARTY_MARITAL_STATUS-SEED-ofbiz_party_marital_status_action_marital_status_read_read] TITLE: OFBIZ_PARTY_MARITAL_STATUS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_marital_status_action_marital_status_read_read" module="OFBIZ_PARTY_MARITAL_STATUS"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_MARITAL_STATUS"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_MARITAL_STATUS"
