[SCENARIO: BDD-OFBIZ_PARTY_PARTY_GEO_POINT-SEED-ofbiz_party_party_geo_point_action_party_geo_point_update_update] TITLE: OFBIZ_PARTY_PARTY_GEO_POINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_geo_point_action_party_geo_point_update_update" module="OFBIZ_PARTY_PARTY_GEO_POINT"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_GEO_POINT"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_GEO_POINT"
