[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_ASSOC_TYPE-SEED-ofbiz_work_effort_work_effort_assoc_type_action_work_effort_assoc_type_update_update] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_ASSOC_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_assoc_type_action_work_effort_assoc_type_update_update" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_ASSOC_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_ASSOC_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_ASSOC_TYPE"
