[SCENARIO: BDD-OFBIZ_MARKETING_SALES_OPPORTUNITY_TRCK_CODE-SEED-ofbiz_marketing_sales_opportunity_trck_code_action_sales_opportunity_trck_code_update_update] TITLE: OFBIZ_MARKETING_SALES_OPPORTUNITY_TRCK_CODE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_sales_opportunity_trck_code_action_sales_opportunity_trck_code_update_update" module="OFBIZ_MARKETING_SALES_OPPORTUNITY_TRCK_CODE"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SALES_OPPORTUNITY_TRCK_CODE"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SALES_OPPORTUNITY_TRCK_CODE"
