[SCENARIO: BDD-OFBIZ_ACCOUNTING_GIFT_CARD_FULFILLMENT-SEED-ofbiz_accounting_gift_card_fulfillment_action_gift_card_fulfillment_read_read] TITLE: OFBIZ_ACCOUNTING_GIFT_CARD_FULFILLMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_gift_card_fulfillment_action_gift_card_fulfillment_read_read" module="OFBIZ_ACCOUNTING_GIFT_CARD_FULFILLMENT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_GIFT_CARD_FULFILLMENT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_GIFT_CARD_FULFILLMENT"
