[SCENARIO: BDD-OFBIZ_COMMON_DATA_SOURCE_TYPE-SEED-ofbiz_common_data_source_type_action_data_source_type_create_create] TITLE: OFBIZ_COMMON_DATA_SOURCE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_data_source_type_action_data_source_type_create_create" module="OFBIZ_COMMON_DATA_SOURCE_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_DATA_SOURCE_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_DATA_SOURCE_TYPE"
