[SCENARIO: BDD-OFBIZ_ORDER_ALLOCATION_PLAN_ITEM-SEED-ofbiz_order_allocation_plan_item_action_allocation_plan_item_read_read] TITLE: OFBIZ_ORDER_ALLOCATION_PLAN_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_allocation_plan_item_action_allocation_plan_item_read_read" module="OFBIZ_ORDER_ALLOCATION_PLAN_ITEM"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ALLOCATION_PLAN_ITEM"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ALLOCATION_PLAN_ITEM"
