[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_GEOGRAPHICAL_APPLIC-SEED-ofbiz_party_agreement_geographical_applic_action_agreement_geographical_applic_read_read] TITLE: OFBIZ_PARTY_AGREEMENT_GEOGRAPHICAL_APPLIC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_geographical_applic_action_agreement_geographical_applic_read_read" module="OFBIZ_PARTY_AGREEMENT_GEOGRAPHICAL_APPLIC"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_GEOGRAPHICAL_APPLIC"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_GEOGRAPHICAL_APPLIC"
