[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_EMAIL_SETTING-SEED-ofbiz_product_product_store_email_setting_action_product_store_email_setting_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_EMAIL_SETTING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_email_setting_action_product_store_email_setting_create_create" module="OFBIZ_PRODUCT_PRODUCT_STORE_EMAIL_SETTING"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_EMAIL_SETTING"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_EMAIL_SETTING"
