[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PRICE_AUTO_NOTICE-SEED-ofbiz_product_product_price_auto_notice_action_product_price_auto_notice_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_PRICE_AUTO_NOTICE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_price_auto_notice_action_product_price_auto_notice_create_create" module="OFBIZ_PRODUCT_PRODUCT_PRICE_AUTO_NOTICE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PRICE_AUTO_NOTICE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PRICE_AUTO_NOTICE"
