[SCENARIO: BDD-OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_APPL-SEED-ofbiz_product_inventory_item_label_appl_action_inventory_item_label_appl_update_update] TITLE: OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_APPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_inventory_item_label_appl_action_inventory_item_label_appl_update_update" module="OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_APPL"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_APPL"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_APPL"
