[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIN_ACCOUNT_TYPE_GL_ACCOUNT-SEED-ofbiz_accounting_fin_account_type_gl_account_action_fin_account_type_gl_account_create_create] TITLE: OFBIZ_ACCOUNTING_FIN_ACCOUNT_TYPE_GL_ACCOUNT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fin_account_type_gl_account_action_fin_account_type_gl_account_create_create" module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TYPE_GL_ACCOUNT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TYPE_GL_ACCOUNT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TYPE_GL_ACCOUNT"
