[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ITEM_SHIP_GRP_INV_RES-SEED-ofbiz_order_order_item_ship_grp_inv_res_action_order_item_ship_grp_inv_res_create_create] TITLE: OFBIZ_ORDER_ORDER_ITEM_SHIP_GRP_INV_RES contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_item_ship_grp_inv_res_action_order_item_ship_grp_inv_res_create_create" module="OFBIZ_ORDER_ORDER_ITEM_SHIP_GRP_INV_RES"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ITEM_SHIP_GRP_INV_RES"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ITEM_SHIP_GRP_INV_RES"
