[SCENARIO: BDD-OFBIZ_ORDER_ORDER_DENYLIST_TYPE-SEED-ofbiz_order_order_denylist_type_action_order_denylist_type_destroy_destroy] TITLE: OFBIZ_ORDER_ORDER_DENYLIST_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_denylist_type_action_order_denylist_type_destroy_destroy" module="OFBIZ_ORDER_ORDER_DENYLIST_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_DENYLIST_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_DENYLIST_TYPE"
