[SCENARIO: BDD-OFBIZ_PRODUCT_PROD_PROMO_CODE_CONTACT_MECH-SEED-ofbiz_product_prod_promo_code_contact_mech_action_prod_promo_code_contact_mech_destroy_destroy] TITLE: OFBIZ_PRODUCT_PROD_PROMO_CODE_CONTACT_MECH contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_prod_promo_code_contact_mech_action_prod_promo_code_contact_mech_destroy_destroy" module="OFBIZ_PRODUCT_PROD_PROMO_CODE_CONTACT_MECH"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PROD_PROMO_CODE_CONTACT_MECH"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PROD_PROMO_CODE_CONTACT_MECH"
