[SCENARIO: BDD-OFBIZ_CONTENT_CONTENT_SEARCH_CONSTRAINT-SEED-ofbiz_content_content_search_constraint_action_content_search_constraint_update_update] TITLE: OFBIZ_CONTENT_CONTENT_SEARCH_CONSTRAINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_content_search_constraint_action_content_search_constraint_update_update" module="OFBIZ_CONTENT_CONTENT_SEARCH_CONSTRAINT"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_CONTENT_SEARCH_CONSTRAINT"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_CONTENT_SEARCH_CONSTRAINT"
