[SCENARIO: BDD-OFBIZ_ACCOUNTING_SETTLEMENT_TERM-SEED-ofbiz_accounting_settlement_term_action_settlement_term_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_SETTLEMENT_TERM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_settlement_term_action_settlement_term_destroy_destroy" module="OFBIZ_ACCOUNTING_SETTLEMENT_TERM"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_SETTLEMENT_TERM"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_SETTLEMENT_TERM"
