[SCENARIO: BDD-OFBIZ_ACCOUNTING_ZIP_SALES_RULE_LOOKUP-SEED-ofbiz_accounting_zip_sales_rule_lookup_action_zip_sales_rule_lookup_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_ZIP_SALES_RULE_LOOKUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_zip_sales_rule_lookup_action_zip_sales_rule_lookup_destroy_destroy" module="OFBIZ_ACCOUNTING_ZIP_SALES_RULE_LOOKUP"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_ZIP_SALES_RULE_LOOKUP"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_ZIP_SALES_RULE_LOOKUP"
