[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_TYPE-SEED-ofbiz_party_agreement_type_action_agreement_type_destroy_destroy] TITLE: OFBIZ_PARTY_AGREEMENT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_type_action_agreement_type_destroy_destroy" module="OFBIZ_PARTY_AGREEMENT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_TYPE"
