[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_SHIPMENT-SEED-ofbiz_product_product_store_vendor_shipment_action_product_store_vendor_shipment_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_SHIPMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_vendor_shipment_action_product_store_vendor_shipment_read_read" module="OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_SHIPMENT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_SHIPMENT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_SHIPMENT"
