[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_CATALOG-SEED-ofbiz_product_product_store_catalog_action_product_store_catalog_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_CATALOG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_catalog_action_product_store_catalog_read_read" module="OFBIZ_PRODUCT_PRODUCT_STORE_CATALOG"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_CATALOG"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_CATALOG"
