[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CATEGORY_MEMBER-SEED-ofbiz_product_product_category_member_action_product_category_member_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_CATEGORY_MEMBER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_category_member_action_product_category_member_read_read" module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_MEMBER"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_MEMBER"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_MEMBER"
