[SCENARIO: BDD-OFBIZ_COMMON_STATUS_ITEM-SEED-ofbiz_common_status_item_action_status_item_update_update] TITLE: OFBIZ_COMMON_STATUS_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_status_item_action_status_item_update_update" module="OFBIZ_COMMON_STATUS_ITEM"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_STATUS_ITEM"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_STATUS_ITEM"
