[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE_GL_ACCOUNT-SEED-ofbiz_accounting_payment_method_type_gl_account_action_payment_method_type_gl_account_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE_GL_ACCOUNT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_method_type_gl_account_action_payment_method_type_gl_account_destroy_destroy" module="OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE_GL_ACCOUNT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE_GL_ACCOUNT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE_GL_ACCOUNT"
