[SCENARIO: BDD-OFBIZ_MARKETING_MARKETING_CAMPAIGN_PRICE-SEED-ofbiz_marketing_marketing_campaign_price_action_marketing_campaign_price_create_create] TITLE: OFBIZ_MARKETING_MARKETING_CAMPAIGN_PRICE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_marketing_campaign_price_action_marketing_campaign_price_create_create" module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_PRICE"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_PRICE"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_PRICE"
