[SCENARIO: BDD-OFBIZ_PRODUCT_INVENTORY_TRANSFER-SEED-ofbiz_product_inventory_transfer_action_inventory_transfer_create_create] TITLE: OFBIZ_PRODUCT_INVENTORY_TRANSFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_inventory_transfer_action_inventory_transfer_create_create" module="OFBIZ_PRODUCT_INVENTORY_TRANSFER"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_INVENTORY_TRANSFER"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_INVENTORY_TRANSFER"
