[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_FEDEX-SEED-ofbiz_shipment_shipment_gateway_fedex_action_shipment_gateway_fedex_destroy_destroy] TITLE: OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_FEDEX contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_gateway_fedex_action_shipment_gateway_fedex_destroy_destroy" module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_FEDEX"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_FEDEX"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_FEDEX"
