[SCENARIO: BDD-OFBIZ_WORK_EFFORT_DELIVERABLE-SEED-ofbiz_work_effort_deliverable_action_deliverable_read_read] TITLE: OFBIZ_WORK_EFFORT_DELIVERABLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_deliverable_action_deliverable_read_read" module="OFBIZ_WORK_EFFORT_DELIVERABLE"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_DELIVERABLE"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_DELIVERABLE"
