[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PROMO-SEED-ofbiz_product_product_promo_action_product_promo_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_PROMO contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_promo_action_product_promo_update_update" module="OFBIZ_PRODUCT_PRODUCT_PROMO"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PROMO"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PROMO"
