[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ITEM_PRICE_INFO-SEED-ofbiz_order_order_item_price_info_action_order_item_price_info_destroy_destroy] TITLE: OFBIZ_ORDER_ORDER_ITEM_PRICE_INFO contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_item_price_info_action_order_item_price_info_destroy_destroy" module="OFBIZ_ORDER_ORDER_ITEM_PRICE_INFO"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ITEM_PRICE_INFO"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ITEM_PRICE_INFO"
