[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_CONTACT_MECH-SEED-ofbiz_work_effort_work_effort_contact_mech_action_work_effort_contact_mech_update_update] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_CONTACT_MECH contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_contact_mech_action_work_effort_contact_mech_update_update" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_CONTACT_MECH"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_CONTACT_MECH"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_CONTACT_MECH"
