[SCENARIO: BDD-OFBIZ_MARKETING_SEGMENT_GROUP-SEED-ofbiz_marketing_segment_group_action_segment_group_read_read] TITLE: OFBIZ_MARKETING_SEGMENT_GROUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_segment_group_action_segment_group_read_read" module="OFBIZ_MARKETING_SEGMENT_GROUP"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SEGMENT_GROUP"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SEGMENT_GROUP"
