[SCENARIO: BDD-OFBIZ_COMMON_STATUS_TYPE-SEED-ofbiz_common_status_type_action_status_type_update_update] TITLE: OFBIZ_COMMON_STATUS_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_status_type_action_status_type_update_update" module="OFBIZ_COMMON_STATUS_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_STATUS_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_STATUS_TYPE"
