[SCENARIO: BDD-OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR-SEED-ofbiz_manufacturing_tech_data_calendar_action_tech_data_calendar_read_read] TITLE: OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_manufacturing_tech_data_calendar_action_tech_data_calendar_read_read" module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR"
WHEN when_execute_seed_contract module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR"
THEN then_seed_contract_should_hold module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR"
