[SCENARIO: BDD-OFBIZ_ACCOUNTING_BUDGET_ITEM_TYPE_ATTR-SEED-ofbiz_accounting_budget_item_type_attr_action_budget_item_type_attr_read_read] TITLE: OFBIZ_ACCOUNTING_BUDGET_ITEM_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_budget_item_type_attr_action_budget_item_type_attr_read_read" module="OFBIZ_ACCOUNTING_BUDGET_ITEM_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_BUDGET_ITEM_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_BUDGET_ITEM_TYPE_ATTR"
