[SCENARIO: BDD-OFBIZ_COMMON_VISUAL_THEME_SET-SEED-ofbiz_common_visual_theme_set_action_visual_theme_set_read_read] TITLE: OFBIZ_COMMON_VISUAL_THEME_SET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_visual_theme_set_action_visual_theme_set_read_read" module="OFBIZ_COMMON_VISUAL_THEME_SET"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_VISUAL_THEME_SET"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_VISUAL_THEME_SET"
