[SCENARIO: BDD-OFBIZ_PRODUCT_OLD_PRODUCT_PROMO_CODE_EMAIL-SEED-ofbiz_product_old_product_promo_code_email_action_old_product_promo_code_email_create_create] TITLE: OFBIZ_PRODUCT_OLD_PRODUCT_PROMO_CODE_EMAIL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_old_product_promo_code_email_action_old_product_promo_code_email_create_create" module="OFBIZ_PRODUCT_OLD_PRODUCT_PROMO_CODE_EMAIL"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_OLD_PRODUCT_PROMO_CODE_EMAIL"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_OLD_PRODUCT_PROMO_CODE_EMAIL"
