[SCENARIO: BDD-OFBIZ_COMMON_GEO_POINT-SEED-ofbiz_common_geo_point_action_geo_point_update_update] TITLE: OFBIZ_COMMON_GEO_POINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_geo_point_action_geo_point_update_update" module="OFBIZ_COMMON_GEO_POINT"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_GEO_POINT"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_GEO_POINT"
