[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ITEM_CONTACT_MECH-SEED-ofbiz_order_order_item_contact_mech_action_order_item_contact_mech_destroy_destroy] TITLE: OFBIZ_ORDER_ORDER_ITEM_CONTACT_MECH contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_item_contact_mech_action_order_item_contact_mech_destroy_destroy" module="OFBIZ_ORDER_ORDER_ITEM_CONTACT_MECH"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ITEM_CONTACT_MECH"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ITEM_CONTACT_MECH"
