[SCENARIO: BDD-OFBIZ_PRODUCT_CONFIG_OPTION_PRODUCT_OPTION-SEED-ofbiz_product_config_option_product_option_action_config_option_product_option_destroy_destroy] TITLE: OFBIZ_PRODUCT_CONFIG_OPTION_PRODUCT_OPTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_config_option_product_option_action_config_option_product_option_destroy_destroy" module="OFBIZ_PRODUCT_CONFIG_OPTION_PRODUCT_OPTION"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_CONFIG_OPTION_PRODUCT_OPTION"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_CONFIG_OPTION_PRODUCT_OPTION"
