[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CONFIG_ITEM-SEED-ofbiz_product_product_config_item_action_product_config_item_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_CONFIG_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_config_item_action_product_config_item_create_create" module="OFBIZ_PRODUCT_PRODUCT_CONFIG_ITEM"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CONFIG_ITEM"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CONFIG_ITEM"
