[SCENARIO: BDD-OFBIZ_ORDER_ORDER_REQUIREMENT_COMMITMENT-SEED-ofbiz_order_order_requirement_commitment_action_order_requirement_commitment_destroy_destroy] TITLE: OFBIZ_ORDER_ORDER_REQUIREMENT_COMMITMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_requirement_commitment_action_order_requirement_commitment_destroy_destroy" module="OFBIZ_ORDER_ORDER_REQUIREMENT_COMMITMENT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_REQUIREMENT_COMMITMENT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_REQUIREMENT_COMMITMENT"
