[SCENARIO: BDD-OFBIZ_ORDER_ORDER_HEADER_NOTE-SEED-ofbiz_order_order_header_note_action_order_header_note_read_read] TITLE: OFBIZ_ORDER_ORDER_HEADER_NOTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_header_note_action_order_header_note_read_read" module="OFBIZ_ORDER_ORDER_HEADER_NOTE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_HEADER_NOTE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_HEADER_NOTE"
