[SCENARIO: BDD-OFBIZ_MARKETING_SALES_OPPORTUNITY_ROLE-SEED-ofbiz_marketing_sales_opportunity_role_action_sales_opportunity_role_destroy_destroy] TITLE: OFBIZ_MARKETING_SALES_OPPORTUNITY_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_sales_opportunity_role_action_sales_opportunity_role_destroy_destroy" module="OFBIZ_MARKETING_SALES_OPPORTUNITY_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SALES_OPPORTUNITY_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SALES_OPPORTUNITY_ROLE"
