[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PROMO_CODE_PARTY-SEED-ofbiz_product_product_promo_code_party_action_product_promo_code_party_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_PROMO_CODE_PARTY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_promo_code_party_action_product_promo_code_party_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_PROMO_CODE_PARTY"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PROMO_CODE_PARTY"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PROMO_CODE_PARTY"
