[SCENARIO: BDD-OFBIZ_COMMON_PORTLET_ATTRIBUTE-SEED-ofbiz_common_portlet_attribute_action_portlet_attribute_create_create] TITLE: OFBIZ_COMMON_PORTLET_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_portlet_attribute_action_portlet_attribute_create_create" module="OFBIZ_COMMON_PORTLET_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_PORTLET_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_PORTLET_ATTRIBUTE"
