[SCENARIO: BDD-OFBIZ_CONTENT_DATA_RESOURCE_TYPE_ATTR-SEED-ofbiz_content_data_resource_type_attr_action_data_resource_type_attr_create_create] TITLE: OFBIZ_CONTENT_DATA_RESOURCE_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_data_resource_type_attr_action_data_resource_type_attr_create_create" module="OFBIZ_CONTENT_DATA_RESOURCE_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_DATA_RESOURCE_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_DATA_RESOURCE_TYPE_ATTR"
