[SCENARIO: BDD-OFBIZ_PARTY_PARTY_GROUP-SEED-ofbiz_party_party_group_action_party_group_create_create] TITLE: OFBIZ_PARTY_PARTY_GROUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_group_action_party_group_create_create" module="OFBIZ_PARTY_PARTY_GROUP"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_GROUP"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_GROUP"
