[SCENARIO: BDD-OFBIZ_MARKETING_SALES_OPPORTUNITY_WORK_EFFORT-SEED-ofbiz_marketing_sales_opportunity_work_effort_action_sales_opportunity_work_effort_create_create] TITLE: OFBIZ_MARKETING_SALES_OPPORTUNITY_WORK_EFFORT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_sales_opportunity_work_effort_action_sales_opportunity_work_effort_create_create" module="OFBIZ_MARKETING_SALES_OPPORTUNITY_WORK_EFFORT"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SALES_OPPORTUNITY_WORK_EFFORT"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SALES_OPPORTUNITY_WORK_EFFORT"
