[SCENARIO: BDD-OFBIZ_ORDER_COMMUNICATION_EVENT_RETURN-SEED-ofbiz_order_communication_event_return_action_communication_event_return_read_read] TITLE: OFBIZ_ORDER_COMMUNICATION_EVENT_RETURN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_communication_event_return_action_communication_event_return_read_read" module="OFBIZ_ORDER_COMMUNICATION_EVENT_RETURN"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_COMMUNICATION_EVENT_RETURN"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_COMMUNICATION_EVENT_RETURN"
