[SCENARIO: BDD-OFBIZ_COMMON_DATA_SOURCE-SEED-ofbiz_common_data_source_action_data_source_update_update] TITLE: OFBIZ_COMMON_DATA_SOURCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_data_source_action_data_source_update_update" module="OFBIZ_COMMON_DATA_SOURCE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_DATA_SOURCE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_DATA_SOURCE"
