[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CONFIG-SEED-ofbiz_product_product_config_action_product_config_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_CONFIG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_config_action_product_config_read_read" module="OFBIZ_PRODUCT_PRODUCT_CONFIG"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CONFIG"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CONFIG"
