[SCENARIO: BDD-OFBIZ_PARTY_PARTY_INVITATION_GROUP_ASSOC-SEED-ofbiz_party_party_invitation_group_assoc_action_party_invitation_group_assoc_create_create] TITLE: OFBIZ_PARTY_PARTY_INVITATION_GROUP_ASSOC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_invitation_group_assoc_action_party_invitation_group_assoc_create_create" module="OFBIZ_PARTY_PARTY_INVITATION_GROUP_ASSOC"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_INVITATION_GROUP_ASSOC"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_INVITATION_GROUP_ASSOC"
