[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_ROLE-SEED-ofbiz_product_product_role_action_product_role_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_role_action_product_role_update_update" module="OFBIZ_PRODUCT_PRODUCT_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_ROLE"
