[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ITEM_ASSOC-SEED-ofbiz_order_order_item_assoc_action_order_item_assoc_create_create] TITLE: OFBIZ_ORDER_ORDER_ITEM_ASSOC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_item_assoc_action_order_item_assoc_create_create" module="OFBIZ_ORDER_ORDER_ITEM_ASSOC"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ITEM_ASSOC"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ITEM_ASSOC"
