[SCENARIO: BDD-OFBIZ_ORDER_OLD_ORDER_BLACKLIST_TYPE-SEED-ofbiz_order_old_order_blacklist_type_action_old_order_blacklist_type_update_update] TITLE: OFBIZ_ORDER_OLD_ORDER_BLACKLIST_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_old_order_blacklist_type_action_old_order_blacklist_type_update_update" module="OFBIZ_ORDER_OLD_ORDER_BLACKLIST_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_OLD_ORDER_BLACKLIST_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_OLD_ORDER_BLACKLIST_TYPE"
