[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_TYPE-SEED-ofbiz_accounting_fin_account_trans_type_action_fin_account_trans_type_create_create] TITLE: OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fin_account_trans_type_action_fin_account_trans_type_create_create" module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_TYPE"
