[SCENARIO: BDD-OFBIZ_ORDER_REQUIREMENT_BUDGET_ALLOCATION-SEED-ofbiz_order_requirement_budget_allocation_action_requirement_budget_allocation_read_read] TITLE: OFBIZ_ORDER_REQUIREMENT_BUDGET_ALLOCATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_requirement_budget_allocation_action_requirement_budget_allocation_read_read" module="OFBIZ_ORDER_REQUIREMENT_BUDGET_ALLOCATION"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_REQUIREMENT_BUDGET_ALLOCATION"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_REQUIREMENT_BUDGET_ALLOCATION"
