[SCENARIO: BDD-OFBIZ_COMMON_COUNTRY_CAPITAL-SEED-ofbiz_common_country_capital_action_country_capital_create_create] TITLE: OFBIZ_COMMON_COUNTRY_CAPITAL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_country_capital_action_country_capital_create_create" module="OFBIZ_COMMON_COUNTRY_CAPITAL"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_COUNTRY_CAPITAL"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_COUNTRY_CAPITAL"
