[SCENARIO: BDD-OFBIZ_CONTENT_SURVEY_APPL_TYPE-SEED-ofbiz_content_survey_appl_type_action_survey_appl_type_create_create] TITLE: OFBIZ_CONTENT_SURVEY_APPL_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_survey_appl_type_action_survey_appl_type_create_create" module="OFBIZ_CONTENT_SURVEY_APPL_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_SURVEY_APPL_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_SURVEY_APPL_TYPE"
