[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CALCULATED_INFO-SEED-ofbiz_product_product_calculated_info_action_product_calculated_info_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_CALCULATED_INFO contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_calculated_info_action_product_calculated_info_update_update" module="OFBIZ_PRODUCT_PRODUCT_CALCULATED_INFO"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CALCULATED_INFO"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CALCULATED_INFO"
