[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_ITEM_TYPE-SEED-ofbiz_party_agreement_item_type_action_agreement_item_type_read_read] TITLE: OFBIZ_PARTY_AGREEMENT_ITEM_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_item_type_action_agreement_item_type_read_read" module="OFBIZ_PARTY_AGREEMENT_ITEM_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_ITEM_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_ITEM_TYPE"
