[SCENARIO: BDD-OFBIZ_PARTY_MARITAL_STATUS_TYPE-SEED-ofbiz_party_marital_status_type_action_marital_status_type_update_update] TITLE: OFBIZ_PARTY_MARITAL_STATUS_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_marital_status_type_action_marital_status_type_update_update" module="OFBIZ_PARTY_MARITAL_STATUS_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_MARITAL_STATUS_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_MARITAL_STATUS_TYPE"
