[SCENARIO: BDD-OFBIZ_PARTY_PARTY_CONTENT-SEED-ofbiz_party_party_content_action_party_content_create_create] TITLE: OFBIZ_PARTY_PARTY_CONTENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_content_action_party_content_create_create" module="OFBIZ_PARTY_PARTY_CONTENT"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_CONTENT"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_CONTENT"
