[SCENARIO: BDD-OFBIZ_COMMON_STANDARD_LANGUAGE-SEED-ofbiz_common_standard_language_action_standard_language_update_update] TITLE: OFBIZ_COMMON_STANDARD_LANGUAGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_standard_language_action_standard_language_update_update" module="OFBIZ_COMMON_STANDARD_LANGUAGE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_STANDARD_LANGUAGE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_STANDARD_LANGUAGE"
