[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_TYPE_ATTR-SEED-ofbiz_work_effort_work_effort_type_attr_action_work_effort_type_attr_create_create] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_type_attr_action_work_effort_type_attr_create_create" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_TYPE_ATTR"
