[SCENARIO: BDD-OFBIZ_WORK_EFFORT_TIMESHEET_ROLE-SEED-ofbiz_work_effort_timesheet_role_action_timesheet_role_update_update] TITLE: OFBIZ_WORK_EFFORT_TIMESHEET_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_timesheet_role_action_timesheet_role_update_update" module="OFBIZ_WORK_EFFORT_TIMESHEET_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_TIMESHEET_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_TIMESHEET_ROLE"
