[SCENARIO: BDD-OFBIZ_MARKETING_SALES_FORECAST_DETAIL-SEED-ofbiz_marketing_sales_forecast_detail_action_sales_forecast_detail_read_read] TITLE: OFBIZ_MARKETING_SALES_FORECAST_DETAIL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_sales_forecast_detail_action_sales_forecast_detail_read_read" module="OFBIZ_MARKETING_SALES_FORECAST_DETAIL"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SALES_FORECAST_DETAIL"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SALES_FORECAST_DETAIL"
