[SCENARIO: BDD-OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_MEMBER-SEED-ofbiz_accounting_gl_account_category_member_action_gl_account_category_member_create_create] TITLE: OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_MEMBER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_gl_account_category_member_action_gl_account_category_member_create_create" module="OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_MEMBER"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_MEMBER"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_MEMBER"
