[SCENARIO: BDD-OFBIZ_PARTY_PARTY_ROLE-SEED-ofbiz_party_party_role_action_party_role_read_read] TITLE: OFBIZ_PARTY_PARTY_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_role_action_party_role_read_read" module="OFBIZ_PARTY_PARTY_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_ROLE"
