[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_GL_ACCOUNT-SEED-ofbiz_product_product_gl_account_action_product_gl_account_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_GL_ACCOUNT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_gl_account_action_product_gl_account_read_read" module="OFBIZ_PRODUCT_PRODUCT_GL_ACCOUNT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_GL_ACCOUNT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_GL_ACCOUNT"
