[SCENARIO: BDD-OFBIZ_ORDER_CUST_REQUEST_PARTY-SEED-ofbiz_order_cust_request_party_action_cust_request_party_create_create] TITLE: OFBIZ_ORDER_CUST_REQUEST_PARTY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_cust_request_party_action_cust_request_party_create_create" module="OFBIZ_ORDER_CUST_REQUEST_PARTY"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_CUST_REQUEST_PARTY"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_CUST_REQUEST_PARTY"
