[SCENARIO: BDD-OFBIZ_HUMAN_RES_JOB_INTERVIEW-SEED-ofbiz_human_res_job_interview_action_job_interview_create_create] TITLE: OFBIZ_HUMAN_RES_JOB_INTERVIEW contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_job_interview_action_job_interview_create_create" module="OFBIZ_HUMAN_RES_JOB_INTERVIEW"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_JOB_INTERVIEW"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_JOB_INTERVIEW"
