[SCENARIO: BDD-OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST_TYPE-SEED-ofbiz_accounting_product_average_cost_type_action_product_average_cost_type_create_create] TITLE: OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_product_average_cost_type_action_product_average_cost_type_create_create" module="OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST_TYPE"
