[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_METER-SEED-ofbiz_product_product_meter_action_product_meter_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_METER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_meter_action_product_meter_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_METER"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_METER"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_METER"
