[SCENARIO: BDD-OFBIZ_ORDER_RETURN_ITEM-SEED-ofbiz_order_return_item_action_return_item_create_create] TITLE: OFBIZ_ORDER_RETURN_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_return_item_action_return_item_create_create" module="OFBIZ_ORDER_RETURN_ITEM"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_RETURN_ITEM"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_RETURN_ITEM"
