[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT-SEED-ofbiz_shipment_shipment_action_shipment_update_update] TITLE: OFBIZ_SHIPMENT_SHIPMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_action_shipment_update_update" module="OFBIZ_SHIPMENT_SHIPMENT"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT"
