[SCENARIO: BDD-OFBIZ_PARTY_PARTY_DATA_SOURCE-SEED-ofbiz_party_party_data_source_action_party_data_source_update_update] TITLE: OFBIZ_PARTY_PARTY_DATA_SOURCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_data_source_action_party_data_source_update_update" module="OFBIZ_PARTY_PARTY_DATA_SOURCE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_DATA_SOURCE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_DATA_SOURCE"
