[SCENARIO: BDD-OFBIZ_MARKETING_SALES_OPPORTUNITY_COMPETITOR-SEED-ofbiz_marketing_sales_opportunity_competitor_action_sales_opportunity_competitor_destroy_destroy] TITLE: OFBIZ_MARKETING_SALES_OPPORTUNITY_COMPETITOR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_sales_opportunity_competitor_action_sales_opportunity_competitor_destroy_destroy" module="OFBIZ_MARKETING_SALES_OPPORTUNITY_COMPETITOR"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SALES_OPPORTUNITY_COMPETITOR"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SALES_OPPORTUNITY_COMPETITOR"
