[SCENARIO: BDD-OFBIZ_ORDER_SHOPPING_LIST_WORK_EFFORT-SEED-ofbiz_order_shopping_list_work_effort_action_shopping_list_work_effort_read_read] TITLE: OFBIZ_ORDER_SHOPPING_LIST_WORK_EFFORT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_shopping_list_work_effort_action_shopping_list_work_effort_read_read" module="OFBIZ_ORDER_SHOPPING_LIST_WORK_EFFORT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_SHOPPING_LIST_WORK_EFFORT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_SHOPPING_LIST_WORK_EFFORT"
