[SCENARIO: BDD-OFBIZ_CONTENT_CONTENT_PURPOSE-SEED-ofbiz_content_content_purpose_action_content_purpose_create_create] TITLE: OFBIZ_CONTENT_CONTENT_PURPOSE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_content_purpose_action_content_purpose_create_create" module="OFBIZ_CONTENT_CONTENT_PURPOSE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_CONTENT_PURPOSE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_CONTENT_PURPOSE"
