[SCENARIO: BDD-OFBIZ_CONTENT_SURVEY_PAGE-SEED-ofbiz_content_survey_page_action_survey_page_create_create] TITLE: OFBIZ_CONTENT_SURVEY_PAGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_survey_page_action_survey_page_create_create" module="OFBIZ_CONTENT_SURVEY_PAGE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_SURVEY_PAGE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_SURVEY_PAGE"
