[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_SURVEY_APPL-SEED-ofbiz_work_effort_work_effort_survey_appl_action_work_effort_survey_appl_create_create] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_SURVEY_APPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_survey_appl_action_work_effort_survey_appl_create_create" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_SURVEY_APPL"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_SURVEY_APPL"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_SURVEY_APPL"
