[SCENARIO: BDD-OFBIZ_HUMAN_RES_PARTY_QUAL-SEED-ofbiz_human_res_party_qual_action_party_qual_read_read] TITLE: OFBIZ_HUMAN_RES_PARTY_QUAL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_party_qual_action_party_qual_read_read" module="OFBIZ_HUMAN_RES_PARTY_QUAL"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_PARTY_QUAL"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_PARTY_QUAL"
