[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CATEGORY_GL_ACCOUNT-SEED-ofbiz_product_product_category_gl_account_action_product_category_gl_account_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_CATEGORY_GL_ACCOUNT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_category_gl_account_action_product_category_gl_account_update_update" module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_GL_ACCOUNT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_GL_ACCOUNT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_GL_ACCOUNT"
