[SCENARIO: BDD-OFBIZ_MARKETING_MARKETING_CAMPAIGN_NOTE-SEED-ofbiz_marketing_marketing_campaign_note_action_marketing_campaign_note_create_create] TITLE: OFBIZ_MARKETING_MARKETING_CAMPAIGN_NOTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_marketing_campaign_note_action_marketing_campaign_note_create_create" module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_NOTE"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_NOTE"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_NOTE"
