[SCENARIO: BDD-OFBIZ_CONTENT_CONTENT_ATTRIBUTE-SEED-ofbiz_content_content_attribute_action_content_attribute_read_read] TITLE: OFBIZ_CONTENT_CONTENT_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_content_attribute_action_content_attribute_read_read" module="OFBIZ_CONTENT_CONTENT_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_CONTENT_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_CONTENT_ATTRIBUTE"
