[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CATEGORY_ATTRIBUTE-SEED-ofbiz_product_product_category_attribute_action_product_category_attribute_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_CATEGORY_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_category_attribute_action_product_category_attribute_read_read" module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_ATTRIBUTE"
