[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_CLASS-SEED-ofbiz_human_res_empl_position_type_class_action_empl_position_type_class_create_create] TITLE: OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_CLASS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_position_type_class_action_empl_position_type_class_create_create" module="OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_CLASS"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_CLASS"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_POSITION_TYPE_CLASS"
