[SCENARIO: BDD-OFBIZ_ORDER_CUST_REQUEST_WORK_EFFORT-SEED-ofbiz_order_cust_request_work_effort_action_cust_request_work_effort_destroy_destroy] TITLE: OFBIZ_ORDER_CUST_REQUEST_WORK_EFFORT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_cust_request_work_effort_action_cust_request_work_effort_destroy_destroy" module="OFBIZ_ORDER_CUST_REQUEST_WORK_EFFORT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_CUST_REQUEST_WORK_EFFORT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_CUST_REQUEST_WORK_EFFORT"
