[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE-SEED-ofbiz_accounting_invoice_item_type_action_invoice_item_type_update_update] TITLE: OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_item_type_action_invoice_item_type_update_update" module="OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE"
