[SCENARIO: BDD-OFBIZ_PRODUCT_FACILITY_GROUP-SEED-ofbiz_product_facility_group_action_facility_group_destroy_destroy] TITLE: OFBIZ_PRODUCT_FACILITY_GROUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_facility_group_action_facility_group_destroy_destroy" module="OFBIZ_PRODUCT_FACILITY_GROUP"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_FACILITY_GROUP"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_FACILITY_GROUP"
