[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_ITEM_ATTRIBUTE-SEED-ofbiz_party_agreement_item_attribute_action_agreement_item_attribute_update_update] TITLE: OFBIZ_PARTY_AGREEMENT_ITEM_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_item_attribute_action_agreement_item_attribute_update_update" module="OFBIZ_PARTY_AGREEMENT_ITEM_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_ITEM_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_ITEM_ATTRIBUTE"
