[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CATEGORY_TYPE_ATTR-SEED-ofbiz_product_product_category_type_attr_action_product_category_type_attr_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_CATEGORY_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_category_type_attr_action_product_category_type_attr_read_read" module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_TYPE_ATTR"
