[SCENARIO: BDD-OFBIZ_SECURITY_SECURITY_PERMISSION-SEED-ofbiz_security_security_permission_action_security_permission_create_create] TITLE: OFBIZ_SECURITY_SECURITY_PERMISSION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_security_security_permission_action_security_permission_create_create" module="OFBIZ_SECURITY_SECURITY_PERMISSION"
WHEN when_execute_seed_contract module="OFBIZ_SECURITY_SECURITY_PERMISSION"
THEN then_seed_contract_should_hold module="OFBIZ_SECURITY_SECURITY_PERMISSION"
