[SCENARIO: BDD-OFBIZ_COMMON_GEO_ASSOC_TYPE-SEED-ofbiz_common_geo_assoc_type_action_geo_assoc_type_destroy_destroy] TITLE: OFBIZ_COMMON_GEO_ASSOC_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_geo_assoc_type_action_geo_assoc_type_destroy_destroy" module="OFBIZ_COMMON_GEO_ASSOC_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_GEO_ASSOC_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_GEO_ASSOC_TYPE"
