[SCENARIO: BDD-OFBIZ_PRODUCT_FACILITY_TYPE_ATTR-SEED-ofbiz_product_facility_type_attr_action_facility_type_attr_destroy_destroy] TITLE: OFBIZ_PRODUCT_FACILITY_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_facility_type_attr_action_facility_type_attr_destroy_destroy" module="OFBIZ_PRODUCT_FACILITY_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_FACILITY_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_FACILITY_TYPE_ATTR"
