[SCENARIO: BDD-OFBIZ_PARTY_NEED_TYPE-SEED-ofbiz_party_need_type_action_need_type_destroy_destroy] TITLE: OFBIZ_PARTY_NEED_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_need_type_action_need_type_destroy_destroy" module="OFBIZ_PARTY_NEED_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_NEED_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_NEED_TYPE"
