[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_KEYWORD-SEED-ofbiz_product_product_keyword_action_product_keyword_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_KEYWORD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_keyword_action_product_keyword_create_create" module="OFBIZ_PRODUCT_PRODUCT_KEYWORD"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_KEYWORD"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_KEYWORD"
