[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAY_PAL_PAYMENT_METHOD-SEED-ofbiz_accounting_pay_pal_payment_method_action_pay_pal_payment_method_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_PAY_PAL_PAYMENT_METHOD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_pay_pal_payment_method_action_pay_pal_payment_method_destroy_destroy" module="OFBIZ_ACCOUNTING_PAY_PAL_PAYMENT_METHOD"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAY_PAL_PAYMENT_METHOD"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAY_PAL_PAYMENT_METHOD"
