[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIN_ACCOUNT-SEED-ofbiz_accounting_fin_account_action_fin_account_read_read] TITLE: OFBIZ_ACCOUNTING_FIN_ACCOUNT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fin_account_action_fin_account_read_read" module="OFBIZ_ACCOUNTING_FIN_ACCOUNT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIN_ACCOUNT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIN_ACCOUNT"
