[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_SECURE_PAY-SEED-ofbiz_accounting_payment_gateway_secure_pay_action_payment_gateway_secure_pay_create_create] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_SECURE_PAY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_secure_pay_action_payment_gateway_secure_pay_create_create" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_SECURE_PAY"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_SECURE_PAY"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_SECURE_PAY"
