[SCENARIO: BDD-OFBIZ_PRODUCT_SUPPLIER_PRODUCT-SEED-ofbiz_product_supplier_product_action_supplier_product_destroy_destroy] TITLE: OFBIZ_PRODUCT_SUPPLIER_PRODUCT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_supplier_product_action_supplier_product_destroy_destroy" module="OFBIZ_PRODUCT_SUPPLIER_PRODUCT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_SUPPLIER_PRODUCT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_SUPPLIER_PRODUCT"
