[SCENARIO: BDD-OFBIZ_COMMON_GEO_ASSOC-SEED-ofbiz_common_geo_assoc_action_geo_assoc_update_update] TITLE: OFBIZ_COMMON_GEO_ASSOC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_geo_assoc_action_geo_assoc_update_update" module="OFBIZ_COMMON_GEO_ASSOC"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_GEO_ASSOC"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_GEO_ASSOC"
