[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET_GEO_POINT-SEED-ofbiz_accounting_fixed_asset_geo_point_action_fixed_asset_geo_point_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET_GEO_POINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_geo_point_action_fixed_asset_geo_point_destroy_destroy" module="OFBIZ_ACCOUNTING_FIXED_ASSET_GEO_POINT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET_GEO_POINT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET_GEO_POINT"
