[SCENARIO: BDD-OFBIZ_HUMAN_RES_JOB_REQUISITION-SEED-ofbiz_human_res_job_requisition_action_job_requisition_update_update] TITLE: OFBIZ_HUMAN_RES_JOB_REQUISITION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_job_requisition_action_job_requisition_update_update" module="OFBIZ_HUMAN_RES_JOB_REQUISITION"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_JOB_REQUISITION"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_JOB_REQUISITION"
