[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_CONTENT_TYPE-SEED-ofbiz_accounting_invoice_content_type_action_invoice_content_type_read_read] TITLE: OFBIZ_ACCOUNTING_INVOICE_CONTENT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_content_type_action_invoice_content_type_read_read" module="OFBIZ_ACCOUNTING_INVOICE_CONTENT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_CONTENT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_CONTENT_TYPE"
