[SCENARIO: BDD-OFBIZ_ORDER_ORDER_HEADER-SEED-ofbiz_order_order_header_action_order_header_read_read] TITLE: OFBIZ_ORDER_ORDER_HEADER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_header_action_order_header_read_read" module="OFBIZ_ORDER_ORDER_HEADER"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_HEADER"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_HEADER"
