[SCENARIO: BDD-OFBIZ_PRODUCT_INVENTORY_ITEM_TEMP_RES-SEED-ofbiz_product_inventory_item_temp_res_action_inventory_item_temp_res_update_update] TITLE: OFBIZ_PRODUCT_INVENTORY_ITEM_TEMP_RES contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_inventory_item_temp_res_action_inventory_item_temp_res_update_update" module="OFBIZ_PRODUCT_INVENTORY_ITEM_TEMP_RES"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_INVENTORY_ITEM_TEMP_RES"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_INVENTORY_ITEM_TEMP_RES"
