[SCENARIO: BDD-OFBIZ_PARTY_CONTACT_MECH_TYPE_ATTR-SEED-ofbiz_party_contact_mech_type_attr_action_contact_mech_type_attr_update_update] TITLE: OFBIZ_PARTY_CONTACT_MECH_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_contact_mech_type_attr_action_contact_mech_type_attr_update_update" module="OFBIZ_PARTY_CONTACT_MECH_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_CONTACT_MECH_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_CONTACT_MECH_TYPE_ATTR"
