[SCENARIO: BDD-OFBIZ_ORDER_RETURN_TYPE-SEED-ofbiz_order_return_type_action_return_type_create_create] TITLE: OFBIZ_ORDER_RETURN_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_return_type_action_return_type_create_create" module="OFBIZ_ORDER_RETURN_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_RETURN_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_RETURN_TYPE"
