[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_FIN_ACT_SETTING-SEED-ofbiz_product_product_store_fin_act_setting_action_product_store_fin_act_setting_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_FIN_ACT_SETTING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_fin_act_setting_action_product_store_fin_act_setting_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_STORE_FIN_ACT_SETTING"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_FIN_ACT_SETTING"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_FIN_ACT_SETTING"
