[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ITEM_CHANGE-SEED-ofbiz_order_order_item_change_action_order_item_change_create_create] TITLE: OFBIZ_ORDER_ORDER_ITEM_CHANGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_item_change_action_order_item_change_create_create" module="OFBIZ_ORDER_ORDER_ITEM_CHANGE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ITEM_CHANGE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ITEM_CHANGE"
