[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_STD-SEED-ofbiz_work_effort_work_effort_fixed_asset_std_action_work_effort_fixed_asset_std_update_update] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_STD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_fixed_asset_std_action_work_effort_fixed_asset_std_update_update" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_STD"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_STD"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_STD"
