[SCENARIO: BDD-OFBIZ_ACCOUNTING_BUDGET_TYPE_ATTR-SEED-ofbiz_accounting_budget_type_attr_action_budget_type_attr_update_update] TITLE: OFBIZ_ACCOUNTING_BUDGET_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_budget_type_attr_action_budget_type_attr_update_update" module="OFBIZ_ACCOUNTING_BUDGET_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_BUDGET_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_BUDGET_TYPE_ATTR"
