[SCENARIO: BDD-OFBIZ_PRODUCT_COST_COMPONENT_ATTRIBUTE-SEED-ofbiz_product_cost_component_attribute_action_cost_component_attribute_create_create] TITLE: OFBIZ_PRODUCT_COST_COMPONENT_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_cost_component_attribute_action_cost_component_attribute_create_create" module="OFBIZ_PRODUCT_COST_COMPONENT_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_COST_COMPONENT_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_COST_COMPONENT_ATTRIBUTE"
