[SCENARIO: BDD-OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP_MEMBER-SEED-ofbiz_accounting_gl_account_group_member_action_gl_account_group_member_create_create] TITLE: OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP_MEMBER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_gl_account_group_member_action_gl_account_group_member_create_create" module="OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP_MEMBER"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP_MEMBER"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_GL_ACCOUNT_GROUP_MEMBER"
