[SCENARIO: BDD-OFBIZ_CONTENT_SURVEY_MULTI_RESP_COLUMN-SEED-ofbiz_content_survey_multi_resp_column_action_survey_multi_resp_column_update_update] TITLE: OFBIZ_CONTENT_SURVEY_MULTI_RESP_COLUMN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_survey_multi_resp_column_action_survey_multi_resp_column_update_update" module="OFBIZ_CONTENT_SURVEY_MULTI_RESP_COLUMN"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_SURVEY_MULTI_RESP_COLUMN"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_SURVEY_MULTI_RESP_COLUMN"
