[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAYFLOW_PRO-SEED-ofbiz_accounting_payment_gateway_payflow_pro_action_payment_gateway_payflow_pro_create_create] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAYFLOW_PRO contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_payflow_pro_action_payment_gateway_payflow_pro_create_create" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAYFLOW_PRO"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAYFLOW_PRO"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAYFLOW_PRO"
