[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_POSITION_FULFILLMENT-SEED-ofbiz_human_res_empl_position_fulfillment_action_empl_position_fulfillment_create_create] TITLE: OFBIZ_HUMAN_RES_EMPL_POSITION_FULFILLMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_position_fulfillment_action_empl_position_fulfillment_create_create" module="OFBIZ_HUMAN_RES_EMPL_POSITION_FULFILLMENT"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_POSITION_FULFILLMENT"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_POSITION_FULFILLMENT"
