[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE-SEED-ofbiz_accounting_payment_method_type_action_payment_method_type_create_create] TITLE: OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_method_type_action_payment_method_type_create_create" module="OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_METHOD_TYPE"
