[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_FEATURE_TYPE-SEED-ofbiz_product_product_feature_type_action_product_feature_type_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_FEATURE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_feature_type_action_product_feature_type_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_FEATURE_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_FEATURE_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_FEATURE_TYPE"
