[SCENARIO: BDD-OFBIZ_PARTY_COMMUNICATION_EVENT_PRP_TYP-SEED-ofbiz_party_communication_event_prp_typ_action_communication_event_prp_typ_update_update] TITLE: OFBIZ_PARTY_COMMUNICATION_EVENT_PRP_TYP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_communication_event_prp_typ_action_communication_event_prp_typ_update_update" module="OFBIZ_PARTY_COMMUNICATION_EVENT_PRP_TYP"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_COMMUNICATION_EVENT_PRP_TYP"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_COMMUNICATION_EVENT_PRP_TYP"
