[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ITEM_ASSOC_TYPE-SEED-ofbiz_order_order_item_assoc_type_action_order_item_assoc_type_read_read] TITLE: OFBIZ_ORDER_ORDER_ITEM_ASSOC_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_item_assoc_type_action_order_item_assoc_type_read_read" module="OFBIZ_ORDER_ORDER_ITEM_ASSOC_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ITEM_ASSOC_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ITEM_ASSOC_TYPE"
