[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_TYPE-SEED-ofbiz_accounting_payment_type_action_payment_type_read_read] TITLE: OFBIZ_ACCOUNTING_PAYMENT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_type_action_payment_type_read_read" module="OFBIZ_ACCOUNTING_PAYMENT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_TYPE"
