[SCENARIO: BDD-OFBIZ_COMMON_ENUMERATION-SEED-ofbiz_common_enumeration_action_enumeration_create_create] TITLE: OFBIZ_COMMON_ENUMERATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_enumeration_action_enumeration_create_create" module="OFBIZ_COMMON_ENUMERATION"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_ENUMERATION"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_ENUMERATION"
