[SCENARIO: BDD-OFBIZ_PRODUCT_SUBSCRIPTION_COMM_EVENT-SEED-ofbiz_product_subscription_comm_event_action_subscription_comm_event_update_update] TITLE: OFBIZ_PRODUCT_SUBSCRIPTION_COMM_EVENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_subscription_comm_event_action_subscription_comm_event_update_update" module="OFBIZ_PRODUCT_SUBSCRIPTION_COMM_EVENT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_SUBSCRIPTION_COMM_EVENT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_SUBSCRIPTION_COMM_EVENT"
