[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_ITEM_ATTRIBUTE-SEED-ofbiz_accounting_invoice_item_attribute_action_invoice_item_attribute_read_read] TITLE: OFBIZ_ACCOUNTING_INVOICE_ITEM_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_item_attribute_action_invoice_item_attribute_read_read" module="OFBIZ_ACCOUNTING_INVOICE_ITEM_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_ITEM_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_ITEM_ATTRIBUTE"
