[SCENARIO: BDD-OFBIZ_ACCOUNTING_BUDGET_SCENARIO_RULE-SEED-ofbiz_accounting_budget_scenario_rule_action_budget_scenario_rule_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_BUDGET_SCENARIO_RULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_budget_scenario_rule_action_budget_scenario_rule_destroy_destroy" module="OFBIZ_ACCOUNTING_BUDGET_SCENARIO_RULE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_BUDGET_SCENARIO_RULE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_BUDGET_SCENARIO_RULE"
