[SCENARIO: BDD-OFBIZ_MARKETING_TRACKING_CODE_TYPE-SEED-ofbiz_marketing_tracking_code_type_action_tracking_code_type_destroy_destroy] TITLE: OFBIZ_MARKETING_TRACKING_CODE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_tracking_code_type_action_tracking_code_type_destroy_destroy" module="OFBIZ_MARKETING_TRACKING_CODE_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_TRACKING_CODE_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_TRACKING_CODE_TYPE"
