[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_ASSOC_TYPE-SEED-ofbiz_product_product_assoc_type_action_product_assoc_type_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_ASSOC_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_assoc_type_action_product_assoc_type_read_read" module="OFBIZ_PRODUCT_PRODUCT_ASSOC_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_ASSOC_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_ASSOC_TYPE"
