[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_ORBITAL-SEED-ofbiz_accounting_payment_gateway_orbital_action_payment_gateway_orbital_update_update] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_ORBITAL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_orbital_action_payment_gateway_orbital_update_update" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_ORBITAL"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_ORBITAL"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_ORBITAL"
