[SCENARIO: BDD-OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_TYPE-SEED-ofbiz_product_inventory_item_label_type_action_inventory_item_label_type_read_read] TITLE: OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_inventory_item_label_type_action_inventory_item_label_type_read_read" module="OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_INVENTORY_ITEM_LABEL_TYPE"
