[SCENARIO: BDD-OFBIZ_COMMON_USER_PREF_GROUP_TYPE-SEED-ofbiz_common_user_pref_group_type_action_user_pref_group_type_read_read] TITLE: OFBIZ_COMMON_USER_PREF_GROUP_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_user_pref_group_type_action_user_pref_group_type_read_read" module="OFBIZ_COMMON_USER_PREF_GROUP_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_USER_PREF_GROUP_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_USER_PREF_GROUP_TYPE"
