[SCENARIO: BDD-OFBIZ_PRODUCT_FACILITY_CONTENT-SEED-ofbiz_product_facility_content_action_facility_content_create_create] TITLE: OFBIZ_PRODUCT_FACILITY_CONTENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_facility_content_action_facility_content_create_create" module="OFBIZ_PRODUCT_FACILITY_CONTENT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_FACILITY_CONTENT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_FACILITY_CONTENT"
