[SCENARIO: BDD-OFBIZ_ACCOUNTING_ZIP_SALES_TAX_LOOKUP-SEED-ofbiz_accounting_zip_sales_tax_lookup_action_zip_sales_tax_lookup_read_read] TITLE: OFBIZ_ACCOUNTING_ZIP_SALES_TAX_LOOKUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_zip_sales_tax_lookup_action_zip_sales_tax_lookup_read_read" module="OFBIZ_ACCOUNTING_ZIP_SALES_TAX_LOOKUP"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_ZIP_SALES_TAX_LOOKUP"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_ZIP_SALES_TAX_LOOKUP"
