[SCENARIO: BDD-OFBIZ_ORDER_ORDER_NOTIFICATION-SEED-ofbiz_order_order_notification_action_order_notification_create_create] TITLE: OFBIZ_ORDER_ORDER_NOTIFICATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_notification_action_order_notification_create_create" module="OFBIZ_ORDER_ORDER_NOTIFICATION"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_NOTIFICATION"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_NOTIFICATION"
