[SCENARIO: BDD-OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_EXC_DAY-SEED-ofbiz_manufacturing_tech_data_calendar_exc_day_action_tech_data_calendar_exc_day_create_create] TITLE: OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_EXC_DAY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_manufacturing_tech_data_calendar_exc_day_action_tech_data_calendar_exc_day_create_create" module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_EXC_DAY"
WHEN when_execute_seed_contract module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_EXC_DAY"
THEN then_seed_contract_should_hold module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_EXC_DAY"
