[SCENARIO: BDD-OFBIZ_MARKETING_SEGMENT_GROUP_CLASSIFICATION-SEED-ofbiz_marketing_segment_group_classification_action_segment_group_classification_destroy_destroy] TITLE: OFBIZ_MARKETING_SEGMENT_GROUP_CLASSIFICATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_segment_group_classification_action_segment_group_classification_destroy_destroy" module="OFBIZ_MARKETING_SEGMENT_GROUP_CLASSIFICATION"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SEGMENT_GROUP_CLASSIFICATION"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SEGMENT_GROUP_CLASSIFICATION"
