[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET-SEED-ofbiz_accounting_fixed_asset_action_fixed_asset_read_read] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_action_fixed_asset_read_read" module="OFBIZ_ACCOUNTING_FIXED_ASSET"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET"
