[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_ROLE-SEED-ofbiz_accounting_invoice_role_action_invoice_role_read_read] TITLE: OFBIZ_ACCOUNTING_INVOICE_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_role_action_invoice_role_read_read" module="OFBIZ_ACCOUNTING_INVOICE_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_ROLE"
