[SCENARIO: BDD-OFBIZ_COMMON_PORTAL_PAGE_PORTLET-SEED-ofbiz_common_portal_page_portlet_action_portal_page_portlet_destroy_destroy] TITLE: OFBIZ_COMMON_PORTAL_PAGE_PORTLET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_portal_page_portlet_action_portal_page_portlet_destroy_destroy" module="OFBIZ_COMMON_PORTAL_PAGE_PORTLET"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_PORTAL_PAGE_PORTLET"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_PORTAL_PAGE_PORTLET"
