[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_ITEM_FEATURE-SEED-ofbiz_shipment_shipment_item_feature_action_shipment_item_feature_read_read] TITLE: OFBIZ_SHIPMENT_SHIPMENT_ITEM_FEATURE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_item_feature_action_shipment_item_feature_read_read" module="OFBIZ_SHIPMENT_SHIPMENT_ITEM_FEATURE"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_ITEM_FEATURE"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_ITEM_FEATURE"
