[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_SEARCH_CONSTRAINT-SEED-ofbiz_work_effort_work_effort_search_constraint_action_work_effort_search_constraint_update_update] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_SEARCH_CONSTRAINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_search_constraint_action_work_effort_search_constraint_update_update" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_SEARCH_CONSTRAINT"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_SEARCH_CONSTRAINT"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_SEARCH_CONSTRAINT"
