[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_FEATURE-SEED-ofbiz_product_product_feature_action_product_feature_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_FEATURE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_feature_action_product_feature_read_read" module="OFBIZ_PRODUCT_PRODUCT_FEATURE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_FEATURE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_FEATURE"
