[SCENARIO: BDD-OFBIZ_ORDER_SHOPPING_LIST_ITEM_SURVEY-SEED-ofbiz_order_shopping_list_item_survey_action_shopping_list_item_survey_update_update] TITLE: OFBIZ_ORDER_SHOPPING_LIST_ITEM_SURVEY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_shopping_list_item_survey_action_shopping_list_item_survey_update_update" module="OFBIZ_ORDER_SHOPPING_LIST_ITEM_SURVEY"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_SHOPPING_LIST_ITEM_SURVEY"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_SHOPPING_LIST_ITEM_SURVEY"
