[SCENARIO: BDD-OFBIZ_COMMON_CUSTOM_TIME_PERIOD-SEED-ofbiz_common_custom_time_period_action_custom_time_period_destroy_destroy] TITLE: OFBIZ_COMMON_CUSTOM_TIME_PERIOD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_custom_time_period_action_custom_time_period_destroy_destroy" module="OFBIZ_COMMON_CUSTOM_TIME_PERIOD"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_CUSTOM_TIME_PERIOD"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_CUSTOM_TIME_PERIOD"
