[SCENARIO: BDD-OFBIZ_HUMAN_RES_PERF_REVIEW-SEED-ofbiz_human_res_perf_review_action_perf_review_update_update] TITLE: OFBIZ_HUMAN_RES_PERF_REVIEW contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_perf_review_action_perf_review_update_update" module="OFBIZ_HUMAN_RES_PERF_REVIEW"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_PERF_REVIEW"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_PERF_REVIEW"
