[SCENARIO: BDD-OFBIZ_PRODUCT_FACILITY_CALENDAR_TYPE-SEED-ofbiz_product_facility_calendar_type_action_facility_calendar_type_read_read] TITLE: OFBIZ_PRODUCT_FACILITY_CALENDAR_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_facility_calendar_type_action_facility_calendar_type_read_read" module="OFBIZ_PRODUCT_FACILITY_CALENDAR_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_FACILITY_CALENDAR_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_FACILITY_CALENDAR_TYPE"
