[SCENARIO: BDD-OFBIZ_ORDER_RETURN_ITEM_BILLING-SEED-ofbiz_order_return_item_billing_action_return_item_billing_create_create] TITLE: OFBIZ_ORDER_RETURN_ITEM_BILLING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_return_item_billing_action_return_item_billing_create_create" module="OFBIZ_ORDER_RETURN_ITEM_BILLING"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_RETURN_ITEM_BILLING"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_RETURN_ITEM_BILLING"
