[SCENARIO: BDD-OFBIZ_CONTENT_CONTENT_OPERATION-SEED-ofbiz_content_content_operation_action_content_operation_read_read] TITLE: OFBIZ_CONTENT_CONTENT_OPERATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_content_operation_action_content_operation_read_read" module="OFBIZ_CONTENT_CONTENT_OPERATION"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_CONTENT_OPERATION"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_CONTENT_OPERATION"
