[SCENARIO: BDD-OFBIZ_ORDER_ORDER_CONTENT-SEED-ofbiz_order_order_content_action_order_content_read_read] TITLE: OFBIZ_ORDER_ORDER_CONTENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_content_action_order_content_read_read" module="OFBIZ_ORDER_ORDER_CONTENT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_CONTENT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_CONTENT"
