[SCENARIO: BDD-OFBIZ_COMMON_UOM_CONVERSION_DATED-SEED-ofbiz_common_uom_conversion_dated_action_uom_conversion_dated_create_create] TITLE: OFBIZ_COMMON_UOM_CONVERSION_DATED contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_uom_conversion_dated_action_uom_conversion_dated_create_create" module="OFBIZ_COMMON_UOM_CONVERSION_DATED"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_UOM_CONVERSION_DATED"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_UOM_CONVERSION_DATED"
