[SCENARIO: BDD-OFBIZ_ORDER_WORK_ORDER_ITEM_FULFILLMENT-SEED-ofbiz_order_work_order_item_fulfillment_action_work_order_item_fulfillment_update_update] TITLE: OFBIZ_ORDER_WORK_ORDER_ITEM_FULFILLMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_work_order_item_fulfillment_action_work_order_item_fulfillment_update_update" module="OFBIZ_ORDER_WORK_ORDER_ITEM_FULFILLMENT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_WORK_ORDER_ITEM_FULFILLMENT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_WORK_ORDER_ITEM_FULFILLMENT"
