[SCENARIO: BDD-OFBIZ_CONTENT_CONTENT_REVISION-SEED-ofbiz_content_content_revision_action_content_revision_create_create] TITLE: OFBIZ_CONTENT_CONTENT_REVISION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_content_revision_action_content_revision_create_create" module="OFBIZ_CONTENT_CONTENT_REVISION"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_CONTENT_REVISION"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_CONTENT_REVISION"
