[SCENARIO: BDD-OFBIZ_PRODUCT_FACILITY_CARRIER_SHIPMENT-SEED-ofbiz_product_facility_carrier_shipment_action_facility_carrier_shipment_create_create] TITLE: OFBIZ_PRODUCT_FACILITY_CARRIER_SHIPMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_facility_carrier_shipment_action_facility_carrier_shipment_create_create" module="OFBIZ_PRODUCT_FACILITY_CARRIER_SHIPMENT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_FACILITY_CARRIER_SHIPMENT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_FACILITY_CARRIER_SHIPMENT"
