[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_CONTACT_MECH-SEED-ofbiz_accounting_invoice_contact_mech_action_invoice_contact_mech_create_create] TITLE: OFBIZ_ACCOUNTING_INVOICE_CONTACT_MECH contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_contact_mech_action_invoice_contact_mech_create_create" module="OFBIZ_ACCOUNTING_INVOICE_CONTACT_MECH"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_CONTACT_MECH"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_CONTACT_MECH"
