[SCENARIO: BDD-OFBIZ_COMMON_TELECOM_GATEWAY_CONFIG-SEED-ofbiz_common_telecom_gateway_config_action_telecom_gateway_config_update_update] TITLE: OFBIZ_COMMON_TELECOM_GATEWAY_CONFIG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_telecom_gateway_config_action_telecom_gateway_config_update_update" module="OFBIZ_COMMON_TELECOM_GATEWAY_CONFIG"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_TELECOM_GATEWAY_CONFIG"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_TELECOM_GATEWAY_CONFIG"
