[SCENARIO: BDD-OFBIZ_PARTY_PARTY_NEED-SEED-ofbiz_party_party_need_action_party_need_read_read] TITLE: OFBIZ_PARTY_PARTY_NEED contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_need_action_party_need_read_read" module="OFBIZ_PARTY_PARTY_NEED"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_NEED"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_NEED"
