[SCENARIO: BDD-OFBIZ_CONTENT_DATA_RESOURCE_ATTRIBUTE-SEED-ofbiz_content_data_resource_attribute_action_data_resource_attribute_create_create] TITLE: OFBIZ_CONTENT_DATA_RESOURCE_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_data_resource_attribute_action_data_resource_attribute_create_create" module="OFBIZ_CONTENT_DATA_RESOURCE_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_DATA_RESOURCE_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_DATA_RESOURCE_ATTRIBUTE"
