[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_PARTY_ASSIGNMENT-SEED-ofbiz_work_effort_work_effort_party_assignment_action_work_effort_party_assignment_destroy_destroy] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_PARTY_ASSIGNMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_party_assignment_action_work_effort_party_assignment_destroy_destroy" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_PARTY_ASSIGNMENT"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_PARTY_ASSIGNMENT"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_PARTY_ASSIGNMENT"
