[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ADJUSTMENT_BILLING-SEED-ofbiz_order_order_adjustment_billing_action_order_adjustment_billing_update_update] TITLE: OFBIZ_ORDER_ORDER_ADJUSTMENT_BILLING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_adjustment_billing_action_order_adjustment_billing_update_update" module="OFBIZ_ORDER_ORDER_ADJUSTMENT_BILLING"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ADJUSTMENT_BILLING"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ADJUSTMENT_BILLING"
