[SCENARIO: BDD-OFBIZ_HUMAN_RES_TRAINING_REQUEST-SEED-ofbiz_human_res_training_request_action_training_request_read_read] TITLE: OFBIZ_HUMAN_RES_TRAINING_REQUEST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_training_request_action_training_request_read_read" module="OFBIZ_HUMAN_RES_TRAINING_REQUEST"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_TRAINING_REQUEST"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_TRAINING_REQUEST"
