[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_FEATURE_CAT_GRP_APPL-SEED-ofbiz_product_product_feature_cat_grp_appl_action_product_feature_cat_grp_appl_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_FEATURE_CAT_GRP_APPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_feature_cat_grp_appl_action_product_feature_cat_grp_appl_read_read" module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CAT_GRP_APPL"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CAT_GRP_APPL"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CAT_GRP_APPL"
