[SCENARIO: BDD-OFBIZ_PARTY_COMM_EVENT_CONTENT_ASSOC-SEED-ofbiz_party_comm_event_content_assoc_action_comm_event_content_assoc_create_create] TITLE: OFBIZ_PARTY_COMM_EVENT_CONTENT_ASSOC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_comm_event_content_assoc_action_comm_event_content_assoc_create_create" module="OFBIZ_PARTY_COMM_EVENT_CONTENT_ASSOC"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_COMM_EVENT_CONTENT_ASSOC"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_COMM_EVENT_CONTENT_ASSOC"
