[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_STATUS-SEED-ofbiz_accounting_invoice_status_action_invoice_status_read_read] TITLE: OFBIZ_ACCOUNTING_INVOICE_STATUS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_status_action_invoice_status_read_read" module="OFBIZ_ACCOUNTING_INVOICE_STATUS"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_STATUS"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_STATUS"
