[SCENARIO: BDD-OFBIZ_ORDER_REQUIREMENT_STATUS-SEED-ofbiz_order_requirement_status_action_requirement_status_create_create] TITLE: OFBIZ_ORDER_REQUIREMENT_STATUS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_requirement_status_action_requirement_status_create_create" module="OFBIZ_ORDER_REQUIREMENT_STATUS"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_REQUIREMENT_STATUS"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_REQUIREMENT_STATUS"
