[SCENARIO: BDD-OFBIZ_ORDER_SHOPPING_LIST_TYPE-SEED-ofbiz_order_shopping_list_type_action_shopping_list_type_destroy_destroy] TITLE: OFBIZ_ORDER_SHOPPING_LIST_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_shopping_list_type_action_shopping_list_type_destroy_destroy" module="OFBIZ_ORDER_SHOPPING_LIST_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_SHOPPING_LIST_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_SHOPPING_LIST_TYPE"
