[SCENARIO: BDD-OFBIZ_CONTENT_SURVEY_QUESTION-SEED-ofbiz_content_survey_question_action_survey_question_destroy_destroy] TITLE: OFBIZ_CONTENT_SURVEY_QUESTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_survey_question_action_survey_question_destroy_destroy" module="OFBIZ_CONTENT_SURVEY_QUESTION"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_SURVEY_QUESTION"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_SURVEY_QUESTION"
