[SCENARIO: BDD-OFBIZ_PARTY_PARTY_NAME_HISTORY-SEED-ofbiz_party_party_name_history_action_party_name_history_update_update] TITLE: OFBIZ_PARTY_PARTY_NAME_HISTORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_name_history_action_party_name_history_update_update" module="OFBIZ_PARTY_PARTY_NAME_HISTORY"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_NAME_HISTORY"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_NAME_HISTORY"
