[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE-SEED-ofbiz_accounting_fixed_asset_type_action_fixed_asset_type_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_type_action_fixed_asset_type_destroy_destroy" module="OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE"
