[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_TRANS_BOX-SEED-ofbiz_work_effort_work_effort_trans_box_action_work_effort_trans_box_update_update] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_TRANS_BOX contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_trans_box_action_work_effort_trans_box_update_update" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_TRANS_BOX"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_TRANS_BOX"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_TRANS_BOX"
