[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_MAINT-SEED-ofbiz_product_product_maint_action_product_maint_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_MAINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_maint_action_product_maint_read_read" module="OFBIZ_PRODUCT_PRODUCT_MAINT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_MAINT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_MAINT"
