[SCENARIO: BDD-OFBIZ_ORDER_ORDER_DELIVERY_SCHEDULE-SEED-ofbiz_order_order_delivery_schedule_action_order_delivery_schedule_create_create] TITLE: OFBIZ_ORDER_ORDER_DELIVERY_SCHEDULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_delivery_schedule_action_order_delivery_schedule_create_create" module="OFBIZ_ORDER_ORDER_DELIVERY_SCHEDULE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_DELIVERY_SCHEDULE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_DELIVERY_SCHEDULE"
