[SCENARIO: BDD-OFBIZ_ORDER_ORDER_SUMMARY_ENTRY-SEED-ofbiz_order_order_summary_entry_action_order_summary_entry_update_update] TITLE: OFBIZ_ORDER_ORDER_SUMMARY_ENTRY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_summary_entry_action_order_summary_entry_update_update" module="OFBIZ_ORDER_ORDER_SUMMARY_ENTRY"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_SUMMARY_ENTRY"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_SUMMARY_ENTRY"
