[SCENARIO: BDD-OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_TYPE-SEED-ofbiz_accounting_gl_account_category_type_action_gl_account_category_type_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_gl_account_category_type_action_gl_account_category_type_destroy_destroy" module="OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_GL_ACCOUNT_CATEGORY_TYPE"
