[SCENARIO: BDD-OFBIZ_PARTY_COMMUNICATION_EVENT-SEED-ofbiz_party_communication_event_action_communication_event_destroy_destroy] TITLE: OFBIZ_PARTY_COMMUNICATION_EVENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_communication_event_action_communication_event_destroy_destroy" module="OFBIZ_PARTY_COMMUNICATION_EVENT"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_COMMUNICATION_EVENT"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_COMMUNICATION_EVENT"
