[SCENARIO: BDD-OFBIZ_HUMAN_RES_BENEFIT_TYPE-SEED-ofbiz_human_res_benefit_type_action_benefit_type_destroy_destroy] TITLE: OFBIZ_HUMAN_RES_BENEFIT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_benefit_type_action_benefit_type_destroy_destroy" module="OFBIZ_HUMAN_RES_BENEFIT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_BENEFIT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_BENEFIT_TYPE"
