[SCENARIO: BDD-OFBIZ_CONTENT_IMAGE_DATA_RESOURCE-SEED-ofbiz_content_image_data_resource_action_image_data_resource_destroy_destroy] TITLE: OFBIZ_CONTENT_IMAGE_DATA_RESOURCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_image_data_resource_action_image_data_resource_destroy_destroy" module="OFBIZ_CONTENT_IMAGE_DATA_RESOURCE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_IMAGE_DATA_RESOURCE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_IMAGE_DATA_RESOURCE"
