[SCENARIO: BDD-OFBIZ_SHIPMENT_CARRIER_SHIPMENT_METHOD-SEED-ofbiz_shipment_carrier_shipment_method_action_carrier_shipment_method_read_read] TITLE: OFBIZ_SHIPMENT_CARRIER_SHIPMENT_METHOD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_carrier_shipment_method_action_carrier_shipment_method_read_read" module="OFBIZ_SHIPMENT_CARRIER_SHIPMENT_METHOD"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_CARRIER_SHIPMENT_METHOD"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_CARRIER_SHIPMENT_METHOD"
