[SCENARIO: BDD-OFBIZ_PARTY_EMAIL_ADDRESS_VERIFICATION-SEED-ofbiz_party_email_address_verification_action_email_address_verification_create_create] TITLE: OFBIZ_PARTY_EMAIL_ADDRESS_VERIFICATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_email_address_verification_action_email_address_verification_create_create" module="OFBIZ_PARTY_EMAIL_ADDRESS_VERIFICATION"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_EMAIL_ADDRESS_VERIFICATION"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_EMAIL_ADDRESS_VERIFICATION"
