[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET_PRODUCT_TYPE-SEED-ofbiz_accounting_fixed_asset_product_type_action_fixed_asset_product_type_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET_PRODUCT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_product_type_action_fixed_asset_product_type_destroy_destroy" module="OFBIZ_ACCOUNTING_FIXED_ASSET_PRODUCT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET_PRODUCT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET_PRODUCT_TYPE"
