[SCENARIO: BDD-OFBIZ_PRODUCT_GOOD_IDENTIFICATION-SEED-ofbiz_product_good_identification_action_good_identification_read_read] TITLE: OFBIZ_PRODUCT_GOOD_IDENTIFICATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_good_identification_action_good_identification_read_read" module="OFBIZ_PRODUCT_GOOD_IDENTIFICATION"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_GOOD_IDENTIFICATION"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_GOOD_IDENTIFICATION"
