[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_TELECOM_SETTING-SEED-ofbiz_product_product_store_telecom_setting_action_product_store_telecom_setting_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_TELECOM_SETTING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_telecom_setting_action_product_store_telecom_setting_update_update" module="OFBIZ_PRODUCT_PRODUCT_STORE_TELECOM_SETTING"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_TELECOM_SETTING"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_TELECOM_SETTING"
