[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_PARTY_APPLIC-SEED-ofbiz_party_agreement_party_applic_action_agreement_party_applic_update_update] TITLE: OFBIZ_PARTY_AGREEMENT_PARTY_APPLIC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_party_applic_action_agreement_party_applic_update_update" module="OFBIZ_PARTY_AGREEMENT_PARTY_APPLIC"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_PARTY_APPLIC"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_PARTY_APPLIC"
