[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_FACILITY_ASSOC-SEED-ofbiz_product_product_facility_assoc_action_product_facility_assoc_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_FACILITY_ASSOC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_facility_assoc_action_product_facility_assoc_read_read" module="OFBIZ_PRODUCT_PRODUCT_FACILITY_ASSOC"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_FACILITY_ASSOC"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_FACILITY_ASSOC"
