[SCENARIO: BDD-OFBIZ_ORDER_CUST_REQUEST_TYPE-SEED-ofbiz_order_cust_request_type_action_cust_request_type_create_create] TITLE: OFBIZ_ORDER_CUST_REQUEST_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_cust_request_type_action_cust_request_type_create_create" module="OFBIZ_ORDER_CUST_REQUEST_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_CUST_REQUEST_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_CUST_REQUEST_TYPE"
