[SCENARIO: BDD-OFBIZ_PARTY_PARTY_NOTE-SEED-ofbiz_party_party_note_action_party_note_destroy_destroy] TITLE: OFBIZ_PARTY_PARTY_NOTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_note_action_party_note_destroy_destroy" module="OFBIZ_PARTY_PARTY_NOTE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_NOTE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_NOTE"
