[SCENARIO: BDD-OFBIZ_MARKETING_MARKETING_CAMPAIGN-SEED-ofbiz_marketing_marketing_campaign_action_marketing_campaign_read_read] TITLE: OFBIZ_MARKETING_MARKETING_CAMPAIGN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_marketing_campaign_action_marketing_campaign_read_read" module="OFBIZ_MARKETING_MARKETING_CAMPAIGN"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_MARKETING_CAMPAIGN"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_MARKETING_CAMPAIGN"
