[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ADJUSTMENT_ATTRIBUTE-SEED-ofbiz_order_order_adjustment_attribute_action_order_adjustment_attribute_read_read] TITLE: OFBIZ_ORDER_ORDER_ADJUSTMENT_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_adjustment_attribute_action_order_adjustment_attribute_read_read" module="OFBIZ_ORDER_ORDER_ADJUSTMENT_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ADJUSTMENT_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ADJUSTMENT_ATTRIBUTE"
