[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_PRODUCT_APPL-SEED-ofbiz_party_agreement_product_appl_action_agreement_product_appl_update_update] TITLE: OFBIZ_PARTY_AGREEMENT_PRODUCT_APPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_product_appl_action_agreement_product_appl_update_update" module="OFBIZ_PARTY_AGREEMENT_PRODUCT_APPL"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_PRODUCT_APPL"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_PRODUCT_APPL"
