[SCENARIO: BDD-OFBIZ_HUMAN_RES_PAY_GRADE-SEED-ofbiz_human_res_pay_grade_action_pay_grade_update_update] TITLE: OFBIZ_HUMAN_RES_PAY_GRADE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_pay_grade_action_pay_grade_update_update" module="OFBIZ_HUMAN_RES_PAY_GRADE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_PAY_GRADE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_PAY_GRADE"
