[SCENARIO: BDD-OFBIZ_HUMAN_RES_PARTY_RESUME-SEED-ofbiz_human_res_party_resume_action_party_resume_update_update] TITLE: OFBIZ_HUMAN_RES_PARTY_RESUME contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_party_resume_action_party_resume_update_update" module="OFBIZ_HUMAN_RES_PARTY_RESUME"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_PARTY_RESUME"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_PARTY_RESUME"
