[SCENARIO: BDD-OFBIZ_COMMON_USER_PREFERENCE-SEED-ofbiz_common_user_preference_action_user_preference_update_update] TITLE: OFBIZ_COMMON_USER_PREFERENCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_user_preference_action_user_preference_update_update" module="OFBIZ_COMMON_USER_PREFERENCE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_USER_PREFERENCE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_USER_PREFERENCE"
