[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PRICE-SEED-ofbiz_product_product_price_action_product_price_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_PRICE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_price_action_product_price_read_read" module="OFBIZ_PRODUCT_PRODUCT_PRICE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PRICE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PRICE"
