[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD_TYPE-SEED-ofbiz_work_effort_work_effort_good_standard_type_action_work_effort_good_standard_type_read_read] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_good_standard_type_action_work_effort_good_standard_type_read_read" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD_TYPE"
