[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_DHL-SEED-ofbiz_shipment_shipment_gateway_dhl_action_shipment_gateway_dhl_create_create] TITLE: OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_DHL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_gateway_dhl_action_shipment_gateway_dhl_create_create" module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_DHL"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_DHL"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_DHL"
