[SCENARIO: BDD-OFBIZ_SHIPMENT_PICKLIST_BIN-SEED-ofbiz_shipment_picklist_bin_action_picklist_bin_update_update] TITLE: OFBIZ_SHIPMENT_PICKLIST_BIN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_picklist_bin_action_picklist_bin_update_update" module="OFBIZ_SHIPMENT_PICKLIST_BIN"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_PICKLIST_BIN"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_PICKLIST_BIN"
