[SCENARIO: BDD-OFBIZ_PRODUCT_SUBSCRIPTION_TYPE-SEED-ofbiz_product_subscription_type_action_subscription_type_update_update] TITLE: OFBIZ_PRODUCT_SUBSCRIPTION_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_subscription_type_action_subscription_type_update_update" module="OFBIZ_PRODUCT_SUBSCRIPTION_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_SUBSCRIPTION_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_SUBSCRIPTION_TYPE"
