[SCENARIO: BDD-OFBIZ_PARTY_PARTY_IDENTIFICATION-SEED-ofbiz_party_party_identification_action_party_identification_read_read] TITLE: OFBIZ_PARTY_PARTY_IDENTIFICATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_identification_action_party_identification_read_read" module="OFBIZ_PARTY_PARTY_IDENTIFICATION"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_IDENTIFICATION"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_IDENTIFICATION"
