[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE_MAP-SEED-ofbiz_accounting_invoice_item_type_map_action_invoice_item_type_map_read_read] TITLE: OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE_MAP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_item_type_map_action_invoice_item_type_map_read_read" module="OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE_MAP"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE_MAP"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_ITEM_TYPE_MAP"
