[SCENARIO: BDD-OFBIZ_ORDER_QUOTE_WORK_EFFORT-SEED-ofbiz_order_quote_work_effort_action_quote_work_effort_create_create] TITLE: OFBIZ_ORDER_QUOTE_WORK_EFFORT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_quote_work_effort_action_quote_work_effort_create_create" module="OFBIZ_ORDER_QUOTE_WORK_EFFORT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_QUOTE_WORK_EFFORT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_QUOTE_WORK_EFFORT"
