[SCENARIO: BDD-OFBIZ_ACCOUNTING_PARTY_ACCTG_PREFERENCE-SEED-ofbiz_accounting_party_acctg_preference_action_party_acctg_preference_read_read] TITLE: OFBIZ_ACCOUNTING_PARTY_ACCTG_PREFERENCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_party_acctg_preference_action_party_acctg_preference_read_read" module="OFBIZ_ACCOUNTING_PARTY_ACCTG_PREFERENCE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PARTY_ACCTG_PREFERENCE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PARTY_ACCTG_PREFERENCE"
