[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_KEYWORD_OVRD-SEED-ofbiz_product_product_store_keyword_ovrd_action_product_store_keyword_ovrd_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_KEYWORD_OVRD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_keyword_ovrd_action_product_store_keyword_ovrd_read_read" module="OFBIZ_PRODUCT_PRODUCT_STORE_KEYWORD_OVRD"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_KEYWORD_OVRD"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_KEYWORD_OVRD"
