[SCENARIO: BDD-OFBIZ_ACCOUNTING_GL_ACCOUNT_ORGANIZATION-SEED-ofbiz_accounting_gl_account_organization_action_gl_account_organization_read_read] TITLE: OFBIZ_ACCOUNTING_GL_ACCOUNT_ORGANIZATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_gl_account_organization_action_gl_account_organization_read_read" module="OFBIZ_ACCOUNTING_GL_ACCOUNT_ORGANIZATION"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_GL_ACCOUNT_ORGANIZATION"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_GL_ACCOUNT_ORGANIZATION"
