[SCENARIO: BDD-OFBIZ_MARKETING_CONTACT_LIST_PARTY-SEED-ofbiz_marketing_contact_list_party_action_contact_list_party_update_update] TITLE: OFBIZ_MARKETING_CONTACT_LIST_PARTY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_contact_list_party_action_contact_list_party_update_update" module="OFBIZ_MARKETING_CONTACT_LIST_PARTY"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_CONTACT_LIST_PARTY"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_CONTACT_LIST_PARTY"
