[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_LEAVE_REASON_TYPE-SEED-ofbiz_human_res_empl_leave_reason_type_action_empl_leave_reason_type_read_read] TITLE: OFBIZ_HUMAN_RES_EMPL_LEAVE_REASON_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_leave_reason_type_action_empl_leave_reason_type_read_read" module="OFBIZ_HUMAN_RES_EMPL_LEAVE_REASON_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_LEAVE_REASON_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_LEAVE_REASON_TYPE"
