[SCENARIO: BDD-OFBIZ_SERVICE_TEMPORAL_EXPRESSION_ASSOC-SEED-ofbiz_service_temporal_expression_assoc_action_temporal_expression_assoc_update_update] TITLE: OFBIZ_SERVICE_TEMPORAL_EXPRESSION_ASSOC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_service_temporal_expression_assoc_action_temporal_expression_assoc_update_update" module="OFBIZ_SERVICE_TEMPORAL_EXPRESSION_ASSOC"
WHEN when_execute_seed_contract module="OFBIZ_SERVICE_TEMPORAL_EXPRESSION_ASSOC"
THEN then_seed_contract_should_hold module="OFBIZ_SERVICE_TEMPORAL_EXPRESSION_ASSOC"
