[SCENARIO: BDD-OFBIZ_ORDER_REQUIREMENT_ATTRIBUTE-SEED-ofbiz_order_requirement_attribute_action_requirement_attribute_destroy_destroy] TITLE: OFBIZ_ORDER_REQUIREMENT_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_requirement_attribute_action_requirement_attribute_destroy_destroy" module="OFBIZ_ORDER_REQUIREMENT_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_REQUIREMENT_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_REQUIREMENT_ATTRIBUTE"
