[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PROMO_CATEGORY-SEED-ofbiz_product_product_promo_category_action_product_promo_category_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_PROMO_CATEGORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_promo_category_action_product_promo_category_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_PROMO_CATEGORY"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PROMO_CATEGORY"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PROMO_CATEGORY"
