[SCENARIO: BDD-OFBIZ_ACCOUNTING_BUDGET_REVISION_IMPACT-SEED-ofbiz_accounting_budget_revision_impact_action_budget_revision_impact_create_create] TITLE: OFBIZ_ACCOUNTING_BUDGET_REVISION_IMPACT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_budget_revision_impact_action_budget_revision_impact_create_create" module="OFBIZ_ACCOUNTING_BUDGET_REVISION_IMPACT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_BUDGET_REVISION_IMPACT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_BUDGET_REVISION_IMPACT"
