[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPLOYMENT-SEED-ofbiz_human_res_employment_action_employment_read_read] TITLE: OFBIZ_HUMAN_RES_EMPLOYMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_employment_action_employment_read_read" module="OFBIZ_HUMAN_RES_EMPLOYMENT"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPLOYMENT"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPLOYMENT"
