[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_STATUS-SEED-ofbiz_work_effort_work_effort_status_action_work_effort_status_create_create] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_STATUS contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_status_action_work_effort_status_create_create" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_STATUS"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_STATUS"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_STATUS"
