[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_RECEIPT-SEED-ofbiz_shipment_shipment_receipt_action_shipment_receipt_update_update] TITLE: OFBIZ_SHIPMENT_SHIPMENT_RECEIPT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_receipt_action_shipment_receipt_update_update" module="OFBIZ_SHIPMENT_SHIPMENT_RECEIPT"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_RECEIPT"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_RECEIPT"
