[SCENARIO: BDD-OFBIZ_ACCOUNTING_PARTY_PREF_DOC_TYPE_TPL-SEED-ofbiz_accounting_party_pref_doc_type_tpl_action_party_pref_doc_type_tpl_create_create] TITLE: OFBIZ_ACCOUNTING_PARTY_PREF_DOC_TYPE_TPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_party_pref_doc_type_tpl_action_party_pref_doc_type_tpl_create_create" module="OFBIZ_ACCOUNTING_PARTY_PREF_DOC_TYPE_TPL"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PARTY_PREF_DOC_TYPE_TPL"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PARTY_PREF_DOC_TYPE_TPL"
