[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_LEAVE-SEED-ofbiz_human_res_empl_leave_action_empl_leave_read_read] TITLE: OFBIZ_HUMAN_RES_EMPL_LEAVE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_leave_action_empl_leave_read_read" module="OFBIZ_HUMAN_RES_EMPL_LEAVE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_LEAVE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_LEAVE"
