[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_FEATURE_DATA_RESOURCE-SEED-ofbiz_product_product_feature_data_resource_action_product_feature_data_resource_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_FEATURE_DATA_RESOURCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_feature_data_resource_action_product_feature_data_resource_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_FEATURE_DATA_RESOURCE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_FEATURE_DATA_RESOURCE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_FEATURE_DATA_RESOURCE"
