[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_TERM_ATTRIBUTE-SEED-ofbiz_accounting_invoice_term_attribute_action_invoice_term_attribute_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_INVOICE_TERM_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_term_attribute_action_invoice_term_attribute_destroy_destroy" module="OFBIZ_ACCOUNTING_INVOICE_TERM_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_TERM_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_TERM_ATTRIBUTE"
