[SCENARIO: BDD-OFBIZ_PRODUCT_COST_COMPONENT_TYPE_ATTR-SEED-ofbiz_product_cost_component_type_attr_action_cost_component_type_attr_update_update] TITLE: OFBIZ_PRODUCT_COST_COMPONENT_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_cost_component_type_attr_action_cost_component_type_attr_update_update" module="OFBIZ_PRODUCT_COST_COMPONENT_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_COST_COMPONENT_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_COST_COMPONENT_TYPE_ATTR"
