[SCENARIO: BDD-OFBIZ_PRODUCT_SUBSCRIPTION-SEED-ofbiz_product_subscription_action_subscription_create_create] TITLE: OFBIZ_PRODUCT_SUBSCRIPTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_subscription_action_subscription_create_create" module="OFBIZ_PRODUCT_SUBSCRIPTION"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_SUBSCRIPTION"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_SUBSCRIPTION"
