[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_CONTENT-SEED-ofbiz_accounting_payment_content_action_payment_content_read_read] TITLE: OFBIZ_ACCOUNTING_PAYMENT_CONTENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_content_action_payment_content_read_read" module="OFBIZ_ACCOUNTING_PAYMENT_CONTENT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_CONTENT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_CONTENT"
