[SCENARIO: BDD-OFBIZ_ORDER_COMMUNICATION_EVENT_ORDER-SEED-ofbiz_order_communication_event_order_action_communication_event_order_create_create] TITLE: OFBIZ_ORDER_COMMUNICATION_EVENT_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_communication_event_order_action_communication_event_order_create_create" module="OFBIZ_ORDER_COMMUNICATION_EVENT_ORDER"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_COMMUNICATION_EVENT_ORDER"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_COMMUNICATION_EVENT_ORDER"
