[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_TERM-SEED-ofbiz_accounting_invoice_term_action_invoice_term_update_update] TITLE: OFBIZ_ACCOUNTING_INVOICE_TERM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_term_action_invoice_term_update_update" module="OFBIZ_ACCOUNTING_INVOICE_TERM"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_TERM"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_TERM"
