[SCENARIO: BDD-OFBIZ_PRODUCT_SUPPLIER_PRODUCT_FEATURE-SEED-ofbiz_product_supplier_product_feature_action_supplier_product_feature_update_update] TITLE: OFBIZ_PRODUCT_SUPPLIER_PRODUCT_FEATURE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_supplier_product_feature_action_supplier_product_feature_update_update" module="OFBIZ_PRODUCT_SUPPLIER_PRODUCT_FEATURE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_SUPPLIER_PRODUCT_FEATURE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_SUPPLIER_PRODUCT_FEATURE"
