[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_CONTENT-SEED-ofbiz_party_agreement_content_action_agreement_content_read_read] TITLE: OFBIZ_PARTY_AGREEMENT_CONTENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_content_action_agreement_content_read_read" module="OFBIZ_PARTY_AGREEMENT_CONTENT"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_CONTENT"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_CONTENT"
