[SCENARIO: BDD-OFBIZ_COMMON_UOM_GROUP-SEED-ofbiz_common_uom_group_action_uom_group_read_read] TITLE: OFBIZ_COMMON_UOM_GROUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_uom_group_action_uom_group_read_read" module="OFBIZ_COMMON_UOM_GROUP"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_UOM_GROUP"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_UOM_GROUP"
