[SCENARIO: BDD-OFBIZ_SHIPMENT_OLD_PICKLIST_STATUS_HISTORY-SEED-ofbiz_shipment_old_picklist_status_history_action_old_picklist_status_history_read_read] TITLE: OFBIZ_SHIPMENT_OLD_PICKLIST_STATUS_HISTORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_old_picklist_status_history_action_old_picklist_status_history_read_read" module="OFBIZ_SHIPMENT_OLD_PICKLIST_STATUS_HISTORY"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_OLD_PICKLIST_STATUS_HISTORY"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_OLD_PICKLIST_STATUS_HISTORY"
