[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIN_ACCOUNT_AUTH-SEED-ofbiz_accounting_fin_account_auth_action_fin_account_auth_read_read] TITLE: OFBIZ_ACCOUNTING_FIN_ACCOUNT_AUTH contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fin_account_auth_action_fin_account_auth_read_read" module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_AUTH"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_AUTH"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_AUTH"
