[SCENARIO: BDD-OFBIZ_ACCOUNTING_ACCTG_TRANS_TYPE_ATTR-SEED-ofbiz_accounting_acctg_trans_type_attr_action_acctg_trans_type_attr_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_ACCTG_TRANS_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_acctg_trans_type_attr_action_acctg_trans_type_attr_destroy_destroy" module="OFBIZ_ACCOUNTING_ACCTG_TRANS_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_ACCTG_TRANS_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_ACCTG_TRANS_TYPE_ATTR"
