[SCENARIO: BDD-OFBIZ_MANUFACTURING_PRODUCT_MANUFACTURING_RULE-SEED-ofbiz_manufacturing_product_manufacturing_rule_action_product_manufacturing_rule_read_read] TITLE: OFBIZ_MANUFACTURING_PRODUCT_MANUFACTURING_RULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_manufacturing_product_manufacturing_rule_action_product_manufacturing_rule_read_read" module="OFBIZ_MANUFACTURING_PRODUCT_MANUFACTURING_RULE"
WHEN when_execute_seed_contract module="OFBIZ_MANUFACTURING_PRODUCT_MANUFACTURING_RULE"
THEN then_seed_contract_should_hold module="OFBIZ_MANUFACTURING_PRODUCT_MANUFACTURING_RULE"
