[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_ICAL_DATA-SEED-ofbiz_work_effort_work_effort_ical_data_action_work_effort_ical_data_create_create] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_ICAL_DATA contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_ical_data_action_work_effort_ical_data_create_create" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_ICAL_DATA"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_ICAL_DATA"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_ICAL_DATA"
