[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET_STD_COST_TYPE-SEED-ofbiz_accounting_fixed_asset_std_cost_type_action_fixed_asset_std_cost_type_read_read] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET_STD_COST_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_std_cost_type_action_fixed_asset_std_cost_type_read_read" module="OFBIZ_ACCOUNTING_FIXED_ASSET_STD_COST_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET_STD_COST_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET_STD_COST_TYPE"
