[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GL_ACCOUNT_TYPE_MAP-SEED-ofbiz_accounting_payment_gl_account_type_map_action_payment_gl_account_type_map_update_update] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GL_ACCOUNT_TYPE_MAP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gl_account_type_map_action_payment_gl_account_type_map_update_update" module="OFBIZ_ACCOUNTING_PAYMENT_GL_ACCOUNT_TYPE_MAP"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GL_ACCOUNT_TYPE_MAP"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GL_ACCOUNT_TYPE_MAP"
