[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CATEGORY_CONTENT-SEED-ofbiz_product_product_category_content_action_product_category_content_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_CATEGORY_CONTENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_category_content_action_product_category_content_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_CONTENT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_CONTENT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CATEGORY_CONTENT"
