[SCENARIO: BDD-OFBIZ_MARKETING_WEB_SITE_CONTACT_LIST-SEED-ofbiz_marketing_web_site_contact_list_action_web_site_contact_list_destroy_destroy] TITLE: OFBIZ_MARKETING_WEB_SITE_CONTACT_LIST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_web_site_contact_list_action_web_site_contact_list_destroy_destroy" module="OFBIZ_MARKETING_WEB_SITE_CONTACT_LIST"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_WEB_SITE_CONTACT_LIST"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_WEB_SITE_CONTACT_LIST"
