[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_CONFIG-SEED-ofbiz_shipment_shipment_gateway_config_action_shipment_gateway_config_destroy_destroy] TITLE: OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_CONFIG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_gateway_config_action_shipment_gateway_config_destroy_destroy" module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_CONFIG"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_CONFIG"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_GATEWAY_CONFIG"
