[SCENARIO: BDD-OFBIZ_PARTY_PARTY_PROFILE_DEFAULT-SEED-ofbiz_party_party_profile_default_action_party_profile_default_read_read] TITLE: OFBIZ_PARTY_PARTY_PROFILE_DEFAULT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_profile_default_action_party_profile_default_read_read" module="OFBIZ_PARTY_PARTY_PROFILE_DEFAULT"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_PROFILE_DEFAULT"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_PROFILE_DEFAULT"
