[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAY_PAL-SEED-ofbiz_accounting_payment_gateway_pay_pal_action_payment_gateway_pay_pal_create_create] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAY_PAL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_pay_pal_action_payment_gateway_pay_pal_create_create" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAY_PAL"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAY_PAL"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_PAY_PAL"
