[SCENARIO: BDD-OFBIZ_MARKETING_MARKETING_CAMPAIGN_PROMO-SEED-ofbiz_marketing_marketing_campaign_promo_action_marketing_campaign_promo_update_update] TITLE: OFBIZ_MARKETING_MARKETING_CAMPAIGN_PROMO contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_marketing_campaign_promo_action_marketing_campaign_promo_update_update" module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_PROMO"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_PROMO"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_MARKETING_CAMPAIGN_PROMO"
