[SCENARIO: BDD-OFBIZ_ORDER_OLD_ORDER_BLACKLIST-SEED-ofbiz_order_old_order_blacklist_action_old_order_blacklist_destroy_destroy] TITLE: OFBIZ_ORDER_OLD_ORDER_BLACKLIST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_old_order_blacklist_action_old_order_blacklist_destroy_destroy" module="OFBIZ_ORDER_OLD_ORDER_BLACKLIST"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_OLD_ORDER_BLACKLIST"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_OLD_ORDER_BLACKLIST"
