[SCENARIO: BDD-OFBIZ_PRODUCT_PROD_CATALOG_ROLE-SEED-ofbiz_product_prod_catalog_role_action_prod_catalog_role_read_read] TITLE: OFBIZ_PRODUCT_PROD_CATALOG_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_prod_catalog_role_action_prod_catalog_role_read_read" module="OFBIZ_PRODUCT_PROD_CATALOG_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PROD_CATALOG_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PROD_CATALOG_ROLE"
