[SCENARIO: BDD-OFBIZ_PARTY_POSTAL_ADDRESS_BOUNDARY-SEED-ofbiz_party_postal_address_boundary_action_postal_address_boundary_update_update] TITLE: OFBIZ_PARTY_POSTAL_ADDRESS_BOUNDARY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_postal_address_boundary_action_postal_address_boundary_update_update" module="OFBIZ_PARTY_POSTAL_ADDRESS_BOUNDARY"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_POSTAL_ADDRESS_BOUNDARY"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_POSTAL_ADDRESS_BOUNDARY"
