[SCENARIO: BDD-OFBIZ_ORDER_QUOTE_COEFFICIENT-SEED-ofbiz_order_quote_coefficient_action_quote_coefficient_destroy_destroy] TITLE: OFBIZ_ORDER_QUOTE_COEFFICIENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_quote_coefficient_action_quote_coefficient_destroy_destroy" module="OFBIZ_ORDER_QUOTE_COEFFICIENT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_QUOTE_COEFFICIENT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_QUOTE_COEFFICIENT"
