[SCENARIO: BDD-OFBIZ_CONTENT_SURVEY_MULTI_RESP-SEED-ofbiz_content_survey_multi_resp_action_survey_multi_resp_read_read] TITLE: OFBIZ_CONTENT_SURVEY_MULTI_RESP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_survey_multi_resp_action_survey_multi_resp_read_read" module="OFBIZ_CONTENT_SURVEY_MULTI_RESP"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_SURVEY_MULTI_RESP"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_SURVEY_MULTI_RESP"
