[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESP_MSG-SEED-ofbiz_accounting_payment_gateway_resp_msg_action_payment_gateway_resp_msg_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESP_MSG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_resp_msg_action_payment_gateway_resp_msg_destroy_destroy" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESP_MSG"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESP_MSG"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESP_MSG"
