[SCENARIO: BDD-OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM-SEED-ofbiz_accounting_billing_account_term_action_billing_account_term_update_update] TITLE: OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_billing_account_term_action_billing_account_term_update_update" module="OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM"
