[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_EWAY-SEED-ofbiz_accounting_payment_gateway_eway_action_payment_gateway_eway_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_EWAY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_eway_action_payment_gateway_eway_destroy_destroy" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_EWAY"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_EWAY"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_EWAY"
