[SCENARIO: BDD-OFBIZ_CONTENT_CONTENT_KEYWORD-SEED-ofbiz_content_content_keyword_action_content_keyword_update_update] TITLE: OFBIZ_CONTENT_CONTENT_KEYWORD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_content_keyword_action_content_keyword_update_update" module="OFBIZ_CONTENT_CONTENT_KEYWORD"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_CONTENT_KEYWORD"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_CONTENT_KEYWORD"
