[SCENARIO: BDD-OFBIZ_PARTY_PARTY_ATTRIBUTE-SEED-ofbiz_party_party_attribute_action_party_attribute_create_create] TITLE: OFBIZ_PARTY_PARTY_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_attribute_action_party_attribute_create_create" module="OFBIZ_PARTY_PARTY_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_ATTRIBUTE"
