[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_POSITION-SEED-ofbiz_human_res_empl_position_action_empl_position_destroy_destroy] TITLE: OFBIZ_HUMAN_RES_EMPL_POSITION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_position_action_empl_position_destroy_destroy" module="OFBIZ_HUMAN_RES_EMPL_POSITION"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_POSITION"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_POSITION"
