[SCENARIO: BDD-OFBIZ_ORDER_RESPONDING_PARTY-SEED-ofbiz_order_responding_party_action_responding_party_destroy_destroy] TITLE: OFBIZ_ORDER_RESPONDING_PARTY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_responding_party_action_responding_party_destroy_destroy" module="OFBIZ_ORDER_RESPONDING_PARTY"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_RESPONDING_PARTY"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_RESPONDING_PARTY"
