[SCENARIO: BDD-OFBIZ_MARKETING_CONTACT_LIST_TYPE-SEED-ofbiz_marketing_contact_list_type_action_contact_list_type_read_read] TITLE: OFBIZ_MARKETING_CONTACT_LIST_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_contact_list_type_action_contact_list_type_read_read" module="OFBIZ_MARKETING_CONTACT_LIST_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_CONTACT_LIST_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_CONTACT_LIST_TYPE"
