[SCENARIO: BDD-OFBIZ_SHIPMENT_PICKLIST_ROLE-SEED-ofbiz_shipment_picklist_role_action_picklist_role_read_read] TITLE: OFBIZ_SHIPMENT_PICKLIST_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_picklist_role_action_picklist_role_read_read" module="OFBIZ_SHIPMENT_PICKLIST_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_PICKLIST_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_PICKLIST_ROLE"
