[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_CYBER_SOURCE-SEED-ofbiz_accounting_payment_gateway_cyber_source_action_payment_gateway_cyber_source_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_CYBER_SOURCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_cyber_source_action_payment_gateway_cyber_source_destroy_destroy" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_CYBER_SOURCE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_CYBER_SOURCE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_CYBER_SOURCE"
