[SCENARIO: BDD-OFBIZ_PRODUCT_PROD_CATALOG-SEED-ofbiz_product_prod_catalog_action_prod_catalog_destroy_destroy] TITLE: OFBIZ_PRODUCT_PROD_CATALOG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_prod_catalog_action_prod_catalog_destroy_destroy" module="OFBIZ_PRODUCT_PROD_CATALOG"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PROD_CATALOG"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PROD_CATALOG"
