[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY-SEED-ofbiz_product_product_feature_category_action_product_feature_category_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_feature_category_action_product_feature_category_create_create" module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_FEATURE_CATEGORY"
