[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_FEATURE_GROUP_APPL-SEED-ofbiz_product_product_feature_group_appl_action_product_feature_group_appl_destroy_destroy] TITLE: OFBIZ_PRODUCT_PRODUCT_FEATURE_GROUP_APPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_feature_group_appl_action_product_feature_group_appl_destroy_destroy" module="OFBIZ_PRODUCT_PRODUCT_FEATURE_GROUP_APPL"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_FEATURE_GROUP_APPL"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_FEATURE_GROUP_APPL"
