[SCENARIO: BDD-OFBIZ_SECURITY_USER_LOGIN_PASSWORD_HISTORY-SEED-ofbiz_security_user_login_password_history_action_user_login_password_history_update_update] TITLE: OFBIZ_SECURITY_USER_LOGIN_PASSWORD_HISTORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_security_user_login_password_history_action_user_login_password_history_update_update" module="OFBIZ_SECURITY_USER_LOGIN_PASSWORD_HISTORY"
WHEN when_execute_seed_contract module="OFBIZ_SECURITY_USER_LOGIN_PASSWORD_HISTORY"
THEN then_seed_contract_should_hold module="OFBIZ_SECURITY_USER_LOGIN_PASSWORD_HISTORY"
