[SCENARIO: BDD-OFBIZ_ACCOUNTING_GIFT_CARD-SEED-ofbiz_accounting_gift_card_action_gift_card_read_read] TITLE: OFBIZ_ACCOUNTING_GIFT_CARD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_gift_card_action_gift_card_read_read" module="OFBIZ_ACCOUNTING_GIFT_CARD"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_GIFT_CARD"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_GIFT_CARD"
