[SCENARIO: BDD-OFBIZ_ORDER_RETURN_ITEM_TYPE_MAP-SEED-ofbiz_order_return_item_type_map_action_return_item_type_map_read_read] TITLE: OFBIZ_ORDER_RETURN_ITEM_TYPE_MAP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_return_item_type_map_action_return_item_type_map_read_read" module="OFBIZ_ORDER_RETURN_ITEM_TYPE_MAP"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_RETURN_ITEM_TYPE_MAP"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_RETURN_ITEM_TYPE_MAP"
