[SCENARIO: BDD-OFBIZ_HUMAN_RES_RESPONSIBILITY_TYPE-SEED-ofbiz_human_res_responsibility_type_action_responsibility_type_update_update] TITLE: OFBIZ_HUMAN_RES_RESPONSIBILITY_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_responsibility_type_action_responsibility_type_update_update" module="OFBIZ_HUMAN_RES_RESPONSIBILITY_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_RESPONSIBILITY_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_RESPONSIBILITY_TYPE"
