[SCENARIO: BDD-OFBIZ_CONTENT_MIME_TYPE_HTML_TEMPLATE-SEED-ofbiz_content_mime_type_html_template_action_mime_type_html_template_read_read] TITLE: OFBIZ_CONTENT_MIME_TYPE_HTML_TEMPLATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_mime_type_html_template_action_mime_type_html_template_read_read" module="OFBIZ_CONTENT_MIME_TYPE_HTML_TEMPLATE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_MIME_TYPE_HTML_TEMPLATE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_MIME_TYPE_HTML_TEMPLATE"
