[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_SUBSCRIPTION_RESOURCE-SEED-ofbiz_product_product_subscription_resource_action_product_subscription_resource_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_SUBSCRIPTION_RESOURCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_subscription_resource_action_product_subscription_resource_update_update" module="OFBIZ_PRODUCT_PRODUCT_SUBSCRIPTION_RESOURCE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_SUBSCRIPTION_RESOURCE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_SUBSCRIPTION_RESOURCE"
