[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD-SEED-ofbiz_work_effort_work_effort_good_standard_action_work_effort_good_standard_create_create] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_good_standard_action_work_effort_good_standard_create_create" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_GOOD_STANDARD"
