[SCENARIO: BDD-OFBIZ_HUMAN_RES_PAY_HISTORY-SEED-ofbiz_human_res_pay_history_action_pay_history_destroy_destroy] TITLE: OFBIZ_HUMAN_RES_PAY_HISTORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_pay_history_action_pay_history_destroy_destroy" module="OFBIZ_HUMAN_RES_PAY_HISTORY"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_PAY_HISTORY"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_PAY_HISTORY"
