[SCENARIO: BDD-OFBIZ_ACCOUNTING_PARTY_TAX_AUTH_INFO-SEED-ofbiz_accounting_party_tax_auth_info_action_party_tax_auth_info_update_update] TITLE: OFBIZ_ACCOUNTING_PARTY_TAX_AUTH_INFO contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_party_tax_auth_info_action_party_tax_auth_info_update_update" module="OFBIZ_ACCOUNTING_PARTY_TAX_AUTH_INFO"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PARTY_TAX_AUTH_INFO"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PARTY_TAX_AUTH_INFO"
