[SCENARIO: BDD-OFBIZ_COMMON_GEO_TYPE-SEED-ofbiz_common_geo_type_action_geo_type_update_update] TITLE: OFBIZ_COMMON_GEO_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_geo_type_action_geo_type_update_update" module="OFBIZ_COMMON_GEO_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_GEO_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_GEO_TYPE"
