[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT-SEED-ofbiz_accounting_payment_action_payment_update_update] TITLE: OFBIZ_ACCOUNTING_PAYMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_action_payment_update_update" module="OFBIZ_ACCOUNTING_PAYMENT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT"
