[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_PAYMENT-SEED-ofbiz_product_product_store_vendor_payment_action_product_store_vendor_payment_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_PAYMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_store_vendor_payment_action_product_store_vendor_payment_read_read" module="OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_PAYMENT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_PAYMENT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_STORE_VENDOR_PAYMENT"
