[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET_DEP_METHOD-SEED-ofbiz_accounting_fixed_asset_dep_method_action_fixed_asset_dep_method_update_update] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET_DEP_METHOD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_dep_method_action_fixed_asset_dep_method_update_update" module="OFBIZ_ACCOUNTING_FIXED_ASSET_DEP_METHOD"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET_DEP_METHOD"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET_DEP_METHOD"
