[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE_ATTR-SEED-ofbiz_accounting_fixed_asset_type_attr_action_fixed_asset_type_attr_read_read] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_type_attr_action_fixed_asset_type_attr_read_read" module="OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET_TYPE_ATTR"
