[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_BUDGET_ALLOCATION-SEED-ofbiz_accounting_payment_budget_allocation_action_payment_budget_allocation_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_PAYMENT_BUDGET_ALLOCATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_budget_allocation_action_payment_budget_allocation_destroy_destroy" module="OFBIZ_ACCOUNTING_PAYMENT_BUDGET_ALLOCATION"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_BUDGET_ALLOCATION"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_BUDGET_ALLOCATION"
