[SCENARIO: BDD-OFBIZ_CONTENT_WEB_SITE_ROLE-SEED-ofbiz_content_web_site_role_action_web_site_role_update_update] TITLE: OFBIZ_CONTENT_WEB_SITE_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_web_site_role_action_web_site_role_update_update" module="OFBIZ_CONTENT_WEB_SITE_ROLE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_WEB_SITE_ROLE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_WEB_SITE_ROLE"
