[SCENARIO: BDD-OFBIZ_SERVICE_RUNTIME_DATA-SEED-ofbiz_service_runtime_data_action_runtime_data_read_read] TITLE: OFBIZ_SERVICE_RUNTIME_DATA contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_service_runtime_data_action_runtime_data_read_read" module="OFBIZ_SERVICE_RUNTIME_DATA"
WHEN when_execute_seed_contract module="OFBIZ_SERVICE_RUNTIME_DATA"
THEN then_seed_contract_should_hold module="OFBIZ_SERVICE_RUNTIME_DATA"
