[SCENARIO: BDD-OFBIZ_SECURITY_TARPITTED_LOGIN_VIEW-SEED-ofbiz_security_tarpitted_login_view_action_tarpitted_login_view_destroy_destroy] TITLE: OFBIZ_SECURITY_TARPITTED_LOGIN_VIEW contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_security_tarpitted_login_view_action_tarpitted_login_view_destroy_destroy" module="OFBIZ_SECURITY_TARPITTED_LOGIN_VIEW"
WHEN when_execute_seed_contract module="OFBIZ_SECURITY_TARPITTED_LOGIN_VIEW"
THEN then_seed_contract_should_hold module="OFBIZ_SECURITY_TARPITTED_LOGIN_VIEW"
