[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_ATTRIBUTE-SEED-ofbiz_party_agreement_attribute_action_agreement_attribute_destroy_destroy] TITLE: OFBIZ_PARTY_AGREEMENT_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_attribute_action_agreement_attribute_destroy_destroy" module="OFBIZ_PARTY_AGREEMENT_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_ATTRIBUTE"
