[SCENARIO: BDD-OFBIZ_CONTENT_CONTENT_ASSOC_PREDICATE-SEED-ofbiz_content_content_assoc_predicate_action_content_assoc_predicate_destroy_destroy] TITLE: OFBIZ_CONTENT_CONTENT_ASSOC_PREDICATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_content_assoc_predicate_action_content_assoc_predicate_destroy_destroy" module="OFBIZ_CONTENT_CONTENT_ASSOC_PREDICATE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_CONTENT_ASSOC_PREDICATE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_CONTENT_ASSOC_PREDICATE"
