[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_CONTENT-SEED-ofbiz_accounting_invoice_content_action_invoice_content_create_create] TITLE: OFBIZ_ACCOUNTING_INVOICE_CONTENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_content_action_invoice_content_create_create" module="OFBIZ_ACCOUNTING_INVOICE_CONTENT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_CONTENT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_CONTENT"
