[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ATTRIBUTE-SEED-ofbiz_order_order_attribute_action_order_attribute_update_update] TITLE: OFBIZ_ORDER_ORDER_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_attribute_action_order_attribute_update_update" module="OFBIZ_ORDER_ORDER_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ATTRIBUTE"
