[SCENARIO: BDD-OFBIZ_PRODUCT_PHYSICAL_INVENTORY-SEED-ofbiz_product_physical_inventory_action_physical_inventory_destroy_destroy] TITLE: OFBIZ_PRODUCT_PHYSICAL_INVENTORY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_physical_inventory_action_physical_inventory_destroy_destroy" module="OFBIZ_PRODUCT_PHYSICAL_INVENTORY"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PHYSICAL_INVENTORY"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PHYSICAL_INVENTORY"
