[SCENARIO: BDD-OFBIZ_COMMON_CUSTOM_METHOD_TYPE-SEED-ofbiz_common_custom_method_type_action_custom_method_type_update_update] TITLE: OFBIZ_COMMON_CUSTOM_METHOD_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_custom_method_type_action_custom_method_type_update_update" module="OFBIZ_COMMON_CUSTOM_METHOD_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_CUSTOM_METHOD_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_CUSTOM_METHOD_TYPE"
