[SCENARIO: BDD-OFBIZ_SECURITY_SECURITY_GROUP_PERMISSION-SEED-ofbiz_security_security_group_permission_action_security_group_permission_read_read] TITLE: OFBIZ_SECURITY_SECURITY_GROUP_PERMISSION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_security_security_group_permission_action_security_group_permission_read_read" module="OFBIZ_SECURITY_SECURITY_GROUP_PERMISSION"
WHEN when_execute_seed_contract module="OFBIZ_SECURITY_SECURITY_GROUP_PERMISSION"
THEN then_seed_contract_should_hold module="OFBIZ_SECURITY_SECURITY_GROUP_PERMISSION"
