[SCENARIO: BDD-OFBIZ_PRODUCT_INVENTORY_ITEM_ATTRIBUTE-SEED-ofbiz_product_inventory_item_attribute_action_inventory_item_attribute_destroy_destroy] TITLE: OFBIZ_PRODUCT_INVENTORY_ITEM_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_inventory_item_attribute_action_inventory_item_attribute_destroy_destroy" module="OFBIZ_PRODUCT_INVENTORY_ITEM_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_INVENTORY_ITEM_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_INVENTORY_ITEM_ATTRIBUTE"
