[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_ATTRIBUTE-SEED-ofbiz_accounting_fin_account_trans_attribute_action_fin_account_trans_attribute_read_read] TITLE: OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fin_account_trans_attribute_action_fin_account_trans_attribute_read_read" module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIN_ACCOUNT_TRANS_ATTRIBUTE"
