[SCENARIO: BDD-OFBIZ_ACCOUNTING_INVOICE_ITEM-SEED-ofbiz_accounting_invoice_item_action_invoice_item_update_update] TITLE: OFBIZ_ACCOUNTING_INVOICE_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_invoice_item_action_invoice_item_update_update" module="OFBIZ_ACCOUNTING_INVOICE_ITEM"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_INVOICE_ITEM"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_INVOICE_ITEM"
