[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_ROUTE_SEGMENT-SEED-ofbiz_shipment_shipment_route_segment_action_shipment_route_segment_destroy_destroy] TITLE: OFBIZ_SHIPMENT_SHIPMENT_ROUTE_SEGMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_route_segment_action_shipment_route_segment_destroy_destroy" module="OFBIZ_SHIPMENT_SHIPMENT_ROUTE_SEGMENT"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_ROUTE_SEGMENT"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_ROUTE_SEGMENT"
