[SCENARIO: BDD-OFBIZ_COMMON_PERIOD_TYPE-SEED-ofbiz_common_period_type_action_period_type_update_update] TITLE: OFBIZ_COMMON_PERIOD_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_period_type_action_period_type_update_update" module="OFBIZ_COMMON_PERIOD_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_PERIOD_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_PERIOD_TYPE"
