[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_POSITION_RESPONSIBILITY-SEED-ofbiz_human_res_empl_position_responsibility_action_empl_position_responsibility_read_read] TITLE: OFBIZ_HUMAN_RES_EMPL_POSITION_RESPONSIBILITY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_position_responsibility_action_empl_position_responsibility_read_read" module="OFBIZ_HUMAN_RES_EMPL_POSITION_RESPONSIBILITY"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_POSITION_RESPONSIBILITY"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_POSITION_RESPONSIBILITY"
