[SCENARIO: BDD-OFBIZ_CONTENT_DOCUMENT_TYPE-SEED-ofbiz_content_document_type_action_document_type_create_create] TITLE: OFBIZ_CONTENT_DOCUMENT_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_document_type_action_document_type_create_create" module="OFBIZ_CONTENT_DOCUMENT_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_DOCUMENT_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_DOCUMENT_TYPE"
