[SCENARIO: BDD-OFBIZ_ORDER_WORK_REQUIREMENT_FULFILLMENT-SEED-ofbiz_order_work_requirement_fulfillment_action_work_requirement_fulfillment_destroy_destroy] TITLE: OFBIZ_ORDER_WORK_REQUIREMENT_FULFILLMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_work_requirement_fulfillment_action_work_requirement_fulfillment_destroy_destroy" module="OFBIZ_ORDER_WORK_REQUIREMENT_FULFILLMENT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_WORK_REQUIREMENT_FULFILLMENT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_WORK_REQUIREMENT_FULFILLMENT"
