[SCENARIO: BDD-OFBIZ_ORDER_ORDER_PAYMENT_PREFERENCE-SEED-ofbiz_order_order_payment_preference_action_order_payment_preference_update_update] TITLE: OFBIZ_ORDER_ORDER_PAYMENT_PREFERENCE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_payment_preference_action_order_payment_preference_update_update" module="OFBIZ_ORDER_ORDER_PAYMENT_PREFERENCE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_PAYMENT_PREFERENCE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_PAYMENT_PREFERENCE"
