[SCENARIO: BDD-OFBIZ_COMMON_CUSTOM_SCREEN_TYPE-SEED-ofbiz_common_custom_screen_type_action_custom_screen_type_create_create] TITLE: OFBIZ_COMMON_CUSTOM_SCREEN_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_custom_screen_type_action_custom_screen_type_create_create" module="OFBIZ_COMMON_CUSTOM_SCREEN_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_CUSTOM_SCREEN_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_CUSTOM_SCREEN_TYPE"
