[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPLOYMENT_APP-SEED-ofbiz_human_res_employment_app_action_employment_app_create_create] TITLE: OFBIZ_HUMAN_RES_EMPLOYMENT_APP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_employment_app_action_employment_app_create_create" module="OFBIZ_HUMAN_RES_EMPLOYMENT_APP"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPLOYMENT_APP"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPLOYMENT_APP"
