[SCENARIO: BDD-OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST-SEED-ofbiz_accounting_product_average_cost_action_product_average_cost_read_read] TITLE: OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_product_average_cost_action_product_average_cost_read_read" module="OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PRODUCT_AVERAGE_COST"
