[SCENARIO: BDD-OFBIZ_ORDER_SHOPPING_LIST_ITEM_ATTRIBUTE-SEED-ofbiz_order_shopping_list_item_attribute_action_shopping_list_item_attribute_read_read] TITLE: OFBIZ_ORDER_SHOPPING_LIST_ITEM_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_shopping_list_item_attribute_action_shopping_list_item_attribute_read_read" module="OFBIZ_ORDER_SHOPPING_LIST_ITEM_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_SHOPPING_LIST_ITEM_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_SHOPPING_LIST_ITEM_ATTRIBUTE"
