[SCENARIO: BDD-OFBIZ_COMMON_UOM_TYPE-SEED-ofbiz_common_uom_type_action_uom_type_destroy_destroy] TITLE: OFBIZ_COMMON_UOM_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_uom_type_action_uom_type_destroy_destroy" module="OFBIZ_COMMON_UOM_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_UOM_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_UOM_TYPE"
