[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_COST_CALC-SEED-ofbiz_work_effort_work_effort_cost_calc_action_work_effort_cost_calc_read_read] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_COST_CALC contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_cost_calc_action_work_effort_cost_calc_read_read" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_COST_CALC"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_COST_CALC"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_COST_CALC"
