[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_CONTACT_MECH-SEED-ofbiz_shipment_shipment_contact_mech_action_shipment_contact_mech_read_read] TITLE: OFBIZ_SHIPMENT_SHIPMENT_CONTACT_MECH contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_contact_mech_action_shipment_contact_mech_read_read" module="OFBIZ_SHIPMENT_SHIPMENT_CONTACT_MECH"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_CONTACT_MECH"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_CONTACT_MECH"
