[SCENARIO: BDD-OFBIZ_PARTY_AGREEMENT_EMPLOYMENT_APPL-SEED-ofbiz_party_agreement_employment_appl_action_agreement_employment_appl_create_create] TITLE: OFBIZ_PARTY_AGREEMENT_EMPLOYMENT_APPL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_agreement_employment_appl_action_agreement_employment_appl_create_create" module="OFBIZ_PARTY_AGREEMENT_EMPLOYMENT_APPL"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_AGREEMENT_EMPLOYMENT_APPL"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_AGREEMENT_EMPLOYMENT_APPL"
