[SCENARIO: BDD-OFBIZ_ACCOUNTING_ACCOMMODATION_MAP-SEED-ofbiz_accounting_accommodation_map_action_accommodation_map_create_create] TITLE: OFBIZ_ACCOUNTING_ACCOMMODATION_MAP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_accommodation_map_action_accommodation_map_create_create" module="OFBIZ_ACCOUNTING_ACCOMMODATION_MAP"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_ACCOMMODATION_MAP"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_ACCOMMODATION_MAP"
