[SCENARIO: BDD-OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_WEEK-SEED-ofbiz_manufacturing_tech_data_calendar_week_action_tech_data_calendar_week_update_update] TITLE: OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_WEEK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_manufacturing_tech_data_calendar_week_action_tech_data_calendar_week_update_update" module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_WEEK"
WHEN when_execute_seed_contract module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_WEEK"
THEN then_seed_contract_should_hold module="OFBIZ_MANUFACTURING_TECH_DATA_CALENDAR_WEEK"
