[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPL_POSITION_REPORTING_STRUCT-SEED-ofbiz_human_res_empl_position_reporting_struct_action_empl_position_reporting_struct_create_create] TITLE: OFBIZ_HUMAN_RES_EMPL_POSITION_REPORTING_STRUCT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_empl_position_reporting_struct_action_empl_position_reporting_struct_create_create" module="OFBIZ_HUMAN_RES_EMPL_POSITION_REPORTING_STRUCT"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPL_POSITION_REPORTING_STRUCT"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPL_POSITION_REPORTING_STRUCT"
