[SCENARIO: BDD-OFBIZ_PRODUCT_GOOD_IDENTIFICATION_TYPE-SEED-ofbiz_product_good_identification_type_action_good_identification_type_destroy_destroy] TITLE: OFBIZ_PRODUCT_GOOD_IDENTIFICATION_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_good_identification_type_action_good_identification_type_destroy_destroy" module="OFBIZ_PRODUCT_GOOD_IDENTIFICATION_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_GOOD_IDENTIFICATION_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_GOOD_IDENTIFICATION_TYPE"
