[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PRICE_CHANGE-SEED-ofbiz_product_product_price_change_action_product_price_change_read_read] TITLE: OFBIZ_PRODUCT_PRODUCT_PRICE_CHANGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_price_change_action_product_price_change_read_read" module="OFBIZ_PRODUCT_PRODUCT_PRICE_CHANGE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PRICE_CHANGE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PRICE_CHANGE"
