[SCENARIO: BDD-OFBIZ_PARTY_PARTY_CLASSIFICATION-SEED-ofbiz_party_party_classification_action_party_classification_read_read] TITLE: OFBIZ_PARTY_PARTY_CLASSIFICATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_classification_action_party_classification_read_read" module="OFBIZ_PARTY_PARTY_CLASSIFICATION"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_CLASSIFICATION"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_CLASSIFICATION"
