[SCENARIO: BDD-OFBIZ_ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT-SEED-ofbiz_accounting_tax_authority_rate_product_action_tax_authority_rate_product_update_update] TITLE: OFBIZ_ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_tax_authority_rate_product_action_tax_authority_rate_product_update_update" module="OFBIZ_ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_TAX_AUTHORITY_RATE_PRODUCT"
