[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_SEARCH_CONSTRAINT-SEED-ofbiz_product_product_search_constraint_action_product_search_constraint_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_SEARCH_CONSTRAINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_search_constraint_action_product_search_constraint_create_create" module="OFBIZ_PRODUCT_PRODUCT_SEARCH_CONSTRAINT"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_SEARCH_CONSTRAINT"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_SEARCH_CONSTRAINT"
