[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PRICE_COND-SEED-ofbiz_product_product_price_cond_action_product_price_cond_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_PRICE_COND contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_price_cond_action_product_price_cond_create_create" module="OFBIZ_PRODUCT_PRODUCT_PRICE_COND"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PRICE_COND"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PRICE_COND"
