[SCENARIO: BDD-OFBIZ_COMMON_STATUS_VALID_CHANGE-SEED-ofbiz_common_status_valid_change_action_status_valid_change_update_update] TITLE: OFBIZ_COMMON_STATUS_VALID_CHANGE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_common_status_valid_change_action_status_valid_change_update_update" module="OFBIZ_COMMON_STATUS_VALID_CHANGE"
WHEN when_execute_seed_contract module="OFBIZ_COMMON_STATUS_VALID_CHANGE"
THEN then_seed_contract_should_hold module="OFBIZ_COMMON_STATUS_VALID_CHANGE"
