[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_CONFIG_OPTION_IACTN-SEED-ofbiz_product_product_config_option_iactn_action_product_config_option_iactn_create_create] TITLE: OFBIZ_PRODUCT_PRODUCT_CONFIG_OPTION_IACTN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_config_option_iactn_action_product_config_option_iactn_create_create" module="OFBIZ_PRODUCT_PRODUCT_CONFIG_OPTION_IACTN"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_CONFIG_OPTION_IACTN"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_CONFIG_OPTION_IACTN"
