[SCENARIO: BDD-OFBIZ_ORDER_ORDER_TERM_ATTRIBUTE-SEED-ofbiz_order_order_term_attribute_action_order_term_attribute_create_create] TITLE: OFBIZ_ORDER_ORDER_TERM_ATTRIBUTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_term_attribute_action_order_term_attribute_create_create" module="OFBIZ_ORDER_ORDER_TERM_ATTRIBUTE"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_TERM_ATTRIBUTE"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_TERM_ATTRIBUTE"
