[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET_MAINT_ORDER-SEED-ofbiz_accounting_fixed_asset_maint_order_action_fixed_asset_maint_order_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET_MAINT_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_maint_order_action_fixed_asset_maint_order_destroy_destroy" module="OFBIZ_ACCOUNTING_FIXED_ASSET_MAINT_ORDER"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET_MAINT_ORDER"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET_MAINT_ORDER"
