[SCENARIO: BDD-OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM_ATTR-SEED-ofbiz_accounting_billing_account_term_attr_action_billing_account_term_attr_update_update] TITLE: OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_billing_account_term_attr_action_billing_account_term_attr_update_update" module="OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_BILLING_ACCOUNT_TERM_ATTR"
