[SCENARIO: BDD-OFBIZ_PRODUCT_PRODUCT_PRICE_RULE-SEED-ofbiz_product_product_price_rule_action_product_price_rule_update_update] TITLE: OFBIZ_PRODUCT_PRODUCT_PRICE_RULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_product_price_rule_action_product_price_rule_update_update" module="OFBIZ_PRODUCT_PRODUCT_PRICE_RULE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_PRODUCT_PRICE_RULE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_PRODUCT_PRICE_RULE"
