[SCENARIO: BDD-OFBIZ_PRODUCT_REORDER_GUIDELINE-SEED-ofbiz_product_reorder_guideline_action_reorder_guideline_create_create] TITLE: OFBIZ_PRODUCT_REORDER_GUIDELINE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_reorder_guideline_action_reorder_guideline_create_create" module="OFBIZ_PRODUCT_REORDER_GUIDELINE"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_REORDER_GUIDELINE"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_REORDER_GUIDELINE"
