[SCENARIO: BDD-OFBIZ_ACCOUNTING_VARIANCE_REASON_GL_ACCOUNT-SEED-ofbiz_accounting_variance_reason_gl_account_action_variance_reason_gl_account_read_read] TITLE: OFBIZ_ACCOUNTING_VARIANCE_REASON_GL_ACCOUNT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_variance_reason_gl_account_action_variance_reason_gl_account_read_read" module="OFBIZ_ACCOUNTING_VARIANCE_REASON_GL_ACCOUNT"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_VARIANCE_REASON_GL_ACCOUNT"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_VARIANCE_REASON_GL_ACCOUNT"
