[SCENARIO: BDD-OFBIZ_ACCOUNTING_ACCOMMODATION_MAP_TYPE-SEED-ofbiz_accounting_accommodation_map_type_action_accommodation_map_type_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_ACCOMMODATION_MAP_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_accommodation_map_type_action_accommodation_map_type_destroy_destroy" module="OFBIZ_ACCOUNTING_ACCOMMODATION_MAP_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_ACCOMMODATION_MAP_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_ACCOMMODATION_MAP_TYPE"
