[SCENARIO: BDD-OFBIZ_SECURITY_SECURITY_GROUP-SEED-ofbiz_security_security_group_action_security_group_destroy_destroy] TITLE: OFBIZ_SECURITY_SECURITY_GROUP contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_security_security_group_action_security_group_destroy_destroy" module="OFBIZ_SECURITY_SECURITY_GROUP"
WHEN when_execute_seed_contract module="OFBIZ_SECURITY_SECURITY_GROUP"
THEN then_seed_contract_should_hold module="OFBIZ_SECURITY_SECURITY_GROUP"
