[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_ASSIGN-SEED-ofbiz_work_effort_work_effort_fixed_asset_assign_action_work_effort_fixed_asset_assign_update_update] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_ASSIGN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_fixed_asset_assign_action_work_effort_fixed_asset_assign_update_update" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_ASSIGN"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_ASSIGN"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_FIXED_ASSET_ASSIGN"
