[SCENARIO: BDD-OFBIZ_ORDER_REQUIREMENT-SEED-ofbiz_order_requirement_action_requirement_update_update] TITLE: OFBIZ_ORDER_REQUIREMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_requirement_action_requirement_update_update" module="OFBIZ_ORDER_REQUIREMENT"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_REQUIREMENT"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_REQUIREMENT"
