[SCENARIO: BDD-OFBIZ_PARTY_PARTY_RELATIONSHIP_TYPE-SEED-ofbiz_party_party_relationship_type_action_party_relationship_type_create_create] TITLE: OFBIZ_PARTY_PARTY_RELATIONSHIP_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_party_party_relationship_type_action_party_relationship_type_create_create" module="OFBIZ_PARTY_PARTY_RELATIONSHIP_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_PARTY_PARTY_RELATIONSHIP_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_PARTY_PARTY_RELATIONSHIP_TYPE"
