[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESPONSE-SEED-ofbiz_accounting_payment_gateway_response_action_payment_gateway_response_read_read] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESPONSE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_response_action_payment_gateway_response_read_read" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESPONSE"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESPONSE"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_RESPONSE"
