[SCENARIO: BDD-OFBIZ_WORK_EFFORT_WORK_EFFORT_KEYWORD-SEED-ofbiz_work_effort_work_effort_keyword_action_work_effort_keyword_update_update] TITLE: OFBIZ_WORK_EFFORT_WORK_EFFORT_KEYWORD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_work_effort_keyword_action_work_effort_keyword_update_update" module="OFBIZ_WORK_EFFORT_WORK_EFFORT_KEYWORD"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_WORK_EFFORT_KEYWORD"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_WORK_EFFORT_KEYWORD"
