[SCENARIO: BDD-OFBIZ_ORDER_ORDER_ITEM_BILLING-SEED-ofbiz_order_order_item_billing_action_order_item_billing_read_read] TITLE: OFBIZ_ORDER_ORDER_ITEM_BILLING contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_order_order_item_billing_action_order_item_billing_read_read" module="OFBIZ_ORDER_ORDER_ITEM_BILLING"
WHEN when_execute_seed_contract module="OFBIZ_ORDER_ORDER_ITEM_BILLING"
THEN then_seed_contract_should_hold module="OFBIZ_ORDER_ORDER_ITEM_BILLING"
