[SCENARIO: BDD-OFBIZ_MARKETING_SALES_OPPORTUNITY_QUOTE-SEED-ofbiz_marketing_sales_opportunity_quote_action_sales_opportunity_quote_create_create] TITLE: OFBIZ_MARKETING_SALES_OPPORTUNITY_QUOTE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_marketing_sales_opportunity_quote_action_sales_opportunity_quote_create_create" module="OFBIZ_MARKETING_SALES_OPPORTUNITY_QUOTE"
WHEN when_execute_seed_contract module="OFBIZ_MARKETING_SALES_OPPORTUNITY_QUOTE"
THEN then_seed_contract_should_hold module="OFBIZ_MARKETING_SALES_OPPORTUNITY_QUOTE"
