[SCENARIO: BDD-OFBIZ_ACCOUNTING_FIXED_ASSET_REGISTRATION-SEED-ofbiz_accounting_fixed_asset_registration_action_fixed_asset_registration_update_update] TITLE: OFBIZ_ACCOUNTING_FIXED_ASSET_REGISTRATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_fixed_asset_registration_action_fixed_asset_registration_update_update" module="OFBIZ_ACCOUNTING_FIXED_ASSET_REGISTRATION"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_FIXED_ASSET_REGISTRATION"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_FIXED_ASSET_REGISTRATION"
