[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_TYPE_ATTR-SEED-ofbiz_shipment_shipment_type_attr_action_shipment_type_attr_update_update] TITLE: OFBIZ_SHIPMENT_SHIPMENT_TYPE_ATTR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_type_attr_action_shipment_type_attr_update_update" module="OFBIZ_SHIPMENT_SHIPMENT_TYPE_ATTR"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_TYPE_ATTR"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_TYPE_ATTR"
