[SCENARIO: BDD-OFBIZ_SHIPMENT_SHIPMENT_COST_ESTIMATE-SEED-ofbiz_shipment_shipment_cost_estimate_action_shipment_cost_estimate_destroy_destroy] TITLE: OFBIZ_SHIPMENT_SHIPMENT_COST_ESTIMATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_shipment_shipment_cost_estimate_action_shipment_cost_estimate_destroy_destroy" module="OFBIZ_SHIPMENT_SHIPMENT_COST_ESTIMATE"
WHEN when_execute_seed_contract module="OFBIZ_SHIPMENT_SHIPMENT_COST_ESTIMATE"
THEN then_seed_contract_should_hold module="OFBIZ_SHIPMENT_SHIPMENT_COST_ESTIMATE"
