[SCENARIO: BDD-OFBIZ_PRODUCT_FACILITY_LOCATION-SEED-ofbiz_product_facility_location_action_facility_location_create_create] TITLE: OFBIZ_PRODUCT_FACILITY_LOCATION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_facility_location_action_facility_location_create_create" module="OFBIZ_PRODUCT_FACILITY_LOCATION"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_FACILITY_LOCATION"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_FACILITY_LOCATION"
