[SCENARIO: BDD-OFBIZ_WORK_EFFORT_APPLICATION_SANDBOX-SEED-ofbiz_work_effort_application_sandbox_action_application_sandbox_update_update] TITLE: OFBIZ_WORK_EFFORT_APPLICATION_SANDBOX contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_work_effort_application_sandbox_action_application_sandbox_update_update" module="OFBIZ_WORK_EFFORT_APPLICATION_SANDBOX"
WHEN when_execute_seed_contract module="OFBIZ_WORK_EFFORT_APPLICATION_SANDBOX"
THEN then_seed_contract_should_hold module="OFBIZ_WORK_EFFORT_APPLICATION_SANDBOX"
