[SCENARIO: BDD-OFBIZ_HUMAN_RES_EMPLOYMENT_APP_SOURCE_TYPE-SEED-ofbiz_human_res_employment_app_source_type_action_employment_app_source_type_create_create] TITLE: OFBIZ_HUMAN_RES_EMPLOYMENT_APP_SOURCE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_human_res_employment_app_source_type_action_employment_app_source_type_create_create" module="OFBIZ_HUMAN_RES_EMPLOYMENT_APP_SOURCE_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_HUMAN_RES_EMPLOYMENT_APP_SOURCE_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_HUMAN_RES_EMPLOYMENT_APP_SOURCE_TYPE"
