[SCENARIO: BDD-OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_AUTHORIZE_NET-SEED-ofbiz_accounting_payment_gateway_authorize_net_action_payment_gateway_authorize_net_destroy_destroy] TITLE: OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_AUTHORIZE_NET contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_accounting_payment_gateway_authorize_net_action_payment_gateway_authorize_net_destroy_destroy" module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_AUTHORIZE_NET"
WHEN when_execute_seed_contract module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_AUTHORIZE_NET"
THEN then_seed_contract_should_hold module="OFBIZ_ACCOUNTING_PAYMENT_GATEWAY_AUTHORIZE_NET"
