[SCENARIO: BDD-OFBIZ_SERVICE_RECURRENCE_RULE-SEED-ofbiz_service_recurrence_rule_action_recurrence_rule_read_read] TITLE: OFBIZ_SERVICE_RECURRENCE_RULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_service_recurrence_rule_action_recurrence_rule_read_read" module="OFBIZ_SERVICE_RECURRENCE_RULE"
WHEN when_execute_seed_contract module="OFBIZ_SERVICE_RECURRENCE_RULE"
THEN then_seed_contract_should_hold module="OFBIZ_SERVICE_RECURRENCE_RULE"
