[SCENARIO: BDD-OFBIZ_CONTENT_DATA_TEMPLATE_TYPE-SEED-ofbiz_content_data_template_type_action_data_template_type_destroy_destroy] TITLE: OFBIZ_CONTENT_DATA_TEMPLATE_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_content_data_template_type_action_data_template_type_destroy_destroy" module="OFBIZ_CONTENT_DATA_TEMPLATE_TYPE"
WHEN when_execute_seed_contract module="OFBIZ_CONTENT_DATA_TEMPLATE_TYPE"
THEN then_seed_contract_should_hold module="OFBIZ_CONTENT_DATA_TEMPLATE_TYPE"
