[SCENARIO: BDD-OFBIZ_PRODUCT_VARIANCE_REASON-SEED-ofbiz_product_variance_reason_action_variance_reason_create_create] TITLE: OFBIZ_PRODUCT_VARIANCE_REASON contract seed scenario TAGS: seed all
GIVEN given_seed_context id="ofbiz_product_variance_reason_action_variance_reason_create_create" module="OFBIZ_PRODUCT_VARIANCE_REASON"
WHEN when_execute_seed_contract module="OFBIZ_PRODUCT_VARIANCE_REASON"
THEN then_seed_contract_should_hold module="OFBIZ_PRODUCT_VARIANCE_REASON"
