[SCENARIO: BDD-ORDER_SHOPPING_LIST_TYPE-SEED-order_shopping_list_type_action_shopping_list_type_destroy_destroy] TITLE: ORDER_SHOPPING_LIST_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="order_shopping_list_type_action_shopping_list_type_destroy_destroy" module="ORDER_SHOPPING_LIST_TYPE"
WHEN when_execute_seed_contract module="ORDER_SHOPPING_LIST_TYPE"
THEN then_seed_contract_should_hold module="ORDER_SHOPPING_LIST_TYPE"
