[SCENARIO: BDD-ORDER_ORDER_ADJUSTMENT_TYPE-SEED-order_order_adjustment_type_action_order_adjustment_type_update_update] TITLE: ORDER_ORDER_ADJUSTMENT_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="order_order_adjustment_type_action_order_adjustment_type_update_update" module="ORDER_ORDER_ADJUSTMENT_TYPE"
WHEN when_execute_seed_contract module="ORDER_ORDER_ADJUSTMENT_TYPE"
THEN then_seed_contract_should_hold module="ORDER_ORDER_ADJUSTMENT_TYPE"
