[SCENARIO: BDD-ORDER_ORDER_ADJUSTMENT-SEED-order_order_adjustment_action_order_adjustment_update_update] TITLE: ORDER_ORDER_ADJUSTMENT contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="order_order_adjustment_action_order_adjustment_update_update" module="ORDER_ORDER_ADJUSTMENT"
WHEN when_execute_seed_contract module="ORDER_ORDER_ADJUSTMENT"
THEN then_seed_contract_should_hold module="ORDER_ORDER_ADJUSTMENT"
