[SCENARIO: BDD-ORDER_ORDER_ITEM_TYPE-SEED-order_order_item_type_action_order_item_type_destroy_destroy] TITLE: ORDER_ORDER_ITEM_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="order_order_item_type_action_order_item_type_destroy_destroy" module="ORDER_ORDER_ITEM_TYPE"
WHEN when_execute_seed_contract module="ORDER_ORDER_ITEM_TYPE"
THEN then_seed_contract_should_hold module="ORDER_ORDER_ITEM_TYPE"
