[SCENARIO: BDD-ORDER_RETURN_TYPE-SEED-order_return_type_action_return_type_destroy_destroy] TITLE: ORDER_RETURN_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="order_return_type_action_return_type_destroy_destroy" module="ORDER_RETURN_TYPE"
WHEN when_execute_seed_contract module="ORDER_RETURN_TYPE"
THEN then_seed_contract_should_hold module="ORDER_RETURN_TYPE"
