[SCENARIO: BDD-ORGANIZATION_PARTY_ROLE-SEED-organization_party_role_action_party_role_destroy_destroy] TITLE: ORGANIZATION_PARTY_ROLE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="organization_party_role_action_party_role_destroy_destroy" module="ORGANIZATION_PARTY_ROLE"
WHEN when_execute_seed_contract module="ORGANIZATION_PARTY_ROLE"
THEN then_seed_contract_should_hold module="ORGANIZATION_PARTY_ROLE"
