[SCENARIO: BDD-PARTY_PARTY_GROUP-SEED-party_party_group_action_party_group_destroy_destroy] TITLE: PARTY_PARTY_GROUP contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="party_party_group_action_party_group_destroy_destroy" module="PARTY_PARTY_GROUP"
WHEN when_execute_seed_contract module="PARTY_PARTY_GROUP"
THEN then_seed_contract_should_hold module="PARTY_PARTY_GROUP"
