[SCENARIO: BDD-PAYMENT_PAYMENT_APPLICATION-SEED-payment_payment_application_action_payment_application_apply_to_invoice_create] TITLE: PAYMENT_PAYMENT_APPLICATION contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="payment_payment_application_action_payment_application_apply_to_invoice_create" module="PAYMENT_PAYMENT_APPLICATION"
WHEN when_execute_seed_contract module="PAYMENT_PAYMENT_APPLICATION"
THEN then_seed_contract_should_hold module="PAYMENT_PAYMENT_APPLICATION"
