[SCENARIO: BDD-PAYMENT_PAYMENT_GATEWAY_RESPONSE-SEED-payment_payment_gateway_response_workflow_payment_gateway_response_gateway_response_record_flow] TITLE: PAYMENT_PAYMENT_GATEWAY_RESPONSE contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="payment_payment_gateway_response_workflow_payment_gateway_response_gateway_response_record_flow" module="PAYMENT_PAYMENT_GATEWAY_RESPONSE"
WHEN when_execute_seed_contract module="PAYMENT_PAYMENT_GATEWAY_RESPONSE"
THEN then_seed_contract_should_hold module="PAYMENT_PAYMENT_GATEWAY_RESPONSE"
