[SCENARIO: BDD-PAYMENT_PAYMENT_TYPE-SEED-payment_payment_type_action_payment_type_create_create_2] TITLE: PAYMENT_PAYMENT_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="payment_payment_type_action_payment_type_create_create_2" module="PAYMENT_PAYMENT_TYPE"
WHEN when_execute_seed_contract module="PAYMENT_PAYMENT_TYPE"
THEN then_seed_contract_should_hold module="PAYMENT_PAYMENT_TYPE"
