[SCENARIO: BDD-PAYMENT_PAYMENT_METHOD-SEED-payment_payment_method_workflow_payment_method_payment_method_lifecycle] TITLE: PAYMENT_PAYMENT_METHOD contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="payment_payment_method_workflow_payment_method_payment_method_lifecycle" module="PAYMENT_PAYMENT_METHOD"
WHEN when_execute_seed_contract module="PAYMENT_PAYMENT_METHOD"
THEN then_seed_contract_should_hold module="PAYMENT_PAYMENT_METHOD"
