[SCENARIO: BDD-PAYMENT_PAYMENT_TOKEN-SEED-payment_payment_token_action_payment_token_revoke_update] TITLE: PAYMENT_PAYMENT_TOKEN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="payment_payment_token_action_payment_token_revoke_update" module="PAYMENT_PAYMENT_TOKEN"
WHEN when_execute_seed_contract module="PAYMENT_PAYMENT_TOKEN"
THEN then_seed_contract_should_hold module="PAYMENT_PAYMENT_TOKEN"
