[SCENARIO: BDD-PLM_ECO_STAGE_APPROVAL_TEMPLATE-SEED-plm_eco_stage_approval_template_action_eco_stage_approval_template_update_update] TITLE: PLM_ECO_STAGE_APPROVAL_TEMPLATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="plm_eco_stage_approval_template_action_eco_stage_approval_template_update_update" module="PLM_ECO_STAGE_APPROVAL_TEMPLATE"
WHEN when_execute_seed_contract module="PLM_ECO_STAGE_APPROVAL_TEMPLATE"
THEN then_seed_contract_should_hold module="PLM_ECO_STAGE_APPROVAL_TEMPLATE"
