[SCENARIO: BDD-PLM_ECO_TYPE_STAGE_LINK-SEED-plm_eco_type_stage_link_action_eco_type_stage_link_read_read] TITLE: PLM_ECO_TYPE_STAGE_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="plm_eco_type_stage_link_action_eco_type_stage_link_read_read" module="PLM_ECO_TYPE_STAGE_LINK"
WHEN when_execute_seed_contract module="PLM_ECO_TYPE_STAGE_LINK"
THEN then_seed_contract_should_hold module="PLM_ECO_TYPE_STAGE_LINK"
