[SCENARIO: BDD-POS_POS_CONFIG_FLOOR-SEED-pos_pos_config_floor_action_pos_config_floor_create_create] TITLE: POS_POS_CONFIG_FLOOR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="pos_pos_config_floor_action_pos_config_floor_create_create" module="POS_POS_CONFIG_FLOOR"
WHEN when_execute_seed_contract module="POS_POS_CONFIG_FLOOR"
THEN then_seed_contract_should_hold module="POS_POS_CONFIG_FLOOR"
