[SCENARIO: BDD-PRODUCT_PRODUCT_STORE_GROUP_TYPE-SEED-product_product_store_group_type_action_product_store_group_type_destroy_destroy] TITLE: PRODUCT_PRODUCT_STORE_GROUP_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="product_product_store_group_type_action_product_store_group_type_destroy_destroy" module="PRODUCT_PRODUCT_STORE_GROUP_TYPE"
WHEN when_execute_seed_contract module="PRODUCT_PRODUCT_STORE_GROUP_TYPE"
THEN then_seed_contract_should_hold module="PRODUCT_PRODUCT_STORE_GROUP_TYPE"
