[SCENARIO: BDD-PRODUCT_FACILITY_TYPE-SEED-product_facility_type_action_facility_type_destroy_destroy] TITLE: PRODUCT_FACILITY_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="product_facility_type_action_facility_type_destroy_destroy" module="PRODUCT_FACILITY_TYPE"
WHEN when_execute_seed_contract module="PRODUCT_FACILITY_TYPE"
THEN then_seed_contract_should_hold module="PRODUCT_FACILITY_TYPE"
