[SCENARIO: BDD-PRODUCT_PRODUCT_CATEGORY-SEED-product_product_category_action_product_category_read_read] TITLE: PRODUCT_PRODUCT_CATEGORY contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="product_product_category_action_product_category_read_read" module="PRODUCT_PRODUCT_CATEGORY"
WHEN when_execute_seed_contract module="PRODUCT_PRODUCT_CATEGORY"
THEN then_seed_contract_should_hold module="PRODUCT_PRODUCT_CATEGORY"
