[SCENARIO: BDD-PRODUCT_PRODUCT_FEATURE_APPL-SEED-product_product_feature_appl_action_product_feature_appl_create_create] TITLE: PRODUCT_PRODUCT_FEATURE_APPL contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="product_product_feature_appl_action_product_feature_appl_create_create" module="PRODUCT_PRODUCT_FEATURE_APPL"
WHEN when_execute_seed_contract module="PRODUCT_PRODUCT_FEATURE_APPL"
THEN then_seed_contract_should_hold module="PRODUCT_PRODUCT_FEATURE_APPL"
