[SCENARIO: BDD-PRODUCT_FACILITY_GROUP-SEED-product_facility_group_action_facility_group_destroy_destroy] TITLE: PRODUCT_FACILITY_GROUP contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="product_facility_group_action_facility_group_destroy_destroy" module="PRODUCT_FACILITY_GROUP"
WHEN when_execute_seed_contract module="PRODUCT_FACILITY_GROUP"
THEN then_seed_contract_should_hold module="PRODUCT_FACILITY_GROUP"
