[SCENARIO: BDD-PROJECT_ANALYTIC_ACCOUNT-SEED-project_analytic_account_action_analytic_account_read_read] TITLE: PROJECT_ANALYTIC_ACCOUNT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="project_analytic_account_action_analytic_account_read_read" module="PROJECT_ANALYTIC_ACCOUNT"
WHEN when_execute_seed_contract module="PROJECT_ANALYTIC_ACCOUNT"
THEN then_seed_contract_should_hold module="PROJECT_ANALYTIC_ACCOUNT"
