[SCENARIO: BDD-PROJECT_PLANNING_SLOT_TEMPLATE-SEED-project_planning_slot_template_action_planning_slot_template_read_read] TITLE: PROJECT_PLANNING_SLOT_TEMPLATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="project_planning_slot_template_action_planning_slot_template_read_read" module="PROJECT_PLANNING_SLOT_TEMPLATE"
WHEN when_execute_seed_contract module="PROJECT_PLANNING_SLOT_TEMPLATE"
THEN then_seed_contract_should_hold module="PROJECT_PLANNING_SLOT_TEMPLATE"
