[SCENARIO: BDD-PROJECT_RESOURCE_CALENDAR-SEED-project_resource_calendar_action_resource_calendar_read_read] TITLE: PROJECT_RESOURCE_CALENDAR contract seed scenario TAGS: seed all
GIVEN given_seed_context id="project_resource_calendar_action_resource_calendar_read_read" module="PROJECT_RESOURCE_CALENDAR"
WHEN when_execute_seed_contract module="PROJECT_RESOURCE_CALENDAR"
THEN then_seed_contract_should_hold module="PROJECT_RESOURCE_CALENDAR"
