[SCENARIO: BDD-PROJECT_TASK_DEPENDENCY-SEED-project_task_dependency_action_task_dependency_read_read] TITLE: PROJECT_TASK_DEPENDENCY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="project_task_dependency_action_task_dependency_read_read" module="PROJECT_TASK_DEPENDENCY"
WHEN when_execute_seed_contract module="PROJECT_TASK_DEPENDENCY"
THEN then_seed_contract_should_hold module="PROJECT_TASK_DEPENDENCY"
