[SCENARIO: BDD-PURCHASING_PRODUCT_SUPPLIERINFO-SEED-purchasing_product_supplierinfo_action_product_supplierinfo_preview_read] TITLE: PURCHASING_PRODUCT_SUPPLIERINFO contract seed scenario TAGS: seed all
GIVEN given_seed_context id="purchasing_product_supplierinfo_action_product_supplierinfo_preview_read" module="PURCHASING_PRODUCT_SUPPLIERINFO"
WHEN when_execute_seed_contract module="PURCHASING_PRODUCT_SUPPLIERINFO"
THEN then_seed_contract_should_hold module="PURCHASING_PRODUCT_SUPPLIERINFO"
