[SCENARIO: BDD-PURCHASING_CROSS_ORG_TRANSACTION-SEED-purchasing_cross_org_transaction_action_cross_org_transaction_read_read] TITLE: PURCHASING_CROSS_ORG_TRANSACTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="purchasing_cross_org_transaction_action_cross_org_transaction_read_read" module="PURCHASING_CROSS_ORG_TRANSACTION"
WHEN when_execute_seed_contract module="PURCHASING_CROSS_ORG_TRANSACTION"
THEN then_seed_contract_should_hold module="PURCHASING_CROSS_ORG_TRANSACTION"
