[SCENARIO: BDD-PURCHASING_PURCHASE_ORDER-SEED-purchasing_purchase_order_workflow_purchase_order_purchase_order_editing] TITLE: PURCHASING_PURCHASE_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="purchasing_purchase_order_workflow_purchase_order_purchase_order_editing" module="PURCHASING_PURCHASE_ORDER"
WHEN when_execute_seed_contract module="PURCHASING_PURCHASE_ORDER"
THEN then_seed_contract_should_hold module="PURCHASING_PURCHASE_ORDER"
