[SCENARIO: BDD-PURCHASING_PURCHASE_REQUISITION_TYPE-SEED-purchasing_purchase_requisition_type_action_purchase_requisition_type_search_read] TITLE: PURCHASING_PURCHASE_REQUISITION_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="purchasing_purchase_requisition_type_action_purchase_requisition_type_search_read" module="PURCHASING_PURCHASE_REQUISITION_TYPE"
WHEN when_execute_seed_contract module="PURCHASING_PURCHASE_REQUISITION_TYPE"
THEN then_seed_contract_should_hold module="PURCHASING_PURCHASE_REQUISITION_TYPE"
