[SCENARIO: BDD-PURCHASING_PURCHASE_REQUISITION_ITEM-SEED-purchasing_purchase_requisition_item_workflow_purchase_requisition_item_requisition_item_editing] TITLE: PURCHASING_PURCHASE_REQUISITION_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="purchasing_purchase_requisition_item_workflow_purchase_requisition_item_requisition_item_editing" module="PURCHASING_PURCHASE_REQUISITION_ITEM"
WHEN when_execute_seed_contract module="PURCHASING_PURCHASE_REQUISITION_ITEM"
THEN then_seed_contract_should_hold module="PURCHASING_PURCHASE_REQUISITION_ITEM"
