[SCENARIO: BDD-PURCHASING_PURCHASE_REQUISITION-SEED-purchasing_purchase_requisition_action_purchase_requisition_search_read] TITLE: PURCHASING_PURCHASE_REQUISITION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="purchasing_purchase_requisition_action_purchase_requisition_search_read" module="PURCHASING_PURCHASE_REQUISITION"
WHEN when_execute_seed_contract module="PURCHASING_PURCHASE_REQUISITION"
THEN then_seed_contract_should_hold module="PURCHASING_PURCHASE_REQUISITION"
