[SCENARIO: BDD-PURCHASING_ACCOUNT_MOVE_LINE-SEED-purchasing_account_move_line_action_account_move_line_list_read] TITLE: PURCHASING_ACCOUNT_MOVE_LINE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="purchasing_account_move_line_action_account_move_line_list_read" module="PURCHASING_ACCOUNT_MOVE_LINE"
WHEN when_execute_seed_contract module="PURCHASING_ACCOUNT_MOVE_LINE"
THEN then_seed_contract_should_hold module="PURCHASING_ACCOUNT_MOVE_LINE"
