[SCENARIO: BDD-QUALITY_QUALITY_ALERT-SEED-quality_quality_alert_action_quality_alert_confirm_update] TITLE: QUALITY_QUALITY_ALERT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="quality_quality_alert_action_quality_alert_confirm_update" module="QUALITY_QUALITY_ALERT"
WHEN when_execute_seed_contract module="QUALITY_QUALITY_ALERT"
THEN then_seed_contract_should_hold module="QUALITY_QUALITY_ALERT"
