[SCENARIO: BDD-QUALITY_MAINTENANCE_REQUEST-SEED-quality_maintenance_request_action_maintenance_request_read_read] TITLE: QUALITY_MAINTENANCE_REQUEST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="quality_maintenance_request_action_maintenance_request_read_read" module="QUALITY_MAINTENANCE_REQUEST"
WHEN when_execute_seed_contract module="QUALITY_MAINTENANCE_REQUEST"
THEN then_seed_contract_should_hold module="QUALITY_MAINTENANCE_REQUEST"
