[SCENARIO: BDD-QUALITY_QUALITY_TEAM_MEMBER_LINK-SEED-quality_quality_team_member_link_action_quality_team_member_link_read_read] TITLE: QUALITY_QUALITY_TEAM_MEMBER_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="quality_quality_team_member_link_action_quality_team_member_link_read_read" module="QUALITY_QUALITY_TEAM_MEMBER_LINK"
WHEN when_execute_seed_contract module="QUALITY_QUALITY_TEAM_MEMBER_LINK"
THEN then_seed_contract_should_hold module="QUALITY_QUALITY_TEAM_MEMBER_LINK"
