[SCENARIO: BDD-QUALITY_QUALITY_REASON-SEED-quality_quality_reason_workflow_quality_reason_quality_reason_maintain_flow] TITLE: QUALITY_QUALITY_REASON contract seed scenario TAGS: seed all
GIVEN given_seed_context id="quality_quality_reason_workflow_quality_reason_quality_reason_maintain_flow" module="QUALITY_QUALITY_REASON"
WHEN when_execute_seed_contract module="QUALITY_QUALITY_REASON"
THEN then_seed_contract_should_hold module="QUALITY_QUALITY_REASON"
