[SCENARIO: BDD-QUALITY_QUALITY_POINT-SEED-quality_quality_point_workflow_quality_point_quality_point_lifecycle] TITLE: QUALITY_QUALITY_POINT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="quality_quality_point_workflow_quality_point_quality_point_lifecycle" module="QUALITY_QUALITY_POINT"
WHEN when_execute_seed_contract module="QUALITY_QUALITY_POINT"
THEN then_seed_contract_should_hold module="QUALITY_QUALITY_POINT"
