[SCENARIO: BDD-RATING_RATING_TYPE-SEED-rating_rating_type_workflow_rating_type_rating_type_lifecycle] TITLE: RATING_RATING_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="rating_rating_type_workflow_rating_type_rating_type_lifecycle" module="RATING_RATING_TYPE"
WHEN when_execute_seed_contract module="RATING_RATING_TYPE"
THEN then_seed_contract_should_hold module="RATING_RATING_TYPE"
