[SCENARIO: BDD-RATING_RATING_SUMMARY-SEED-rating_rating_summary_event_rating_summary_recalculate_rating_summary_updated] TITLE: RATING_RATING_SUMMARY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="rating_rating_summary_event_rating_summary_recalculate_rating_summary_updated" module="RATING_RATING_SUMMARY"
WHEN when_execute_seed_contract module="RATING_RATING_SUMMARY"
THEN then_seed_contract_should_hold module="RATING_RATING_SUMMARY"
