[SCENARIO: BDD-RATING_RATING_SCORE-SEED-rating_rating_score_action_rating_score_submit_create] TITLE: RATING_RATING_SCORE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="rating_rating_score_action_rating_score_submit_create" module="RATING_RATING_SCORE"
WHEN when_execute_seed_contract module="RATING_RATING_SCORE"
THEN then_seed_contract_should_hold module="RATING_RATING_SCORE"
