[SCENARIO: BDD-RATING_RATING_CRITERIA-SEED-rating_rating_criteria_action_rating_criteria_update_update] TITLE: RATING_RATING_CRITERIA contract seed scenario TAGS: seed all
GIVEN given_seed_context id="rating_rating_criteria_action_rating_criteria_update_update" module="RATING_RATING_CRITERIA"
WHEN when_execute_seed_contract module="RATING_RATING_CRITERIA"
THEN then_seed_contract_should_hold module="RATING_RATING_CRITERIA"
