[SCENARIO: BDD-RENTAL_PRODUCT_TEMPLATE-SEED-rental_product_template_action_product_template_read_read] TITLE: RENTAL_PRODUCT_TEMPLATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="rental_product_template_action_product_template_read_read" module="RENTAL_PRODUCT_TEMPLATE"
WHEN when_execute_seed_contract module="RENTAL_PRODUCT_TEMPLATE"
THEN then_seed_contract_should_hold module="RENTAL_PRODUCT_TEMPLATE"
