[SCENARIO: BDD-SALES_CROSS_ORG_TRANSACTION-SEED-sales_cross_org_transaction_action_cross_org_transaction_read_read] TITLE: SALES_CROSS_ORG_TRANSACTION contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sales_cross_org_transaction_action_cross_org_transaction_read_read" module="SALES_CROSS_ORG_TRANSACTION"
WHEN when_execute_seed_contract module="SALES_CROSS_ORG_TRANSACTION"
THEN then_seed_contract_should_hold module="SALES_CROSS_ORG_TRANSACTION"
