[SCENARIO: BDD-SALES_SALES_ORDER_ITEM_TAX_REL-SEED-sales_sales_order_item_tax_rel_action_sales_order_item_tax_rel_preview_read] TITLE: SALES_SALES_ORDER_ITEM_TAX_REL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sales_sales_order_item_tax_rel_action_sales_order_item_tax_rel_preview_read" module="SALES_SALES_ORDER_ITEM_TAX_REL"
WHEN when_execute_seed_contract module="SALES_SALES_ORDER_ITEM_TAX_REL"
THEN then_seed_contract_should_hold module="SALES_SALES_ORDER_ITEM_TAX_REL"
