[SCENARIO: BDD-SALES_DELIVERY_CARRIER-SEED-sales_delivery_carrier_workflow_delivery_carrier_delivery_carrier_lifecycle] TITLE: SALES_DELIVERY_CARRIER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sales_delivery_carrier_workflow_delivery_carrier_delivery_carrier_lifecycle" module="SALES_DELIVERY_CARRIER"
WHEN when_execute_seed_contract module="SALES_DELIVERY_CARRIER"
THEN then_seed_contract_should_hold module="SALES_DELIVERY_CARRIER"
