[SCENARIO: BDD-SALES_SALES_ORDER_SHIPMENT-SEED-sales_sales_order_shipment_event_sales_order_shipment_deliver_sales_shipment_delivered] TITLE: SALES_SALES_ORDER_SHIPMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sales_sales_order_shipment_event_sales_order_shipment_deliver_sales_shipment_delivered" module="SALES_SALES_ORDER_SHIPMENT"
WHEN when_execute_seed_contract module="SALES_SALES_ORDER_SHIPMENT"
THEN then_seed_contract_should_hold module="SALES_SALES_ORDER_SHIPMENT"
