[SCENARIO: BDD-SALES_RETURN_ITEM-SEED-sales_return_item_action_return_item_update_update_2] TITLE: SALES_RETURN_ITEM contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_item_action_return_item_update_update_2" module="SALES_RETURN_ITEM"
WHEN when_execute_seed_contract module="SALES_RETURN_ITEM"
THEN then_seed_contract_should_hold module="SALES_RETURN_ITEM"
