[SCENARIO: BDD-SHIPMENT_CARRIER_SHIPMENT_METHOD-SEED-shipment_carrier_shipment_method_action_carrier_shipment_method_destroy_destroy_2] TITLE: SHIPMENT_CARRIER_SHIPMENT_METHOD contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="shipment_carrier_shipment_method_action_carrier_shipment_method_destroy_destroy_2" module="SHIPMENT_CARRIER_SHIPMENT_METHOD"
WHEN when_execute_seed_contract module="SHIPMENT_CARRIER_SHIPMENT_METHOD"
THEN then_seed_contract_should_hold module="SHIPMENT_CARRIER_SHIPMENT_METHOD"
