[SCENARIO: BDD-SHIPMENT_SHIPMENT_PACKAGE_ROUTE_SEG-SEED-shipment_shipment_package_route_seg_action_shipment_package_route_seg_create_create_2] TITLE: SHIPMENT_SHIPMENT_PACKAGE_ROUTE_SEG contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="shipment_shipment_package_route_seg_action_shipment_package_route_seg_create_create_2" module="SHIPMENT_SHIPMENT_PACKAGE_ROUTE_SEG"
WHEN when_execute_seed_contract module="SHIPMENT_SHIPMENT_PACKAGE_ROUTE_SEG"
THEN then_seed_contract_should_hold module="SHIPMENT_SHIPMENT_PACKAGE_ROUTE_SEG"
