[SCENARIO: BDD-SHIPMENT_SHIPMENT_ROUTE_SEGMENT-SEED-shipment_shipment_route_segment_action_shipment_route_segment_update_update_2] TITLE: SHIPMENT_SHIPMENT_ROUTE_SEGMENT contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="shipment_shipment_route_segment_action_shipment_route_segment_update_update_2" module="SHIPMENT_SHIPMENT_ROUTE_SEGMENT"
WHEN when_execute_seed_contract module="SHIPMENT_SHIPMENT_ROUTE_SEGMENT"
THEN then_seed_contract_should_hold module="SHIPMENT_SHIPMENT_ROUTE_SEGMENT"
