[SCENARIO: BDD-SHIPMENT_SHIPMENT_METHOD_TYPE-SEED-shipment_shipment_method_type_action_shipment_method_type_destroy_destroy_2] TITLE: SHIPMENT_SHIPMENT_METHOD_TYPE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="shipment_shipment_method_type_action_shipment_method_type_destroy_destroy_2" module="SHIPMENT_SHIPMENT_METHOD_TYPE"
WHEN when_execute_seed_contract module="SHIPMENT_SHIPMENT_METHOD_TYPE"
THEN then_seed_contract_should_hold module="SHIPMENT_SHIPMENT_METHOD_TYPE"
