[SCENARIO: BDD-SIGN_SIGN_REQUEST-SEED-sign_sign_request_event_sign_request_complete_sign_request_completed] TITLE: SIGN_SIGN_REQUEST contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_request_event_sign_request_complete_sign_request_completed" module="SIGN_SIGN_REQUEST"
WHEN when_execute_seed_contract module="SIGN_SIGN_REQUEST"
THEN then_seed_contract_should_hold module="SIGN_SIGN_REQUEST"
