[SCENARIO: BDD-SIGN_SIGN_TEMPLATE-SEED-sign_sign_template_workflow_sign_template_sign_template_write_flow] TITLE: SIGN_SIGN_TEMPLATE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_template_workflow_sign_template_sign_template_write_flow" module="SIGN_SIGN_TEMPLATE"
WHEN when_execute_seed_contract module="SIGN_SIGN_TEMPLATE"
THEN then_seed_contract_should_hold module="SIGN_SIGN_TEMPLATE"
