[SCENARIO: BDD-SIGN_SIGN_REQUEST_ITEM-SEED-sign_sign_request_item_action_sign_request_item_sign_update] TITLE: SIGN_SIGN_REQUEST_ITEM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_sign_request_item_action_sign_request_item_sign_update" module="SIGN_SIGN_REQUEST_ITEM"
WHEN when_execute_seed_contract module="SIGN_SIGN_REQUEST_ITEM"
THEN then_seed_contract_should_hold module="SIGN_SIGN_REQUEST_ITEM"
