[SCENARIO: BDD-STUDIO_CUSTOM_MODEL-SEED-studio_custom_model_event_custom_model_archive_studio_model_archived] TITLE: STUDIO_CUSTOM_MODEL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="studio_custom_model_event_custom_model_archive_studio_model_archived" module="STUDIO_CUSTOM_MODEL"
WHEN when_execute_seed_contract module="STUDIO_CUSTOM_MODEL"
THEN then_seed_contract_should_hold module="STUDIO_CUSTOM_MODEL"
