[SCENARIO: BDD-STUDIO_CUSTOM_VIEW-SEED-studio_custom_view_workflow_custom_view_custom_view_maintain_flow] TITLE: STUDIO_CUSTOM_VIEW contract seed scenario TAGS: seed all
GIVEN given_seed_context id="studio_custom_view_workflow_custom_view_custom_view_maintain_flow" module="STUDIO_CUSTOM_VIEW"
WHEN when_execute_seed_contract module="STUDIO_CUSTOM_VIEW"
THEN then_seed_contract_should_hold module="STUDIO_CUSTOM_VIEW"
