[SCENARIO: BDD-STUDIO_CUSTOM_FIELD-SEED-studio_custom_field_action_custom_field_archive_update] TITLE: STUDIO_CUSTOM_FIELD contract seed scenario TAGS: seed all
GIVEN given_seed_context id="studio_custom_field_action_custom_field_archive_update" module="STUDIO_CUSTOM_FIELD"
WHEN when_execute_seed_contract module="STUDIO_CUSTOM_FIELD"
THEN then_seed_contract_should_hold module="STUDIO_CUSTOM_FIELD"
