[SCENARIO: BDD-STUDIO_AUTOMATION_RULE-SEED-studio_automation_rule_action_automation_rule_create_create] TITLE: STUDIO_AUTOMATION_RULE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="studio_automation_rule_action_automation_rule_create_create" module="STUDIO_AUTOMATION_RULE"
WHEN when_execute_seed_contract module="STUDIO_AUTOMATION_RULE"
THEN then_seed_contract_should_hold module="STUDIO_AUTOMATION_RULE"
