[SCENARIO: BDD-SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE_TAX_LINK-SEED-subscriptions_subscription_order_line_tax_link_action_subscription_order_line_tax_link_read_read] TITLE: SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE_TAX_LINK contract seed scenario TAGS: seed all
GIVEN given_seed_context id="subscriptions_subscription_order_line_tax_link_action_subscription_order_line_tax_link_read_read" module="SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE_TAX_LINK"
WHEN when_execute_seed_contract module="SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE_TAX_LINK"
THEN then_seed_contract_should_hold module="SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE_TAX_LINK"
