[SCENARIO: BDD-SUBSCRIPTIONS_SUBSCRIPTION_LOG-SEED-subscriptions_subscription_log_workflow_subscription_log_log_creation] TITLE: SUBSCRIPTIONS_SUBSCRIPTION_LOG contract seed scenario TAGS: seed all
GIVEN given_seed_context id="subscriptions_subscription_log_workflow_subscription_log_log_creation" module="SUBSCRIPTIONS_SUBSCRIPTION_LOG"
WHEN when_execute_seed_contract module="SUBSCRIPTIONS_SUBSCRIPTION_LOG"
THEN then_seed_contract_should_hold module="SUBSCRIPTIONS_SUBSCRIPTION_LOG"
