[SCENARIO: BDD-SUBSCRIPTIONS_SALES_TEAM-SEED-subscriptions_sales_team_action_sales_team_read_read] TITLE: SUBSCRIPTIONS_SALES_TEAM contract seed scenario TAGS: seed all
GIVEN given_seed_context id="subscriptions_sales_team_action_sales_team_read_read" module="SUBSCRIPTIONS_SALES_TEAM"
WHEN when_execute_seed_contract module="SUBSCRIPTIONS_SALES_TEAM"
THEN then_seed_contract_should_hold module="SUBSCRIPTIONS_SALES_TEAM"
