[SCENARIO: BDD-SUBSCRIPTIONS_PAYMENT_TOKEN-SEED-subscriptions_payment_token_action_payment_token_read_read] TITLE: SUBSCRIPTIONS_PAYMENT_TOKEN contract seed scenario TAGS: seed all
GIVEN given_seed_context id="subscriptions_payment_token_action_payment_token_read_read" module="SUBSCRIPTIONS_PAYMENT_TOKEN"
WHEN when_execute_seed_contract module="SUBSCRIPTIONS_PAYMENT_TOKEN"
THEN then_seed_contract_should_hold module="SUBSCRIPTIONS_PAYMENT_TOKEN"
