[SCENARIO: BDD-SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE-SEED-subscriptions_subscription_order_line_action_subscription_order_line_create_create] TITLE: SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="subscriptions_subscription_order_line_action_subscription_order_line_create_create" module="SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE"
WHEN when_execute_seed_contract module="SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE"
THEN then_seed_contract_should_hold module="SUBSCRIPTIONS_SUBSCRIPTION_ORDER_LINE"
