[SCENARIO: BDD-SUBSCRIPTIONS_CLOSE_REASON-SEED-subscriptions_close_reason_action_close_reason_create_create] TITLE: SUBSCRIPTIONS_CLOSE_REASON contract seed scenario TAGS: seed all
GIVEN given_seed_context id="subscriptions_close_reason_action_close_reason_create_create" module="SUBSCRIPTIONS_CLOSE_REASON"
WHEN when_execute_seed_contract module="SUBSCRIPTIONS_CLOSE_REASON"
THEN then_seed_contract_should_hold module="SUBSCRIPTIONS_CLOSE_REASON"
