[SCENARIO: BDD-SURVEY_USER_INPUT-SEED-survey_user_input_event_user_input_mark_done_survey_user_input_done] TITLE: SURVEY_USER_INPUT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="survey_user_input_event_user_input_mark_done_survey_user_input_done" module="SURVEY_USER_INPUT"
WHEN when_execute_seed_contract module="SURVEY_USER_INPUT"
THEN then_seed_contract_should_hold module="SURVEY_USER_INPUT"
