[SCENARIO: BDD-TRAVEL_HOTEL_OFFER-SEED-travel_hotel_offer_workflow_hotel_offer_hotel_offer_lifecycle] TITLE: TRAVEL_HOTEL_OFFER contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="travel_hotel_offer_workflow_hotel_offer_hotel_offer_lifecycle" module="TRAVEL_HOTEL_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_HOTEL_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_HOTEL_OFFER"
