[SCENARIO: BDD-TRAVEL_VACATION_OFFER-SEED-travel_vacation_offer_event_vacation_offer_activate_travel_catalog_vacation_offer_activated] TITLE: TRAVEL_VACATION_OFFER contract seed scenario TAGS: seed event_contract
GIVEN given_seed_context id="travel_vacation_offer_event_vacation_offer_activate_travel_catalog_vacation_offer_activated" module="TRAVEL_VACATION_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_VACATION_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_VACATION_OFFER"
