[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_action_train_offer_destroy_destroy] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="travel_train_offer_action_train_offer_destroy_destroy" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"
