[SCENARIO: BDD-TRAVEL_TRAVEL_FULFILLMENT-SEED-travel_travel_fulfillment_event_travel_fulfillment_confirm_booking_travel_fulfillment_confirmed] TITLE: TRAVEL_TRAVEL_FULFILLMENT contract seed scenario TAGS: seed event_contract
GIVEN given_seed_context id="travel_travel_fulfillment_event_travel_fulfillment_confirm_booking_travel_fulfillment_confirmed" module="TRAVEL_TRAVEL_FULFILLMENT"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_FULFILLMENT"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_FULFILLMENT"
