[SCENARIO: BDD-TRAVEL_TRAVEL_CHANGE_ORDER_COMPLETE-SEED-travel_action_travel_change_order_complete_update] TITLE: TRAVEL_TRAVEL_CHANGE_ORDER_COMPLETE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="travel_action_travel_change_order_complete_update" module="TRAVEL_TRAVEL_CHANGE_ORDER_COMPLETE"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_CHANGE_ORDER_COMPLETE"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_CHANGE_ORDER_COMPLETE"
