[SCENARIO: BDD-TRAVEL_FLIGHT_OFFER-SEED-travel_flight_offer_action_flight_offer_activate_update] TITLE: TRAVEL_FLIGHT_OFFER contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="travel_flight_offer_action_flight_offer_activate_update" module="TRAVEL_FLIGHT_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_FLIGHT_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_FLIGHT_OFFER"
