[SCENARIO: BDD-TRAVEL_HOTEL_OFFER-SEED-travel_hotel_offer_event_hotel_offer_expire_travel_catalog_hotel_offer_expired] TITLE: TRAVEL_HOTEL_OFFER contract seed scenario TAGS: seed event_contract
GIVEN given_seed_context id="travel_hotel_offer_event_hotel_offer_expire_travel_catalog_hotel_offer_expired" module="TRAVEL_HOTEL_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_HOTEL_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_HOTEL_OFFER"
