[SCENARIO: BDD-TRAVEL_TRAVEL_ROOM_TYPE-SEED-travel_travel_room_type_action_travel_room_type_create_create] TITLE: TRAVEL_TRAVEL_ROOM_TYPE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_travel_room_type_action_travel_room_type_create_create" module="TRAVEL_TRAVEL_ROOM_TYPE"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_ROOM_TYPE"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_ROOM_TYPE"
