[SCENARIO: BDD-TRAVEL_TRAVEL_AIRLINE-SEED-travel_travel_airline_action_travel_airline_update_update] TITLE: TRAVEL_TRAVEL_AIRLINE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="travel_travel_airline_action_travel_airline_update_update" module="TRAVEL_TRAVEL_AIRLINE"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_AIRLINE"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_AIRLINE"
