[SCENARIO: BDD-TRAVEL_TRAVEL-SEED-travel_event_travel_refund_order_refund_travel_refund_order_refunded] TITLE: TRAVEL_TRAVEL contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="travel_event_travel_refund_order_refund_travel_refund_order_refunded" module="TRAVEL_TRAVEL"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL"
