[SCENARIO: BDD-TRAVEL_TRAVEL_STATIC_CODE_MAPPING-SEED-travel_travel_static_code_mapping_action_travel_static_code_mapping_create_create] TITLE: TRAVEL_TRAVEL_STATIC_CODE_MAPPING contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="travel_travel_static_code_mapping_action_travel_static_code_mapping_create_create" module="TRAVEL_TRAVEL_STATIC_CODE_MAPPING"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_STATIC_CODE_MAPPING"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_STATIC_CODE_MAPPING"
