[SCENARIO: BDD-TRAVEL_TRAVEL_ORDER-SEED-travel_travel_order_workflow_travel_order_travel_order_lifecycle] TITLE: TRAVEL_TRAVEL_ORDER contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="travel_travel_order_workflow_travel_order_travel_order_lifecycle" module="TRAVEL_TRAVEL_ORDER"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_ORDER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_ORDER"
