[SCENARIO: BDD-TRAVEL_TRAVEL_ORDER-SEED-travel_travel_order_integration_travel_order_shop_eligibility_quote] TITLE: TRAVEL_TRAVEL_ORDER contract seed scenario TAGS: seed integration_contract
GIVEN given_seed_context id="travel_travel_order_integration_travel_order_shop_eligibility_quote" module="TRAVEL_TRAVEL_ORDER"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_ORDER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_ORDER"
