[SCENARIO: BDD-TRAVEL_TRAVEL_POLICY_CREATE-SEED-travel_action_travel_policy_create_create] TITLE: TRAVEL_TRAVEL_POLICY_CREATE contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="travel_action_travel_policy_create_create" module="TRAVEL_TRAVEL_POLICY_CREATE"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_POLICY_CREATE"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_POLICY_CREATE"
