[SCENARIO: BDD-TRAVEL_TRAVEL_HOTEL-SEED-travel_travel_hotel_action_travel_hotel_read_read] TITLE: TRAVEL_TRAVEL_HOTEL contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="travel_travel_hotel_action_travel_hotel_read_read" module="TRAVEL_TRAVEL_HOTEL"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_HOTEL"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_HOTEL"
