[SCENARIO: BDD-TRAVEL_TRAVEL_AIRLINE-SEED-travel_travel_airline_action_travel_airline_read_read] TITLE: TRAVEL_TRAVEL_AIRLINE contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_travel_airline_action_travel_airline_read_read" module="TRAVEL_TRAVEL_AIRLINE"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_AIRLINE"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_AIRLINE"
