# Generated by: bcc bdd seed --step organize

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_workflow_vo_ip_call_voip_call_lifecycle_flow] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_workflow_vo_ip_call_voip_call_lifecycle_flow" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_transfer_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_transfer_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_create_create] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_create_create" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_miss_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_miss_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_event_vo_ip_call_miss_voip_call_missed] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_event_vo_ip_call_miss_voip_call_missed" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_to_voicemail_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_to_voicemail_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_add_note_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_add_note_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_update_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_update_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_hold_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_hold_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_event_vo_ip_call_answer_voip_call_answered] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_event_vo_ip_call_answer_voip_call_answered" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_answer_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_answer_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_event_vo_ip_call_transfer_voip_call_transferred] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_event_vo_ip_call_transfer_voip_call_transferred" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_unhold_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_unhold_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_end_call_update] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_end_call_update" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_action_vo_ip_call_read_read] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_action_vo_ip_call_read_read" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_event_vo_ip_call_hold_voip_call_held] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_event_vo_ip_call_hold_voip_call_held" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_event_vo_ip_call_unhold_voip_call_resumed] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_event_vo_ip_call_unhold_voip_call_resumed" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

[SCENARIO: BDD-IO_T_VO_IP_CALL-SEED-io_t_vo_ip_call_event_vo_ip_call_end_call_voip_call_ended] TITLE: IO_T_VO_IP_CALL contract seed scenario TAGS: seed all
GIVEN given_seed_context id="io_t_vo_ip_call_event_vo_ip_call_end_call_voip_call_ended" module="IO_T_VO_IP_CALL"
WHEN when_execute_seed_contract module="IO_T_VO_IP_CALL"
THEN then_seed_contract_should_hold module="IO_T_VO_IP_CALL"

