# Generated by: bcc bdd seed --step organize

[SCENARIO: BDD-PARTY_PARTY-SEED-party_party_action_party_update_update] TITLE: PARTY_PARTY contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="party_party_action_party_update_update" module="PARTY_PARTY"
WHEN when_execute_seed_contract module="PARTY_PARTY"
THEN then_seed_contract_should_hold module="PARTY_PARTY"

[SCENARIO: BDD-PARTY_PARTY-SEED-party_party_action_party_read_read_3] TITLE: PARTY_PARTY contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="party_party_action_party_read_read_3" module="PARTY_PARTY"
WHEN when_execute_seed_contract module="PARTY_PARTY"
THEN then_seed_contract_should_hold module="PARTY_PARTY"

[SCENARIO: BDD-PARTY_PARTY-SEED-party_party_action_party_destroy_destroy] TITLE: PARTY_PARTY contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="party_party_action_party_destroy_destroy" module="PARTY_PARTY"
WHEN when_execute_seed_contract module="PARTY_PARTY"
THEN then_seed_contract_should_hold module="PARTY_PARTY"

[SCENARIO: BDD-PARTY_PARTY-SEED-party_party_action_party_create_create] TITLE: PARTY_PARTY contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="party_party_action_party_create_create" module="PARTY_PARTY"
WHEN when_execute_seed_contract module="PARTY_PARTY"
THEN then_seed_contract_should_hold module="PARTY_PARTY"

