# Generated by: bcc bdd seed --step organize

[SCENARIO: BDD-SALES_TAX-SEED-sales_tax_action_tax_read_read_2] TITLE: SALES_TAX contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_tax_action_tax_read_read_2" module="SALES_TAX"
WHEN when_execute_seed_contract module="SALES_TAX"
THEN then_seed_contract_should_hold module="SALES_TAX"

[SCENARIO: BDD-SALES_TAX-SEED-sales_tax_action_tax_get_read] TITLE: SALES_TAX contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_tax_action_tax_get_read" module="SALES_TAX"
WHEN when_execute_seed_contract module="SALES_TAX"
THEN then_seed_contract_should_hold module="SALES_TAX"

[SCENARIO: BDD-SALES_TAX-SEED-sales_tax_action_tax_list_read] TITLE: SALES_TAX contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_tax_action_tax_list_read" module="SALES_TAX"
WHEN when_execute_seed_contract module="SALES_TAX"
THEN then_seed_contract_should_hold module="SALES_TAX"

[SCENARIO: BDD-SALES_TAX-SEED-sales_tax_action_tax_lookup_read] TITLE: SALES_TAX contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_tax_action_tax_lookup_read" module="SALES_TAX"
WHEN when_execute_seed_contract module="SALES_TAX"
THEN then_seed_contract_should_hold module="SALES_TAX"

[SCENARIO: BDD-SALES_TAX-SEED-sales_tax_action_tax_compute_read] TITLE: SALES_TAX contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_tax_action_tax_compute_read" module="SALES_TAX"
WHEN when_execute_seed_contract module="SALES_TAX"
THEN then_seed_contract_should_hold module="SALES_TAX"

[SCENARIO: BDD-SALES_TAX-SEED-sales_tax_action_tax_preview_read] TITLE: SALES_TAX contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_tax_action_tax_preview_read" module="SALES_TAX"
WHEN when_execute_seed_contract module="SALES_TAX"
THEN then_seed_contract_should_hold module="SALES_TAX"

[SCENARIO: BDD-SALES_TAX-SEED-sales_tax_action_tax_search_read] TITLE: SALES_TAX contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_tax_action_tax_search_read" module="SALES_TAX"
WHEN when_execute_seed_contract module="SALES_TAX"
THEN then_seed_contract_should_hold module="SALES_TAX"

