# Generated by: bcc bdd seed --step organize

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_event_return_approve_sales_return_approved] TITLE: SALES_RETURN contract seed scenario TAGS: seed event_contract
GIVEN given_seed_context id="sales_return_event_return_approve_sales_return_approved" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_search_read] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_search_read" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_workflow_return_return_lifecycle] TITLE: SALES_RETURN contract seed scenario TAGS: seed workflow_contract
GIVEN given_seed_context id="sales_return_workflow_return_return_lifecycle" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_read_read] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_read_read" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_receive_update] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_receive_update" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_compute_read] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_compute_read" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_create_create] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_create_create" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_preview_read] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_preview_read" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_complete_update] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_complete_update" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_lookup_read] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_lookup_read" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_cancel_update] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_cancel_update" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_approve_update] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_approve_update" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_event_return_complete_sales_return_completed] TITLE: SALES_RETURN contract seed scenario TAGS: seed event_contract
GIVEN given_seed_context id="sales_return_event_return_complete_sales_return_completed" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_list_read] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_list_read" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

[SCENARIO: BDD-SALES_RETURN-SEED-sales_return_action_return_get_read] TITLE: SALES_RETURN contract seed scenario TAGS: seed action_contract
GIVEN given_seed_context id="sales_return_action_return_get_read" module="SALES_RETURN"
WHEN when_execute_seed_contract module="SALES_RETURN"
THEN then_seed_contract_should_hold module="SALES_RETURN"

