# Generated by: bcc bdd seed --step organize

[SCENARIO: BDD-SIGN_PARTY-SEED-sign_party_action_party_read_read] TITLE: SIGN_PARTY contract seed scenario TAGS: seed all
GIVEN given_seed_context id="sign_party_action_party_read_read" module="SIGN_PARTY"
WHEN when_execute_seed_contract module="SIGN_PARTY"
THEN then_seed_contract_should_hold module="SIGN_PARTY"

