# Generated by: bcc bdd seed --step organize

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_action_train_offer_expire_update] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_action_train_offer_expire_update" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_action_train_offer_activate_update] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_action_train_offer_activate_update" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_action_train_offer_read_read] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_action_train_offer_read_read" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_event_train_offer_expire_travel_catalog_train_offer_expired] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_event_train_offer_expire_travel_catalog_train_offer_expired" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_event_train_offer_activate_travel_catalog_train_offer_activated] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_event_train_offer_activate_travel_catalog_train_offer_activated" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_event_train_offer_deactivate_travel_catalog_train_offer_deactivated] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_event_train_offer_deactivate_travel_catalog_train_offer_deactivated" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_action_train_offer_create_create] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_action_train_offer_create_create" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_action_train_offer_destroy_destroy] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_action_train_offer_destroy_destroy" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_action_train_offer_deactivate_update] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_action_train_offer_deactivate_update" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_workflow_train_offer_train_offer_lifecycle] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_workflow_train_offer_train_offer_lifecycle" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_action_train_offer_update_update] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_action_train_offer_update_update" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"

