// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/biantaishabi2/unibo-ex-poc/travel-go/ent/flightoffer"
	"github.com/google/uuid"
)

// FlightOffer is the model entity for the FlightOffer schema.
type FlightOffer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// HostShopID holds the value of the "host_shop_id" field.
	HostShopID uuid.UUID `json:"host_shop_id,omitempty"`
	// SupplierCode holds the value of the "supplier_code" field.
	SupplierCode string `json:"supplier_code,omitempty"`
	// ItineraryCode holds the value of the "itinerary_code" field.
	ItineraryCode string `json:"itinerary_code,omitempty"`
	// FlightNo holds the value of the "flight_no" field.
	FlightNo string `json:"flight_no,omitempty"`
	// DepartureAirportCode holds the value of the "departure_airport_code" field.
	DepartureAirportCode string `json:"departure_airport_code,omitempty"`
	// ArrivalAirportCode holds the value of the "arrival_airport_code" field.
	ArrivalAirportCode string `json:"arrival_airport_code,omitempty"`
	// DepartureAt holds the value of the "departure_at" field.
	DepartureAt time.Time `json:"departure_at,omitempty"`
	// ArrivalAt holds the value of the "arrival_at" field.
	ArrivalAt time.Time `json:"arrival_at,omitempty"`
	// CabinClass holds the value of the "cabin_class" field.
	CabinClass string `json:"cabin_class,omitempty"`
	// FareFamily holds the value of the "fare_family" field.
	FareFamily string `json:"fare_family,omitempty"`
	// ListedPrice holds the value of the "listed_price" field.
	ListedPrice float64 `json:"listed_price,omitempty"`
	// SettlementPrice holds the value of the "settlement_price" field.
	SettlementPrice float64 `json:"settlement_price,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// SeatsAvailable holds the value of the "seats_available" field.
	SeatsAvailable int `json:"seats_available,omitempty"`
	// BaggagePolicy holds the value of the "baggage_policy" field.
	BaggagePolicy string `json:"baggage_policy,omitempty"`
	// RefundChangePolicy holds the value of the "refund_change_policy" field.
	RefundChangePolicy string `json:"refund_change_policy,omitempty"`
	// SaleStatus holds the value of the "sale_status" field.
	SaleStatus flightoffer.SaleStatus `json:"sale_status,omitempty"`
	// InsertedAt holds the value of the "inserted_at" field.
	InsertedAt time.Time `json:"inserted_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FlightOfferQuery when eager-loading is set.
	Edges        FlightOfferEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FlightOfferEdges holds the relations/edges for other nodes in the graph.
type FlightOfferEdges struct {
	// Orders holds the value of the orders edge.
	Orders []*TravelOrder `json:"orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedOrders map[string][]*TravelOrder
}

// OrdersOrErr returns the Orders value or an error if the edge
// was not loaded in eager-loading.
func (e FlightOfferEdges) OrdersOrErr() ([]*TravelOrder, error) {
	if e.loadedTypes[0] {
		return e.Orders, nil
	}
	return nil, &NotLoadedError{edge: "orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FlightOffer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case flightoffer.FieldListedPrice, flightoffer.FieldSettlementPrice:
			values[i] = new(sql.NullFloat64)
		case flightoffer.FieldSeatsAvailable:
			values[i] = new(sql.NullInt64)
		case flightoffer.FieldSupplierCode, flightoffer.FieldItineraryCode, flightoffer.FieldFlightNo, flightoffer.FieldDepartureAirportCode, flightoffer.FieldArrivalAirportCode, flightoffer.FieldCabinClass, flightoffer.FieldFareFamily, flightoffer.FieldCurrency, flightoffer.FieldBaggagePolicy, flightoffer.FieldRefundChangePolicy, flightoffer.FieldSaleStatus:
			values[i] = new(sql.NullString)
		case flightoffer.FieldDepartureAt, flightoffer.FieldArrivalAt, flightoffer.FieldInsertedAt, flightoffer.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case flightoffer.FieldID, flightoffer.FieldTenantID, flightoffer.FieldHostShopID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FlightOffer fields.
func (fo *FlightOffer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case flightoffer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				fo.ID = *value
			}
		case flightoffer.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				fo.TenantID = *value
			}
		case flightoffer.FieldHostShopID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field host_shop_id", values[i])
			} else if value != nil {
				fo.HostShopID = *value
			}
		case flightoffer.FieldSupplierCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_code", values[i])
			} else if value.Valid {
				fo.SupplierCode = value.String
			}
		case flightoffer.FieldItineraryCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field itinerary_code", values[i])
			} else if value.Valid {
				fo.ItineraryCode = value.String
			}
		case flightoffer.FieldFlightNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flight_no", values[i])
			} else if value.Valid {
				fo.FlightNo = value.String
			}
		case flightoffer.FieldDepartureAirportCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field departure_airport_code", values[i])
			} else if value.Valid {
				fo.DepartureAirportCode = value.String
			}
		case flightoffer.FieldArrivalAirportCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field arrival_airport_code", values[i])
			} else if value.Valid {
				fo.ArrivalAirportCode = value.String
			}
		case flightoffer.FieldDepartureAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field departure_at", values[i])
			} else if value.Valid {
				fo.DepartureAt = value.Time
			}
		case flightoffer.FieldArrivalAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field arrival_at", values[i])
			} else if value.Valid {
				fo.ArrivalAt = value.Time
			}
		case flightoffer.FieldCabinClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cabin_class", values[i])
			} else if value.Valid {
				fo.CabinClass = value.String
			}
		case flightoffer.FieldFareFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fare_family", values[i])
			} else if value.Valid {
				fo.FareFamily = value.String
			}
		case flightoffer.FieldListedPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field listed_price", values[i])
			} else if value.Valid {
				fo.ListedPrice = value.Float64
			}
		case flightoffer.FieldSettlementPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_price", values[i])
			} else if value.Valid {
				fo.SettlementPrice = value.Float64
			}
		case flightoffer.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				fo.Currency = value.String
			}
		case flightoffer.FieldSeatsAvailable:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field seats_available", values[i])
			} else if value.Valid {
				fo.SeatsAvailable = int(value.Int64)
			}
		case flightoffer.FieldBaggagePolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field baggage_policy", values[i])
			} else if value.Valid {
				fo.BaggagePolicy = value.String
			}
		case flightoffer.FieldRefundChangePolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_change_policy", values[i])
			} else if value.Valid {
				fo.RefundChangePolicy = value.String
			}
		case flightoffer.FieldSaleStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sale_status", values[i])
			} else if value.Valid {
				fo.SaleStatus = flightoffer.SaleStatus(value.String)
			}
		case flightoffer.FieldInsertedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field inserted_at", values[i])
			} else if value.Valid {
				fo.InsertedAt = value.Time
			}
		case flightoffer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				fo.UpdatedAt = value.Time
			}
		default:
			fo.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FlightOffer.
// This includes values selected through modifiers, order, etc.
func (fo *FlightOffer) Value(name string) (ent.Value, error) {
	return fo.selectValues.Get(name)
}

// QueryOrders queries the "orders" edge of the FlightOffer entity.
func (fo *FlightOffer) QueryOrders() *TravelOrderQuery {
	return NewFlightOfferClient(fo.config).QueryOrders(fo)
}

// Update returns a builder for updating this FlightOffer.
// Note that you need to call FlightOffer.Unwrap() before calling this method if this FlightOffer
// was returned from a transaction, and the transaction was committed or rolled back.
func (fo *FlightOffer) Update() *FlightOfferUpdateOne {
	return NewFlightOfferClient(fo.config).UpdateOne(fo)
}

// Unwrap unwraps the FlightOffer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (fo *FlightOffer) Unwrap() *FlightOffer {
	_tx, ok := fo.config.driver.(*txDriver)
	if !ok {
		panic("ent: FlightOffer is not a transactional entity")
	}
	fo.config.driver = _tx.drv
	return fo
}

// String implements the fmt.Stringer.
func (fo *FlightOffer) String() string {
	var builder strings.Builder
	builder.WriteString("FlightOffer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", fo.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", fo.TenantID))
	builder.WriteString(", ")
	builder.WriteString("host_shop_id=")
	builder.WriteString(fmt.Sprintf("%v", fo.HostShopID))
	builder.WriteString(", ")
	builder.WriteString("supplier_code=")
	builder.WriteString(fo.SupplierCode)
	builder.WriteString(", ")
	builder.WriteString("itinerary_code=")
	builder.WriteString(fo.ItineraryCode)
	builder.WriteString(", ")
	builder.WriteString("flight_no=")
	builder.WriteString(fo.FlightNo)
	builder.WriteString(", ")
	builder.WriteString("departure_airport_code=")
	builder.WriteString(fo.DepartureAirportCode)
	builder.WriteString(", ")
	builder.WriteString("arrival_airport_code=")
	builder.WriteString(fo.ArrivalAirportCode)
	builder.WriteString(", ")
	builder.WriteString("departure_at=")
	builder.WriteString(fo.DepartureAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("arrival_at=")
	builder.WriteString(fo.ArrivalAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("cabin_class=")
	builder.WriteString(fo.CabinClass)
	builder.WriteString(", ")
	builder.WriteString("fare_family=")
	builder.WriteString(fo.FareFamily)
	builder.WriteString(", ")
	builder.WriteString("listed_price=")
	builder.WriteString(fmt.Sprintf("%v", fo.ListedPrice))
	builder.WriteString(", ")
	builder.WriteString("settlement_price=")
	builder.WriteString(fmt.Sprintf("%v", fo.SettlementPrice))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(fo.Currency)
	builder.WriteString(", ")
	builder.WriteString("seats_available=")
	builder.WriteString(fmt.Sprintf("%v", fo.SeatsAvailable))
	builder.WriteString(", ")
	builder.WriteString("baggage_policy=")
	builder.WriteString(fo.BaggagePolicy)
	builder.WriteString(", ")
	builder.WriteString("refund_change_policy=")
	builder.WriteString(fo.RefundChangePolicy)
	builder.WriteString(", ")
	builder.WriteString("sale_status=")
	builder.WriteString(fmt.Sprintf("%v", fo.SaleStatus))
	builder.WriteString(", ")
	builder.WriteString("inserted_at=")
	builder.WriteString(fo.InsertedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fo.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NamedOrders returns the Orders named value or an error if the edge was not
// loaded in eager-loading with this name.
func (fo *FlightOffer) NamedOrders(name string) ([]*TravelOrder, error) {
	if fo.Edges.namedOrders == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := fo.Edges.namedOrders[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (fo *FlightOffer) appendNamedOrders(name string, edges ...*TravelOrder) {
	if fo.Edges.namedOrders == nil {
		fo.Edges.namedOrders = make(map[string][]*TravelOrder)
	}
	if len(edges) == 0 {
		fo.Edges.namedOrders[name] = []*TravelOrder{}
	} else {
		fo.Edges.namedOrders[name] = append(fo.Edges.namedOrders[name], edges...)
	}
}

// FlightOffers is a parsable slice of FlightOffer.
type FlightOffers []*FlightOffer
