[SCENARIO: BDD-TRAVEL_VACATION_OFFER-SEED-travel_vacation_offer_workflow_vacation_offer_vacation_offer_lifecycle_risk_branch_or_exception] TITLE: TRAVEL_VACATION_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_vacation_offer_workflow_vacation_offer_vacation_offer_lifecycle_risk_branch_or_exception" module="TRAVEL_VACATION_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_VACATION_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_VACATION_OFFER"
