[SCENARIO: BDD-TRAVEL_HOTEL_OFFER-SEED-travel_hotel_offer_action_hotel_offer_expire_update_risk_validation_fail] TITLE: TRAVEL_HOTEL_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_hotel_offer_action_hotel_offer_expire_update_risk_validation_fail" module="TRAVEL_HOTEL_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_HOTEL_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_HOTEL_OFFER"
