[SCENARIO: BDD-TRAVEL_FLIGHT_OFFER-SEED-travel_flight_offer_workflow_flight_offer_flight_offer_lifecycle_risk_mainline] TITLE: TRAVEL_FLIGHT_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_flight_offer_workflow_flight_offer_flight_offer_lifecycle_risk_mainline" module="TRAVEL_FLIGHT_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_FLIGHT_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_FLIGHT_OFFER"
