[SCENARIO: BDD-TRAVEL_VACATION_OFFER-SEED-travel_vacation_offer_event_vacation_offer_deactivate_travel_catalog_vacation_offer_deactivated_risk_idempotent_replay] TITLE: TRAVEL_VACATION_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_vacation_offer_event_vacation_offer_deactivate_travel_catalog_vacation_offer_deactivated_risk_idempotent_replay" module="TRAVEL_VACATION_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_VACATION_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_VACATION_OFFER"
