[SCENARIO: BDD-TRAVEL_TRAVEL_FULFILLMENT-SEED-travel_travel_fulfillment_event_travel_fulfillment_fail_fulfillment_travel_fulfillment_failed_risk_idempotent_replay] TITLE: TRAVEL_TRAVEL_FULFILLMENT contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_travel_fulfillment_event_travel_fulfillment_fail_fulfillment_travel_fulfillment_failed_risk_idempotent_replay" module="TRAVEL_TRAVEL_FULFILLMENT"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_FULFILLMENT"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_FULFILLMENT"
