[SCENARIO: BDD-TRAVEL_TRAIN_OFFER-SEED-travel_train_offer_event_train_offer_activate_travel_catalog_train_offer_activated_risk_normal_publish] TITLE: TRAVEL_TRAIN_OFFER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_train_offer_event_train_offer_activate_travel_catalog_train_offer_activated_risk_normal_publish" module="TRAVEL_TRAIN_OFFER"
WHEN when_execute_seed_contract module="TRAVEL_TRAIN_OFFER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAIN_OFFER"
