[SCENARIO: BDD-TRAVEL_TRAVEL_ORDER-SEED-travel_travel_order_event_travel_order_mark_order_failed_travel_order_failed] TITLE: TRAVEL_TRAVEL_ORDER contract seed scenario TAGS: seed all
GIVEN given_seed_context id="travel_travel_order_event_travel_order_mark_order_failed_travel_order_failed" module="TRAVEL_TRAVEL_ORDER"
WHEN when_execute_seed_contract module="TRAVEL_TRAVEL_ORDER"
THEN then_seed_contract_should_hold module="TRAVEL_TRAVEL_ORDER"
