defmodule UniboExPoc.Ofbiz.HumanRes do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboExPoc.Ofbiz.HumanRes.PartyQual
    resource UniboExPoc.Ofbiz.HumanRes.PartyQual.Version
    resource UniboExPoc.Ofbiz.HumanRes.PartyQualType
    resource UniboExPoc.Ofbiz.HumanRes.PartyQualType.Version
    resource UniboExPoc.Ofbiz.HumanRes.PartyResume
    resource UniboExPoc.Ofbiz.HumanRes.PartyResume.Version
    resource UniboExPoc.Ofbiz.HumanRes.PartySkill
    resource UniboExPoc.Ofbiz.HumanRes.PartySkill.Version
    resource UniboExPoc.Ofbiz.HumanRes.PerfRatingType
    resource UniboExPoc.Ofbiz.HumanRes.PerfRatingType.Version
    resource UniboExPoc.Ofbiz.HumanRes.PerfReview
    resource UniboExPoc.Ofbiz.HumanRes.PerfReviewItem
    resource UniboExPoc.Ofbiz.HumanRes.PerfReviewItemType
    resource UniboExPoc.Ofbiz.HumanRes.PerfReviewItemType.Version
    resource UniboExPoc.Ofbiz.HumanRes.PerformanceNote
    resource UniboExPoc.Ofbiz.HumanRes.PersonTraining
    resource UniboExPoc.Ofbiz.HumanRes.PersonTraining.Version
    resource UniboExPoc.Ofbiz.HumanRes.ResponsibilityType
    resource UniboExPoc.Ofbiz.HumanRes.ResponsibilityType.Version
    resource UniboExPoc.Ofbiz.HumanRes.SkillType
    resource UniboExPoc.Ofbiz.HumanRes.SkillType.Version
    resource UniboExPoc.Ofbiz.HumanRes.TrainingClassType
    resource UniboExPoc.Ofbiz.HumanRes.TrainingClassType.Version
    resource UniboExPoc.Ofbiz.HumanRes.BenefitType
    resource UniboExPoc.Ofbiz.HumanRes.BenefitType.Version
    resource UniboExPoc.Ofbiz.HumanRes.Employment
    resource UniboExPoc.Ofbiz.HumanRes.EmploymentApp
    resource UniboExPoc.Ofbiz.HumanRes.EmploymentApp.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmploymentAppSourceType
    resource UniboExPoc.Ofbiz.HumanRes.EmploymentAppSourceType.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplLeave
    resource UniboExPoc.Ofbiz.HumanRes.EmplLeave.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplLeaveType
    resource UniboExPoc.Ofbiz.HumanRes.EmplLeaveType.Version
    resource UniboExPoc.Ofbiz.HumanRes.PartyBenefit
    resource UniboExPoc.Ofbiz.HumanRes.PayGrade
    resource UniboExPoc.Ofbiz.HumanRes.PayGrade.Version
    resource UniboExPoc.Ofbiz.HumanRes.PayHistory
    resource UniboExPoc.Ofbiz.HumanRes.PayrollPreference
    resource UniboExPoc.Ofbiz.HumanRes.SalaryStep
    resource UniboExPoc.Ofbiz.HumanRes.TerminationReason
    resource UniboExPoc.Ofbiz.HumanRes.TerminationReason.Version
    resource UniboExPoc.Ofbiz.HumanRes.TerminationType
    resource UniboExPoc.Ofbiz.HumanRes.TerminationType.Version
    resource UniboExPoc.Ofbiz.HumanRes.UnemploymentClaim
    resource UniboExPoc.Ofbiz.HumanRes.UnemploymentClaim.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplPosition
    resource UniboExPoc.Ofbiz.HumanRes.EmplPosition.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionClassType
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionClassType.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionFulfillment
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionFulfillment.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionReportingStruct
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionReportingStruct.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionResponsibility
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionResponsibility.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionType
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionType.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionTypeClass
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionTypeClass.Version
    resource UniboExPoc.Ofbiz.HumanRes.ValidResponsibility
    resource UniboExPoc.Ofbiz.HumanRes.ValidResponsibility.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionTypeRate
    resource UniboExPoc.Ofbiz.HumanRes.EmplPositionTypeRate.Version
    resource UniboExPoc.Ofbiz.HumanRes.JobRequisition
    resource UniboExPoc.Ofbiz.HumanRes.JobRequisition.Version
    resource UniboExPoc.Ofbiz.HumanRes.JobInterview
    resource UniboExPoc.Ofbiz.HumanRes.JobInterview.Version
    resource UniboExPoc.Ofbiz.HumanRes.JobInterviewType
    resource UniboExPoc.Ofbiz.HumanRes.JobInterviewType.Version
    resource UniboExPoc.Ofbiz.HumanRes.TrainingRequest
    resource UniboExPoc.Ofbiz.HumanRes.TrainingRequest.Version
    resource UniboExPoc.Ofbiz.HumanRes.EmplLeaveReasonType
    resource UniboExPoc.Ofbiz.HumanRes.EmplLeaveReasonType.Version
    resource UniboExPoc.Ofbiz.HumanRes.Content
    resource UniboExPoc.Ofbiz.HumanRes.DeductionType
    resource UniboExPoc.Ofbiz.HumanRes.Enumeration
    resource UniboExPoc.Ofbiz.HumanRes.Party
    resource UniboExPoc.Ofbiz.HumanRes.Payment
    resource UniboExPoc.Ofbiz.HumanRes.PaymentMethodType
    resource UniboExPoc.Ofbiz.HumanRes.PeriodType
    resource UniboExPoc.Ofbiz.HumanRes.Person
    resource UniboExPoc.Ofbiz.HumanRes.RateType
    resource UniboExPoc.Ofbiz.HumanRes.StatusItem
    resource UniboExPoc.Ofbiz.HumanRes.WorkEffort
  end
end
