// Code generated by ent, DO NOT EDIT.

package flightoffer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/biantaishabi2/unibo-ex-poc/travel-go/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldTenantID, v))
}

// HostShopID applies equality check predicate on the "host_shop_id" field. It's identical to HostShopIDEQ.
func HostShopID(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldHostShopID, v))
}

// SupplierCode applies equality check predicate on the "supplier_code" field. It's identical to SupplierCodeEQ.
func SupplierCode(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldSupplierCode, v))
}

// ItineraryCode applies equality check predicate on the "itinerary_code" field. It's identical to ItineraryCodeEQ.
func ItineraryCode(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldItineraryCode, v))
}

// FlightNo applies equality check predicate on the "flight_no" field. It's identical to FlightNoEQ.
func FlightNo(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldFlightNo, v))
}

// DepartureAirportCode applies equality check predicate on the "departure_airport_code" field. It's identical to DepartureAirportCodeEQ.
func DepartureAirportCode(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldDepartureAirportCode, v))
}

// ArrivalAirportCode applies equality check predicate on the "arrival_airport_code" field. It's identical to ArrivalAirportCodeEQ.
func ArrivalAirportCode(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldArrivalAirportCode, v))
}

// DepartureAt applies equality check predicate on the "departure_at" field. It's identical to DepartureAtEQ.
func DepartureAt(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldDepartureAt, v))
}

// ArrivalAt applies equality check predicate on the "arrival_at" field. It's identical to ArrivalAtEQ.
func ArrivalAt(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldArrivalAt, v))
}

// CabinClass applies equality check predicate on the "cabin_class" field. It's identical to CabinClassEQ.
func CabinClass(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldCabinClass, v))
}

// FareFamily applies equality check predicate on the "fare_family" field. It's identical to FareFamilyEQ.
func FareFamily(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldFareFamily, v))
}

// ListedPrice applies equality check predicate on the "listed_price" field. It's identical to ListedPriceEQ.
func ListedPrice(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldListedPrice, v))
}

// SettlementPrice applies equality check predicate on the "settlement_price" field. It's identical to SettlementPriceEQ.
func SettlementPrice(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldSettlementPrice, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldCurrency, v))
}

// SeatsAvailable applies equality check predicate on the "seats_available" field. It's identical to SeatsAvailableEQ.
func SeatsAvailable(v int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldSeatsAvailable, v))
}

// BaggagePolicy applies equality check predicate on the "baggage_policy" field. It's identical to BaggagePolicyEQ.
func BaggagePolicy(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldBaggagePolicy, v))
}

// RefundChangePolicy applies equality check predicate on the "refund_change_policy" field. It's identical to RefundChangePolicyEQ.
func RefundChangePolicy(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldRefundChangePolicy, v))
}

// InsertedAt applies equality check predicate on the "inserted_at" field. It's identical to InsertedAtEQ.
func InsertedAt(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldInsertedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldTenantID, v))
}

// HostShopIDEQ applies the EQ predicate on the "host_shop_id" field.
func HostShopIDEQ(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldHostShopID, v))
}

// HostShopIDNEQ applies the NEQ predicate on the "host_shop_id" field.
func HostShopIDNEQ(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldHostShopID, v))
}

// HostShopIDIn applies the In predicate on the "host_shop_id" field.
func HostShopIDIn(vs ...uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldHostShopID, vs...))
}

// HostShopIDNotIn applies the NotIn predicate on the "host_shop_id" field.
func HostShopIDNotIn(vs ...uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldHostShopID, vs...))
}

// HostShopIDGT applies the GT predicate on the "host_shop_id" field.
func HostShopIDGT(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldHostShopID, v))
}

// HostShopIDGTE applies the GTE predicate on the "host_shop_id" field.
func HostShopIDGTE(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldHostShopID, v))
}

// HostShopIDLT applies the LT predicate on the "host_shop_id" field.
func HostShopIDLT(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldHostShopID, v))
}

// HostShopIDLTE applies the LTE predicate on the "host_shop_id" field.
func HostShopIDLTE(v uuid.UUID) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldHostShopID, v))
}

// HostShopIDIsNil applies the IsNil predicate on the "host_shop_id" field.
func HostShopIDIsNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIsNull(FieldHostShopID))
}

// HostShopIDNotNil applies the NotNil predicate on the "host_shop_id" field.
func HostShopIDNotNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotNull(FieldHostShopID))
}

// SupplierCodeEQ applies the EQ predicate on the "supplier_code" field.
func SupplierCodeEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldSupplierCode, v))
}

// SupplierCodeNEQ applies the NEQ predicate on the "supplier_code" field.
func SupplierCodeNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldSupplierCode, v))
}

// SupplierCodeIn applies the In predicate on the "supplier_code" field.
func SupplierCodeIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldSupplierCode, vs...))
}

// SupplierCodeNotIn applies the NotIn predicate on the "supplier_code" field.
func SupplierCodeNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldSupplierCode, vs...))
}

// SupplierCodeGT applies the GT predicate on the "supplier_code" field.
func SupplierCodeGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldSupplierCode, v))
}

// SupplierCodeGTE applies the GTE predicate on the "supplier_code" field.
func SupplierCodeGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldSupplierCode, v))
}

// SupplierCodeLT applies the LT predicate on the "supplier_code" field.
func SupplierCodeLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldSupplierCode, v))
}

// SupplierCodeLTE applies the LTE predicate on the "supplier_code" field.
func SupplierCodeLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldSupplierCode, v))
}

// SupplierCodeContains applies the Contains predicate on the "supplier_code" field.
func SupplierCodeContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldSupplierCode, v))
}

// SupplierCodeHasPrefix applies the HasPrefix predicate on the "supplier_code" field.
func SupplierCodeHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldSupplierCode, v))
}

// SupplierCodeHasSuffix applies the HasSuffix predicate on the "supplier_code" field.
func SupplierCodeHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldSupplierCode, v))
}

// SupplierCodeEqualFold applies the EqualFold predicate on the "supplier_code" field.
func SupplierCodeEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldSupplierCode, v))
}

// SupplierCodeContainsFold applies the ContainsFold predicate on the "supplier_code" field.
func SupplierCodeContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldSupplierCode, v))
}

// ItineraryCodeEQ applies the EQ predicate on the "itinerary_code" field.
func ItineraryCodeEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldItineraryCode, v))
}

// ItineraryCodeNEQ applies the NEQ predicate on the "itinerary_code" field.
func ItineraryCodeNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldItineraryCode, v))
}

// ItineraryCodeIn applies the In predicate on the "itinerary_code" field.
func ItineraryCodeIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldItineraryCode, vs...))
}

// ItineraryCodeNotIn applies the NotIn predicate on the "itinerary_code" field.
func ItineraryCodeNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldItineraryCode, vs...))
}

// ItineraryCodeGT applies the GT predicate on the "itinerary_code" field.
func ItineraryCodeGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldItineraryCode, v))
}

// ItineraryCodeGTE applies the GTE predicate on the "itinerary_code" field.
func ItineraryCodeGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldItineraryCode, v))
}

// ItineraryCodeLT applies the LT predicate on the "itinerary_code" field.
func ItineraryCodeLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldItineraryCode, v))
}

// ItineraryCodeLTE applies the LTE predicate on the "itinerary_code" field.
func ItineraryCodeLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldItineraryCode, v))
}

// ItineraryCodeContains applies the Contains predicate on the "itinerary_code" field.
func ItineraryCodeContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldItineraryCode, v))
}

// ItineraryCodeHasPrefix applies the HasPrefix predicate on the "itinerary_code" field.
func ItineraryCodeHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldItineraryCode, v))
}

// ItineraryCodeHasSuffix applies the HasSuffix predicate on the "itinerary_code" field.
func ItineraryCodeHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldItineraryCode, v))
}

// ItineraryCodeEqualFold applies the EqualFold predicate on the "itinerary_code" field.
func ItineraryCodeEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldItineraryCode, v))
}

// ItineraryCodeContainsFold applies the ContainsFold predicate on the "itinerary_code" field.
func ItineraryCodeContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldItineraryCode, v))
}

// FlightNoEQ applies the EQ predicate on the "flight_no" field.
func FlightNoEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldFlightNo, v))
}

// FlightNoNEQ applies the NEQ predicate on the "flight_no" field.
func FlightNoNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldFlightNo, v))
}

// FlightNoIn applies the In predicate on the "flight_no" field.
func FlightNoIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldFlightNo, vs...))
}

// FlightNoNotIn applies the NotIn predicate on the "flight_no" field.
func FlightNoNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldFlightNo, vs...))
}

// FlightNoGT applies the GT predicate on the "flight_no" field.
func FlightNoGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldFlightNo, v))
}

// FlightNoGTE applies the GTE predicate on the "flight_no" field.
func FlightNoGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldFlightNo, v))
}

// FlightNoLT applies the LT predicate on the "flight_no" field.
func FlightNoLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldFlightNo, v))
}

// FlightNoLTE applies the LTE predicate on the "flight_no" field.
func FlightNoLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldFlightNo, v))
}

// FlightNoContains applies the Contains predicate on the "flight_no" field.
func FlightNoContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldFlightNo, v))
}

// FlightNoHasPrefix applies the HasPrefix predicate on the "flight_no" field.
func FlightNoHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldFlightNo, v))
}

// FlightNoHasSuffix applies the HasSuffix predicate on the "flight_no" field.
func FlightNoHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldFlightNo, v))
}

// FlightNoEqualFold applies the EqualFold predicate on the "flight_no" field.
func FlightNoEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldFlightNo, v))
}

// FlightNoContainsFold applies the ContainsFold predicate on the "flight_no" field.
func FlightNoContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldFlightNo, v))
}

// DepartureAirportCodeEQ applies the EQ predicate on the "departure_airport_code" field.
func DepartureAirportCodeEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeNEQ applies the NEQ predicate on the "departure_airport_code" field.
func DepartureAirportCodeNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeIn applies the In predicate on the "departure_airport_code" field.
func DepartureAirportCodeIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldDepartureAirportCode, vs...))
}

// DepartureAirportCodeNotIn applies the NotIn predicate on the "departure_airport_code" field.
func DepartureAirportCodeNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldDepartureAirportCode, vs...))
}

// DepartureAirportCodeGT applies the GT predicate on the "departure_airport_code" field.
func DepartureAirportCodeGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeGTE applies the GTE predicate on the "departure_airport_code" field.
func DepartureAirportCodeGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeLT applies the LT predicate on the "departure_airport_code" field.
func DepartureAirportCodeLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeLTE applies the LTE predicate on the "departure_airport_code" field.
func DepartureAirportCodeLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeContains applies the Contains predicate on the "departure_airport_code" field.
func DepartureAirportCodeContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeHasPrefix applies the HasPrefix predicate on the "departure_airport_code" field.
func DepartureAirportCodeHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeHasSuffix applies the HasSuffix predicate on the "departure_airport_code" field.
func DepartureAirportCodeHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeEqualFold applies the EqualFold predicate on the "departure_airport_code" field.
func DepartureAirportCodeEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldDepartureAirportCode, v))
}

// DepartureAirportCodeContainsFold applies the ContainsFold predicate on the "departure_airport_code" field.
func DepartureAirportCodeContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldDepartureAirportCode, v))
}

// ArrivalAirportCodeEQ applies the EQ predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeNEQ applies the NEQ predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeIn applies the In predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldArrivalAirportCode, vs...))
}

// ArrivalAirportCodeNotIn applies the NotIn predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldArrivalAirportCode, vs...))
}

// ArrivalAirportCodeGT applies the GT predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeGTE applies the GTE predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeLT applies the LT predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeLTE applies the LTE predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeContains applies the Contains predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeHasPrefix applies the HasPrefix predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeHasSuffix applies the HasSuffix predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeEqualFold applies the EqualFold predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldArrivalAirportCode, v))
}

// ArrivalAirportCodeContainsFold applies the ContainsFold predicate on the "arrival_airport_code" field.
func ArrivalAirportCodeContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldArrivalAirportCode, v))
}

// DepartureAtEQ applies the EQ predicate on the "departure_at" field.
func DepartureAtEQ(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldDepartureAt, v))
}

// DepartureAtNEQ applies the NEQ predicate on the "departure_at" field.
func DepartureAtNEQ(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldDepartureAt, v))
}

// DepartureAtIn applies the In predicate on the "departure_at" field.
func DepartureAtIn(vs ...time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldDepartureAt, vs...))
}

// DepartureAtNotIn applies the NotIn predicate on the "departure_at" field.
func DepartureAtNotIn(vs ...time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldDepartureAt, vs...))
}

// DepartureAtGT applies the GT predicate on the "departure_at" field.
func DepartureAtGT(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldDepartureAt, v))
}

// DepartureAtGTE applies the GTE predicate on the "departure_at" field.
func DepartureAtGTE(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldDepartureAt, v))
}

// DepartureAtLT applies the LT predicate on the "departure_at" field.
func DepartureAtLT(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldDepartureAt, v))
}

// DepartureAtLTE applies the LTE predicate on the "departure_at" field.
func DepartureAtLTE(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldDepartureAt, v))
}

// ArrivalAtEQ applies the EQ predicate on the "arrival_at" field.
func ArrivalAtEQ(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldArrivalAt, v))
}

// ArrivalAtNEQ applies the NEQ predicate on the "arrival_at" field.
func ArrivalAtNEQ(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldArrivalAt, v))
}

// ArrivalAtIn applies the In predicate on the "arrival_at" field.
func ArrivalAtIn(vs ...time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldArrivalAt, vs...))
}

// ArrivalAtNotIn applies the NotIn predicate on the "arrival_at" field.
func ArrivalAtNotIn(vs ...time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldArrivalAt, vs...))
}

// ArrivalAtGT applies the GT predicate on the "arrival_at" field.
func ArrivalAtGT(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldArrivalAt, v))
}

// ArrivalAtGTE applies the GTE predicate on the "arrival_at" field.
func ArrivalAtGTE(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldArrivalAt, v))
}

// ArrivalAtLT applies the LT predicate on the "arrival_at" field.
func ArrivalAtLT(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldArrivalAt, v))
}

// ArrivalAtLTE applies the LTE predicate on the "arrival_at" field.
func ArrivalAtLTE(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldArrivalAt, v))
}

// CabinClassEQ applies the EQ predicate on the "cabin_class" field.
func CabinClassEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldCabinClass, v))
}

// CabinClassNEQ applies the NEQ predicate on the "cabin_class" field.
func CabinClassNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldCabinClass, v))
}

// CabinClassIn applies the In predicate on the "cabin_class" field.
func CabinClassIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldCabinClass, vs...))
}

// CabinClassNotIn applies the NotIn predicate on the "cabin_class" field.
func CabinClassNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldCabinClass, vs...))
}

// CabinClassGT applies the GT predicate on the "cabin_class" field.
func CabinClassGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldCabinClass, v))
}

// CabinClassGTE applies the GTE predicate on the "cabin_class" field.
func CabinClassGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldCabinClass, v))
}

// CabinClassLT applies the LT predicate on the "cabin_class" field.
func CabinClassLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldCabinClass, v))
}

// CabinClassLTE applies the LTE predicate on the "cabin_class" field.
func CabinClassLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldCabinClass, v))
}

// CabinClassContains applies the Contains predicate on the "cabin_class" field.
func CabinClassContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldCabinClass, v))
}

// CabinClassHasPrefix applies the HasPrefix predicate on the "cabin_class" field.
func CabinClassHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldCabinClass, v))
}

// CabinClassHasSuffix applies the HasSuffix predicate on the "cabin_class" field.
func CabinClassHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldCabinClass, v))
}

// CabinClassEqualFold applies the EqualFold predicate on the "cabin_class" field.
func CabinClassEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldCabinClass, v))
}

// CabinClassContainsFold applies the ContainsFold predicate on the "cabin_class" field.
func CabinClassContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldCabinClass, v))
}

// FareFamilyEQ applies the EQ predicate on the "fare_family" field.
func FareFamilyEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldFareFamily, v))
}

// FareFamilyNEQ applies the NEQ predicate on the "fare_family" field.
func FareFamilyNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldFareFamily, v))
}

// FareFamilyIn applies the In predicate on the "fare_family" field.
func FareFamilyIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldFareFamily, vs...))
}

// FareFamilyNotIn applies the NotIn predicate on the "fare_family" field.
func FareFamilyNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldFareFamily, vs...))
}

// FareFamilyGT applies the GT predicate on the "fare_family" field.
func FareFamilyGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldFareFamily, v))
}

// FareFamilyGTE applies the GTE predicate on the "fare_family" field.
func FareFamilyGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldFareFamily, v))
}

// FareFamilyLT applies the LT predicate on the "fare_family" field.
func FareFamilyLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldFareFamily, v))
}

// FareFamilyLTE applies the LTE predicate on the "fare_family" field.
func FareFamilyLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldFareFamily, v))
}

// FareFamilyContains applies the Contains predicate on the "fare_family" field.
func FareFamilyContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldFareFamily, v))
}

// FareFamilyHasPrefix applies the HasPrefix predicate on the "fare_family" field.
func FareFamilyHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldFareFamily, v))
}

// FareFamilyHasSuffix applies the HasSuffix predicate on the "fare_family" field.
func FareFamilyHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldFareFamily, v))
}

// FareFamilyIsNil applies the IsNil predicate on the "fare_family" field.
func FareFamilyIsNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIsNull(FieldFareFamily))
}

// FareFamilyNotNil applies the NotNil predicate on the "fare_family" field.
func FareFamilyNotNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotNull(FieldFareFamily))
}

// FareFamilyEqualFold applies the EqualFold predicate on the "fare_family" field.
func FareFamilyEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldFareFamily, v))
}

// FareFamilyContainsFold applies the ContainsFold predicate on the "fare_family" field.
func FareFamilyContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldFareFamily, v))
}

// ListedPriceEQ applies the EQ predicate on the "listed_price" field.
func ListedPriceEQ(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldListedPrice, v))
}

// ListedPriceNEQ applies the NEQ predicate on the "listed_price" field.
func ListedPriceNEQ(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldListedPrice, v))
}

// ListedPriceIn applies the In predicate on the "listed_price" field.
func ListedPriceIn(vs ...float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldListedPrice, vs...))
}

// ListedPriceNotIn applies the NotIn predicate on the "listed_price" field.
func ListedPriceNotIn(vs ...float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldListedPrice, vs...))
}

// ListedPriceGT applies the GT predicate on the "listed_price" field.
func ListedPriceGT(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldListedPrice, v))
}

// ListedPriceGTE applies the GTE predicate on the "listed_price" field.
func ListedPriceGTE(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldListedPrice, v))
}

// ListedPriceLT applies the LT predicate on the "listed_price" field.
func ListedPriceLT(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldListedPrice, v))
}

// ListedPriceLTE applies the LTE predicate on the "listed_price" field.
func ListedPriceLTE(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldListedPrice, v))
}

// SettlementPriceEQ applies the EQ predicate on the "settlement_price" field.
func SettlementPriceEQ(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldSettlementPrice, v))
}

// SettlementPriceNEQ applies the NEQ predicate on the "settlement_price" field.
func SettlementPriceNEQ(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldSettlementPrice, v))
}

// SettlementPriceIn applies the In predicate on the "settlement_price" field.
func SettlementPriceIn(vs ...float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldSettlementPrice, vs...))
}

// SettlementPriceNotIn applies the NotIn predicate on the "settlement_price" field.
func SettlementPriceNotIn(vs ...float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldSettlementPrice, vs...))
}

// SettlementPriceGT applies the GT predicate on the "settlement_price" field.
func SettlementPriceGT(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldSettlementPrice, v))
}

// SettlementPriceGTE applies the GTE predicate on the "settlement_price" field.
func SettlementPriceGTE(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldSettlementPrice, v))
}

// SettlementPriceLT applies the LT predicate on the "settlement_price" field.
func SettlementPriceLT(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldSettlementPrice, v))
}

// SettlementPriceLTE applies the LTE predicate on the "settlement_price" field.
func SettlementPriceLTE(v float64) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldSettlementPrice, v))
}

// SettlementPriceIsNil applies the IsNil predicate on the "settlement_price" field.
func SettlementPriceIsNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIsNull(FieldSettlementPrice))
}

// SettlementPriceNotNil applies the NotNil predicate on the "settlement_price" field.
func SettlementPriceNotNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotNull(FieldSettlementPrice))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyIsNil applies the IsNil predicate on the "currency" field.
func CurrencyIsNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIsNull(FieldCurrency))
}

// CurrencyNotNil applies the NotNil predicate on the "currency" field.
func CurrencyNotNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotNull(FieldCurrency))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldCurrency, v))
}

// SeatsAvailableEQ applies the EQ predicate on the "seats_available" field.
func SeatsAvailableEQ(v int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldSeatsAvailable, v))
}

// SeatsAvailableNEQ applies the NEQ predicate on the "seats_available" field.
func SeatsAvailableNEQ(v int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldSeatsAvailable, v))
}

// SeatsAvailableIn applies the In predicate on the "seats_available" field.
func SeatsAvailableIn(vs ...int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldSeatsAvailable, vs...))
}

// SeatsAvailableNotIn applies the NotIn predicate on the "seats_available" field.
func SeatsAvailableNotIn(vs ...int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldSeatsAvailable, vs...))
}

// SeatsAvailableGT applies the GT predicate on the "seats_available" field.
func SeatsAvailableGT(v int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldSeatsAvailable, v))
}

// SeatsAvailableGTE applies the GTE predicate on the "seats_available" field.
func SeatsAvailableGTE(v int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldSeatsAvailable, v))
}

// SeatsAvailableLT applies the LT predicate on the "seats_available" field.
func SeatsAvailableLT(v int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldSeatsAvailable, v))
}

// SeatsAvailableLTE applies the LTE predicate on the "seats_available" field.
func SeatsAvailableLTE(v int) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldSeatsAvailable, v))
}

// SeatsAvailableIsNil applies the IsNil predicate on the "seats_available" field.
func SeatsAvailableIsNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIsNull(FieldSeatsAvailable))
}

// SeatsAvailableNotNil applies the NotNil predicate on the "seats_available" field.
func SeatsAvailableNotNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotNull(FieldSeatsAvailable))
}

// BaggagePolicyEQ applies the EQ predicate on the "baggage_policy" field.
func BaggagePolicyEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldBaggagePolicy, v))
}

// BaggagePolicyNEQ applies the NEQ predicate on the "baggage_policy" field.
func BaggagePolicyNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldBaggagePolicy, v))
}

// BaggagePolicyIn applies the In predicate on the "baggage_policy" field.
func BaggagePolicyIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldBaggagePolicy, vs...))
}

// BaggagePolicyNotIn applies the NotIn predicate on the "baggage_policy" field.
func BaggagePolicyNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldBaggagePolicy, vs...))
}

// BaggagePolicyGT applies the GT predicate on the "baggage_policy" field.
func BaggagePolicyGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldBaggagePolicy, v))
}

// BaggagePolicyGTE applies the GTE predicate on the "baggage_policy" field.
func BaggagePolicyGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldBaggagePolicy, v))
}

// BaggagePolicyLT applies the LT predicate on the "baggage_policy" field.
func BaggagePolicyLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldBaggagePolicy, v))
}

// BaggagePolicyLTE applies the LTE predicate on the "baggage_policy" field.
func BaggagePolicyLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldBaggagePolicy, v))
}

// BaggagePolicyContains applies the Contains predicate on the "baggage_policy" field.
func BaggagePolicyContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldBaggagePolicy, v))
}

// BaggagePolicyHasPrefix applies the HasPrefix predicate on the "baggage_policy" field.
func BaggagePolicyHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldBaggagePolicy, v))
}

// BaggagePolicyHasSuffix applies the HasSuffix predicate on the "baggage_policy" field.
func BaggagePolicyHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldBaggagePolicy, v))
}

// BaggagePolicyIsNil applies the IsNil predicate on the "baggage_policy" field.
func BaggagePolicyIsNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIsNull(FieldBaggagePolicy))
}

// BaggagePolicyNotNil applies the NotNil predicate on the "baggage_policy" field.
func BaggagePolicyNotNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotNull(FieldBaggagePolicy))
}

// BaggagePolicyEqualFold applies the EqualFold predicate on the "baggage_policy" field.
func BaggagePolicyEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldBaggagePolicy, v))
}

// BaggagePolicyContainsFold applies the ContainsFold predicate on the "baggage_policy" field.
func BaggagePolicyContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldBaggagePolicy, v))
}

// RefundChangePolicyEQ applies the EQ predicate on the "refund_change_policy" field.
func RefundChangePolicyEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldRefundChangePolicy, v))
}

// RefundChangePolicyNEQ applies the NEQ predicate on the "refund_change_policy" field.
func RefundChangePolicyNEQ(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldRefundChangePolicy, v))
}

// RefundChangePolicyIn applies the In predicate on the "refund_change_policy" field.
func RefundChangePolicyIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldRefundChangePolicy, vs...))
}

// RefundChangePolicyNotIn applies the NotIn predicate on the "refund_change_policy" field.
func RefundChangePolicyNotIn(vs ...string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldRefundChangePolicy, vs...))
}

// RefundChangePolicyGT applies the GT predicate on the "refund_change_policy" field.
func RefundChangePolicyGT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldRefundChangePolicy, v))
}

// RefundChangePolicyGTE applies the GTE predicate on the "refund_change_policy" field.
func RefundChangePolicyGTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldRefundChangePolicy, v))
}

// RefundChangePolicyLT applies the LT predicate on the "refund_change_policy" field.
func RefundChangePolicyLT(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldRefundChangePolicy, v))
}

// RefundChangePolicyLTE applies the LTE predicate on the "refund_change_policy" field.
func RefundChangePolicyLTE(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldRefundChangePolicy, v))
}

// RefundChangePolicyContains applies the Contains predicate on the "refund_change_policy" field.
func RefundChangePolicyContains(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContains(FieldRefundChangePolicy, v))
}

// RefundChangePolicyHasPrefix applies the HasPrefix predicate on the "refund_change_policy" field.
func RefundChangePolicyHasPrefix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasPrefix(FieldRefundChangePolicy, v))
}

// RefundChangePolicyHasSuffix applies the HasSuffix predicate on the "refund_change_policy" field.
func RefundChangePolicyHasSuffix(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldHasSuffix(FieldRefundChangePolicy, v))
}

// RefundChangePolicyIsNil applies the IsNil predicate on the "refund_change_policy" field.
func RefundChangePolicyIsNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIsNull(FieldRefundChangePolicy))
}

// RefundChangePolicyNotNil applies the NotNil predicate on the "refund_change_policy" field.
func RefundChangePolicyNotNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotNull(FieldRefundChangePolicy))
}

// RefundChangePolicyEqualFold applies the EqualFold predicate on the "refund_change_policy" field.
func RefundChangePolicyEqualFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEqualFold(FieldRefundChangePolicy, v))
}

// RefundChangePolicyContainsFold applies the ContainsFold predicate on the "refund_change_policy" field.
func RefundChangePolicyContainsFold(v string) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldContainsFold(FieldRefundChangePolicy, v))
}

// SaleStatusEQ applies the EQ predicate on the "sale_status" field.
func SaleStatusEQ(v SaleStatus) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldSaleStatus, v))
}

// SaleStatusNEQ applies the NEQ predicate on the "sale_status" field.
func SaleStatusNEQ(v SaleStatus) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldSaleStatus, v))
}

// SaleStatusIn applies the In predicate on the "sale_status" field.
func SaleStatusIn(vs ...SaleStatus) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldSaleStatus, vs...))
}

// SaleStatusNotIn applies the NotIn predicate on the "sale_status" field.
func SaleStatusNotIn(vs ...SaleStatus) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldSaleStatus, vs...))
}

// SaleStatusIsNil applies the IsNil predicate on the "sale_status" field.
func SaleStatusIsNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIsNull(FieldSaleStatus))
}

// SaleStatusNotNil applies the NotNil predicate on the "sale_status" field.
func SaleStatusNotNil() predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotNull(FieldSaleStatus))
}

// InsertedAtEQ applies the EQ predicate on the "inserted_at" field.
func InsertedAtEQ(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldInsertedAt, v))
}

// InsertedAtNEQ applies the NEQ predicate on the "inserted_at" field.
func InsertedAtNEQ(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldInsertedAt, v))
}

// InsertedAtIn applies the In predicate on the "inserted_at" field.
func InsertedAtIn(vs ...time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldInsertedAt, vs...))
}

// InsertedAtNotIn applies the NotIn predicate on the "inserted_at" field.
func InsertedAtNotIn(vs ...time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldInsertedAt, vs...))
}

// InsertedAtGT applies the GT predicate on the "inserted_at" field.
func InsertedAtGT(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldInsertedAt, v))
}

// InsertedAtGTE applies the GTE predicate on the "inserted_at" field.
func InsertedAtGTE(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldInsertedAt, v))
}

// InsertedAtLT applies the LT predicate on the "inserted_at" field.
func InsertedAtLT(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldInsertedAt, v))
}

// InsertedAtLTE applies the LTE predicate on the "inserted_at" field.
func InsertedAtLTE(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldInsertedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FlightOffer {
	return predicate.FlightOffer(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOrders applies the HasEdge predicate on the "orders" edge.
func HasOrders() predicate.FlightOffer {
	return predicate.FlightOffer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, OrdersTable, OrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrdersWith applies the HasEdge predicate on the "orders" edge with a given conditions (other predicates).
func HasOrdersWith(preds ...predicate.TravelOrder) predicate.FlightOffer {
	return predicate.FlightOffer(func(s *sql.Selector) {
		step := newOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FlightOffer) predicate.FlightOffer {
	return predicate.FlightOffer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FlightOffer) predicate.FlightOffer {
	return predicate.FlightOffer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FlightOffer) predicate.FlightOffer {
	return predicate.FlightOffer(sql.NotPredicates(p))
}
