defmodule UniboV4.Ofbiz.Accounting do
  use Ash.Domain,
    extensions: [AshGraphql.Domain]

  graphql do
    authorize? false
  end

  resources do
    resource UniboV4.Ofbiz.Accounting.Budget
    resource UniboV4.Ofbiz.Accounting.Budget.Version
    resource UniboV4.Ofbiz.Accounting.BudgetAttribute
    resource UniboV4.Ofbiz.Accounting.BudgetAttribute.Version
    resource UniboV4.Ofbiz.Accounting.BudgetItem
    resource UniboV4.Ofbiz.Accounting.BudgetItem.Version
    resource UniboV4.Ofbiz.Accounting.BudgetItemAttribute
    resource UniboV4.Ofbiz.Accounting.BudgetItemType
    resource UniboV4.Ofbiz.Accounting.BudgetItemType.Version
    resource UniboV4.Ofbiz.Accounting.BudgetItemTypeAttr
    resource UniboV4.Ofbiz.Accounting.BudgetItemTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.BudgetReview
    resource UniboV4.Ofbiz.Accounting.BudgetReviewResultType
    resource UniboV4.Ofbiz.Accounting.BudgetReviewResultType.Version
    resource UniboV4.Ofbiz.Accounting.BudgetRevision
    resource UniboV4.Ofbiz.Accounting.BudgetRevision.Version
    resource UniboV4.Ofbiz.Accounting.BudgetRevisionImpact
    resource UniboV4.Ofbiz.Accounting.BudgetRole
    resource UniboV4.Ofbiz.Accounting.BudgetScenario
    resource UniboV4.Ofbiz.Accounting.BudgetScenario.Version
    resource UniboV4.Ofbiz.Accounting.BudgetScenarioApplication
    resource UniboV4.Ofbiz.Accounting.BudgetScenarioApplication.Version
    resource UniboV4.Ofbiz.Accounting.BudgetScenarioRule
    resource UniboV4.Ofbiz.Accounting.BudgetScenarioRule.Version
    resource UniboV4.Ofbiz.Accounting.BudgetStatus
    resource UniboV4.Ofbiz.Accounting.BudgetStatus.Version
    resource UniboV4.Ofbiz.Accounting.BudgetType
    resource UniboV4.Ofbiz.Accounting.BudgetType.Version
    resource UniboV4.Ofbiz.Accounting.BudgetTypeAttr
    resource UniboV4.Ofbiz.Accounting.BudgetTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.FinAccount
    resource UniboV4.Ofbiz.Accounting.FinAccount.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountAttribute
    resource UniboV4.Ofbiz.Accounting.FinAccountAttribute.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountAuth
    resource UniboV4.Ofbiz.Accounting.FinAccountAuth.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountRole
    resource UniboV4.Ofbiz.Accounting.FinAccountStatus
    resource UniboV4.Ofbiz.Accounting.FinAccountTrans
    resource UniboV4.Ofbiz.Accounting.FinAccountTrans.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountTransAttribute
    resource UniboV4.Ofbiz.Accounting.FinAccountTransAttribute.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountTransType
    resource UniboV4.Ofbiz.Accounting.FinAccountTransType.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountTransTypeAttr
    resource UniboV4.Ofbiz.Accounting.FinAccountTransTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountType
    resource UniboV4.Ofbiz.Accounting.FinAccountType.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountTypeAttr
    resource UniboV4.Ofbiz.Accounting.FinAccountTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.FinAccountTypeGlAccount
    resource UniboV4.Ofbiz.Accounting.FinAccountTypeGlAccount.Version
    resource UniboV4.Ofbiz.Accounting.FixedAsset
    resource UniboV4.Ofbiz.Accounting.FixedAsset.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetAttribute
    resource UniboV4.Ofbiz.Accounting.FixedAssetAttribute.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetDepMethod
    resource UniboV4.Ofbiz.Accounting.FixedAssetDepMethod.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetGeoPoint
    resource UniboV4.Ofbiz.Accounting.FixedAssetIdent
    resource UniboV4.Ofbiz.Accounting.FixedAssetIdent.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetIdentType
    resource UniboV4.Ofbiz.Accounting.FixedAssetIdentType.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetMaint
    resource UniboV4.Ofbiz.Accounting.FixedAssetMaint.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetMeter
    resource UniboV4.Ofbiz.Accounting.FixedAssetProduct
    resource UniboV4.Ofbiz.Accounting.FixedAssetProductType
    resource UniboV4.Ofbiz.Accounting.FixedAssetProductType.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetTypeGlAccount
    resource UniboV4.Ofbiz.Accounting.FixedAssetTypeGlAccount.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetRegistration
    resource UniboV4.Ofbiz.Accounting.FixedAssetRegistration.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetStdCost
    resource UniboV4.Ofbiz.Accounting.FixedAssetStdCost.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetStdCostType
    resource UniboV4.Ofbiz.Accounting.FixedAssetStdCostType.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetType
    resource UniboV4.Ofbiz.Accounting.FixedAssetType.Version
    resource UniboV4.Ofbiz.Accounting.FixedAssetTypeAttr
    resource UniboV4.Ofbiz.Accounting.FixedAssetTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.PartyFixedAssetAssignment
    resource UniboV4.Ofbiz.Accounting.FixedAssetMaintOrder
    resource UniboV4.Ofbiz.Accounting.AccommodationClass
    resource UniboV4.Ofbiz.Accounting.AccommodationClass.Version
    resource UniboV4.Ofbiz.Accounting.AccommodationSpot
    resource UniboV4.Ofbiz.Accounting.AccommodationSpot.Version
    resource UniboV4.Ofbiz.Accounting.AccommodationMap
    resource UniboV4.Ofbiz.Accounting.AccommodationMap.Version
    resource UniboV4.Ofbiz.Accounting.AccommodationMapType
    resource UniboV4.Ofbiz.Accounting.AccommodationMapType.Version
    resource UniboV4.Ofbiz.Accounting.Invoice
    resource UniboV4.Ofbiz.Accounting.Invoice.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceAttribute
    resource UniboV4.Ofbiz.Accounting.InvoiceAttribute.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceContent
    resource UniboV4.Ofbiz.Accounting.InvoiceContentType
    resource UniboV4.Ofbiz.Accounting.InvoiceContentType.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceContactMech
    resource UniboV4.Ofbiz.Accounting.InvoiceItem
    resource UniboV4.Ofbiz.Accounting.InvoiceItem.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceItemAssoc
    resource UniboV4.Ofbiz.Accounting.InvoiceItemAssocType
    resource UniboV4.Ofbiz.Accounting.InvoiceItemAssocType.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceItemAttribute
    resource UniboV4.Ofbiz.Accounting.InvoiceItemType
    resource UniboV4.Ofbiz.Accounting.InvoiceItemType.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceItemTypeAttr
    resource UniboV4.Ofbiz.Accounting.InvoiceItemTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceItemTypeGlAccount
    resource UniboV4.Ofbiz.Accounting.InvoiceItemTypeGlAccount.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceItemTypeMap
    resource UniboV4.Ofbiz.Accounting.InvoiceItemTypeMap.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceRole
    resource UniboV4.Ofbiz.Accounting.InvoiceStatus
    resource UniboV4.Ofbiz.Accounting.InvoiceTerm
    resource UniboV4.Ofbiz.Accounting.InvoiceTerm.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceTermAttribute
    resource UniboV4.Ofbiz.Accounting.InvoiceTermAttribute.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceType
    resource UniboV4.Ofbiz.Accounting.InvoiceType.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceTypeAttr
    resource UniboV4.Ofbiz.Accounting.InvoiceTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.InvoiceNote
    resource UniboV4.Ofbiz.Accounting.InvoiceNote.Version
    resource UniboV4.Ofbiz.Accounting.AcctgTrans
    resource UniboV4.Ofbiz.Accounting.AcctgTrans.Version
    resource UniboV4.Ofbiz.Accounting.AcctgTransAttribute
    resource UniboV4.Ofbiz.Accounting.AcctgTransAttribute.Version
    resource UniboV4.Ofbiz.Accounting.AcctgTransEntry
    resource UniboV4.Ofbiz.Accounting.AcctgTransEntry.Version
    resource UniboV4.Ofbiz.Accounting.AcctgTransEntryType
    resource UniboV4.Ofbiz.Accounting.AcctgTransEntryType.Version
    resource UniboV4.Ofbiz.Accounting.AcctgTransType
    resource UniboV4.Ofbiz.Accounting.AcctgTransType.Version
    resource UniboV4.Ofbiz.Accounting.AcctgTransTypeAttr
    resource UniboV4.Ofbiz.Accounting.AcctgTransTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.GlAccount
    resource UniboV4.Ofbiz.Accounting.GlAccount.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountClass
    resource UniboV4.Ofbiz.Accounting.GlAccountClass.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountGroup
    resource UniboV4.Ofbiz.Accounting.GlAccountGroup.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountGroupMember
    resource UniboV4.Ofbiz.Accounting.GlAccountGroupMember.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountGroupType
    resource UniboV4.Ofbiz.Accounting.GlAccountGroupType.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountHistory
    resource UniboV4.Ofbiz.Accounting.GlAccountOrganization
    resource UniboV4.Ofbiz.Accounting.GlAccountOrganization.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountRole
    resource UniboV4.Ofbiz.Accounting.GlAccountType
    resource UniboV4.Ofbiz.Accounting.GlAccountType.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountTypeDefault
    resource UniboV4.Ofbiz.Accounting.GlAccountTypeDefault.Version
    resource UniboV4.Ofbiz.Accounting.GlBudgetXref
    resource UniboV4.Ofbiz.Accounting.GlBudgetXref.Version
    resource UniboV4.Ofbiz.Accounting.GlFiscalType
    resource UniboV4.Ofbiz.Accounting.GlFiscalType.Version
    resource UniboV4.Ofbiz.Accounting.GlJournal
    resource UniboV4.Ofbiz.Accounting.GlJournal.Version
    resource UniboV4.Ofbiz.Accounting.GlReconciliation
    resource UniboV4.Ofbiz.Accounting.GlReconciliation.Version
    resource UniboV4.Ofbiz.Accounting.GlReconciliationEntry
    resource UniboV4.Ofbiz.Accounting.GlReconciliationEntry.Version
    resource UniboV4.Ofbiz.Accounting.GlResourceType
    resource UniboV4.Ofbiz.Accounting.GlResourceType.Version
    resource UniboV4.Ofbiz.Accounting.GlXbrlClass
    resource UniboV4.Ofbiz.Accounting.GlXbrlClass.Version
    resource UniboV4.Ofbiz.Accounting.PartyAcctgPreference
    resource UniboV4.Ofbiz.Accounting.PartyAcctgPreference.Version
    resource UniboV4.Ofbiz.Accounting.PartyPrefDocTypeTpl
    resource UniboV4.Ofbiz.Accounting.PartyPrefDocTypeTpl.Version
    resource UniboV4.Ofbiz.Accounting.ProductAverageCost
    resource UniboV4.Ofbiz.Accounting.ProductAverageCostType
    resource UniboV4.Ofbiz.Accounting.ProductAverageCostType.Version
    resource UniboV4.Ofbiz.Accounting.SettlementTerm
    resource UniboV4.Ofbiz.Accounting.SettlementTerm.Version
    resource UniboV4.Ofbiz.Accounting.VarianceReasonGlAccount
    resource UniboV4.Ofbiz.Accounting.BillingAccount
    resource UniboV4.Ofbiz.Accounting.BillingAccount.Version
    resource UniboV4.Ofbiz.Accounting.BillingAccountRole
    resource UniboV4.Ofbiz.Accounting.BillingAccountTerm
    resource UniboV4.Ofbiz.Accounting.BillingAccountTerm.Version
    resource UniboV4.Ofbiz.Accounting.BillingAccountTermAttr
    resource UniboV4.Ofbiz.Accounting.BillingAccountTermAttr.Version
    resource UniboV4.Ofbiz.Accounting.CreditCard
    resource UniboV4.Ofbiz.Accounting.CreditCard.Version
    resource UniboV4.Ofbiz.Accounting.CreditCardTypeGlAccount
    resource UniboV4.Ofbiz.Accounting.Deduction
    resource UniboV4.Ofbiz.Accounting.Deduction.Version
    resource UniboV4.Ofbiz.Accounting.DeductionType
    resource UniboV4.Ofbiz.Accounting.DeductionType.Version
    resource UniboV4.Ofbiz.Accounting.EftAccount
    resource UniboV4.Ofbiz.Accounting.EftAccount.Version
    resource UniboV4.Ofbiz.Accounting.CheckAccount
    resource UniboV4.Ofbiz.Accounting.CheckAccount.Version
    resource UniboV4.Ofbiz.Accounting.GiftCard
    resource UniboV4.Ofbiz.Accounting.GiftCard.Version
    resource UniboV4.Ofbiz.Accounting.GiftCardFulfillment
    resource UniboV4.Ofbiz.Accounting.GiftCardFulfillment.Version
    resource UniboV4.Ofbiz.Accounting.Payment
    resource UniboV4.Ofbiz.Accounting.Payment.Version
    resource UniboV4.Ofbiz.Accounting.PaymentApplication
    resource UniboV4.Ofbiz.Accounting.PaymentApplication.Version
    resource UniboV4.Ofbiz.Accounting.PaymentAttribute
    resource UniboV4.Ofbiz.Accounting.PaymentAttribute.Version
    resource UniboV4.Ofbiz.Accounting.PaymentBudgetAllocation
    resource UniboV4.Ofbiz.Accounting.PaymentBudgetAllocation.Version
    resource UniboV4.Ofbiz.Accounting.PaymentContent
    resource UniboV4.Ofbiz.Accounting.PaymentContentType
    resource UniboV4.Ofbiz.Accounting.PaymentContentType.Version
    resource UniboV4.Ofbiz.Accounting.PaymentMethod
    resource UniboV4.Ofbiz.Accounting.PaymentMethod.Version
    resource UniboV4.Ofbiz.Accounting.PaymentMethodType
    resource UniboV4.Ofbiz.Accounting.PaymentMethodType.Version
    resource UniboV4.Ofbiz.Accounting.PaymentMethodTypeGlAccount
    resource UniboV4.Ofbiz.Accounting.PaymentMethodTypeGlAccount.Version
    resource UniboV4.Ofbiz.Accounting.PaymentType
    resource UniboV4.Ofbiz.Accounting.PaymentType.Version
    resource UniboV4.Ofbiz.Accounting.PaymentTypeAttr
    resource UniboV4.Ofbiz.Accounting.PaymentTypeAttr.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGlAccountTypeMap
    resource UniboV4.Ofbiz.Accounting.PaymentGlAccountTypeMap.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayConfigType
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayConfigType.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayConfig
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayConfig.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewaySagePay
    resource UniboV4.Ofbiz.Accounting.PaymentGatewaySagePay.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayAuthorizeNet
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayAuthorizeNet.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayEway
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayEway.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayCyberSource
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayCyberSource.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayPayflowPro
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayPayflowPro.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayPayPal
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayPayPal.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayClearCommerce
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayClearCommerce.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayWorldPay
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayWorldPay.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayOrbital
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayOrbital.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewaySecurePay
    resource UniboV4.Ofbiz.Accounting.PaymentGatewaySecurePay.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayRespMsg
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayRespMsg.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayResponse
    resource UniboV4.Ofbiz.Accounting.PaymentGatewayResponse.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGroup
    resource UniboV4.Ofbiz.Accounting.PaymentGroup.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGroupType
    resource UniboV4.Ofbiz.Accounting.PaymentGroupType.Version
    resource UniboV4.Ofbiz.Accounting.PaymentGroupMember
    resource UniboV4.Ofbiz.Accounting.PaymentGroupMember.Version
    resource UniboV4.Ofbiz.Accounting.PayPalPaymentMethod
    resource UniboV4.Ofbiz.Accounting.PayPalPaymentMethod.Version
    resource UniboV4.Ofbiz.Accounting.ValueLinkKey
    resource UniboV4.Ofbiz.Accounting.ValueLinkKey.Version
    resource UniboV4.Ofbiz.Accounting.PartyTaxAuthInfo
    resource UniboV4.Ofbiz.Accounting.TaxAuthority
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityAssoc
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityAssocType
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityAssocType.Version
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityCategory
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityGlAccount
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityRateProduct
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityRateProduct.Version
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityRateType
    resource UniboV4.Ofbiz.Accounting.TaxAuthorityRateType.Version
    resource UniboV4.Ofbiz.Accounting.ZipSalesRuleLookup
    resource UniboV4.Ofbiz.Accounting.ZipSalesTaxLookup
    resource UniboV4.Ofbiz.Accounting.PartyGlAccount
    resource UniboV4.Ofbiz.Accounting.RateType
    resource UniboV4.Ofbiz.Accounting.RateType.Version
    resource UniboV4.Ofbiz.Accounting.RateAmount
    resource UniboV4.Ofbiz.Accounting.PartyRate
    resource UniboV4.Ofbiz.Accounting.GlAccountCategory
    resource UniboV4.Ofbiz.Accounting.GlAccountCategory.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountCategoryMember
    resource UniboV4.Ofbiz.Accounting.GlAccountCategoryMember.Version
    resource UniboV4.Ofbiz.Accounting.GlAccountCategoryType
    resource UniboV4.Ofbiz.Accounting.GlAccountCategoryType.Version
  end
end
